NG-ZORRO/ng-zorro-antd

- src/showcase/nz-demo-message/nz-demo-message-icon.component.ts
The show error message button should use type `error` rather than `info`.
> docs(message): fix error message type

- package.json
Move the angular core packages out of dependencies to rely on user's installing
Close #23
> build(packaging): fix conflict version of angular

- src/components/carousel/nz-carousel-content.directive.ts
- src/components/carousel/nz-carousel.component.ts
- src/showcase/nz-demo-carousel/nz-demo-carousel-auto.component.ts
- src/showcase/nz-demo-carousel/nz-demo-carousel-basic.component.ts
- src/showcase/nz-demo-carousel/nz-demo-carousel-fade.component.ts
- src/showcase/nz-demo-carousel/nz-demo-carousel-vertical.component.ts
Closes NG-ZORRO/ng-zorro-antd#56
> fix(module:carousel): support dynamic change of nz-carousel-content

- src/components/input/nz-input.component.ts
provide ngFocus event
closes #73
```
[ ] Bugfix
[x] Feature
```
Issue Number: #73
```
[ ] Yes
[ ] No
```
> feat(module:input): provide nzFocus event

- src/components/checkbox/nz-checkbox.component.ts
close #104
```
[ ] Yes
[ ] No
```
> fix(module:checkbox): fix checkbox host class lost bug

- src/components/ng-zorro-antd.module.spec.ts
- src/components/ng-zorro-antd.module.ts
- src/components/root/nz-root-config.spec.ts
- src/components/root/nz-root-config.ts
- src/components/root/nz-root-style.component.ts
- src/components/root/nz-root.component.spec.ts
- src/components/root/nz-root.component.ts
- src/components/root/nz-root.module.spec.ts
- src/components/root/nz-root.module.ts
- src/showcase/app.component.html
- src/showcase/app.module.ts
- src/showcase/nz-intro-getting-started/README.md
Closes #34 .
For `NgZorroAntdModule.forRoot()` method, there is an optional parameter in signature `{ extraFontName: string, extraFontUrl: string }`, like:
```typescript
const options = { extraFontName: 'some-name', extraFontUrl: 'some-url' };
imports: [
NgZorroAntdModule.forRoot(options)
]
```
It would be same as using `<nz-root nzExtraFontName="some-name" nzExtraFontUrl="some-url">`.
Meanwhile, user can manually provide an `NZ_ROOT_CONFIG` if they don't want to import the entire lib.
> feat(module:root): make nz-root optional

- src/components/select/nz-select.component.ts
Fix #139 
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #139 
```
[ ] Yes
[x] No
```
> fix(module:select): fix option incorrect active status

- src/components/input/nz-input.component.ts
- src/components/input/nz-input.directive.component.ts
input component and directive
close #103
[ ] Feature
```
[ ] Yes
[ ] No
```
> fix(module:input): fix input disabled style bug

- .travis.yml
- README-zh_CN.md
- README.md
- package.json
- src/showcase/nz-demo-icon/README.md
- src/showcase/nz-intro-changelog/README.md
- src/showcase/nz-intro-getting-started/README.md
- src/showcase/nz-intro-index/README.md
close #151
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.5.0-rc.3): pre-release 0.5.0-rc.3

- src/components/popconfirm/nz-popconfirm.component.ts
- src/components/popover/nz-popover.component.ts
- src/components/tooltip/nz-tooltip.component.ts
- src/showcase/nz-demo-popconfirm/nz-demo-popconfirm.component.ts
- src/showcase/nz-demo-popover/nz-demo-popover.component.ts
- src/showcase/nz-demo-tooltip/nz-demo-tooltip.component.ts
add subject to support changeDetection of OnPush
change showcases’ changeDetection to OnPush
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:tooltip,popconfirm,popover): support OnPush

- src/components/dropdown/nz-dropdown-button.component.ts
- src/components/dropdown/nz-dropdown.component.ts
1. use Observable to replace Subject, which could dispose eventListener.
2. use ChangeDetectionStrategy.OnPush to reduce check times.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:dropdown): improve performance

- src/components/calendar/nz-calendar.component.ts
Use ngTemplateOutletContext instead.
```
[ ] Bugfix
[ ] Feature
```
My test app using ng-zorro-antd is compiled OK with Angular 5.0.0-beta.5 but not started, because the beta version removed deprecated ngOutletContext which is currently used in the calendar module, even though the module is not used from my app.
> Error: Template parse errors:
> Can't bind to 'ngOutletContext' since it isn't a known …
> refactor(calendar): replace deprecated ngOutletContext

- src/components/pagination/nz-pagination.component.ts
Fix #171 
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #171 
In the `nzShowQuickJumper` and `nzSimple` model,  `nzPageIndexChange ` event can emit as normal.
```
[ ] Yes
[x] No
```
> fix(module:pagination): fix nzPageIndexChange event does not emit

- src/components/modal/nz-modal.component.ts
use #modal.open() instead of set nzVisible=true
use #modal.close() instead of set nzVisible=false
use #modal.setConfirmLoading(loading:boolean) instead of set confirmLoading
close #118
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:modal): provide open & close & setConfirmLoading function

- src/components/input/nz-input.component.ts
fix(module:input):fix nz-input's nzSize not work when nz-input not set nzDisabled property
```
[x] Bugfix
[ ] Feature
```
if I do not set 'nzDisabled' property on nz-input ,'nzSize' will not work fine.
Issue Number:#208
if I only set nzSize like 'nzSize'="'large'", nz-input can work fine.
```
[ ] Yes
[x] No
```
> fix(module:input):fix nz-input's nzSize not work when nz-input not set nzDisabled property

- src/components/cascader/nz-cascader.component.ts
- src/components/checkbox/nz-checkbox-group.component.ts
- src/components/checkbox/nz-checkbox.component.ts
- src/components/datepicker/nz-datepicker.component.ts
- src/components/input-number/nz-input-number.component.ts
- src/components/input/nz-input.component.ts
- src/components/radio/nz-radio-group.component.ts
- src/components/rate/nz-rate.component.ts
- src/components/select/nz-select.component.ts
- src/components/slider/nz-slider.component.ts
- src/components/switch/nz-switch.component.ts
- src/components/time-picker/nz-timepicker-inner.component.ts
- src/components/time-picker/nz-timepicker.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #134 #195 
```
[ ] Yes
[x] No
```
Patch all components with setDisabledState. 
Work in process:
> fix(module:*): patch all components with setDisabledState

- src/components/cascader/nz-cascader.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-basic.component.ts
fix(module:cascader): fix nz-cascader don't refresh when nzOptions binding data changed (#219)
```
[x] Bugfix
[ ] Feature
```
Issue Number: 219
when nzOptions binding data changed, auto rebuild component render
```
[ ] Yes
[x] No
```
> fix(module:cascader): fix nz-cascader don't refresh when nzOptions binding data changed (#219)

- src/components/core/floater/floater.service.ts
- src/components/root/nz-root.component.ts
- src/components/root/nz-root.module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: fixes https://github.com/NG-ZORRO/ng-zorro-antd/issues/69
`DOCUMENT` in `@angular/common` was introduced in [4.3.0-rc.0](https://github.com/angular/angular/commit/2a7ebbe982624c7cc617670f6f0284780de2d55d), as we documented the compatibility for ~4.0.0, it should not be used in production codes. (Won't matter for showcase or documentation)
```
[ ] Yes
[x] No
``` …
> fix(module:core,root): ensure compatibility to v4

- src/components/datepicker/nz-datepicker.component.ts
close #232
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:datepicker): year and month display in opposite way

- src/components/core/overlay/scroll/scroll-dispatcher.ts
- src/components/tabs/nz-tabs-nav.component.ts
- src/components/tabs/nz-tabset.component.ts
```
[ ] Bugfix
[ ] Feature
```
Using operators re-exported (and type-enhanced) from cdk.
Cdk operators are only designed for `StrictRxChain` usage, which does not cover all available operators and not guaranteed by documentation (availability could change during time).
It would cause breaking change once cdk adjust the operators re-exported.
```
[ ] Yes
[x] No
```
> refactor(module:core,tabs): not use re-exported operators from cdk

- src/components/menu/nz-menu.component.ts
- src/components/menu/style/index.less
- src/showcase/nz-demo-menu/nz-demo-menu-collapsed.component.ts
- src/showcase/nz-demo-menu/nz-demo-menu.component.ts
- src/showcase/nz-demo-menu/nz-demo-menu.html
- src/showcase/nz-demo-menu/nz-demo-menu.module.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #206
```
[ ] Yes
[X] No
```
> feat(module:menu): support unfolds/folds & add demo and api docs

- src/components/checkbox/nz-checkbox.component.ts
Close #254 
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #254 
make `nzChecked` @Input only and only let the click on the host to control the check status.
```
[ ] Yes
[x] No
```
> fix(module:checkbox): fix trigger twitce in safari

- src/components/input/nz-input.component.ts
- src/components/input/nz-input.directive.component.ts
- src/components/util/calculate-node-height.ts
- src/showcase/nz-demo-input/nz-demo-input-textarea-auot-size.component.ts
- src/showcase/nz-demo-input/nz-demo-input.component.ts
- src/showcase/nz-demo-input/nz-demo-input.html
- src/showcase/nz-demo-input/nz-demo-input.module.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #252 
Autosizing the height to fit the content, like https://ant.design/components/input/
```
[ ] Yes
[X] No
```
> feat(module:input): support nzAutosize property

- src/components/datepicker/nz-datepicker.component.ts
- src/components/input-number/nz-input-number.component.ts
- src/components/input/nz-input.component.ts
- src/components/select/nz-select.component.ts
- src/components/slider/nz-slider.component.ts
change the "writeValue" to not trigger "view -> control updating" while "control -> view updating"
close #114
```
[x] Bugfix
[ ] Feature
```
Issue Number: #114 
```
[ ] Yes
[x] No
```
> fix(module:input,datepicker,input-number,select,slider): still dirty when "form.reset()" called

- src/showcase/nz-demo-select/nz-demo-select-basic.component.ts
remove unused variable in `select`: `nz-demo-select-basic`
```
[ ] Bugfix
[ ] Feature
[X] Build related changes
```
```
[ ] Yes
[ ] No
```
> style(showcase:select): remove unused variable

- src/components/menu/nz-menu.component.spec.ts
- src/components/menu/nz-submenu.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #262 
```
[ ] Yes
[X] No
```
> feat(module:menu): selected child item, its parent highlight

- package.json
- rollup.config.js
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #315 #85 #169 #240
```
[ ] Yes
[ ] No
```
> fix(moment): use replace plugin to replace moment

- src/components/cascader/nz-cascader.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-basic.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-change-on-select.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-custom-render.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-custom-trigger.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-default-value.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-disabled.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-hover.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-lazy.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-reactive-form.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader-size.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader.component.ts
- src/showcase/nz-demo-cascader/nz-demo-cascader.html
- src/showcase/nz-demo-cascader/nz-demo-cascader.module.ts
fix(module:cascader): select and render leaf label & reset in reactive form (#335) (#336)
close #335 close #336 
```
[x] Bugfix
[ ] Feature
```
Issue Number: #335 #336 
```
[ ] Yes
[x] No
```
> fix(module:cascader): select and render leaf label & reset in reactive form (#335) (#336)

- src/components/badge/nz-badge.component.ts
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
```
[ ] Yes
[X] No
```
> style(module:badge): format the code in template

- src/components/select/nz-select.component.ts
close #284
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:select): support undefined reset select

- src/components/table/nz-table.component.ts
- src/showcase/nz-demo-table/nz-demo-table.html
```
[ ] Bugfix
[x] Feature
```
Issue Number: [#348](https://github.com/NG-ZORRO/ng-zorro-antd/issues/348)
```
[ ] Yes
[x] No
```
> nz-table: add nzIsPageIndexReset option

- src/components/modal/nz-modal.service.ts
- src/showcase/nz-demo-modal/nz-demo-confirm-async.component.ts
- src/showcase/nz-demo-modal/nz-demo-modal-service.component.ts
- src/showcase/nz-demo-modal/nz-demo-modal.html
```
[ ] Bugfix
[x] Feature
```
[#365](https://github.com/NG-ZORRO/ng-zorro-antd/issues/365)
```
[ ] Yes
[x] No
```
> feat(module:modal): loading state (confirmLoading) of default footer in modal opened by nzModalService

- src/components/menu/nz-submenu.component.ts
```
[ ] Bugfix
[x] Feature
```
子菜单展开/收起时，高度突变
子菜单展开/收起时，高度变化有动画效果
```
[ ] Yes
[x] No
```
> feature(menu): animate expand/collapse menu

- src/components/input-number/nz-input-number.component.ts
- src/showcase/nz-demo-input-number/nz-demo-input-number.html
```
[ ] Bugfix
[X] Feature
```
Issue Number: #396 
```
[ ] Yes
[X] No
```
如果像 nz-input 一样处理的话，当点击上下按钮时会出发多余的事件，因此我做了一些必要处理。
> feat(module:input-number): add nzBlur & nzFocus property

- src/showcase/nz-demo-input/nz-demo-input.html
```
[ ] Bugfix
[ ] Feature
```
Add note on `textarea` showcase in `nzInput`. Let the description be more complete.
r? @vthinkxie
> docs(showcase): add note to `textarea`

- src/components/calendar/nz-calendar.component.ts
- src/components/datepicker/nz-datepicker.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-disable-date.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #442 
```
[ ] Yes
[X] No
```
> feat(module:datepicker): support [nzDisabledDate] property in month mode

- src/components/tabs/nz-tabset.component.ts
- src/showcase/nz-demo-tabs/nz-demo-tabs-extra.component.ts
- src/showcase/nz-demo-tabs/nz-demo-tabs.html
```
[X] Bugfix
[X] Feature
```
Issue Number: #452
added `[nzTabBarExtraTemplate] ` property to make `#nzTabBarExtraContent` optional
```
[ ] Yes
[X] No
```
> fix(module:tabs): repeat rendering the TabBarExtra when used nested tabs

- src/components/modal/nz-confirm.component.ts
- src/components/modal/nz-modal.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #285 
When the `[nzMaskClosable]` or `maskClosable ` is `false`, disable the esc key
```
[ ] Yes
[X] No
```
考虑到实际使用场景，通过 `maskClosable` 同时控制蒙层及`esc`的行为，就像 ant-react 和 material-angular 一样。
> feat(module:modal): support disable the esc key to close

- src/components/locale/locales/en-US.ts
- src/components/locale/locales/zh-CN.ts
- src/components/locale/nz-locale.class.ts
- src/components/ng-zorro-antd.module.ts
- src/components/transfer/item.ts
- src/components/transfer/nz-transfer-list.component.ts
- src/components/transfer/nz-transfer-search.component.ts
- src/components/transfer/nz-transfer.component.ts
- src/components/transfer/nz-transfer.module.ts
- src/components/transfer/nz-transfer.spec.ts
- src/components/transfer/style/index.less
- src/components/transfer/style/patch.less
- src/showcase/nz-demo-transfer/nz-demo-transfer-advanced.component.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer-basic.component.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer-custom-item.component.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer-search.component.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer.component.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer.html
- src/showcase/nz-demo-transfer/nz-demo-transfer.module.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer.routing.module.ts
- src/showcase/router.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:transfer): add transfer component

- src/components/util/nz-date.pipe.ts
```
[ ] Bugfix
[x] Feature
```
目前，datepicker组件仅仅支持Date类型和数字类型时间戳或字符类型时间戳的输入，其他类型的输入都会被处理成`Invalid date`。
Issue Number: #123 ([feat] about `nzDate` #123), #121 (the value of DatePicker component is only just Date type? #121)
修改后，该组件可以正确显示字符串类型的ISO 8601时间以及数字类型的时间戳，`momentjs`不支持的类型都会显示为`Invalid Date`，充分利用了`momentjs`的兼容能力，如下图所示。
```
[ ] Yes
[x] No
```
> feat(module:datepicker): support string and number type as value

- src/components/pagination/nz-pagination.component.ts
- src/components/table/nz-table.component.ts
- src/showcase/nz-demo-pagination/nz-demo-pagination.html
- src/showcase/nz-demo-table/nz-demo-table.html
```
[ ] Bugfix
[x] Feature
```
support custom the page size changer select values.
Issue Number: #608 
support custom the page size changer select values
```
[ ] Yes
[x] No
```
> feat(module:table and pagination): support custom the page size changer select values(#608)

- .travis.yml
- integration/angular-cli/package.json
- integration/rollup/package.json
- integration/webpack/package.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
Issue Number: execution by sequence.
execution in parallel.
```
[ ] Yes
[x] No
```
Too simple, no need to create issue.
> ci: parallelize build process to speed up

- src/components/select/nz-select.component.ts
- src/showcase/nz-demo-select/nz-demo-select.html
close #676
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:select): support nzScrollToBottom event

- src/components/select/nz-option.component.ts
- src/components/select/nz-select.component.ts
- src/showcase/nz-demo-select/nz-demo-select-pagination.component.ts
- src/showcase/nz-demo-select/nz-demo-select-template.component.ts
- src/showcase/nz-demo-select/nz-demo-select.component.ts
- src/showcase/nz-demo-select/nz-demo-select.html
- src/showcase/nz-demo-select/nz-demo-select.module.ts
close #227
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:select): support custom option template

- src/components/input-number/nz-input-number.component.ts
close #651
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:input-number): check value when press tab key

- src/components/popconfirm/nz-popconfirm.component.ts
- src/components/popover/nz-popover.component.ts
- src/components/tooltip/nz-tooltip.component.ts
- src/components/tooltip/nz-tooltip.directive.ts
close #701, close #631 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #701, #631 
```
[ ] Yes
[x] No
```
> feat(module:tooltip,popover,popconfirm): support hover on the content and don't show when empty

- src/components/datepicker/nz-datepicker.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: fixes #724
```
[ ] Yes
[x] No
```
> fix(module:datepicker): enable simplified boolean usage

- src/components/datepicker/nz-datepicker.component.ts
- src/components/input-number/nz-input-number.component.ts
- src/showcase/nz-demo-input-number/nz-demo-input-number-formatter.component.ts
- src/showcase/nz-demo-input-number/nz-demo-input-number.component.ts
- src/showcase/nz-demo-input-number/nz-demo-input-number.html
- src/showcase/nz-demo-input-number/nz-demo-input-number.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
>  feat(module:input-number): support formatter & parser

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.7): release 0.6.7

- build.sh
- inline-template.js
- package.json
- src/components/button/nz-button.component.html
- src/components/button/nz-button.component.ts
closes #684
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #684 
Enable using `templateUrl` for components.
```
[ ] Yes
[x] No
```
Only made change for button here since it's covered by integration tests. Others can be done in follow ups.
> build: add inline step for templateUrl

- src/components/transfer/nz-transfer.component.ts
- src/components/transfer/nz-transfer.spec.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer-can-move.component.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer.component.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer.html
- src/showcase/nz-demo-transfer/nz-demo-transfer.module.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #793
```
[ ] Yes
[x] No
```
> feat(module:transfer): add canMove property & make component using OnPush

- src/components/calendar/nz-calendar.component.ts
```
[x] Bugfix
[ ] Feature
```
ng-zorro-antd calendar month/year mode view is switched wrongly as I reported the problem in 767.
Issue Number: #767
fixes the month/year mode view
```
[ ] Yes
[x] No
```
> fix(module:calendar): fix month/year view switched

- src/components/transfer/nz-transfer-list.component.ts
- src/components/transfer/nz-transfer.component.ts
- src/components/transfer/nz-transfer.spec.ts
- src/showcase/nz-demo-transfer/nz-demo-transfer-can-move.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:transfer): 1.fix the "checkAll" status not updated 2.change "ArrayObservable.of" to "of"

- src/components/calendar/nz-calendar.component.ts
- src/components/datepicker/nz-datepicker.module.ts
- src/components/datepicker/nz-rangepicker.component.ts
- src/components/datepicker/style/patch.less
- src/components/locale/locales/en-US.ts
- src/components/locale/locales/ru-RU.ts
- src/components/locale/locales/tr-TR.ts
- src/components/locale/locales/zh-CN.ts
- src/components/locale/locales/zh-TW.ts
- src/components/locale/nz-locale.class.ts
- src/components/ng-zorro-antd.module.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-basic.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-disable-date.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-disabled.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-formatter.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-size.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-time.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker.html
- src/showcase/nz-demo-locale/nz-demo-locale-all.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #646 -
```
[ ] Yes
[X] No
```
> feat(module:datepicker): add range-picker component

- src/components/calendar/nz-calendar.component.ts
- src/components/datepicker/nz-datepicker.component.ts
- src/components/datepicker/nz-rangepicker.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-size.component.ts
```
[x] Bugfix
[ ] Feature
```
ng-zorro-antd calendar month/year mode view is switched wrongly as I reported the problem in 767.
Issue Number: #767 
fixes the month/year mode view
```
[ ] Yes
[x] No
```
> fix(module:calendar & datepicker): fix month/year view switched

- src/components/affix/nz-affix.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
add missing tests for affix module to improve the reliability of the
project.
```
[ ] Yes
[x] No
```
> test(module:affix): add affix tests

- src/components/datepicker/nz-rangepicker.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1006
```
[ ] Yes
[X] No
```
> fix(module:datepicker): range-picker reposition browser compatibility

- src/components/upload/nz-upload.component.ts
- src/components/upload/nz-upload.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1038
```
[ ] Yes
[x] No
```
> fix(module:upload): remove unnecessary checks

- components/calendar/nz-calendar-header.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:calendar): use correct classNames

- components/input/nz-input.directive.ts
- components/input/nz-input.spec.ts
- package.json
```
[x] Bugfix
[ ] Feature
```
close #1166 
```
[ ] Yes
[x] No
```
> fix(module:input): fix input disable style in reactive form

- README.md
- components/form/demo/horizontal-login.ts
- components/form/nz-form-control.component.ts
- components/form/nz-form-control.spec.ts
- components/tag/doc/index.en-US.md
- components/tag/doc/index.zh-CN.md
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
close #1170 close #1173
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:form): fix form init style miss & fix doc

- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/nz-tree-node.ts
- components/tree/nz-tree.service.ts
- components/tree/nz-tree.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): add origin param to NzTreeNode

- components/table/nz-th.component.ts
- components/table/nz-th.spec.ts
close #1238
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix table th filter style

- components/mention/demo/async.ts
- components/mention/demo/multiple-trigger.ts
- components/mention/doc/index.en-US.md
- components/mention/doc/index.zh-CN.md
- components/mention/mention.component.ts
- components/mention/mention.spec.ts
```
[ ] Bugfix
[X] Feature
```
```ts
nzOnSearchChange: EventEmitter<string>
```
```ts
export interface MentionOnSearchTypes {
value: string;
prefix: string;
}
nzOnSearchChange: EventEmitter<MentionOnSearchTypes>
```
```
[X] Yes
[ ] No
```
类似 Github 的提及，`@` 和 `#` 会请求不同的接口获取数据。需要在事件中带上触发的前缀才能识别。
> feat(module:mention): add prefix property to nzOnSearchChange payload

- components/input-number/nz-input-number.component.ts
- components/input-number/nz-input-number.spec.ts
```
[x] Bugfix
[ ] Feature
```
After nzFormatter changed, the text on element will not apply the new formatter, unless changes value or unfocus.
Text updates immediately if formatter changed.
```
[ ] Yes
[x] No
```
> fix(module:input-number): fix display value after formatter changed

- PROGRESS.md
- components/time-picker/nz-time-picker-panel.component.spec.ts
- components/time-picker/nz-time-picker-panel.component.ts
- components/time-picker/nz-time-picker.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:time-picker): support null value in time-picker-panel

- components/steps/nz-steps.component.ts
- components/steps/nz-steps.spec.ts
- package.json
close #1418
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:steps): fix steps ngfor

- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1437
```
[ ] Yes
[x] No
```
> fix(module:autocomplete): form related bugs

- components/input-number/nz-input-number.component.ts
- components/input-number/nz-input-number.spec.ts
fix(module:input-number): fix focused style could not be removed after blur (#1449). The reason was when up/down button is clicked, the input is not focused, so it won't emit blur event to remove focused style. Fixed by manually focusing it.
```
[x] Bugfix
[ ] Feature
```
After clicking the up/down button of a `nz-input-number` without focusing it, clicking outside of the `nz-input-number` would not remove …
> fix(module:input-number): fix focused style could not be removed after blur

- components/tabs/doc/index.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
The line about `nzAnimated` is wrong because of conflict between vertical-bar and markdown table.
add Chinese vertical bar to fix the bug
```
[ ] Yes
[x] No
```
> fix(module: tab): fix vertical-bar error in docs

- components/slider/nz-slider.component.ts
- components/slider/nz-slider.spec.ts
Fixes #1529
```
[x] Bugfix
[ ] Feature
```
`nz-slider` in reactive form has incorrect initial value (`setValue` is not executed from `wirteValue` during initialization due to optimazation for "template form" case)
Issue Number: #1529 
`nz-slider` in reactive form has correct initial value that matches value from form control
```
[ ] Yes
[x] No
```
> fix(module:slider) Fix initial value for slider in reactive form

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/picker.component.html
- components/date-picker/picker.component.ts
Fixes #1539
```
[x] Bugfix
[ ] Feature
```
- Date picker can't be opened after it was closed by "Escape" key.
- `nzOnOpenChange` is emitted with `true` when `nzOpen` is `false` and a user clicks on the input (date picker is still hidden, but it's expected behavior)
Issue Number: #1539 
- Date picker works fine after closing by "Escape" key.
- `nzOnOpenChange` is not emitted when `nzOpen` is `false` and a …
> fix(module:date-picker) fix problem with date-picker after "Esc"

- components/components.less
- components/core/animation/select-dropdown-animations.ts
- components/core/animation/select-tag-animations.ts
- components/ng-zorro-antd.module.ts
- components/tree-select/demo/async.md
- components/tree-select/demo/async.ts
- components/tree-select/demo/basic.md
- components/tree-select/demo/basic.ts
- components/tree-select/demo/checkable.md
- components/tree-select/demo/checkable.ts
- components/tree-select/demo/multiple.md
- components/tree-select/demo/multiple.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/index.ts
- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.module.ts
- components/tree-select/nz-tree-select.spec.ts
- components/tree-select/public-api.ts
- components/tree-select/style/index.less
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree-node.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.service.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1391
```
[ ] Yes
[x] No
```
> feat:(module:tree-select): add tree-select component

- components/radio/nz-radio-group.component.ts
- components/radio/nz-radio.spec.ts
close #1543
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:radio): fix nzDisabled in radio-group

- components/checkbox/nz-checkbox-wrapper.component.html
- components/checkbox/nz-checkbox-wrapper.component.ts
- components/checkbox/nz-checkbox.spec.ts
close #1359
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:checkbox): fix invalid setting width via style

- components/tree/demo/dir-tree.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/nz-tree-node.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): support custom property

- components/tree/demo/dir-tree.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> [WIP] fix(module: tree): fix nzOnSearchChange & folder tree demo

- components/modal/nz-modal.component.ts
- components/modal/nz-modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Double click on cancel button or on "mask" of a modal window causes multiple invocations of `ngOnCancel`.
Issue Number: #958 
Only first click on cancel button or "mask" invokes `ngOnCancel`.
```
[ ] Yes
[x] No
```
> fix(module:modal): fix multiple nzOnCancel calls

- build.sh
- package.json
- schematics/README.md
- schematics/ng-add/index.ts
- schematics/ng-add/schema.json
- schematics/ng-add/schema.ts
- schematics/utils/custom-theme.ts
- schematics/utils/lib-versions.ts
- schematics_script/set-theme.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(schematic:ng-add): fix import path in theme file

- schematics/ng-add/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(schematic:ng-add): remove compiled css from styles when use custom theme

- components/alert/nz-alert.component.html
- components/alert/nz-alert.component.ts
Fixes #1666
```
[x] Bugfix
[ ] Feature
```
`nzOnClose` is emitted immediately and as a result, ngIfon alert hides it before the animation is done
Issue Number: #1666
`nzOnClose` is emitted only when a fade animation is finished, so you will be able to see animation if you are controlling the visibility of alert with ngIf
```
[ ] Yes
[x] No
```
> fix(module:nz-alert): emit close after fade animation is done

- components/table/demo/custom-filter-panel.ts
- components/table/nz-th.component.ts
- components/table/nz-th.spec.ts
close #1671 close #1660
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:th): fix table th filter & style bug

- components/carousel/nz-carousel.component.ts
- components/dropdown/nz-dropdown.component.ts
- components/menu/nz-submenu.component.ts
- components/modal/nz-modal.component.ts
- components/pagination/nz-pagination.component.ts
- components/popconfirm/nz-popconfirm.directive.ts
- components/select/nz-option-container.component.ts
- components/steps/nz-steps.component.ts
- components/table/nz-table.component.ts
- components/table/nz-thead.component.ts
- components/time-picker/nz-time-picker-panel.component.ts
- components/timeline/nz-timeline.component.ts
- components/tooltip/nz-tooltip.directive.ts
- components/transfer/nz-transfer.component.ts
```
[ ] Bugfix
[ ] Feature
```
```ts
import { merge } from 'rxjs/operators';
a$.pipe(merge(b$, c$));
// becomes
import { merge } from 'rxjs';
merge(a$, b$, c$);
```
```ts
import { combineLatest } from 'rxjs/operators';
a$.pipe(combineLatest(b$, c$));
// becomes
import { combineLatest } from 'rxjs';
combineLatest(a$, b$, c$);
```
```ts
this.aSubscription = a$.subscribe(...); …
```
> refactor:(module:all): use takeUntil to manage unsubscribe and update deprecations

- components/table/demo/dynamic-settings.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/nz-table.component.html
- components/table/nz-table.component.ts
- components/table/nz-table.spec.ts
close #1599
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:table): support nzSimple option

- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- components/carousel/nz-carousel.component.ts
- components/carousel/nz-carousel.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1711 
```
[ ] Yes
[x] No
```
> feat(module:carousel): support autoplay speed

- components/table/nz-td.component.ts
- components/table/nz-td.spec.ts
- components/table/nz-th.component.ts
- components/table/nz-th.spec.ts
```
[ ] Bugfix
[x] Feature
```
"td" and "th" selector will conflict with user custom component and throw Template parse error: "More than one component matched on this element..."
Issue Number: [#1736](https://github.com/NG-ZORRO/ng-zorro-antd/issues/1736)
"td" and "th" selector will not conflict with user custom component by use “not:(.custom-tag)” in selector
```
[ ] Yes
[x] No
```
> feat(module:table): fix selector error

- components/select/nz-select-top-control.component.html
- components/select/nz-select-top-control.component.ts
```
[x] Bugfix
[ ] Feature
```
Keyboard does't show up on ios
Keyboard show up on ios
```
[ ] Yes
[x] No
```
> fix(module:select): trigger keyboard on ios (#1653)

- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/mention/mention.component.ts
- components/tree-select/nz-tree-select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #1756
```
[ ] Yes
[x] No
```
> fix(module:auto-complete, mention, tree-select): update cdk overlay positioning strategy

- components/date-picker/abstract-picker.component.ts
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/demo/basic.ts
close #1717
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1717
```
[ ] Yes
[x] No
```
> fix(module:date-picker): support changing language at runtime

- components/i18n/languages/ko_KR.ts
fix(i18n) : update of missing field in ko_KR.
Required message field is missing in ko_KR.ts
https://github.com/NG-ZORRO/ng-zorro-antd/issues/1797
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1797 
```
[ ] Yes
[X] No
```
> fix(i18n) : update of missing field in ko_KR.ts

- components/tabs/nz-tabs.spec.ts
- components/tabs/nz-tabset.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1821
Reset `scrollLeft` & `document.activeElement` when scroll.
```
[ ] Yes
[x] No
```
> fix(module:tabs): prevent focus cause scroll offset

- components/input-number/nz-input-number.component.ts
- components/input-number/nz-input-number.spec.ts
close #1706
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1706 
HTML `autofocus` attribute now would work in Chrome.
Instead of using HTML `autofocus`, I manually invoke `focus` method. So `input-number` would focus whenever it get rendered, which may be what users want. See discussions in the issue.
```
[ ] Yes
[x] No
```
> fix(input-number): NzAutoFocus doesn't work or work as expected

- components/input/nz-input-group.component.html
- components/input/nz-input-group.component.ts
- components/input/nz-input.spec.ts
close #1795
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:input): mix using addon and affix

- components/date-picker/date-picker.module.ts
- components/date-picker/demo/basic.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/header-picker.component.html
- components/date-picker/header-picker.component.ts
- components/date-picker/lib/calendar/calendar-header.component.ts
- components/date-picker/lib/lib-packer-supplements.spec.ts
- components/date-picker/year-picker.component.spec.ts
- components/date-picker/year-picker.component.ts
…onth panel
close #1899
```
[ ] Bugfix
[x] Feature
```
Issue Number: #416 
```
[ ] Yes
[x] No
```
> feat(module:date-picker): refactoring and add new feature of year-picker

- components/table/demo/default-filter.md
- components/table/demo/default-filter.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/nz-th.component.ts
- components/table/nz-th.spec.ts
close #1872
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1872 
Users can name some filters as default.
```
[ ] Yes
[x] No
```
> feat(module:table): support default filter

- components/radio/doc/index.en-US.md
- components/radio/doc/index.zh-CN.md
- components/radio/nz-radio-group.component.ts
- components/radio/nz-radio.spec.ts
- components/radio/style/index.less
close #1891
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1891 
Same as https://ant.design/components/radio/#components-radio-demo-radiobutton-solid.
```
[ ] Yes
[x] No
```
I temporarily add style in `index.less`.
> feat(module:radio): add solid button style

- .vscode/launch.json
- components/cascader/demo/search.md
- components/cascader/demo/search.ts
- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
- components/cascader/nz-cascader.component.html
- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.spec.ts
- components/cascader/style/index.less
```
[ ] Bugfix
[x] Feature
```
User can search in Cascader now.
Issue Number: #1773 
User can search options by inputing.
```
[] Yes
[x] No
```
> feat(module:cascader): Add search

- components/components.less
- components/drawer/demo/basic-left.md
- components/drawer/demo/basic-left.ts
- components/drawer/demo/basic-right.md
- components/drawer/demo/basic-right.ts
- components/drawer/demo/from-drawer.md
- components/drawer/demo/from-drawer.ts
- components/drawer/demo/multi-level-drawer.md
- components/drawer/demo/multi-level-drawer.ts
- components/drawer/demo/user-profile.md
- components/drawer/demo/user-profile.ts
- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/index.ts
- components/drawer/nz-drawer.component.html
- components/drawer/nz-drawer.component.ts
- components/drawer/nz-drawer.module.ts
- components/drawer/nz-drawer.spec.ts
- components/drawer/public-api.ts
- components/drawer/style/drawer.less
- components/drawer/style/index.less
- components/ng-zorro-antd.module.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1565
```
[ ] Yes
[x] No
```
> feat(module:drawer): add drawer component

- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.spec.ts
close #1927
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1927 
```
[ ] Yes
[x] No
```
> fix(module:cascader): fix dynamic loading error

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #1934
```
[ ] Yes
[ ] No
```
> fix(module:tree-select): update selected nodes when after set nodes

- components/timeline/doc/index.en-US.md
- components/timeline/doc/index.zh-CN.md
- components/timeline/nz-timeline-item.component.ts
- components/timeline/nz-timeline.spec.ts
close #1956
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1956 
Developers could use CSS color in `[nzColor]`.
```
[ ] Yes
[x] No
```
It's a feature written in doc but not implemented.
> feat(module:timeline): support custom circle color

- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #2053 
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): can't select option when touch

- components/pagination/nz-pagination.component.html
- components/pagination/nz-pagination.component.ts
- components/pagination/nz-pagination.spec.ts
close #2036
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2036 
When the last page shows up, `range[1]` would be `nzTotal`.
```
[ ] Yes
[x] No
```
> fix(module:pagination): take minimum of page range and total

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2012
```
[ ] Yes
[x] No
```
> fix(module:tree-select): unable close when used OnPush

- components/select/nz-select.component.ts
- components/select/nz-select.spec.ts
close #1909
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1909 
User can open and close select panel when select component has focus.
```
[ ] Yes
[x] No
```
Other components may lack of this feature. Maybe we should go through these in next refactor.
> feat(module:select): support open and close panel via keyboard

- components/steps/demo/start-index.md
- components/steps/demo/start-index.ts
- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
- components/steps/nz-steps.component.ts
- components/steps/nz-steps.spec.ts
close #1994
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1994 
Now user can specify the starting index.
```
[ ] Yes
[x] No
```
> feat(module:steps): support customized starting index

- schematics/ng-add/index.ts
- schematics/utils/ast.ts
- schematics/utils/project-main-file.ts
- schematics/utils/project-targets.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: schematics/ng-add
```
```
[ ] Yes
[x] No
```
https://github.com/NG-ZORRO/today-ng-steps/issues/1
> fix(schematics): compatibility with Angular CLI 6.2.0

- components/card/demo/loading.ts
- components/card/nz-card.spec.ts
- components/components.less
- components/list/demo/loadmore.ts
- components/ng-zorro-antd.module.ts
- components/skeleton/demo/active.md
- components/skeleton/demo/active.ts
- components/skeleton/demo/basic.md
- components/skeleton/demo/basic.ts
- components/skeleton/demo/children.md
- components/skeleton/demo/children.ts
- components/skeleton/demo/complex.md
- components/skeleton/demo/complex.ts
- components/skeleton/demo/list.md
- components/skeleton/demo/list.ts
- components/skeleton/doc/index.en-US.md
- components/skeleton/doc/index.zh-CN.md
- components/skeleton/index.ts
- components/skeleton/nz-skeleton.component.html
- components/skeleton/nz-skeleton.component.ts
- components/skeleton/nz-skeleton.module.ts
- components/skeleton/nz-skeleton.spec.ts
- components/skeleton/nz-skeleton.type.ts
- components/skeleton/public-api.ts
- components/skeleton/style/index.less
- components/style/themes/default.less
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1808 
```
[ ] Yes
[x] No
```
> feat(module:skeleton):add skeleton component

- package.json
- publish_scripts/publish.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: modify publish script
```
```
[ ] Yes
[x] No
```
Add version number validation check. Rename npm script because `npm publish` command would run `npm run publish` as well, throwing error unreasonably.
> fix(publish): add version number validation and rename script

- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2104 
If a root node is also a leaf node, it can also be searched and highlighted correctly.
```
[ ] Yes
[x] No
```
> fix(module:cascader): search correctly when a root node is a leaf node

- components/upload/nz-upload-btn.component.ts
Fix typo in exception if no HttpClient provided
```
[ ] Bugfix
[ ] Feature
```
If application doesn't import `HttpClientModule` the `NzUploadBtnComponent` throw exception which says `HttpClientModel` is not provided.
Exception should say that `HttpClientModule` is not provided.
```
[ ] Yes
[x] No
```
> fix(upload): no HttpClient exception typo

- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- docs/changelog.zh-CN.md
- package.json
- schematics/collection.json
- schematics/fix-icon/index.ts
- schematics/fix-icon/schema.json
- schematics/fix-icon/schema.ts
- schematics/ng-add/index.ts
- schematics/ng-add/schema.json
- schematics/utils/devkit-utils/config.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2171
```
[ ] Yes
[x] No
```
> feat(schematics): add fix icon schematic

- LICENSE
- angular.json
- components/button/nz-button.component.ts
- components/button/nz-button.spec.ts
- components/core/util/check.ts
close #2191
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:button): fix button loading bug

- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:icon): fix icon classname writeback

- components/modal/nz-modal.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number:  #2124
```
[ ] Yes
[x] No
```
> feat(module:modal): auto focus when open and restore focus when close

- components/tabs/nz-tabs-nav.component.ts
- components/tabs/nz-tabs.spec.ts
- components/tabs/nz-tabset.component.html
close #1964
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
The class `ant-tabs-bar` which defined in `[nz-tabs-nav]` host is rendered after `ngAfterContentInit` ( this conclusion is only according to my debugging, is there any angular mechanism to point this ? ).
https://github.com/NG-ZORRO/ng-zorro-antd/blob/2d123ebd613aa6900bc8c1552e0b1bd06ea2ee64/components/tabs/nz-tabs-nav.compo …
> fix(module:tabs): hide next and prev buttons

- angular.json
- components/breadcrumb/demo/separator.ts
- components/icon/demo/basic.ts
- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.spec.ts
- components/icon/page/index.ts
- components/ng-zorro-antd.module.ts
- components/package.json
- components/tsconfig.json
- package.json
- schematics/fix-icon/index.ts
- scripts/site/_site/src/app/app.component.ts
```
[ ] Bugfix
[ ] Feature
```
Change dependencies and how users access icons.
```
[ ] Yes
[x] No
```
The fact that `@ant-design/icons` doesn't support tree shake is intolerant. I wrote a new repo as a better solution. See https://github.com/NG-ZORRO/ng-zorro-icons.
> refactor(module:icon): switch dependency to support tree shake

- components/button/nz-button.spec.ts
- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.spec.ts
- components/form/nz-form-control.component.html
- components/icon/demo/basic.ts
- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.service.ts
- components/icon/nz-icon.spec.ts
- components/layout/nz-layout.module.ts
- components/layout/nz-sider.component.html
- components/package.json
- components/pagination/nz-pagination.component.html
- components/pagination/nz-pagination.spec.ts
- components/progress/nz-progress.spec.ts
- components/steps/nz-steps.spec.ts
- package.json
* update dependency to reduce icons requests
* fix class name not changes when `type` changes
* add svg data-icon
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:icon): fix icons problems

- components/package.json
- components/spin/nz-spin.component.html
- components/spin/nz-spin.component.ts
- components/spin/nz-spin.spec.ts
- components/table/nz-table.spec.ts
- package.json
- scripts/site/_site/src/style/patch.less
close #2346
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:spin): fix spin hang error with submenu

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.8.0): release 1.8.0

- components/alert/nz-alert.component.html
- components/alert/nz-alert.component.ts
- components/alert/nz-alert.module.ts
- components/card/nz-card-meta.component.html
- components/card/nz-card-meta.component.ts
- components/card/nz-card.component.html
- components/card/nz-card.component.ts
- components/card/nz-card.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:alert & card): refactor card & refactor template outlet

- components/core/util/convert.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2474
```
[ ] Yes
[x] No
```
> refactor(module:core): refactor input convert decorators

- components/transfer/demo/basic.ts
- components/transfer/demo/search.ts
- components/transfer/doc/index.en-US.md
- components/transfer/doc/index.zh-CN.md
- components/transfer/nz-transfer-list.component.html
- components/transfer/nz-transfer-list.component.ts
- components/transfer/nz-transfer-search.component.html
- components/transfer/nz-transfer-search.component.ts
- components/transfer/nz-transfer.component.html
- components/transfer/nz-transfer.component.ts
- components/transfer/transfer.spec.ts
- feat: add nzDisabled property
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:transfer): refactor transfer

- components/back-top/back-top.spec.ts
- components/back-top/doc/index.en-US.md
- components/back-top/doc/index.zh-CN.md
- components/back-top/nz-back-top.component.ts
- feat: the nzTarget support string value
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:back-top): refactor back-top

- components/anchor/anchor.spec.ts
- components/anchor/demo/basic.ts
- components/anchor/demo/static.ts
- components/anchor/doc/index.en-US.md
- components/anchor/doc/index.zh-CN.md
- components/anchor/nz-anchor-link.component.ts
- components/anchor/nz-anchor.component.html
- components/anchor/nz-anchor.component.ts
- feat: the nzTarget support string value
- fix: invalid id in demo
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:anchor): refactor anchor

- components/select/nz-select-top-control.component.html
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1974 
add title property for select component
```
[ ] Yes
[x] No
```
> fix(module:select): add title property for select component

- components/input-number/nz-input-number.component.ts
- components/input-number/nz-input-number.spec.ts
- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/nz-tab-body.component.html
- components/tabs/nz-tab-body.component.ts
- components/tabs/nz-tab-label.directive.ts
- components/tabs/nz-tab.component.ts
- components/tabs/nz-tabs-ink-bar.directive.ts
- components/tabs/nz-tabs-nav.component.ts
- components/tabs/nz-tabs.module.ts
- components/tabs/nz-tabs.spec.ts
- components/tabs/nz-tabset.component.html
- components/tabs/nz-tabset.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:tabs): support forceRender in tabs

- components/list/nz-list.component.ts
- components/upload/demo/avatar.ts
- components/upload/demo/filter.ts
- components/upload/interface.ts
- components/upload/nz-upload-btn.component.ts
- components/upload/upload.spec.ts
- fix(module:list): fix missing :host
- #2389
```
[ ] Bugfix
[x] Feature
```
Issue Number: 
```
[ ] Yes
[x] No
```
> feat(module:upload): support Observable in nzFilter

- schematics/ng-add/index.ts
- schematics/ng-add/schema.json
- schematics/ng-add/schema.ts
- schematics/ng-add/setup-project/add-animations-module.ts
- schematics/ng-add/setup-project/add-required-modules.ts
- schematics/ng-add/setup-project/index.ts
- schematics/ng-add/setup-project/register-locale.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(schematics): compatible with old version options

- components/input/demo/autosize-textarea.ts
- components/input/nz-autoresize.directive.ts
close #2646
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:input): fix input autoresize

- components/form/demo/validate-static.ts
Fix typo in Template-driven Forms Validation text
```
[ ] Bugfix
[ ] Feature
```
The text in field "Validating" in the Template-driven Forms Validation demo says `The content is being validating` and the validation message says `I'm the content is being validating`
The text should say `The content is being validated` and `I'm validating the content`
```
[ ] Yes
[x] No
```
> fix(form): Template-driven Forms Validation typo

- components/i18n/languages/fr_FR.ts
```
[ ] Bugfix
[x] Feature
```
support fr-FR for NzI18nService.
```
[ ] Yes
[x] No
```
> feat(module:i18n): update missing fields in fr_FR(NG-ZORRO#2586)

- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.module.ts
- components/tree-select/nz-tree-select.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:tree-select): support set `nzNotFoundContent`

- scripts/build/generate-less.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
```less
// win32
@import "./affix\style\index.less";
@import "./alert\style\index.less";
@import "./anchor\style\index.less";
@import "./auto-complete\style\index.less";
// posix
@import "./affix/style/index.less";
@import "./alert/style/index.less";
@import "./anchor/style/index.less";
@import "./auto-complete/style/index.less";
```
> build: fix style path error on Windows platform

- components/avatar/avatar.spec.ts
- components/breadcrumb/nz-breadcrumb.spec.ts
- components/button/nz-button.spec.ts
- components/divider/divider.spec.ts
- components/dropdown/nz-dropdown.spec.ts
- components/icon/demo/namespace.md
- components/icon/demo/namespace.ts
- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- components/icon/nz-icon-test.module.ts
- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.service.ts
- components/layout/nz-layout.spec.ts
- components/list/list.spec.ts
- components/mention/nz-mention.spec.ts
- components/menu/nz-menu.spec.ts
- components/modal/nz-modal.spec.ts
- components/package.json
- components/popconfirm/nz-popconfirm.spec.ts
- components/popover/nz-popover.spec.ts
- components/spin/nz-spin.spec.ts
- components/steps/nz-steps.spec.ts
- components/switch/nz-switch.spec.ts
- components/tooltip/nz-tooltip.spec.ts
- components/transfer/transfer.spec.ts
- components/tree/nz-tree.spec.ts
- components/upload/upload.spec.ts
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update a dependency
```
```
[ ] Yes
[x] No
```
> feat(module:icon): update dependency to support namespace

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/nz-modal.component.html
- components/modal/nz-modal.component.ts
- components/modal/nz-modal.spec.ts
- components/modal/nz-modal.type.ts
```
[ ] Bugfix
[x] Feature
```
Modal doesn't support set `nzOkDisabled` and `nzCancelDisabled`
Issue Number: #1838
Modal support set `nzOkDisabled` and `nzCancelDisabled`
```
[ ] Yes
[x] No
```
> feat(module:modal): support set `nzOkDisabled` and `nzCancelDisabled`

- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.spec.ts
- components/input/demo/addon.ts
- components/input/nz-input-group.component.html
- components/input/nz-input-group.spec.ts
- components/input/nz-input.spec.ts
- components/table/nz-thead.spec.ts
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
Fix some test failures because `NzIconTestModule` is not imported.
> feat(module:input): fix *fix icon new api capability

- components/empty/nz-empty.component.html
- components/empty/nz-empty.component.ts
- components/empty/nz-empty.spec.ts
- components/icon/nz-icon.service.ts
- components/table/nz-table.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:empty): fix locale cannot change dynamically

- components/core/util/keycodes.ts
- components/core/util/public-api.ts
- components/icon/nz-icon.service.ts
- components/rate/demo/text.ts
- components/rate/doc/index.en-US.md
- components/rate/doc/index.zh-CN.md
- components/rate/nz-rate-item.component.html
- components/rate/nz-rate-item.component.ts
- components/rate/nz-rate.component.html
- components/rate/nz-rate.component.ts
- components/rate/nz-rate.module.ts
- components/rate/nz-rate.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:rate): add tooltip support

- scripts/site/_site/src/app/app.component.html
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/app.module.ts
- scripts/site/_site/src/style/common.less
- scripts/site/_site/src/style/drawer.less
- scripts/site/_site/src/style/footer.less
- scripts/site/_site/src/style/icons.less
- scripts/site/_site/src/style/index.less
- scripts/site/_site/src/style/patch.less
- scripts/site/_site/src/style/responsive.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: optimize mobile experience

- components/cascader/nz-cascader.component.ts
close #2181, #2809
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:cascader): reposition cascader when column opens

- components/cascader/nz-cascader.component.html
close #2903 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cascader): fix empty shown when searching value

- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2885
```
[ ] Yes
[x] No
```
> feat(module:auto-complete): close panel when the trigger element blur

- components/notification/demo/template.md
- components/notification/demo/template.ts
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/notification/nz-notification.component.html
- components/notification/nz-notification.definitions.ts
- components/notification/nz-notification.spec.ts
close #2755
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2755
Now user can pass an `nzData` when use template in notification, this `nzData` would be access in the template with name `data`.
```
[ ] Yes
[ ] No
```
> feat(module:notification): support nzData as context in template

- components/collapse/demo/custom.ts
- components/collapse/doc/index.en-US.md
- components/collapse/doc/index.zh-CN.md
- components/collapse/nz-collapse-panel.component.html
- components/collapse/nz-collapse-panel.component.ts
- components/collapse/nz-collapse.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: revert support of `nzExtra` of `nz-collapse-header` since it's not officially merged to master branch of ant design.
```
```
[ ] Yes
[x] No, since it never got released
```
> revert(module:collapse): remove extra field

- components/calendar/demo/basic.ts
- components/calendar/demo/select.ts
- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
- components/calendar/nz-calendar.component.ts
- components/calendar/nz-calendar.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2769 
```
[ ] Yes
[x] No
```
> feat(module:calendar): sync some changes from ant-design (#2769)

- components/message/demo/close.md
- components/message/demo/close.ts
- components/message/doc/index.en-US.md
- components/message/doc/index.zh-CN.md
- components/message/nz-message-container.component.ts
- components/message/nz-message.component.ts
- components/message/nz-message.definitions.ts
- components/message/nz-message.service.ts
- components/message/nz-message.spec.ts
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/notification/nz-notification-container.component.ts
- components/notification/nz-notification.component.ts
- components/notification/nz-notification.definitions.ts
- components/notification/nz-notification.spec.ts
close #2458
```
[ ] Bugfix
[x] Feature
```
There is a `onClose` subject on both `NzMessageDataFilled` and `NzNotificationDataFilled` and a `onClick` on `NzMessageDataFilled`. They would emit events as their names suggest. And especially, `onClose` would emit a `true` if it's closed by user.
```
[ ] Yes
[x] No
```
> feat(module:message,notification): add close event

- components/slider/demo/basic.ts
- components/slider/demo/event.ts
- components/slider/demo/mark.md
- components/slider/demo/mark.ts
- components/slider/demo/vertical.ts
- components/slider/doc/index.en-US.md
- components/slider/doc/index.zh-CN.md
- components/slider/nz-slider-error.ts
- components/slider/nz-slider.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:slider): fix defaultValue check error

- components/cascader/nz-cascader-li.component.ts
- components/cascader/nz-cascader.component.ts
- components/icon/nz-icon-test.module.ts
- components/icon/public-api.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cascader): fix children state not changed in async demo

- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tree-select): fix nzNodes type

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
- components/tree/demo/basic.ts
- components/tree/demo/customized-icon.ts
- components/tree/demo/directory.ts
- components/tree/demo/draggable.ts
- components/tree/demo/dynamic.ts
- components/tree/demo/line.ts
- components/tree/demo/search.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/nz-tree-base.service.ts
- components/tree/nz-tree-node.component.html
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree-node.ts
- components/tree/nz-tree.component.html
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.spec.ts
close #3001
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3001 
```
[ ] Yes
[x] No
```
> fix(module: tree): fix default keys bug with setTimeOut

- components/steps/nz-step.component.ts
- components/steps/nz-steps.component.ts
- components/steps/nz-steps.spec.ts
```
[x] Bugfix
[ ] Feature
```
when we use steps under onpush stategy , modify the nzCurrent can correct diplay step status.
```
[ ] Yes
[x] No
```
> fix(module:steps): fix steps state change error under onpus strategy

- components/table/demo/default-filter.ts
- components/table/nz-th.component.html
- components/table/nz-th.component.ts
- components/table/nz-th.spec.ts
close #3028 close #3056 close #3058
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix th check not trigger bug

- components/table/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix some doc spelling mistake errors

- components/message/doc/index.en-US.md
- components/message/doc/index.zh-CN.md
- components/message/nz-message.component.html
- components/message/nz-message.definitions.ts
- components/message/nz-message.module.ts
- components/message/nz-message.service.ts
- components/message/nz-message.spec.ts
close #3081
```
[ ] Bugfix
[x] Feature
```
A user cannot pass a `TemplateRef` to `content`. They have to use inline HTML.
Issue Number: #3081
Now a user can pass a `TemplateRef<void>` to `content`.
```
[ ] Yes
[x] No
```
> feat(module:message): support template

- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/app.routing.module.ts
```
[ ] Bugfix
[ ] Feature
```
Now the docs site would be in English. Add when the doc site boots up and language is not specified in URL, it would detect visitor's language and redirect to Chinese doc if needed.
```
[ ] Yes
[ ] No
```
> docs: add browser language detection

- components/input/demo/autosize-textarea.md
- components/input/nz-autoresize.directive.ts
- components/input/nz-autosize.directive.ts
- components/input/nz-autosize.spec.ts
- components/input/nz-input.module.ts
- components/modal/nz-modal.component.html
- components/modal/nz-modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2286, #2713
```
[ ] Yes
[x] No
```
> fix(module:modal): integrate with tabs and autosize

- components/affix/nz-affix.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3040
After triggering the resize event, the Affix element will not lose height and behave normally.
```
[ ] Yes
[x] No
```
> fix(module:affix): set correct style of Affix after trigger resize

- components/collapse/demo/extra.md
- components/collapse/demo/extra.ts
- components/collapse/doc/index.en-US.md
- components/collapse/doc/index.zh-CN.md
- components/collapse/nz-collapse-panel.component.html
- components/collapse/nz-collapse-panel.component.ts
- components/collapse/nz-collapse.spec.ts
- components/collapse/style/index.less
- components/style/themes/default.less
- scripts/site/_site/doc/theme.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:collapse): support `nzExtra`

- components/i18n/languages/ca_ES.ts
- components/i18n/languages/pagination/ca_ES.ts
```
[X] Bugfix
[ ] Feature
```
This pull request fixes the missing catalan translations.
Issue Number: [#2569](https://github.com/NG-ZORRO/ng-zorro-antd/issues/2569)
```
[ ] Yes
[X] No
```
> fix(module:i18n): fix catalan translations

- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/nz-form-item.component.ts
- components/form/nz-form-label.component.html
- components/form/nz-form-label.component.ts
- components/form/nz-form-label.spec.ts
- components/form/nz-form.directive.ts
- components/form/nz-form.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Sync https://github.com/ant-design/ant-design/pull/15276
Ref https://github.com/ant-design/ant-design/issues/15585
> feat(module:form): support hide the label colon

- components/tree/nz-tree.component.ts
close #3320
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3320
```
[ ] Yes
[x] No
```
> fix(module: tree): fix nodes list to render correctly

- components/radio/nz-radio.component.ts
- components/tabs/nz-tabs-nav.component.ts
Prevent memory leaks for radio and tabs components.
```
[x] Bugfix
[ ] Feature
```
No change with behavior.
```
[ ] Yes
[x] No
```
When I used the site of ng.ant.design,  I found there are other memory leaks  in ng-zorro.
> fix(module:radio, tab): Fixed memory leak problem.

- components/cascader/nz-cascader.component.ts
- components/checkbox/nz-checkbox-group.component.ts
- components/switch/nz-switch.component.ts
- components/tooltip/nz-tooltip.directive.ts
```
[x] Bugfix
[ ] Feature
```
Fix memory leak problem.
```
[ ] Yes
[x] No
```
> fix(module:cascader,checkbox,switch,tooltip): fix memory leak problem

- components/tree-select/demo/customized-icon.md
- components/tree-select/demo/customized-icon.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.ts
Close #3330 
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
tree-select 初始状态下无法获取 `treeRef`，所以在 tree 里面加了 `nzTreeSelectTemplate` 来传递 template
> feat(module:tree-select): support customized icon

- components/menu/nz-menu.spec.ts
- components/menu/nz-submenu.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3434
```
[ ] Yes
[x] No
```
> fix(module:menu): submenu should not remain highlighted

- components/modal/nz-modal.component.html
- components/modal/nz-modal.component.ts
- components/modal/nz-modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3394
```
[ ] Yes
[ ] No
```
> fix(module:modal): should not close when mousedown in the body

- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: set @angular/compiler version in stackblitz

- components/cascader/nz-cascader.service.ts
close #3480
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:cascader): fix reset trigger redraw

- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- components/carousel/nz-carousel-definitions.ts
- components/carousel/nz-carousel.component.ts
- components/carousel/nz-carousel.spec.ts
- components/carousel/public-api.ts
- components/test.ts
- tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Users can provide custom strategies to make transitions between carousel items.
```
[ ] Yes
[x] No
```
> feat(module:carousel): support custom strategies

- components/button/demo/basic.ts
- components/button/demo/block.ts
- components/button/demo/disabled.ts
- components/button/demo/ghost.ts
- components/button/demo/size.ts
- components/button/doc/index.en-US.md
- components/button/doc/index.zh-CN.md
- components/button/nz-button.component.ts
- components/button/nz-button.spec.ts
- components/button/style/index.less
- components/button/style/mixin.less
- components/core/wave/nz-wave-renderer.ts
- components/core/wave/nz-wave.directive.ts
- components/core/wave/nz-wave.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:button): support link type

- components/auto-complete/nz-autocomplete-trigger.directive.ts
change previousValue setting logics to openPanel
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix tests failed
```
case `should reset the backfilled value display when pressing tabbing` would fail now,
because `previousValue` was not updated when invoking `openPanel`. To solve the problem, we need to change `openPanel` to `handleFocus` in test or put `previousValue` updating logics into `openPanel` in …
> refactor(module:auto-complete): refactor and fix tests

- components/select/nz-select.service.spec.ts
- components/select/nz-select.service.ts
close #3424 close #3563
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select tag option display

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(7.5.1): release 7.5.1

- docs/faq.en-US.md
```
[ ] Bugfix
[ ] Feature
```
Currently it's telling people to exclude Angular of search results.
Corrected to tell people to exclude Angular.js
```
[ ] Yes
[x] No
```
> docs: fix wrong mention of angular -> angular.js

- components/table/nz-thead.component.ts
- components/table/nz-thead.spec.ts
sortChange() called multiple times after columns changed
```
[x ] Bugfix
[ ] Feature
```
Issue Number:  #3603
Fixes #3603 
```
[ ] Yes
[x] No
```
> fix(module:table): fix sortChange with dynamic columns (#3603)

- components/page-header/nz-page-header.component.html
- components/page-header/nz-page-header.component.ts
- components/page-header/nz-page-header.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #3569
```
[ ] Yes
[x] No
```
> chore: sync with antd 3.19

- components/input/nz-input-group.component.html
- ~Docs have been added / updated (for bug fixes / features)~ N/A
```
[x] Bugfix
[ ] Feature
```
Projected content inside of an `<nz-input-group>` disappears when `[nzAddOnBeforeIcon]` is updated.
Issue Number: #3596
Projected content is displayed, `[nzAddOnBeforeIcon]` behaves correctly.
```
[ ] Yes
[x] No
```
I attempted to add tests, but I find angular testing difficult and could not come up with …
> fix(module:input): fix ng-content [nzAddOnBeforeIcon] content projection

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
Docs update
```
[ ] Bugfix
[ ] Feature
```
Incorrect valid values specified
Corrected
```
[ ] Yes
[x] No
```
N/A
> docs(typo): Specify valid values for select#nzNotFoundContent

- scripts/site/_site/doc/app/app.component.ts
- ~~[ ] Tests for the changes have been added (for bug fixes / features)~~
```
[ ] Bugfix
[ ] Feature
```
Fix a responsive design bug by making the menu collapse at a wider screen width.
```
[ ] Yes
[x] No
```
> docs: fix responsive

- components/select/demo/custom-template.md
- components/select/demo/custom-template.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/nz-select-top-control.component.html
- components/select/nz-select-top-control.component.ts
- components/select/nz-select.component.html
- components/select/nz-select.component.spec.ts
- components/select/nz-select.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2946
```
[ ] Yes
[x] No
```
> feat(module:select): support custom template in select component

- components/breadcrumb/demo/dropdown.md
- components/breadcrumb/demo/dropdown.ts
- components/breadcrumb/nz-breadcrumb-item.component.html
- components/breadcrumb/nz-breadcrumb-item.component.ts
- components/breadcrumb/nz-breadcrumb.module.ts
- components/breadcrumb/nz-breadcrumb.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:breadcrumb): support dropdown

- components/i18n/date-helper.service.ts
- components/pagination/nz-pagination.component.html
- components/pagination/nz-pagination.spec.ts
close #3648
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:pagination): fix pagination nzTotal 0 bug

- components/mention/demo/controlled.ts
- components/mention/doc/index.en-US.md
- components/mention/doc/index.zh-CN.md
- components/mention/nz-mention-trigger.ts
- components/mention/nz-mention.component.ts
- components/mention/nz-mention.service.ts
- components/mention/nz-mention.spec.ts
- components/mention/public-api.ts
close #3629
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:mention): fix cannot to switch trigger

- components/descriptions/demo/border.ts
- components/descriptions/nz-descriptions.component.ts
- components/descriptions/nz-descriptions.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix a demo
```
```
[ ] Yes
[ ] No
```
> fix(module:descriptions): fix warning without logger

- components/dropdown/nz-context-menu.service.ts
close #3768
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:dropdown): fix dropdown contextmenu

- components/modal/nz-modal.component.html
- components/modal/nz-modal.component.ts
- components/modal/nz-modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3679
```
[ ] Yes
[x] No
```
> fix(module:modal): buttons cannot disable when confirm mode

- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
- components/dropdown/nz-dropdown.directive.spec.ts
- components/dropdown/nz-dropdown.directive.ts
Needs someone that translate the documentation to Chinese, I'm afraid I cannot :smile:  
See "current behavior" for explanation.
```
[ ] Bugfix
[X] Feature
```
Currently the backdrop is enforced when using `trigger = 'click'`.  
This causes **usability problems** when used in conjunction, for example, with a custom table filter.
The backdrop can be disabled by setting `nzBackdrop = false`.
```
[ ] Yes
[X] …
```
> feat(module:dropdown): allow backdrop to be disabled

- components/date-picker/lib/popups/inner-popup.component.html
```
[ x] Bugfix
[ ] Feature
```
Binding `nzShowTime` of a date-picker to an object that has `nzUse12Hours` set to `true` has no effect on a time picker, it still uses 24 hour picker.
Binding the nzShowTime input of a date-picker to an object that has nzUse12Hours set to true modifies the time picker to use 12 hours format picker as expected.
```
[ ] Yes
[ x] No
```
> fix(module:date-picker): missing nzUse12Hours binding

- components/core/util/measure-scrollbar.ts
- components/page-header/demo/module
- components/page-header/nz-page-header-cells.ts
- components/page-header/nz-page-header.component.html
- components/page-header/nz-page-header.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:page-header): fix page-header style break change

- components/select/nz-select-top-control.component.html
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3710
```
[ ] Yes
[x] No
```
> fix(module:select): fix single selection choice content display issues

- components/descriptions/doc/index.zh-CN.md
- components/descriptions/nz-descriptions-item.component.ts
- components/descriptions/nz-descriptions.component.ts
- components/descriptions/nz-descriptions.spec.ts
- components/page-header/doc/index.zh-CN.md
close #3795
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3795 
Changes to the inputs of `nz-description-item` would be updated.
```
[ ] Yes
[x] No
```
> fix(module:descriptions): fix changes to inputs of children not working

- components/ng-zorro-antd.module.ts
- components/version.ts
- components/version/index.ts
- components/version/package.json
- components/version/public-api.ts
- components/version/version.ts
- docs/universal.en-US.md
- docs/universal.zh-CN.md
- schematics/ng-update/index.ts
- scripts/release/release.ts
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
- scripts/site/generate-site.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:version): add secondary entries

- components/modal/demo/confirm.md
- components/modal/demo/footer2.md
- components/modal/demo/footer2.ts
- components/modal/demo/info.md
- components/modal/demo/locale.md
- components/modal/demo/manual.md
- components/modal/demo/position.md
- components/modal/demo/service.md
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/nz-modal-footer.directive.spec.ts
- components/modal/nz-modal-footer.directive.ts
- components/modal/nz-modal.component.html
- components/modal/nz-modal.component.ts
- components/modal/nz-modal.module.ts
- components/modal/public-api.ts
- package.json
close #3035
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:modal): support use directive to define the footer

- components/dropdown/nz-dropdown.directive.spec.ts
- components/dropdown/nz-dropdown.directive.ts
```
[X] Bugfix
[ ] Feature
```
After PR https://github.com/NG-ZORRO/ng-zorro-antd/pull/3769, I noticed that to exit the dropdown, one must click on the backdrop DOM element.  
Being with `nzBackdrop=false` there was no such element, it was not possible to hide the visible dropdown.
When `nzBackdrop=false`, the backdrop is present, but `opacity` is always set to `0`.  
Also, the `Escape` functionality to …
> fix(module:dropdown): restore escape and hide backdrop when disabled

- components/tsconfig.lib.json
```
[ ] Bugfix
[ ] Feature
[X] Build related changes
```
Declarations annotated with `@internal` are not preserved in `d.ts` files.  
An example might come from the PR https://github.com/NG-ZORRO/ng-zorro-antd/pull/3766
https://github.com/NG-ZORRO/ng-zorro-antd/blob/386b962792a1ea5b1003b4d93c46e7dd6c5774b1/components/table/nz-table.component.ts#L73-L79
As you can see, the `viewChange` field is used internally. There is no point in …
> build(module:*): strip internal-annotated declarations

- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3833
```
[ ] Yes
[x] No
```
> fix(module:tree-select): should not close when the selectable is false

- components/date-picker/lib/calendar/calendar-input.component.html
- components/date-picker/lib/calendar/calendar-input.component.ts
- components/date-picker/lib/popups/date-range-popup.component.html
- components/date-picker/nz-date-picker.component.spec.ts
- components/date-picker/nz-month-picker.component.spec.ts
- components/date-picker/nz-range-picker.component.spec.ts
- components/date-picker/nz-year-picker.component.spec.ts
- components/date-picker/picker.component.html
- components/date-picker/picker.component.ts
Extracted the good parts suitable for a11y from #3146. See discussion there.
```
[X] Bugfix
[ ] Feature
```
Opening date-picker with keyboard is not possible.
Opening date-picker by a click, does not focus on the inner input element.
You can open date-picker pressing enter on the keyboard when the wrapper element is selected.
Once date-picker is open, the inner input element is selected, …
> fix(module:date-picker): open on enter and focus on inner input

- components/calendar/date-table.component.ts
- components/date-picker/nz-date-picker.component.spec.ts
close #2576, close #1949
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): keep the time value while clicking date

- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/nz-tabset.component.ts
close #3858
```
[ ] Bugfix
[x] Feature
```
Issue Number: #3858
```
[ ] Yes
[x] No
```
> feat(module:tabs): add router exact active parameter

- components/core/testing/public-api.ts
- components/timeline/demo/color.md
- components/timeline/demo/color.ts
- components/timeline/doc/index.en-US.md
- components/timeline/doc/index.zh-CN.md
- components/timeline/nz-timeline-item.component.html
- components/timeline/nz-timeline-item.component.ts
- components/timeline/nz-timeline.spec.ts
- components/timeline/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
It works with the latest style update #3921.
> feat(module:timeline): add gray as a default color

- components/core/logger/logger.ts
- components/core/services/nz-singleton.service.ts
- components/core/services/public-api.ts
- components/message/demo/info.md
- components/message/nz-message-base.service.ts
- components/message/nz-message.service.ts
- components/message/nz-message.spec.ts
- components/notification/nz-notification.service.ts
close #3845
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3845 
```
[ ] Yes
[x] No
```
> fix(module:message): fix container instance not destroyed in HMR

- schematics/ng-add/index.ts
- schematics/ng-generate/side-menu/index.ts
- schematics/utils/project-style.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): `ng-add` identify the project style extension

- components/page-header/doc/index.en-US.md
- components/page-header/doc/index.zh-CN.md
- components/page-header/nz-page-header.component.ts
- components/page-header/nz-page-header.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #3421
```
[ ] Yes
[x] No
```
> feat(module:page-header): add default behavior for the back button

- components/avatar/avatar.spec.ts
- components/avatar/doc/index.en-US.md
- components/avatar/doc/index.zh-CN.md
- components/avatar/nz-avatar.component.html
- components/avatar/nz-avatar.component.ts
close #3223 
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:avatar): support image load error event

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/nz-drawer-options.ts
- components/drawer/nz-drawer-ref.ts
- components/drawer/nz-drawer.component.ts
- components/drawer/nz-drawer.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:drawer): support `nzKeyboard` property

- components/descriptions/doc/index.en-US.md
- components/descriptions/doc/index.zh-CN.md
- components/descriptions/nz-descriptions.component.html
- components/descriptions/nz-descriptions.component.ts
- components/descriptions/style/index.less
- components/progress/nz-progress.component.html
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
It works with the latest style update #3921.
> feat(module:descriptions): add nzColon to toggle colon

- components/badge/doc/index.en-US.md
- components/badge/doc/index.zh-CN.md
- components/badge/nz-badge.component.html
- components/badge/nz-badge.component.ts
- components/badge/nz-badge.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:badge): support nzTitle and nzOffset property

- components/date-picker/demo/basic.ts
- components/date-picker/lib/lib-packer-supplements.spec.ts
- components/date-picker/lib/popups/date-range-popup.component.ts
- components/date-picker/nz-range-picker.component.spec.ts
close #3940, close #1642 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): sort range picker value when start is after end

- components/code-editor/nz-code-editor.component.ts
```
[x] Bugfix
[ ] Feature
```
Open code editor's page and quickly switch to another component's page before monaco editor is rendered.
When the editor is destroying, it checks if `editorInstance` is truthy before calling `dispose` method on it.
```
[ ] Yes
[x] No
```
> fix(module:editor): fix destroying error when editor is not initialized

- components/tabs/nz-tabset.component.ts
close #3873
```
[x] Bugfix
[ ] Feature
```
When no route is matched, the tabs component would set `nzHideAll` to `true`.
```
[ ] Yes
[x] No
```
> fix(module:tabs): fix tabs still shows when no route is matched

- components/table/style/patch.less
Reverts NG-ZORRO/ng-zorro-antd#3849
It will cause another issue of small table hover style. Ant design has fixed small sticky style (https://github.com/NG-ZORRO/ng-zorro-antd/commit/0608f4596bce89ad5b59124adfdecf182e8038b5#diff-6f1e26fcf688fcefd89a8725673c03abR78)
> revert: table small sticky style

- components/tabs/nz-tabset.component.ts
close #3873
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3873
```
[ ] Yes
[x] No
```
> fix(module:tabs): fix selected index not updated

- components/i18n/languages/ca_ES.ts
```
[x] Bugfix
[ ] Feature
```
Catalan translations were wrong.
```
[ ] Yes
[x] No
```
> fix(module:i18n): missing catalan translations added

- components/cascader/nz-cascader.service.ts
- components/cascader/nz-cascader.spec.ts
close #4110
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4110
Value could be falsy value expect for `undefined` and `null`.
```
[ ] Yes
[x] No
```
> fix(module:cascader): support falsy value expect for undefined and null

- components/code-editor/demo/complex.ts
- components/code-editor/demo/full-control.ts
close #4099 
```
[ ] Bugfix
[ ] Feature
```
Remove `any` as much as possible in the demo.
```
[ ] Yes
[x] No
```
> docs(module:editor): fix type any

- components/core/testing/event-objects.ts
- components/resizable/nz-resizable-utils.ts
- components/resizable/nz-resizable.directive.ts
- components/resizable/nz-resizable.service.ts
- components/resizable/nz-resizable.spec.ts
- components/resizable/nz-resize-handle.component.ts
- components/resizable/public-api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> perf(module:resizable): listen document events when resizing start

- components/steps/demo/clickable.ts
- components/steps/demo/nav.md
- components/steps/demo/nav.ts
- components/steps/demo/simple.ts
- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
- components/steps/nz-step.component.html
- components/steps/nz-step.component.ts
- components/steps/nz-steps.component.ts
- components/steps/nz-steps.spec.ts
- components/steps/style/index.less
- components/steps/style/nav.less
- components/steps/style/small.less
- components/steps/style/vertical.less
```
[ ] Bugfix
[x] Feature
```
Issue Number: #3931
```
[ ] Yes
[x] No
```
> feat(module:steps): support navigation type and nzDisable nzSubtitle

- components/popconfirm/nz-popconfirm.directive.ts
- components/slider/doc/index.en-US.md
- components/slider/doc/index.zh-CN.md
- components/slider/nz-slider-handle.component.html
- components/slider/nz-slider-handle.component.ts
- components/slider/nz-slider.component.html
- components/slider/nz-slider.component.ts
- components/tooltip/base/nz-tooltip-base.directive.ts
```
[ ] Bugfix
[x] Feature
```
Users can set the default position of the tooltip by `nzTooltipPlacement`.
```
[ ] Yes
[x] No
```
> feat(module:slider): support nzTooltipPlacement

- components/i18n/languages/ar_EG.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4159
all localization for ar_EG should be displayed in arabic
```
[ ] Yes
[x] No
```
> fix(module:i18n): added property missing in ar_EG

- components/progress/demo/gradient.ts
- components/progress/nz-progress-utils.spec.ts
- components/progress/nz-progress-utils.ts
- components/progress/nz-progress.component.html
- components/progress/nz-progress.component.ts
- components/progress/nz-progress.definitions.ts
- components/progress/public-api.ts
close #4176 
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4176 
Circle gradient stops would now be sorted.
```
[ ] Yes
[x] No
```
> fix(module:progress): fix circle gradient not sorted

- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix dependency
```
```
[ ] Yes
[x] No
```
> chore(module:*): lock @types/jasmine version to avoid a bug

- README-zh_CN.md
- README.md
- components/select/demo/automatic-tokenization.ts
- components/select/demo/basic.ts
- components/select/demo/coordinate.ts
- components/select/demo/custom-content.ts
- components/select/demo/custom-dropdown-menu.ts
- components/select/demo/custom-template.ts
- components/select/demo/default-value.ts
- components/select/demo/frontend-search.md
- components/select/demo/frontend-search.ts
- components/select/demo/hide-selected.ts
- components/select/demo/label-in-value.ts
- components/select/demo/multiple.ts
- components/select/demo/optgroup.ts
- components/select/demo/scroll-load.ts
- components/select/demo/search-box.ts
- components/select/demo/search.ts
- components/select/demo/select-users.ts
- components/select/demo/size.ts
- components/select/demo/tags.ts
- components/select/nz-select-top-control.component.html
- components/select/nz-select-top-control.component.ts
- components/select/nz-select-top-control.spec.ts
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
close #2427 close #3907
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select input not grow correctly in IE

- components/core/config/config.ts
- components/spin/doc/index.en-US.md
- components/spin/doc/index.zh-CN.md
- components/spin/nz-spin.component.ts
- components/spin/nz-spin.spec.ts
close #2792
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2792
```
[ ] Yes
[x] No
```
> feat(module:spin): support global indicator

- components/i18n/date-helper.service.ts
Close #3854 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:time-picker): add null input judgement when using datefns

- components/core/animation/collapse.ts
- components/tree/nz-tree-node.component.html
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.spec.ts
- components/tree/style/patch.less
Change the collapsed of the treeNode from display: none to *ngIf.
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #4182 
Use `display: none` to collapse treeNode.
Change the collapsed of the treeNode from `display: none` to `*ngIf`.
```
[ ] Yes
[x] No
```
> perf(module:tree): change the collapsed of the treeNode to ngIf

- components/tooltip/base/nz-tooltip-base.directive.ts
close #4103
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip): fix tooltip component not destory

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/tooltip/base/nz-tooltip-base.directive.ts
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:tooltip etc): trigger could be null

- docs/global-config.en-US.md
closes #4318
```
[ ] Bugfix
[ ] Feature
```
See issue.
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/4318
Plus fixed a typo: Dynamically <s>Chaing</s>Chaining Configurations
```
[ ] Yes
[x] No
```
> docs: explain how to submit TemplateRef instances in global config

- components/page-header/nz-page-header.component.ts
- components/page-header/style/index.less
```
[x] Bugfix
[ ] Feature
```
Issue Number:  https://github.com/NG-ZORRO/ng-zorro-antd/pull/4208#pullrequestreview-302491480
```
[ ] Yes
[x] No
```
> fix(module:page-header): fix break change on the style

- components/drawer/nz-drawer.component.html
- components/drawer/nz-drawer.spec.ts
close #4304
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4304
```
[ ] Yes
[x] No
```
> fix(module:drawer): fix the HTML structure of the drawer header

- components/pagination/nz-pagination.component.html
```
[x] Bugfix
[ ] Feature
```
The character used in pagination is changed from '／' with '/'. The full-width one is only used in some Chinese paragraph.
```
[ ] Yes
[x] No
```
> fix(module:pagination): replace full-width character with half-width

- components/page-header/nz-page-header.component.ts
- components/page-header/nz-page-header.spec.ts
```
[x] Bugfix
[ ] Feature
```
`NzPageHeaderComponent` don't use `.has-breadcrumb`  `.has-footer` style class
use `.has-breadcrumb`  `.has-footer` style class
```
[ ] Yes
[x] No
```
> fix(module:page-header): has footer or breadcrumb style bug

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
- components/tree/nz-tree.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4364
```
[ ] Yes
[x] No
```
> fix(module:tree-select): default tags incorrect in strictly mode

- components/tooltip/base/nz-tooltip-base.directive.ts
- components/tooltip/nz-tooltip.spec.ts
close #4365
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:tooltip): support changing trigger

- components/calendar/date-table.component.ts
- components/date-picker/lib/calendar/calendar-header.component.ts
- components/date-picker/lib/popups/inner-popup.component.html
- components/date-picker/lib/popups/inner-popup.component.ts
- components/date-picker/nz-date-picker.component.spec.ts
- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
Close #4331 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): `nzDefaultOpenValue` not work in time panel

- components/select/nz-select.component.spec.ts
- components/select/nz-select.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4377
Hidden options cannot be selected.
```
[ ] Yes
[x] No
```
> fix(module:select): prevent hidden options from being selected

- components/tooltip/base/nz-tooltip-base.directive.ts
close #3875
close #4317
close #4386
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tooltip): fix tooltip accessing destroyed view

- components/date-picker/lib/calendar/calendar-input.component.ts
- components/date-picker/picker.component.html
- components/date-picker/picker.component.ts
- docs/i18n.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:date-picker): overlay panel flicker when position changes

- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v9/deprecated-class-dropdown.spec.ts
- schematics/ng-update/test-cases/v9/deprecated-component-dropdown.spec.ts
- schematics/ng-update/upgrade-rules/checks/dropdown-class-rule.ts
- schematics/ng-update/upgrade-rules/checks/dropdown-template-rule.ts
- scripts/gulp/tasks/schematic.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add v9 migration rules for dropdown

- components/table/demo/ajax.md
Possible corrections for "this example use mock api..." are "This example makes use of a Mock api..." and "This  example uses a Mock api...."
[X] Documentation only content changes
```
[ ] Yes
[*] No
```
This PR corrects the usage of grammar within the docs. 
The correct usage for proposed changes : "this example use mock api..." are "This example makes use of a Mock api..." and "This  example uses a Mock api...."
The PR proposes we change the usage to match common English language usage patterns
> docs: correct grammar within English docs

- components/resizable/nz-resizable.directive.ts
- components/resizable/style/index.less
In order to keep the style consistent, the cursors for col-resize should be changed to ew-resize (row-resize to ns-resize).
```
[ ] Bugfix
[ ] Feature
```
* Cursors for [Resizable](https://ng.ant.design/experimental/resizable/en) are now using different styles between `[col/row]` and `[ew/ns]`, which make the UI style inconsistent (e.g., on Windows).
+ Because there are events to add these cursor styles to …
> refactor(module: resizable): change cursor styles

- components/carousel/nz-carousel.component.html
- components/carousel/nz-carousel.component.ts
- components/carousel/nz-carousel.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: remove nzVertical API of carousel component
```
```
[x] Yes
[ ] No
```
> chore(module:carousel): remove vertical api

- schematics/ng-update/data/input-names.ts
- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v9/input-names-calendar.spec.ts
- schematics/ng-update/test-cases/v9/input-names-icon.spec.ts
- schematics/ng-update/upgrade-rules/checks/calendar-input-rule.ts
- schematics/ng-update/upgrade-rules/checks/icon-template-rule.ts
- schematics/utils/ng-update/elements.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add v9 migration rules for icon and calendar

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.spec.ts
PR Checklist
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
BREAKING CHANGE:
* tree
- Removed `[nzDefaultExpandAll]` use `[nzExpandAll]` instead.
- Removed `[nzDefaultExpandedKeys]` use `[nzExpandedKeys]` instead.
- Removed `[nzDefaultSelectedKeys]` use `[nzSelectedKeys]` instead.
- Removed `[nzDefaultCheckedKeys]` use `[nzCheckedKeys]` instead.
- Removed `(nzOnSearchNode)` use …
> chore(module:tree, tree-select): remove deprecated API

- components/tag/demo/status.md
- components/tag/demo/status.ts
- components/tag/nz-tag.component.ts
- components/tag/nz-tag.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4622, #4413
```
[ ] Yes
[x] No
```
> feat(module:tag): support status colors

- components/input-number/demo/precision.md
- components/input-number/demo/precision.ts
- components/input-number/doc/index.en-US.md
- components/input-number/doc/index.zh-CN.md
- components/input-number/nz-input-number.component.ts
- components/input-number/nz-input-number.spec.ts
close #4173
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:input-number): support nzPrecisionMode mode

- components/tree-select/demo/basic.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4508
```
[ ] Yes
[x] No
```
> feat(module:tree-select): support `nzDropdownClassName` property

- components/tag/nz-tag.component.html
- components/tag/public-api.ts
- components/tag/tag.component.ts
- components/tag/tag.module.ts
- components/tag/tag.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:tag): refactor

- components/empty/demo/customize.ts
- components/empty/partial/default.ts
- components/empty/partial/simple.ts
- components/empty/style/index.less
close #4921
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4921
The empty image looks strangly white in dark mode.
The empty image looks good in dark mode.
```
[ ] Yes
[x] No
```
> fix(module:empty): fix empty image style in dark mode

- components/i18n/date-helper.service.spec.ts
- components/i18n/date-helper.service.ts
- components/time-picker/time-picker-panel.component.ts
- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
- components/time-picker/time-value-accessor.directive.ts
Fixes #4775 
Fixes #4777
Fixed #4871 
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:time-picker): allow inputting string type

- components/date-picker/calendar-footer.component.ts
- components/date-picker/date-picker.component.html
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/demo/disabled-date.ts
- components/date-picker/lib/abstract-table.ts
- components/date-picker/picker.component.ts
- components/date-picker/public-api.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/util.ts
Fixes #3499
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:date-picker): click date cell not work when changing month or year

- components/badge/badge.component.ts
- components/badge/badge.spec.ts
- components/badge/demo/no-wrapper.ts
- components/badge/doc/index.en-US.md
- components/badge/doc/index.zh-CN.md
- components/badge/preset-colors.ts
- components/badge/types.ts
- scripts/site/_site/doc/style/patch.less
close #4776
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #4776
```
[ ] Yes
[x] No
```
> fix(module:badge): allow `nzTitle` set to null

- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v9/deprecated-injection-tokens.spec.ts
- schematics/ng-update/test-cases/v9/deprecated-inputs-carousel.spec.ts
- schematics/ng-update/upgrade-rules/checks/carousel-like-template-rule.ts
- schematics/ng-update/upgrade-rules/checks/injection-token-rule.ts
- schematics/utils/ng-update/module-specifiers.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add v9 migration rules for carousel and inject tokens

- components/core/config/config.ts
- components/form/demo/auto-tips.md
- components/form/demo/auto-tips.ts
- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/form-control.component.ts
- components/form/form-control.spec.ts
- components/form/form.directive.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4523 
```
[ ] Yes
[x] No
```
> feat(module:form): support auto error tips

- components/core/types/input-observable.ts
- components/core/types/public-api.ts
- components/form/form-control.component.ts
- components/form/form-control.spec.ts
- components/form/form-label.component.ts
- components/form/form.directive.ts
```
[x] Bugfix
[ ] Feature
```
When nz-form-item uses * NgFor, Nnz-form sets nzNoColon to throw an exception: `ExpressionChangedAfterItHasBeenCheckedError`
Issue Number: #4554 
```
[ ] Yes
[x] No
```
> fix(module:form): fix changes not calling detectChanges

- components/input/input-group.component.ts
- components/input/input-group.spec.ts
- components/input/input.directive.ts
close #5064
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:input): fix input group missing focus and disabled

- components/message/base.ts
close #5121
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:message): fix message remove error when no container

- components/select/option-container.component.ts
- components/select/select.component.ts
close #5120 close #5116
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix virtual scroll hover bug

- components/cascader/style/entry.less
- components/cascader/style/patch.less
- components/core/overlay/overlay-position.ts
close #5102
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:cascader): fix cascader position

- components/auto-complete/autocomplete-trigger.directive.ts
- components/auto-complete/autocomplete.component.ts
- components/auto-complete/autocomplete.spec.ts
- components/auto-complete/demo/object-value.md
- components/auto-complete/demo/object-value.ts
- components/auto-complete/doc/index.en-US.md
- components/auto-complete/doc/index.zh-CN.md
close #4981
```
[x] Bugfix
[x] Feature
```
Issue Number: #4981
```
[ ] Yes
[x] No
```
> feat(module:autocomplete): support values whit object type

- components/button/button.component.ts
- components/button/button.spec.ts
- components/core/wave/nz-wave.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5226
```
[ ] Yes
[x] No
```
> fix(module:button): disabled not work with anchor

- components/core/config/config.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-container.ts
- components/modal/modal-ref.ts
- components/modal/modal.component.ts
- components/modal/modal.spec.ts
- components/modal/utils.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5128
```
[ ] Yes
[x] No
```
> fix(module:modal): modal cannot close after the host view destroyed

- components/select/option-item.component.ts
```
[x] Bugfix
[ ] Feature
```
nz-select selected falsy value (eg.0) doesn't have the selected class
[https://stackblitz.com/edit/angular-8iudzt](https://stackblitz.com/edit/angular-8iudzt)
Selected falsy value should have the selected class
```
[ ] Yes
[x] No
```
> fix(module:select): option item not selected with falsy value

- components/calendar/calendar.component.ts
- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4615 
If  you provide `nzDisabledDate` to `calendar` component, then the date you disabled will only display but not to response.
```
[ ] Yes
[x] No
```
> feat(module:calendar): support nzDisabledDate of calendar

- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
- scripts/site/_site/doc/app/app.component.html
- fix the componet doc footer, language is not passed to the footer component
- fix the typo in dropdown doc
```
[ ] Bugfix
[ ] Feature
```
In the documentation site's component section, for English documentation, the footer always appears in Chinese.
Also, fix a couple of typos in the dropdown component documentation. It shows Chinese character one place rather than English. Also, fix the table cell …
> docs(module:dropdown): fix component doc footer language & dropdown typo

- components/card/doc/index.en-US.md
- components/typography/doc/index.en-US.md
- components/typography/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
in the card english page, there are chinese characters in the documentation.
also, import statement is missing in the typography documentation.
```
[ ] Yes
[x] No
```
> docs(module:typhography): add the import in documentation

- components/code-editor/code-editor.component.ts
- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
`nzEditorInitialized` return the `IEditor` type, but often uses the methods of the `IStandaloneCodeEditor` type, so many type-assertion need to be written.
```
[ ] Yes
[x] No
```
`IEditor` is the base class of `IStandaloneCodeEditor`, there should be no breaking changes.
Also I tried to narrow the type through `NzCodeEditorComponent<T extends NzEditorMode>`, …
> chore(module:code-editor): update the instance types

- components/list/list-item-cell.ts
Fix nz-list-item-actions cannot render nz-list-item-action until next VM
turn.
(#5393)
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5393 
```
[ ] Yes
[x] No
```
> fix(module:list): nz-list-item-actions rendered nothing

- angular.json
- components/affix/affix.module.ts
- components/anchor/anchor.module.ts
- components/back-top/back-top.module.ts
- components/core/services/scroll.ts
- components/date-picker/lib/abstract-panel-header.ts
- components/date-picker/lib/abstract-table.ts
- components/timeline/timeline.service.ts
- components/tooltip/base.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:*): migrate the source code to Angular v10

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/picker.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4534
```
[ ] Yes
[x] No
```
> feat(module:datapicker): add `[nzInputReadOnly]`

- components/table/src/addon/filter.component.ts
close #5505
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table filter false or 0 error

- components/upload/doc/index.en-US.md
- components/upload/doc/index.zh-CN.md
- components/upload/upload-list.component.ts
- components/upload/upload.component.html
- components/upload/upload.component.ts
- components/upload/upload.spec.ts
- close #5520
- close #4990
`nzPreviewIsImage` 可以更好的自定义预览文件URL是否有效的图像格式，特别是一些CDN它们本身没有一个很明确的图像资源标识，比如：
- https://a.com/1.jpg 一种标准图像路径
- https://a.com/key?w=800&force_format=jpg 也算是一个有效的图像路径
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:upload): add `nzPreviewIsImage` property

- components/resizable/demo/basic.ts
- components/resizable/doc/index.en-US.md
- components/resizable/doc/index.zh-CN.md
- components/resizable/resizable.directive.ts
- components/resizable/resizable.spec.ts
- components/resizable/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:resizable): add `nzDisabled` property

- components/form/form-control.component.ts
- components/form/form.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:form): optimize code to increase robustness

- components/tree/tree.component.ts
- components/tree/tree.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): fix nzBlockNode not work

- components/drawer/drawer.component.ts
- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-container.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/NG-ZORRO/ng-zorro-antd/issues/5591
the new introduced `ConfigurableFocusTrapFactory` strategy disables clicks outside overlay, which is not compatible with many third-party libraries.
Literally, FocusTrap should only prevent focus event other than click event.
On the other hand, even Angular Material is still using the deprecated `FocusTrapFactory` for now. …
> fix(module:modal): change back to FocusTrapFactory

- components/tabs/tab-nav-operation.component.ts
- components/tabs/tabset.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tabs): not emit click event from dropdown menu

- components/date-picker/picker.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/5630
When Sever Side Rendering there is no more "ERROR ReferenceError: window is not defined at ng_zorro_antd_date_picker_NzPickerComponent.ngAfterViewInit"
```
[ ] Yes
[x] No
```
> fix(module:date-picker): window is not defined

- components/tabs/demo/link-router.ts
- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/style/patch.less
- components/tabs/tab-link.directive.ts
- components/tabs/tab.component.ts
- components/tabs/tabs.module.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tabs): router link content projection error

- components/tabs/demo/slide.ts
- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/interfaces.ts
- components/tabs/tab-link.directive.ts
- components/tabs/tab-nav-operation.component.ts
- components/tabs/tab.component.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number:  #5712
```
[ ] Yes
[x] No
```
> feat(module:tabs): support (nzContextmenu) event 

- components/carousel/carousel.component.ts
- components/carousel/strategies/base-strategy.ts
- components/carousel/strategies/transform-strategy.ts
close #4292
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes, all custom strategies should add the forth parameter to their constructors
[ ] No
```
> fix(module:carousel): support SSR

- docs/global-config.en-US.md
There is a small typo on [Global Configuration](https://ng.ant.design/docs/global-config/en) page
I changed barge to large.
> docs: fix typo for global config page (en)

- components/cascader/typings.ts
- schematics/ng-update/data/class-names.ts
- `CascaderOption` has been removed, use `NzCascaderOption` instead.
- `CascaderSearchOption` has been removed, use `NzCascaderSearchOption` instead.
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:cascader): remove deprecated APIs for v10

- components/anchor/anchor.component.ts
- components/anchor/anchor.spec.ts
- schematics/ng-update/data/input-names.ts
- `nzTarget` has been removed, use `nzContainer` instead.
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:anchor): remove deprecated APIs for v10

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5575
That you can use the arrow icon in multi-select and tag mode.
But by default it's false. So you need to set it true in multi and tag mode.
```
[ ] Yes
[x] No
```
> fix(module:select): arrow icon can be used when not using single-select

- components/code-editor/code-editor.service.ts
- components/code-editor/demo/config.ts
- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
- components/code-editor/typings.ts
- schematics/ng-update/data/property-names.ts
- schematics/ng-update/test-cases/v9/deprecated-injection-tokens.spec.ts
- schematics/ng-update/upgrade-rules/checks/global-config-rule.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:code-editor): remove deprecated APIs for v10

- components/icon/icon.directive.ts
- components/tag/demo/icon.md
- components/tag/demo/icon.ts
- components/tag/demo/module
- components/tag/demo/status.ts
- components/tag/tag.component.ts
- components/tag/tag.spec.ts
BREAK CHANGES: '(nzAfterClose)' Output is going to be removed in 9.0.0. Please use '(nzOnClose)' instead.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:tag): support icon in tag

- components/menu/demo/inline-collapsed.ts
- components/popconfirm/popconfirm.spec.ts
- components/popconfirm/popconfirm.ts
- components/popover/popover.spec.ts
- components/popover/popover.ts
- components/steps/demo/customized-progress-dot.ts
- components/tooltip/base.ts
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
BREAKING-CHANGE: remove API without specific prefix
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: remove deprecated API
```
```
[ ] Yes
[ ] No
```
> chore(module:tooltip,*): remove deprecated API

- components/slider/slider.component.ts
- components/slider/slider.spec.ts
Fix slider value when min and max value is defined.
Previously the value was calculated incorrectly.
```
[x] Bugfix
[ ] Feature
```
When specifying the nzMin on a reversed slider, the value would be calculated incorrectly.
This would create a bug where the selected position on the slider wouldn't align with the value it created.
The value gets calculated correctly and takes the min value …
> fix(module:slider): fix reverse slider value with min and max

- components/core/time/candy-date.spec.ts
- components/core/time/candy-date.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
Closes #5572
Closes #5651
Closes #5631
- if one value change, the cursor will always move to the other input although has value.
- will not sort the range date.
- when sorting is wrong, reset the other input.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:date-picker): will not sort range date

- components/select/select-search.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5656
IME input is not displayed in the select box completely.
IME input is displayed in the select box completely.
```
[ ] Yes
[x] No
```
The side effect is that a search is performed every time a key is pressed in IME input mode.
> fix(module:select): display IME input completely

- components/code-editor/code-editor.component.ts
Since monaco is initialized outside the Angular zone, the onDidChangeContent
method will inherit this and therefore no change detection ends up being
triggered. This can cause e.g. validation tips to be shown with a delay
(only once another change detection cycle comes along).
Therefore we run the callback explicitly inside the Angular zone.
```
[X] Bugfix
[ ] Feature
```
> fix(module:code-editor): run value changes in Angular zone

- components/select/select.component.ts
```
[ ] Bugfix
[x] Feature
```
When using nz-select component with an option where `[nzValue]="0"` and hitting enter the value is not being saved, because `this.activatedValue = 0` and it is a falsy value thus not entering the if block to call the `onItemClick` method.
Optional @Input() was added to solve this problem. By passing `[nzAcceptZeroValue]="true"` to `NzSelectComponent`
```
[ ] …
```
> fix(module:select): accept 0 value on enter

- components/spin/demo/delay-and-debounce.md
- components/spin/spin.component.ts
- components/spin/spin.spec.ts
```
[X] Bugfix
[ ] Feature
```
* delay is now also respected when the component is initialized
* delay is only considered when nzSpinning turns from false to true, but not vice versa
If you don't agree with either change let me know and I can update the PR.
```
[ ] Yes
[X] No
```
fixes #5926 
fixes #5928
> fix(module:spin): make delay behave more accurately

- components/code-editor/code-editor.component.ts
Before notifying Angular (through the ControlValueAccessor mechanism) of a change to
the value we make sure that the value has actually changed. This is necessary to
avoid feedback loops as writeValue (model -> view) would otherwise cause this to be
fired (view -> model) which can cause infinite loop issues on the usage side or
broken validation detection.
fixes #5869
```
[X] Bugfix
[ ] Feature
```
Issue …
> fix(module:code-editor): only emit update if value changed

- components/layout/doc/index.en-US.md
- components/layout/doc/index.zh-CN.md
nzCollapsed is describe twice
https://ng.ant.design/components/layout/en
> fix(doc layout): duplicated binding description

- components/auto-complete/autocomplete-trigger.directive.ts
- components/auto-complete/autocomplete.spec.ts
- components/cascader/cascader.component.ts
- components/cascader/style/patch.less
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/year-picker.component.spec.ts
- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
- components/dropdown/dropdown.directive.ts
- components/mention/mention.component.ts
- components/mention/nz-mention.spec.ts
- components/popconfirm/popconfirm.ts
- components/popover/popover.ts
- components/select/select-top-control.component.ts
- components/select/select.component.ts
- components/select/select.spec.ts
- components/time-picker/time-picker.component.ts
- components/tooltip/base.ts
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
- components/tree-select/tree-select.component.ts
- components/tree-select/tree-select.spec.ts
related components: cascader, datepicker, timepicker, popconfirm, popover, select, treeselect.
@angular/cdk >= 10.1.0
close #4763
close #5061
close #4259
close #2508
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:all): remove the backdrop of most components

- docs/recommendation.en-US.md
- docs/recommendation.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
The linked Akita website is not working. I believe it was the outdated link.
Replace with the current documentation website
```
[ ] Yes
[x] No
```
> docs: update Akita documentation website URL

- components/form/form-control.component.ts
```
[x] Bugfix
[ ] Feature
```
Autotips do not apply to child components of a form with form controls, just direct descendants. 
Remove the @Host binding so that child components can take advantage of nzAutotips
```
[ ] Yes
[x] No
```
> fix(module:form): remove @host so child components recieve autotips

- components/core/config/config.ts
- components/form/demo/register.ts
- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/form-label.component.ts
- components/form/form-label.spec.ts
- components/form/form.directive.ts
- components/form/form.module.ts
close #5905
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:form): `nz-form-label` support `nzFormTooltip`

- components/select/select.component.ts
- components/select/select.spec.ts
close #5965
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5965
```
[ ] Yes
[x] No
```
> fix(module:select): the ESC keydown event not handled correctly

- components/upload/upload.component.ts
```
[x] Bugfix
```
if the upload component is destroyed before the `ngOnInit` call, I got the following error:
```batch
Cannot read property 'unsubscribe' of undefined
at NzUploadComponent.ngOnDestroy 
```
```
[ ] Yes
[x] No
```
> fix(module:upload): ensure i18n$ is defined on unsubscribe

- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
#5980 
time picker will hidden clear icon when disabled
```
[ ] Yes
[x] No
```
> fix(module:time-picker): hidden clear icon when disabled

- components/select/select-top-control.component.ts
- components/select/select.component.ts
close #6005
close #6007
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): disabled allows to open panel

- components/cascader/cascader.component.ts
```
[x] Bugfix
[ ] Feature
```
Cascader popover is not closed after clicking a none-leaf node when using nzChangeOnSelect and hover trigger, which is very misleading.
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/6022
Cascader popover is closed after clicking a none-leaf node when using nzChangeOnSelect and hover trigger
```
[ ] Yes
[x] No
```
https://react-fvmcpb-2ij3hv.stackblitz.io
Both …
> fix(module:cascader):  menu closing behavoir

- components/cascader/cascader.component.ts
```
[x] Bugfix
[ ] Feature
```
when Cascader search bar is not empty and focused, the font color is pure black
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/6020
when Cascader search bar is not empty and focused, the font color is gray
```
[ ] Yes
[x] No
```
Due to the lack of experience of git collaboration, I ruined the old pull request …
> fix(module:cascader): sync class name with ant-design

- components/cascader/cascader.component.ts
```
[x] Bugfix
[ ] Feature
```
nzChangeOnSelect is broken 
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/6048
nzChangeOnSelect works well
```
[ ] Yes
[x] No
```
this bug is introduced by https://github.com/NG-ZORRO/ng-zorro-antd/pull/6023/files .
When clicking a none leaf node, the menu should only disappear when combining `nzChangeOnSelect` and `nzExpandTrigger === 'hover'`
> fix(module:cascader): fix broken nzChangeOnSelect

- components/code-editor/code-editor.component.ts
Calling #setValue() on a monaco editor instance causes the mouse cursor to jump to the
beginning of the document, which is undesirable for a ControlValueAccessor implementation
which should only update the content. Also see
https://github.com/microsoft/monaco-editor/issues/1397 for more information.
Unfortunately, using #executeEdits() doesn't really work as a replacement because it will
mess with selections. Therefore we memorize and restore the cursor position before/after
setting the value. Since #setValue() also causes a selection to be lost we do the same for
those. Restoring selections may produce slightly unexpected results if the selection covers
part of the content that has been changed, but is still preferable to losing the selection
altogether.
fixes #6038
Please check if your …
> fix(module:code-editor): memorize cursor position and selections

- components/cascader/cascader-li.component.ts
- components/cascader/cascader.component.ts
```
[x] Bugfix
[ ] Feature
```
The menu stays at top no matter whether there are activated options.
Issue Number: #6037
After the cascader is selected, the menu scrolls to activated options every time it is opened.
```
[ ] Yes
[x] No
```
> fix(module:cascader): scroll active options into view

- components/cascader/cascader.component.ts
- components/cascader/cascader.spec.ts
```
[x] Bugfix
[ ] Feature
```
close #6036 
```
[ ] Yes
[x] No
```
> fix(module:cascader): restore its value after cancel search

- components/drawer/demo/basic-right.ts
- components/drawer/demo/from-drawer.ts
- components/drawer/demo/multi-level-drawer.ts
- components/drawer/demo/placement.ts
- components/drawer/demo/user-profile.ts
- components/drawer/drawer-content.directive.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.module.ts
- components/drawer/public-api.ts
DEPRECATED: Usage `<ng-content></ng-content>` is deprecated, use `<ng-template nzDrawerContent></ng-template>` to declare the contents of the drawer.
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:drawer): add `nzDrawerContent` directive

- components/modal/demo/async.ts
- components/modal/demo/basic.ts
- components/modal/demo/footer.md
- components/modal/demo/footer.ts
- components/modal/demo/footer2.md
- components/modal/demo/footer2.ts
- components/modal/demo/locale.ts
- components/modal/demo/position.ts
- components/modal/demo/service.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-content.directive.ts
- components/modal/modal-footer.directive.spec.ts
- components/modal/modal.component.ts
- components/modal/modal.module.ts
- components/modal/public-api.ts
close #6065
DEPRECATED: Usage `<ng-content></ng-content>` is deprecated, use `<ng-template nzModalContent></ng-template>` to declare the contents of the modal.
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6065
```
[ ] Yes
[x] No
```
> feat(module:modal): add `nzModalContent` directive

- components/input/demo/module
- components/input/demo/textarea-with-character-count.md
- components/input/demo/textarea-with-character-count.ts
- components/input/doc/index.en-US.md
- components/input/doc/index.zh-CN.md
- components/input/input.module.ts
- components/input/public-api.ts
- components/input/textarea-count.component.ts
- components/input/textarea-count.spec.ts
close NG-ZORRO#5907
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5907 
It now supports displaying character count at the bottom-right corner below the textarea. User can customize max length and character count computation function.
```
[ ] Yes
[x] No
```
> feat(module:input): textarea supports character count

- components/table/src/table/table.component.ts
- components/table/src/testing/table.spec.ts
close NG-ZORRO#6080
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6080 
No remaining pagination style including vertical margin is shown after nzHideOnSinglePage.
```
[ ] Yes
[x] No
```
> fix(module:table): showPagination in ngIf when nzHideOnSinglePage

- components/select/select.component.ts
close #6041
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6041 
First item or first selected item is activated every time option container is open.
```
[ ] Yes
[x] No
```
> fix(module:select): activate first item or first selected item

- components/date-picker/date-range-popup.component.ts
- components/time-picker/time-picker-panel.component.ts
close #6170
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(module:date-picker,time-picker): prevent losing input focus

- components/transfer/demo/table-transfer.ts
- components/transfer/demo/tree-transfer.ts
- components/transfer/transfer-list.component.ts
- close #5641
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:transfer): fix only filtered data in `nzRenderList`

- components/graph/graph-zoom.directive.ts
This allows a usage from the template without being forced to go through
a ViewChild query:
```
<nz-graph nz-graph-zoom #zoomController="nzGraphZoom" …></nz-graph>
<button (click)="zoomController?.fitCenter()" …></button>
```
```
[ ] Bugfix
[x] Feature
```
To access the zoom directive we need to use a ViewChild query.
The directive is exported.
```
[ ] Yes
[x] No
```
> feat(module:graph): export nz-graph-zoom as nzGraphZoom

- components/button/button.component.ts
Only warn about the deprecated nzType="danger" value if that value
is actually used rather than any value for nzType.
fixes #6191
fixes #6187
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6191
```
[ ] Yes
[x] No
```
> fix(module:button): only warn about deprecated value when used

- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
add content of how to override i18n configuration
https://github.com/NG-ZORRO/ng-zorro-antd/discussions/6183#discussioncomment-202737
```
[ ] Yes
[x] No
```
> docs: add override i18n configuration

- components/dropdown/dropdown.directive.spec.ts
- components/dropdown/dropdown.directive.ts
```
[ ] Bugfix
[ ] Feature
```
1. `nzBackDrop` will be deprecated in v12.
2. Introduce replaced input `nzHasBackDrop`.
3. Default values of both are set to false.
```
[ ] Yes
[x] No
```
> refactor(module:dropdown): move nzBackDrop deprecation to v12

- components/tabs/tab-link.directive.ts
- components/tabs/tab.component.ts
- components/tabs/tabset.component.ts
- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v11/tabs-deprecated.spec.ts
- schematics/ng-update/upgrade-rules/checks/tabs-input-rule.ts
- schematics/ng-update/upgrade-rules/checks/tabs-output-rule.ts
- schematics/ng-update/upgrade-rules/checks/tabs-template-rule.ts
- schematics/utils/ng-update/elements.ts
- `[nzShowPagination]` input has been removed, please remove it manually.
- `(nzOnPrevClick)` output has been removed, please remove it manually.
- `(nzOnNextClick)` output has been removed, please remove it manually.
- `a[nz-tab-link]` selector has been removed, please use `ng-template[nzTabLink] > a[nz-tab-link]` instead.
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] …
```
> refactor(module:tabs): remove deprecated APIs for v11

- schematics/ng-add/index.spec.ts
- schematics/ng-add/index.ts
- schematics/ng-add/schema.json
- schematics/ng-add/schema.ts
- schematics/ng-generate/side-menu/index.spec.ts
```
[ ] Bugfix
[x] Feature
```
目前 ng-add Schematic 内使用 `RunSchematicTask` 来执行内部 Schematic，由于外部无法获取 `RunSchematicTask` 的 TaskId 导致其无法与其他（外部） Schematic 进行串联
使用 `chain` 和 `schematic` 方法重写 ng-add Schematic 逻辑，现在可以很好的与其他 Schematic 进行串联
```typescript
export function mySchematic(options: NgNewSchema): Rule {
return chain([
schematic('ng-new', options),
externalSchematic('ng-zorro-antd', …
```
> feat(schematics): make ng-add schematics chainable

- components/slider/demo/reverse.ts
- components/slider/marks.component.ts
- components/slider/slider.component.ts
- components/slider/slider.spec.ts
- components/slider/step.component.ts
```
[X] Bugfix
[ ] Feature
```
Currently the marks and steps of sliders don't get updated when the slider get reversed. When you reverse a slider with marks, the '0' mark will be under value 100 and the '100' mark will be under value 0. The same thing happens for steps, when you have slider value 50 the '0' step doesn't show as 'active', while the '100' step does.
Now the marks get built …
> fix(module:slider): fix slider style + reverse marks if reversed slider

- components/select/select.component.ts
```
[x] Bugfix
[ ] Feature
```
can clear content when clear and arrow icon overlap in nz-select component
#5989
```
[ ] Yes
[x] No
```
> fix(module:select): change order for clear and arrow

- components/table/demo/dynamic-settings.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/table.types.ts
- components/table/src/table/table.component.ts
```
[ ] Bugfix
[x] Feature
```
close #5913 
```
[ ] Yes
[x] No
```
> feat(module:table): support nzPaginationType property

- schematics/collection.json
```
[x] Bugfix
[ ] Feature
```
`collection.json` 中的 `add-icon-assets` 配置引用了一个错误的 `schema` 路径，导致如果其他 schematics 扩展了 ng-zorro-antd 的 schematics 后，执行 `ng g --help` 命令会由于配置不正确而报错
经查找，应该在某次提交 NG-ZORRO/ng-zorro-antd@69072de8a83e3a5beb264eb628fd18e7c97dfdc4 中，原有的 `schema.json` 被移除了
简单起见，复用了 `blank` schematic 目录中的 `schema.json` （因为 git 的 diff 结果也是显示 boot-page 被重命名为 blank 了）
正确引用相应的 `schema.json`
```
[ ] Yes
[x] No …
```
> fix(schematics): fix `add-icon-assets`  schema path

- components/input/autosize.directive.ts
- components/input/autosize.spec.ts
close #6403
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6403 
```
[ ] Yes
[x] No
```
> fix(module:input): fix [nzAutosize]="true" (#6403)

- components/dropdown/dropdown.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: resolve #6353
```
[ ] Yes
[x] No
```
> fix(module:dropdown): close menu when click again (#6353)

- components/message/base.ts
- components/message/message.component.ts
- components/message/message.spec.ts
- components/notification/notification.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: resolve #6296
```
[ ] Yes
[x] No
```
> fix(module:message): avoid flicker when window close (#6296)

- components/date-picker/date-picker.component.ts
- components/date-picker/picker.component.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select-search.component.ts
- components/select/select-top-control.component.ts
- components/select/select.component.ts
- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
- components/time-picker/time-picker.component.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/tree-select.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:time-picker,select,tree-select): support `nzId`

- components/core/animation/zoom.ts
- components/select/select-top-control.component.ts
- components/select/select.component.ts
- components/tree-select/tree-select.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> perf(module:select): avoid reflow when select init

- components/grid/doc/index.en-US.md
- components/grid/doc/index.zh-CN.md
- components/grid/grid.spec.ts
- components/grid/row.directive.ts
The following code style is better in `strictTemplates` mode:
```html
<nz-row [nzGutter]="16">
```
better:
```html
<nz-row nzGutter="16">
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:grid): `nzGutter` support string type

- components/auto-complete/autocomplete-trigger.directive.ts
- components/auto-complete/autocomplete.component.ts
- components/auto-complete/autocomplete.spec.ts
- components/dropdown/dropdown-menu.component.ts
- components/dropdown/dropdown.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6018 
Dropdown has open animation every time which triggers it. Autocompletion has close animation after clicking outside the input.
```
[ ] Yes
[x] No
```
> fix: dropdown and autocomplete animations

- components/notification/demo/duration.ts
```
[ ] Bugfix
[ ] Feature
```
The notification content in the demo-duration does not seem reasonable:
```
I will never close automatically. I will be close automatically. I will never close automatically.
```
Replace the notification content of demo-duration with the same as the react version
```
[ ] Yes
[x] No
```
> docs(module:notification): use more reasonable content for duration demo

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/option-group.component.ts
- components/select/option-item-group.component.ts
- components/select/option-item.component.ts
- components/select/option.component.ts
- components/select/select-item.component.ts
- components/select/select.component.ts
- components/select/select.spec.ts
- components/select/select.types.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: close #6535
```
[ ] Yes
[x] No
```
> feat(module:select): support number as label (#6535)

- components/tabs/style/patch.less
```
[x] Bugfix
[ ] Feature
```
PR #5708 为了增大 `nz-tab-link` 的可点击区域而增加的 `::before` 元素的蒙层会覆盖整个 Tab 的点击区域，导致关闭按钮无法点击。
通过为关闭按钮添加 `position: relative` 属性来激活其 `z-index`，使得位于 `[nz-tab-link]::before` 之后的 `ant-tabs-tab-remove` 默认拥有更高的层级，以避免被覆盖。
```
[ ] Yes
[x] No
```
> fix(module:tabs): make remove icon of nz-tab-link clickable

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/year-picker.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6595
```
[ ] Yes
[x] No
```
> fix(module:date-picker): click outside not change value

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/year-picker.component.spec.ts
`blur` event has not the `relatedTarget` in IE11, use `focusout` instead.
```
[x] Bugfix
[ ] Feature
```
Issue Number: 
```
[ ] Yes
[ ] No
```
> fix(module:date-picker): time picker panel not scroll at first time

- components/i18n/languages/sv_SE.ts
style(module:transfer): changing swedish translation
Going from less used 'element' to 'objekt' for 'item'/'items' translation
- [n/a] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Change in translation 
```
```
[ ] Yes
[x] No
```
> fix(module:i18n): Changed swedish translation

- components/badge/badge-sup.component.ts
- components/badge/badge.component.ts
- components/badge/badge.module.ts
- components/badge/badge.spec.ts
- components/style/patch.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6478
```
[ ] Yes
[x] No
```
> fix(module:badge): enable nzNoAnimation support

- components/tabs/demo/card-top.md
- components/tabs/demo/card.md
- components/tabs/demo/centered.md
- components/tabs/demo/centered.ts
- components/tabs/demo/custom-add-trigger.md
- components/tabs/demo/editable-card.md
- components/tabs/demo/extra.md
- components/tabs/demo/guard.md
- components/tabs/demo/icon.md
- components/tabs/demo/lazy.md
- components/tabs/demo/link-router.md
- components/tabs/demo/position.md
- components/tabs/demo/size.md
- components/tabs/demo/slide.md
- components/tabs/style/index.less
- components/tabs/style/position.less
```
[x] Bugfix
[ ] Feature
```
close #6703
```
[ ] Yes
[x] No
```
> fix(module:tabs): fix `nzCentered` not working

- components/cascader/cascader.component.ts
- components/cascader/cascader.service.ts
- components/cascader/cascader.spec.ts
Add the missing nzClear emit to the clearSelection method on the cascader component.
Extend the cascader e2e tests to ensure that the event emitter works as expected.
fix #6751
```
[x] Bugfix
[ ] Feature
```
The nzClear event emitter would not emit when the cascader value was cleared as the implementation was missing.
Issue Number: #6751 
When the clearSelection method is executed on the cascader …
> fix(module:cascader): add nzClear functionality to cascader

- components/drawer/drawer.component.ts
- components/modal/modal.component.ts
- components/modal/utils.ts
- Modal
* usage of `ng-content` has been removed, please use `<ng-template nzModalContent></ng-template>` instead.
- Drawer
* usage of `ng-content` has been removed, please use `<ng-template nzDrawerContent></ng-template>` instead.
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:modal, drawer): remove deprecated APIs for v12

- components/tree-view/tree-virtual-scroll-view.ts
- schematics/ng-update/data/input-names.ts
- `[nzNodeWidth]` has been removed, please use `[nzItemSize]` instead.
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[] No
```
> refactor(module:tree-view): remove deprecated APIs for v12

- components/progress/typings.ts
- components/steps/demo/progress.md
- components/steps/demo/progress.ts
- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
- components/steps/step.component.ts
- components/steps/steps.component.ts
- components/steps/steps.module.ts
close NG-ZORRO#5684
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5684 
Support circular progress bar for basic `nz-steps`.
```
[ ] Yes
[x] No
```
> feat(module:steps): steps support circular progress bar

- components/pagination/pagination.component.ts
```
[x] Bugfix
[ ] Feature
```
Can't trigger page index change while the nzPageIndexChange is not set due to the Zone refresh strategy
Issue Number: 6661
https://github.com/NG-ZORRO/ng-zorro-antd/issues/6661
Trigger change after emit the output function
```
[ ] Yes
[x] No
```
> fix(pagination): add cdr check while page index change

- components/date-picker/date-picker.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6806
```
[ ] Yes
[x] No
```
> fix(module:date-picker): nz-range-picker support nzId

- components/checkbox/checkbox.component.ts
- components/checkbox/doc/index.en-US.md
- components/checkbox/doc/index.zh-CN.md
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
```
[x ] Bugfix
[ ] Feature
```
Issue Number: #6801
```
[ ] Yes
[x ] No
```
> feat(module:checkbox): add nzId input

- components/icon/icon.service.ts
```
[x] Bugfix
```
I've noticed the `NzIconService` cannot be GC'd since it subscribes `configUpdated$` which is a subject and keeps subscribers in its `observers` property until it's teardowned. The creates a memory leak for server-side rendered application since the `NzIconService` is created and destroyed there per each HTTP request.
The `NzIconService` is GC'd successfully.
```
[x] No
```
> fix(module:icon): resolve memory leak

- components/drawer/drawer.component.ts
```
[x] Bugfix
```
The drawer component schedules the DOM timer which causes Angular to run the change detection even if there're no `nzOnViewInit` listeners. This sometimes causes frame drops if the composite thread is busy doing layout stuff but can't delay that timer until next  message loop tick.
It won't schedule the timer and trigger `tick()` until there're `nzOnViewInit` listeners.
```
[x] No
```
> fix(module:drawer): trigger change detection only if there are `nzOnViewInit` listeners

- components/code-editor/code-editor.component.ts
```
[x] Bugfix
```
Currently, it's running `tick()` whenever the `onDidChangeContent` callback is invoked, but there's an `if` condition which checks if the value has been changed and does nothing if **not**.
The `nz-code-editor` will run `tick()` only if the value has been changed.
```
[ ] Yes
[x] No
```
> fix(module:code-editor): re-enter the Angular zone only if the value has been changed

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/NG-ZORRO/ng-zorro-antd/issues/6897
Issue Number: 6897
There is no animation for inline mode datepicker so it's not going invisible after re-opening
```
[ ] Yes
[x] No
```
Inline datepicker don't need to have animation because it's inline, nothing is opened through dropdown. Problems was in animation attached to inline mode so it's going to make `opacity: 0` …
> fix(module:datepicker): fixed opacity 0 on inline datepicker reopen

- components/table/src/table/table.component.ts
```
[x] Bugfix
[ ] Feature
```
Currently when the table is initially loaded (with `nzLoading="true"`) then only table header is shown with loading icon on the top and it does not look good. I've checked React behavior and it shows additionally empty icon in the table body.
The new behavior shows empty state regardless of loading value. So initially when there is no data and …
> fix(module:table): show empty state regardless of loading value

- components/tooltip/base.ts
- components/tooltip/tooltip.spec.ts
close #6955
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6955
Since `focus` and `blur` are events that don't propagate, nz-tooltip and other components such as nz-popconfirm and nz-popover fail to detect a focus event on a deeply wrapped child element.
Use `focusin` and `focusout` events which can propagate and [IE11-compatible](https://caniuse.com/?search=focusin) instead. `trigger="focus"` works for …
> fix(module:tooltip): fix tooltip for deeply wrapped focusable elements

- components/i18n/languages/en_GB.ts
Adding missing translations from the en_US file to the en_GB file.
> fix(module:i18n): update en_GB.ts translations

- components/affix/affix.component.ts
- close #6764
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:affix): fix update position when target resize

- components/image/image-preview-ref.ts
- components/image/image.directive.ts
- components/image/image.spec.ts
```
[x] Bugfix
```
Currently, event listeners are not removed from the image element when the directive is destroyed, tho they keep capturing `this` and prevent the directive from being GC'd.
`__ngContext__[2] & 256` is `lView[FLAGS] & LViewFlags.Destroyed`, which checks if the directive is in destroyed status (it is):
The image preview can be closed by clicking on the close button on either container. This means that one of the streams will emit (`containerClick` or `closeClick`). If `containerClick` emits, then the `closeClick` will never complete and vice-versa:
The `NzImageDirective` is GC'd successfully.
```
[x] No
```
> fix(module:image): resolve memory leak

- package.json
- muse be upgrade `eslint-plugin-jsdoc` to latest version, fixed error
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser/tokenizers/description.js' is not defined by "exports" in /Users/cipchk/Desktop/work/ng-zorro-antd/node_modules/@es-joy/jsdoccomment/node_modules/comment-parser/package.json
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: fix ng lint fail

- components/upload/upload-btn.component.ts
- components/upload/upload.spec.ts
```
[x] Bugfix
```
Currently, it runs change detection each time the `nz-upload-btn` is clicked, tho it opens a native OS file picker. This is considered as a "dead" change detection (`ApplicationRef.tick()` is run, but there's nothing to update). This may cause a frame drop when opening a native file picker (because Angular has to run the whole change detection before opening it).
There's no dead change detection when the `nz-upload-btn` is clicked.
```
[ ] Yes
[x] No
```
> fix(module:upload): do not trigger change detection for `nz-upload-btn`

- components/breadcrumb/breadcrumb.component.ts
- components/breadcrumb/breadcrumb.spec.ts
```
[x] Bugfix
```
Currently, the `navigate` method re-enters the Angular zone by calling `ngZone.run`. The `navigate` method is a `click` event handler, template event listeners are added within the Angular zone hence there's no need to re-enter it.
Each `ngZone.run` invocation triggers zone's `onInvoke` lifecycle hook which runs `checkStable()` and might trigger the change detection (considering the number of tasks in the current message loop tick).
The Angular's zone is not re-entered when the `navigate()` is called.
```
[x] No
```
> fix(module:breadcrumb): do not re-enter the Angular zone when calling `navigate`

- components/select/select.component.ts
- components/select/select.spec.ts
```
```
Currently, the `nz-select` calls `updateCdkConnectedOverlayStatus` every time the select is opened or closed. The `updateCdkConnectedOverlayStatus` schedules a frame callback which is triggering the whole layout update (due to `getBoundingClientRect()`) and it calls `markForCheck()` which forces Angular to run the change detection from the root component down to `nz-select`.
It causes frame drops since the main thread is busy with:
1) updating layout
2) executing `tick()`
We don't need to run the `markForCheck()` since we don't need the "global" change detection. The `triggerWidth` is bound to `cdkConnectedOverlayMinWidth`, the `triggerWidth` is a number, number bindings are not updated each change detection cycle, since …
> perf(module:select): do not run change detection if the `triggerWidth` has not been changed

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.spec.ts
- components/popconfirm/popconfirm.ts
```
[x] Bugfix
[ ] Feature
```
nzOkType="danger" is not applied to the ok button
Issue Number: #6864
adding new property as nzOkDanger to apply Danger style to the ok button
```
[ ] Yes
[ ] No
```
I guess, same as for the Modal Footer component, maybe the migration steps needed here ?
> fix(module:popconfirm): add nzOkDanger option for nz-popconfirm

- components/core/transition-patch/transition-patch.directive.ts
- components/core/transition-patch/transition-patch.spec.ts
- fix hidden attribute behavior
- make hidden behavior same as angular
Closes #6918
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6918
```
[ ] Yes
[x] No
```
> fix(module: core): correct hidden behavior

- components/modal/modal-footer.component.ts
- components/modal/modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
https://codesandbox.io/s/hopeful-hoover-3eddg?file=/src/app/app.component.ts
No feedback if error occurred in promise without explicitly catching, because `onClick` handler catched the error.
Rethrow error on catching.
```
[ ] Yes
[x] No
```
> fix(module:modal): footer onClick rethrow error in promise catch

- components/code-editor/code-editor.service.ts
- components/code-editor/typings.ts
```
[x] Bugfix
```
We should load Monaco only once, it even has a warning within its source code (see the screenshot). This applies to apps that are bootstrapped and destroyed multiple times.
Monaco is ensured to be loaded only once.
```
[ ] Yes
[x] No
```
> fix(module:code-editor): load Monaco only once

- components/table/src/table/table-fixed-row.component.ts
```
[x] Bugfix
```
The `hostWidth$` subject keeps the `NzTableFixedRowComponent.hostWidth$` within its `observers` property until it unsubscribes.
```
[ ] Yes
[x] No
```
> fix(module:table): resolve leak within the `nz-table-fixed-row`

- components/auto-complete/autocomplete-option.component.ts
- components/auto-complete/autocomplete.spec.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): do not run change detection on `mousedown` and `mouseenter` for `nz-auto-option`

- components/upload/upload-list.component.ts
- components/upload/upload.spec.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:upload): previewing images should be cancellable when the component gets destroyed

- components/tabs/style/index.less
- components/tabs/style/patch.less
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
There is a problem with the tabs component. When opening and closing the tab page and the Add button, if all the open tab pages are closed, the Add button will not be found. This problem can be repeated in the official website document demo.
Tabs组件有一个问题，当开启关闭tab页和添加按钮时，如果把开启的tab页全部关掉，添加按钮也找不到了，这个问题在官网文档demo中即可复现。
https://ng.ant.design/components/tabs/en#components-tabs-demo-card-top
```
[x] Bugfix
[ ] Feature
[ ] Other... Please …
```
> fix(module:tabs): tabs add btn disappear after all tab closed 

- components/timeline/timeline.component.ts
- components/timeline/timeline.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:timeline): when the data clear, reset items

- components/popconfirm/popconfirm.ts
```
[x] Bugfix
[ ] Feature
```
Any default nz-popconfirm will not show the 'arrow' even though it is marked as the default action.
Issue Number: [#7064](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7064)
When using nz-popconfirm it used to have the little 'arrow' on the edge of the popconfirm dialog box;
```
[ ] Yes
[x] No
```
> fix(module:popconfirm): missing arrow

- components/mention/mention.component.ts
- components/mention/nz-mention.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:mention): do not run change detections on `mousedown` events

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-range-popup.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:date-picker): do not run change detection when the `date-range-popup` is clicked

- components/carousel/carousel.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:carousel): do not run change detection on non-handled `keydown` events

- components/time-picker/time-picker-panel.component.spec.ts
- components/time-picker/time-picker-panel.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:time-picker): do not run change detection when the time picker panel is clicked

- components/tree/tree-node.component.ts
- components/tree/tree.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:tree): do not run change detection when the tree node is clicked

- components/icon/icon.directive.ts
close #7186
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:icon): fix old icon element not removed

- components/rate/rate.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:rate): do not run change detection on `focus` and `blur` events if there are no output listeners

- components/drawer/drawer.component.ts
- components/drawer/style/drawer.less
fix close icon button without title property
```
[x] Bugfix
[ ] Feature
```
Issue Number:  [#7164](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7164)
close icon button will align right,  when does not set nzTitle property
```
[ ] Yes
[x] No
```
> fix(module:drawer): fix close icon position without title property

- components/code-editor/code-editor.component.ts
> fix(module:code-editor): always initialize outside of the Angular zone

- components/tree-view/node.ts
- components/tree-view/tree-virtual-scroll-view.ts
```
[x] Bugfix
[ ] Feature
```
1. default `innerTrackBy` function value being assigned on each `OnChanges` call 
2. during scroll further and back of VirtualTree, nodes is broken 
-   Reproduce - [Codesandbox](https://codesandbox.io/s/kwdhb) 
Issue Number: #7118
1. innerTrackBy function value being assigned only in case when `@Input trackBy` changing
2. VirtualTree scroll recreates nodes as it should be
- …
> fix(module:tree-view): fix innerTrackBy function #7118

- components/graph/core/minimap.ts
- components/graph/graph-minimap.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:graph): do not run change detection on animation frame

- components/modal/modal-ref.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:modal): resolve memory leaks

- components/input-number/input-number.component.ts
- components/input-number/input-number.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:input-number): reduce change detection cycles

- components/checkbox/checkbox.component.ts
- components/checkbox/checkbox.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:checkbox): reduce change detection cycles

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-range-popup.component.ts
close #7069, close #5335
```
[x] Bugfix
[ ] Feature
```
Issue Number: #7069, #5335 
Update the time status when the date changes
```
[ ] Yes
[x] No
```
> fix(module:date-picker): fix disable time when date changes

- components/slider/slider.component.ts
- components/slider/slider.spec.ts
```
[x] Bugfix
[ ] Feature
```
The key down event won't trigger the nzOnAfterChange callback
Issue Number: [#7251](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7251)
The key down event will trigger the nzOnAfterChange callback
```
[ ] Yes
[x] No
```
> fix(module:slider): fix keydown not trigger nzOnAfterChange

- components/input/autosize.spec.ts
- components/input/style/patch.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: #7203 
The textarea auto resizes correctly
```
[ ] Yes
[x] No
```
> fix(module:input): do not set box-sizing when measuring

- components/typography/text-edit.component.ts
- components/typography/typography.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:typography): do not run change detection on `input` and `keydown` events

- components/select/select.component.ts
- components/select/select.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: [#7216](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7216)
Does not do anything, if option data is null
```
[ ] Yes
[x] No
```
> fix(module:select): fix keyboard event error when option data is empty

- components/collapse/collapse-panel.component.ts
- components/collapse/collapse.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:collapse): do not run change detection if the panel is disabled

- components/i18n/languages/pt_BR.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: I18n pt_BR update
```
There are missing translations keys and a spelling error
Adding missing translations from the en_US file to the pt_BR file.
```
[ ] Yes
[x] No
```
> fix(module:i18n): update pt_BR.ts translations

- components/select/select.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:select): do not run change detection unnecessarily on click events

- components/button/button.component.ts
- components/button/button.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: [#7264](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7264)
When the button state is loading or disabled, the default event will not fire
```
[ ] Yes
[x] No
```
> fix(module:button): prevent default event fire

- components/resizable/resizable.directive.ts
- components/resizable/resizable.service.ts
- components/resizable/resizable.spec.ts
- components/resizable/resize-handle.component.ts
- components/resizable/resize-handles.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:resizable): do not run change detection on `mousedown` and `touchstart` events

- components/drawer/demo/module
- components/drawer/demo/service.ts
- components/drawer/demo/size.md
- components/drawer/demo/size.ts
- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer-options.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
close #7226 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7226 
Support `nzSize` and `nzExtra`
```
[ ] Yes
[x] No
```
Default width and height changes from `250px` to `378px`.
> feat(module:drawer): support new apis nzSize and nzExtra

- components/table/src/table/tr-measure.component.ts
> perf(module:table): do not unnecessarily re-enter the Angular zone

- components/table/src/table/table-inner-scroll.component.ts
> perf(module:table): spawn timers and add listener outside of the zone

- components/input/input-group.component.ts
```
[x] Bugfix
[ ] Feature
```
incorrect background-color when using `nzSuffix` and `nzAddOnAfter`
Issue Number: [#7247](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7247)
Close:  [#7247](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7247)
correct background-color
```
[ ] Yes
[x] No
```
> fix(module:input): incorrect background color in disabled state

- components/carousel/carousel.component.ts
- components/carousel/strategies/experimental/flip-strategy.ts
- components/carousel/typings.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:carousel): do not run change detection when the timer fires

- components/dropdown/context-menu.service.spec.ts
- components/dropdown/context-menu.service.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:dropdown): do not run change detection if the dropdown has been clicked inside

- components/select/option-item.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:select): do not run change detection on events if the `nz-option-item` is disabled

- angular.json
- components/avatar/avatar.spec.ts
- components/table/src/testing/table.spec.ts
- components/tabs/tabset.component.spec.ts
- components/time-picker/time-picker-panel.component.spec.ts
- components/transfer/transfer.spec.ts
- components/tree/tree.spec.ts
- custom-webpack-spec.config.js
- package.json
Since styleUrls with `ng-zorro-antd.less` in *.spec.ts make testing too slow, we should not inlcude all styles and need to solve the problem named `variable undefined`.
I'm not sure if `@angular-builders/custom-webpack:karma` is the best way, maybe someone can check this issue.
Refer to [ant-design webpack.config.js](https://github.com/ant-design/ant-design/blob/master/webpack.config.js#L125)
```
[ ] Bugfix
[ ] Feature
[ ] Other... …
```
> test(module:*): fix testing styleUrls to make it faster

- components/alert/alert.component.ts
- components/alert/alert.spec.ts
- components/alert/demo/action.md
- components/alert/demo/action.ts
- components/alert/demo/module
- components/alert/doc/index.en-US.md
- components/alert/doc/index.zh-CN.md
close #7245 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7245
```
[ ] Yes
[x] No
```
> feat(module:alert): support nzAction for customizing actions

- .husky/pre-commit
- package.json
Currently no stdout during pre-commit hook. By add a npm script we can display this process's stdout.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: add pre-commit npm script to display command process stdout

- components/icon/icon.directive.ts
- components/icon/icon.service.ts
- package.json
> fix(module:icon): do not try to load SVG on the Node.js side since it will throw an error

- components/upload/upload-btn.component.ts
```
[x] Bugfix
[ ] Feature
```
The transformed file will be ignored in subsequent pipeline operations.
Transformed file are not ignored.
```
[ ] Yes
[x] No
```
> fix(module:upload): fix the problem that the transformed file is lost

- components/list/list-item-cell.ts
The `NgZone.onStable` always emits outside of the Angular zone, but the zone has not been
re-entered. This leads to change detection being called outside of the Angular zone.
> fix(module:list): re-enter the Angular zone when the `NgZone.onStable` emits

- components/upload/upload.component.ts
…91 and 92
```
[x ] Bugfix
[ ] Feature
```
解决nz-upload在火狐浏览器91及92版本上拖拽上传时会默认打开一个新窗口
```
[ ] Yes
[x ] No
```
> fix(module:upload): fix upload drag drop will open new tab in firefox 91 and 92

- components/carousel/carousel.component.ts
- components/carousel/carousel.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: [#7323](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7323)
nzAfterChange callback return correctly 
Closed:  [#7323](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7323)
```
[ ] Yes
[x] No
```
> fix(module:carousel): fix nzAfterChange callback value not correctly

- components/image/doc/index.en-US.md
- components/image/doc/index.zh-CN.md
- components/image/image-preview-options.ts
- components/image/image-preview-ref.ts
- components/image/image.spec.ts
The nz-image add nzEnableLeftRightArrow to support press `left` or `right` to switch image
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:image): nz-image add press `left` or `right` to switch image

- components/modal/modal-ref.ts
- components/modal/modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
目前在关闭 Modal 的动画窗口期仍然能够触发 `nzOnOK` 或 `nzOnCancel`，造成用户意外的双击或者快速点击的情况下会重复的触发事件
当 Modal 处于 `Closing` 状态下时，将忽略 `nzOnOK` 或 `nzOnCancel` 的事件
```
[x] Yes
[ ] No
```
> fix(module:modal): no longer trigger any action when closing

- components/popconfirm/popconfirm.ts
```
[x] Bugfix
[ ] Feature
```
Event nzPopconfirmVisibleChange missing from the component.
Issue Number: #7337
Returns the deleted output event(nzPopconfirmVisibleChange) from the component.
```
[ ] Yes
[x] No
```
> fix(module:popconfirm): reverting missing nzPopconfirmVisibleChange

- components/modal/modal-container.directive.ts
- components/modal/modal.spec.ts
Calling `focus()` on the element causes browsers to do re-layouts. This can been seen here:
https://gist.github.com/paulirish/5d52fb081b3570c81e3a#setting-focus
Microtasks are executed asynchronously, but within the current rendering frame. Using `requestAnimationFrame`
except of `Promise.resolve` basically unloads the current frame and calls `focus()` on the next rendering
frame, this prevent frame drops on slower devices when the modal is opened:
> perf(module:modal): call `focus()` on the next rendering frame to prevent frame drop

- components/core/config/config.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:code-editor): remove monaco-editor dependency in config.ts

- components/cascader/cascader.component.ts
- components/cascader/cascader.spec.ts
- components/cascader/demo/status.md
- components/cascader/demo/status.ts
- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
- components/core/types/public-api.ts
- components/core/types/status.ts
- components/core/types/type.ts
- components/core/util/public-api.ts
- components/core/util/status-util.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7389
```
[ ] Yes
[x] No
```
> feat(module:cascader): support setting status

- components/core/color/generate.ts
- components/core/color/public-api.ts
- components/core/config/config.service.ts
- components/core/config/config.spec.ts
- components/core/config/config.ts
- components/core/config/css-variables.ts
- components/core/config/public-api.ts
- components/core/util/can-use-dom.ts
- components/core/util/dynamic-css.ts
- components/core/util/public-api.ts
- components/graph/style/index.less
- components/ng-zorro-antd.less
- components/ng-zorro-antd.variable.less
- components/style/patch.less
- docs/customize-theme-variable.en-US.md
- docs/customize-theme-variable.zh-CN.md
- package.json
- scripts/build/compile-styles.ts
- scripts/site/_site/doc/styles.less
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7389
- add `@ctrl/tinycolor`
- support setting css variable via `NzConfigService`
- sync codes about `css variable` from `ant-design`
```
[ ] Yes
[ ] No
```
> chore: add variable.less to support css variable

- components/cascader/cascader.spec.ts
- components/input-number/demo/status.md
- components/input-number/demo/status.ts
- components/input-number/doc/index.en-US.md
- components/input-number/doc/index.zh-CN.md
- components/input-number/input-number.component.ts
- components/input-number/input-number.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7389
```
[ ] Yes
[ ] No
```
> feat(module:input-number): support setting status

- components/transfer/transfer.component.ts
Fixes #7410.
```
[x] Bugfix
[ ] Feature
```
Inside the form, the `transfer` component is triggered by moving to the `right/left` on the `enter` command.
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7410
```
[ ] Yes
[x] No
```
> fix(module:transfer): `submit` behavior for button inside form

- components/date-picker/style/patch.less
```
[x] Bugfix
[ ] Feature
```
Make sure the picker popup is in the right position.
Caused by https://github.com/ant-design/ant-design/blob/master/components/date-picker/style/index.less#L225
```
[ ] Yes
[x] No
```
> fix(module:date-picker): fix position of picker popup

- components/mention/demo/async.ts
- components/mention/demo/avatar.md
- components/mention/demo/avatar.ts
- components/mention/demo/basic.ts
- components/mention/demo/custom-tag.md
- components/mention/demo/custom-tag.ts
- components/mention/demo/form.md
- components/mention/demo/form.ts
- components/mention/demo/multilines.md
- components/mention/demo/placement.md
- components/mention/demo/placement.ts
- components/mention/demo/prefix.md
- components/mention/demo/prefix.ts
- components/mention/demo/readonly.md
- components/mention/demo/readonly.ts
- components/mention/demo/status.md
- components/mention/demo/status.ts
- components/mention/doc/index.en-US.md
- components/mention/doc/index.zh-CN.md
- components/mention/mention.component.ts
- components/mention/nz-mention.spec.ts
- components/mention/style/patch.less
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(module:mentions): support setting status

- components/select/demo/module
- components/select/demo/status.md
- components/select/demo/status.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
- components/select/select.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7389\
```
[ ] Yes
[x] No
```
> feat(module:select): support setting status

- components/time-picker/demo/module
- components/time-picker/demo/status.md
- components/time-picker/demo/status.ts
- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:time-picker): support setting status

- components/tree-select/demo/module
- components/tree-select/demo/status.md
- components/tree-select/demo/status.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/tree-select.component.ts
- components/tree-select/tree-select.spec.ts
add 'nzStatus' , display diffrent status of tree-select
* docs  update 'nzStatus' docs
* test add 'nzStatus' tests
- [ x] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
Issue Number: 7389
```
[ ] Yes
[x] No
```
> feat(module:tree-select): add status

- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #7502 
Remove the deprecated monaco editor option link
```
[ ] Yes
[x] No
```
> docs(module:code-editor): fix monaco editor options deprecated

- components/input-number/input-number-group-slot.component.ts
- components/input-number/input-number-group.component.ts
- components/input-number/input-number.component.ts
- components/input/input-group-slot.component.ts
- components/input/input-group.component.ts
- components/input/input.directive.ts
- components/input/style/patch.less
- components/progress/progress.component.ts
- components/steps/step.component.ts
- components/steps/steps.component.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #7514 #7513
```
[ ] Yes
[ ] No
```
> fix(module:input, input-number, steps): fix styles in components

- components/input-number/demo/borderless.md
- components/input-number/demo/borderless.ts
- components/input-number/input-number.component.ts
- components/input-number/input-number.spec.ts
```
[ ] Bugfix
[x] Feature
```
Input number can be displayed without border
```
[ ] Yes
[x] No
```
> feat(module:input-number): add borderless support

- components/segmented/doc/index.en-US.md
the segmented component does not have an example import statement, unlike all the other components
```
[ ] Bugfix
[ ] Feature
```
The documentation for the Segmented Component does not included an example import statement, unlike all the other components
The documentation for the Segmented Component now includes an example import statement
```
[ ] Yes
[x] No
```
> docs(module:segmented): add example import

- components/core/overlay/overlay-position.ts
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/demo/placement.md
- components/date-picker/demo/placement.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7389
```
[ ] Yes
[x] No
```
> feat(module:date-picker): support date-picker placement

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
When opening a datepicker by code using open() function, the picker open fine but the picker input is not focused, involving problems to exit picker.
Can be reproduce on the customized range picker exemple [here](https://ng.ant.design/components/date-picker/en#components-date-picker-demo-start-end)
When opening by code, picket input get focused if not …
> fix(module:datepicker): focus input when opened programmatically

- components/transfer/transfer-list.component.ts
- components/transfer/transfer.spec.ts
> fix(module:transfer): uncheck "Select all" checkbox when filtered items are moved

- components/anchor/anchor-link.component.ts
- components/anchor/anchor.component.ts
- components/anchor/anchor.spec.ts
- components/anchor/demo/customize-highlight.md
- components/anchor/demo/customize-highlight.ts
- components/anchor/demo/on-change.md
- components/anchor/demo/on-change.ts
- components/anchor/demo/on-click.md
- components/anchor/demo/on-click.ts
- components/anchor/demo/target-offset.md
- components/anchor/demo/target-offset.ts
- components/anchor/doc/index.en-US.md
- components/anchor/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:anchor): sync new properties

- components/switch/doc/index.en-US.md
- components/switch/doc/index.zh-CN.md
- components/switch/switch.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6808
```
[ ] Yes
[x] No
```
> feat(module:switch): add nzId input

- components/steps/demo/nav.ts
- components/steps/steps.component.ts
- components/steps/steps.spec.ts
The first `div` child of the `nz-steps` element is redundant and should be merged with the `nz-steps` element.
```
[x] Bugfix
[ ] Feature
```
There is a layer of redundant `div` element under the `nz-steps` element.
Remove redundant `div` element.
```
[x] Yes
[ ] No
```
I'm not sure if this introduces breaking changes, but this changes the existing DOM structure.
> fix(module:steps): remove top-level redundant `div` element

- components/popconfirm/demo/async.md
- components/popconfirm/demo/async.ts
- components/popconfirm/demo/promise.md
- components/popconfirm/demo/promise.ts
- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.spec.ts
- components/popconfirm/popconfirm.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: popconfirm): support async close

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
[code line](https://github.com/NG-ZORRO/ng-zorro-antd/blob/797b2617f08394b56fe0a7903dc69e2d75984219/components/popconfirm/popconfirm.ts#L61)
> docs(module:popconfirm): fix `nzPopconfirmTrigger` default value to `click`

- components/breadcrumb/breadcrumb.spec.ts
- components/dropdown/context-menu.service.spec.ts
- components/dropdown/dropdown.directive.spec.ts
- components/menu/menu.spec.ts
- components/table/src/testing/th.spec.ts
- components/tabs/tabset.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test: add RouterTestingModule to spec files

- components/pagination/pagination-default.component.ts
- components/pagination/pagination-options.component.ts
- components/pagination/pagination-simple.component.ts
- components/pagination/pagination.component.ts
- components/pagination/pagination.spec.ts
```
[x] Bugfix
[ ] Feature
```
The pagination component missing `ul` tag
Issue Number:  [#7493](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7493)
Close:  [#7493](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7493)
Add `ul` tag
```
[ ] Yes
[x] No
```
> fix(module:pagination): add ul tag

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/demo/week-number.md
- components/date-picker/demo/week-number.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/inner-popup.component.ts
- components/date-picker/lib/abstract-table.ts
- components/date-picker/lib/date-table.component.ts
- components/date-picker/style/patch.less
```
[ ] Bugfix
[x] Feature
```
Week numbers are only shown in the week picker component.
Issue Number: Fixes #3764 
`[nzShowWeekNumber]` can control whether week numbers are shown in the date picker. Week numbers are still always shown in the week picker.
```
[ ] Yes
[x] No
```
> feat(module:date-picker): add nzShowWeekNumber property

- components/select/style/patch.less
```
[x] Bugfix
[ ] Feature
```
when set [nzDropdownMatchSelectWidth]="false", there is always a blank area at the bottom of the dropdown.
Issue Number: [#7625](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7625)
make [nzDropdownMatchSelectWidth]="false" behaviar normoal
```
[ ] Yes
[x] No
```
It's related to this PR [https://github.com/angular/components/pull/24394](https://github.com/angular/components/ …
> fix(module:select): fix broken cdk virtual scroll integration

- components/select/demo/placement.md
- components/select/demo/placement.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
- components/select/select.spec.ts
- components/select/select.types.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: select): support placement

- components/progress/demo/dashboard-layout.md
- components/progress/demo/dashboard-layout.ts
- package.json
- scripts/site/generate-site.js
- scripts/site/utils/get-meta.js
Add `debug: true` in the yaml meta, we could me a demo only visible in local development. It would be convenient to debug reproductions from the community.
允许在 demo 中增加 `debug: true` 属性，来让这个 demo 只出现在本地开发环境中，这样调试用户提供的复现时就会方便一些。
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:*): debug demos

- components/core/overlay/overlay-position.ts
- components/menu/demo/horizontal-position.md
- components/menu/demo/horizontal-position.ts
- components/menu/doc/index.en-US.md
- components/menu/doc/index.zh-CN.md
- components/menu/submenu.component.ts
Closes #4743
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4743 
Add new option for set position sub-menu
```
[ ] Yes
[x ] No
```
> feat(module:menu): add support nzPlacement for nz-submenu

- components/table/demo/multiple-sorter.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:table): update `multiple-sorter.ts`

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
```
[ ] Bugfix
[x] Feature
```
NzDropdownClassName only support string.
Issue Number: [#7611 ](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7611)
nzDropdownClassName supports both string and string[].
```
[ ] Yes
[x] No
```
> feat(module:select): add string array support for nzDropdownClassName

- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
```
[ ] Bugfix
[x] Feature
```
Not support input readonly.
Support input readonly.
```
[ ] Yes
[x] No
```
> feat(module:time-picker): support input readonly

- components/statistic/statistic.component.ts
- components/statistic/statistic.spec.ts
```
[x] Bugfix
[ ] Feature
```
There is a layer of redundant `div` element under the `nz-statistic` element.
Remove redundant `div` element.
```
[x] Yes
[ ] No
```
DOM structure will change.
> fix(module:statistic): remove top-level redundant `div` element

- components/date-picker/date-picker.component.ts
- components/date-picker/range-picker.component.spec.ts
```
[ x] Bugfix
[ ] Feature
```
Issue Number: 7534
it can clear range-picker when it has default value
```
[ ] Yes
[x ] No
```
> fix(module:date-picker): fix datePicker can't clear

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/range-picker.component.spec.ts
```
[ x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7450
it wiill show normally
```
[ ] Yes
[ x] No
```
> fix(module:date-picker): fix datePicker show multi panel

- components/date-picker/date-range-popup.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/style/patch.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7373
close: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7373
```
[ ] Yes
[x] No
```
> fix(module:date-picker): arrow in wrong position for RTL direction

- components/carousel/carousel.component.ts
- components/carousel/carousel.spec.ts
- components/carousel/demo/loop.md
- components/carousel/demo/loop.ts
- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- components/core/config/config.ts
- components/core/util/text-mesure.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7652 
close: #7652 
Set `[nzLoop] = "false"` can prevent the carousel to go in a loop, for example when we are on the last item and swipe it right it should stay there, not going on the first item.
```
[ ] Yes
[x] No
```
> feat(module: carousel): `nzLoop` to prevent the carousel to go in a loop

- components/icon/icon.directive.ts
> fix(module:icon): re-enter Angular zone after icons have been loaded

- components/popconfirm/popconfirm.ts
```
[ ] Bugfix
[ ] Feature
```
```html
<a nz-popconfirm [nzOkDanger]="true"></a>
```
```html
<a nz-popconfirm nzOkDanger></a>
```
```
[ ] Yes
[x] No
```
> fix(module:popconfirm): make nzOkDanger coerce to boolean

- components/alert/alert.component.ts
- components/alert/alert.spec.ts
- components/alert/demo/custom-icon.md
- components/alert/demo/custom-icon.ts
- components/alert/doc/index.en-US.md
- components/alert/doc/index.zh-CN.md
- components/alert/style/patch.less
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7687 
close: #7687 
Supported custom icon.
```
[ ] Yes
[x] No
```
Perhaps a field describing which version the feature was added could be provided, like Ant Design React.
> feat(module: alert): support custom icon

- components/table/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
nzShowSort is missing in English documentation
Issue Number: #7736 
nzShowSort is added to English documentation
```
[ ] Yes
[x] No
```
> docs(module:table): add missing nzShowSort to English documentation (#7736)

- components/select/select.component.ts
```
[x] Bugfix
[ ] Feature
```
- Load on Scroll - Activated Value resets to zero position after the adding of new page of data
- Multiple Selection - After selecting an item Activated Value resets to the first selected element instead of staying the same. And one have to navigate through all the list again to continue selection. It's significant for selecting by keyboard.
- Load on Scroll …
> fix(module:select): activated value resetting during load on scroll

- components/table/doc/index.en-US.md
updated wrong input name for the nzTotal binding of the table component docs.
```
[ ] Bugfix
[ ] Feature
```
docs with correct binding name for the current library master version.
```
[ ] Yes
[X] No
```
> docs(module:table): update wrong parameter name

- components/cron-expression/cron-expression-input.component.ts
- components/cron-expression/cron-expression-label.component.ts
- components/cron-expression/cron-expression-preview.component.ts
- components/cron-expression/cron-expression.component.ts
- components/cron-expression/cron-expression.module.ts
- components/cron-expression/demo/semantic.md
- components/cron-expression/demo/semantic.ts
- components/cron-expression/demo/use.md
- components/cron-expression/doc/index.en-US.md
- components/cron-expression/doc/index.zh-CN.md
- components/cron-expression/style/index.less
fix #7745
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
替换Collapse，新增自定义渲染cron时间
> feat(module:cron-expression): Optimize cron result display & support custom rendering cron time

- components/date-picker/date-picker.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/range-picker.component.spec.ts
add the possibility to assign an ElementRef to nzSeparator in nz-range-picker
```
[ ] Bugfix
[x] Feature
```
The nz-range-picker's nzSeparator accepts only a string
Now the nz-range-picker's nzSeparator accepts both string and ElementRef
```
[ ] Yes
[x] No
```
> feat(module:date-picker): add ElementRef type to nzSeparator

- components/tree-select/demo/virtual-scroll.ts
- components/tree/tree.component.ts
- components/tree/tree.spec.ts
```
[X] Bugfix
[ ] Feature
[X] Application (the showcase website) / infrastructure changes
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/5873
```
[ ] Yes
[X] No
```
For nz-tree component
when nzVirtualHeight is defined and nzHideUnMatched=true
then we should remove node with canHide=true from nzFlattenNodes
In showcase website, for tree select component, i put nzHideUnMatched=true for virtual scroll sample
> fix(module:tree): tree select search slow in virtual mode

- components/tree/tree-node-title.component.ts
```
[x] Bugfix
[ ] Feature
```
The `nz-tree-drop-indicator` is only rendered for tree nodes if no custom `treeTemplate` is provided
The `nz-tree-drop-indicator` is also rendered for tree nodes with a custom `treeTemplate`
```
[ ] Yes
[x] No
```
In this screenshot you can see the new behaviour: https://www.awesomescreenshot.com/video/10188107
The first tree uses a custom node template, the …
> fix(module: tree): nz-tree-drop-indicator for custom tree node templates

- components/list/list.component.ts
```
[x] Bugfix
[ ] Feature
```
Currently input `nzRenderItem` on NzList component is defined as `TemplateRef<void>` but it is instantiated with a context.
It works in current version to pass in a template, which relies on a provided context. Unfortunately template refs and their context are not type checked by Angular. So you can pass in a TemplateRef with context even if a TemplateRef without context is …
> fix(list): specify template ref context on input to match instantiation

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
- components/select/select.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7622
If nzSelectOnTab is true - selection of an item might be performed by TAB key
```
[ ] Yes
[x] No
```
> feat(module:select): select on Tab support

- components/select/select.component.ts
- components/select/select.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7681
close: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7681
```
[ ] Yes
[x] No
```
> fix(module:select): disabled option can be selected by Enter

- components/cascader/cascader.component.ts
- components/checkbox/checkbox.component.ts
- components/checkbox/checkbox.spec.ts
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/input-number/input-number.component.ts
- components/input-number/input-number.spec.ts
- components/radio/radio.component.ts
- components/radio/radio.spec.ts
- components/rate/rate.component.ts
- components/rate/rate.spec.ts
- components/select/select.component.ts
- components/select/select.spec.ts
- components/slider/slider.component.ts
- components/slider/slider.spec.ts
- components/switch/switch.component.ts
- components/switch/switch.spec.ts
- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
- package.json
```
[x] Bugfix
[ ] Feature
```
if the component is bind to a formControl and the property nzDisable is set to true initially the form element will stay enable. This is not the correct behavior. Form component should be disable
Issue Number: 7726 (release v15)
Form component bind by ngModel and property nzDisable set to true are now disable initially (this was the behavior in version 14) 
```
[ ] Yes
[x] No …
```
> fix: some forms component can't be disable

- components/checkbox/checkbox-group.component.ts
- components/checkbox/checkbox.spec.ts
- components/radio/radio-group.component.ts
- components/radio/radio.spec.ts
Fix a regression on disabling radio group and checkbox group initially if form is enable and input nzDisabled is set to true
```
[x] Bugfix
[ ] Feature
```
Radio Group and Checkbox group is enabled if form is initially enable and input nzDisabled is set to true
Issue Number
Radio Group and Checkbox group is disabled if form is initially enable and input nzDisabled is set to true
```
[ ] Yes
[x] No
```
> fix(module:checkbox): chebox group can't be disable initially

- components/radio/radio.component.ts
- components/radio/radio.spec.ts
Fix a regression on disabling state of radio button in a radio group 
```
[x] Bugfix
[ ] Feature
```
If radio-group is used with an enable formControl allthe radio button of this radio group are enable even if the nzDisable property is set to true
Issue Number: 7811
If radio-group is used with an enable formControl all the radio button disable state must respect the value of NzDisabled property initially
```
[ ] Yes
[x] No
```
> fix(module:radio): invalid disable state

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/range-picker.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
valueChange/ngModelChange is notified event if value don't change
Issue Number: #7814 
valueChange / ngModelChange  is not notified anymore if value not change
```
[ ] Yes
[x] No
```
> fix(module:datepicker): send OnChange event for same value

- components/typography/demo/text.ts
Remove mistakenly placed `<Link />` tag in typography docs
https://github.com/NG-ZORRO/ng-zorro-antd/issues/7832
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:typography): remove undesired tag

- components/date-picker/date-picker.component.spec.ts
- components/modal/demo/service.md
- components/modal/demo/service.ts
- components/modal/doc/index.en-US.md
- components/modal/modal-config.ts
- components/modal/modal-types.ts
- components/modal/modal.service.ts
- components/modal/modal.spec.ts
- components/qr-code/qrcode.component.spec.ts
- components/tooltip/tooltip.spec.ts
deprecate nzComponentParams
```
[ ] Bugfix
[x] Feature
```
Currently data pass to a custom component when nzContent is a component are retrieved thanks to nzComponentParams 
Now nzComponentParams property is deprecated, and data pass to a custom component when nzContent is a component are retrieved thanks to the Nz_MODAL_DATA injection token
```
[ ] Yes
[x] No
```
nzComponentParams …
> feat(module:modal): pass data to modal component through injection token

- components/form/demo/label-align.md
- components/form/demo/label-align.ts
- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/form-label.component.ts
- components/form/form-label.spec.ts
- components/form/form.directive.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:form): support form label align

- .github/CODEOWNERS
- components/components.less
- components/water-mark/demo/basic.md
- components/water-mark/demo/basic.ts
- components/water-mark/demo/custom.md
- components/water-mark/demo/custom.ts
- components/water-mark/demo/image.md
- components/water-mark/demo/image.ts
- components/water-mark/demo/module
- components/water-mark/demo/multi-line.md
- components/water-mark/demo/multi-line.ts
- components/water-mark/doc/index.en-US.md
- components/water-mark/doc/index.zh-CN.md
- components/water-mark/index.ts
- components/water-mark/ng-package.json
- components/water-mark/public-api.ts
- components/water-mark/style/entry.less
- components/water-mark/style/index.less
- components/water-mark/typings.ts
- components/water-mark/util.ts
- components/water-mark/water-mark.component.ts
- components/water-mark/water-mark.module.ts
- components/water-mark/water-mark.spec.ts
- scripts/prerender/route-paths.txt
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:watermark): add watermark component

- components/time-picker/time-picker-panel.component.spec.ts
- components/time-picker/time-picker-panel.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7699
close: https://github.com/NG-ZORRO/ng-zorro-antd/issues/7699
```
[ ] Yes
[X] No
```
> fix(module:time-picker): fix AM/PM selector hide

- components/radio/radio.component.ts
Fixes #7877.
```
[x] Bugfix
[ ] Feature
```
After clicking on a radio element, the focus monitor for the form state of the `touch` element is started
```
[ ] Yes
[x] No
```
> fix(module:radio): update `touch` status when `focus` and `blur` events

- scripts/site/_site/doc/app/app.component.ts
```
[x] Bugfix
[ ] Feature
```
when theme style file load failed (not exists or other causes), <link...${theme}...> will  always be added in DOM and useless.
and the message component will always display with processing UI.
If theme style file load failed, show error message with "Switching theme failed" and will not add multi-same <link> in DOM
```
[ ] Yes
[x] No
```
> fix: add error handler for style file load failed

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
This PR introduce a bug fix. 
```
[x] Bugfix
[ ] Feature
```
Before this PR, when the user  loose the focus without selected a value of date-picker input, datapicker control stay untouched
Issue Number: #7879
When the user loose the focus without selected a date, datePicker control become touched
```
[ ] Yes
[X] No
```
> fix(module:date-picker): ng-untouched when loose focus

- components/slider/slider.component.ts
fix #7943
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:slider): the first disable is invalid

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #7916
show week-number year rather than current year
```
[ ] Yes
[x] No
```
close #7916
> fix(module:date-picker): week number error when cross years

- components/water-mark/water-mark.component.ts
```
[x] Bugfix
[ ] Feature
```
MutationObserver 无法监听当前demo的删除事件
监听往上移一层，事件处理时判断是否为水印节点后再进行重绘
```
[ ] Yes
[ ] No
```
> fix(module:watermark): removing the watermark fails to redraw

- components/cascader/cascader.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cascader): customize the option title to undefined

- components/qr-code/demo/background.md
- components/qr-code/demo/background.ts
- components/qr-code/demo/color.md
- components/qr-code/demo/download.md
- components/qr-code/demo/error-level.md
- components/qr-code/demo/padding.md
- components/qr-code/demo/padding.ts
- components/qr-code/doc/index.en-US.md
- components/qr-code/doc/index.zh-CN.md
- components/qr-code/qrcode.component.ts
- components/qr-code/qrcode.spec.ts
- components/qr-code/qrcode.ts
Review the QR code drawing method to take care of padding and background color. So that the exported images (right click > save image as ...) looks better.
```
[X] Bugfix
[ ] Feature
```
Once you right click the QRCode element, and choose "Save Image As ..." in order to export the QR code, it doesn't have any paddings and background.
Issue Number: 7999
You are able to provide padding (default 10px) and BackgroundColor (default #fff) on the …
> feat(module:qrcode): padding & background color for qrcode

- .gitignore
- components/message/base.ts
- components/notification/demo/update.ts
- components/notification/notification.service.ts
- components/notification/notification.spec.ts
This PR is a fix for generating a new messageId for updating notification
```
[x] Bugfix
[ ] Feature
```
When we update a notification, the service generate a new messageId
Issue Number: 7975
When we update a notification, the service don't generate a new messageId
```
[ ] Yes
[x] No
```
> fix(module:notification): don't create new messageId for update

- components/resizable/demo/basic.ts
- components/resizable/doc/index.en-US.md
- components/resizable/doc/index.zh-CN.md
- components/resizable/resizable.directive.ts
- components/resizable/resizable.spec.ts
- [✅] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✅] Tests for the changes have been added (for bug fixes / features)
- [✅] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7986
NzResizeEvent will now contains a direction parameter with type NzResizeDirection
```
[ ] Yes
[x] …
```
> feat(module:resizable): add direction parameter in NzResizeEvent

- components/list/list-item-cell.ts
- components/list/list.spec.ts
Bug fix where asynchrone actions are not display in an item of a list
```
[x] Bugfix
[ ] Feature
```
Asynchrone action item are not displayed in the item.
Issue Number: #7954
Asynchronous action item list are now displayed
```
[ ] Yes
[x] No
```
> fix(module: list): fix the bug that synchrone action item are not displayed in the item

- components/modal/demo/service.md
- components/modal/demo/service.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-footer.component.ts
- components/modal/modal-types.ts
- components/modal/modal.component.ts
- components/modal/modal.service.ts
- components/modal/modal.spec.ts
- components/modal/utils.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7827
```
[x] Yes
[ ] No
```
> feat(module:modal): Remove nzComponentParams in v16

- components/dropdown/context-menu.service.spec.ts
- components/dropdown/context-menu.service.ts
```
[ ] Bugfix
[x] Feature
```
Currently on dropwdown context menu it's only possible to close the context menu if the user click outside of this context menu or clikcon an item of this context menu
Issue Number: #7911
Now it's possible to close the context menu on pressing the button key espcape
```
[ ] Yes
[x] No
```
> feat(module:dropdown): close context menu on escape

- components/select/select-top-control.component.ts
```
[ ] Bugfix
[ ] Feature
```
none
```
[ ] Yes
[x] No
```
> perf(module:select): remove unused types

- components/form/demo/label-wrap.md
- components/form/demo/label-wrap.ts
- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/form-label.component.ts
- components/form/form-label.spec.ts
- components/form/form.directive.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:form): support form label wrap

- components/dropdown/context-menu.service.spec.ts
- components/dropdown/context-menu.service.ts
- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
`NzContextMenuService#create()` return `void`，developer cannot listen to view destroy event.
`NzContextMenuService#create()` will now return `EmbeddedViewRef`, developers can listen to view destroy event through `EmbeddedViewRef#onDestroy()`.
```
[ ] Yes
[x] No
```
> feat(module:dropdown): improve `NzContextMenuService#create()`

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/option.component.ts
- components/select/select.component.ts
- components/select/select.types.ts
When 'object' is used as 'value' for select option re-rendering occurs each time data comes, to solve this added new 'key' param | 'nzKey' Input
```
[x] Bugfix
[ ] Feature
```
Under the hood nz-select uses value | nzValue as key for rendering optimizations. In case if value of 'object' type this doesn't work well.
Issue Number: #8034
We use value as fallback and allow passing key | nzKey for this specific …
> perf(module:select): ability to pass key | nzKey to select option

- components/tree-view/node.ts
- components/tree-view/tree-virtual-scroll-view.ts
```
[x] Bugfix
[ ] Feature
```
`node.ts / hasContextShapeChanged` function previously didn't allow customisation of how to compare data objects and did that by simple object link comparison.
Now it will use treeControl.trackBy function to extract concreate `key` field from object (as user defined) and do it in proper and optimised way
```
[ ] Yes
[x] No
```
> fix(module:tree-view): re-rendering fix for virtual-scroll-view

- components/cascader/demo/reactive-form.ts
- components/cron-expression/demo/use.ts
- components/form/demo/advanced-search.ts
- components/form/demo/auto-tips.ts
- components/form/demo/coordinated.ts
- components/form/demo/dynamic-form-item.ts
- components/form/demo/dynamic-rule.ts
- components/form/demo/horizontal-login.ts
- components/form/demo/label-align.ts
- components/form/demo/label-wrap.ts
- components/form/demo/layout.ts
- components/form/demo/normal-login.ts
- components/form/demo/register.ts
- components/form/demo/time-related-controls.ts
- components/form/demo/validate-reactive.ts
- components/input/demo/textarea-with-character-count.ts
- components/mention/demo/form.ts
- components/table/demo/dynamic-settings.ts
- components/water-mark/demo/custom.ts
**这是 [PR #8018](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8018) 的第二部分**
为了使示例代码的表单类型更为清晰，我为它们显式编写了类型，这会使代码量增加。
实际上表单类型可以通过类型推导自动得出：
```ts
const validateForm = fb.group({ field: [''] });
// ^? `FormGroup<{ field: FormControl<string | null> }>`
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(*): migrate to typed form

- components/table/src/cell/custom-column.directive.ts
```
[x] Bugfix
[ ] Feature
```
https://stackblitz.com/edit/angular-z9xssu
When using custom fixed-width columns, empty space appears between columns if the total width of the columns is less than the width of the table
```
[ ] Yes
[x] No
```
> fix(module:table): remove empty space in custom columns

- components/resizable/demo/grid.ts
- components/resizable/demo/layout.ts
- components/resizable/doc/index.en-US.md
- components/resizable/doc/index.zh-CN.md
- components/resizable/resizable.directive.ts
- components/resizable/resizable.spec.ts
- components/resizable/resize-handle.component.ts
- components/resizable/resize-handles.component.ts
- components/resizable/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:resizable): support for multiple cursor types

- components/breadcrumb/breadcrumb-item.component.ts
- components/breadcrumb/breadcrumb-separator.component.ts
- components/breadcrumb/doc/index.en-US.md
- components/breadcrumb/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
The `nz-breadcrumb-separator` has extra dom nodes.
Remove redundant dom nodes in `nz-breadcrumb-separator`.
```
[x] Yes
[ ] No
```
This may break user custom styles, which may be rare:
```css
nz-breadcrumb-separator .ant-breadcrumb-separator { }
nz-breadcrumb-separator > .ant-breadcrumb-separator { }
nz-breadcrumb-separator span { }
nz-breadcrumb-separator > …
```
> refactor(module:breadcrumb): remove redundant dom nodes

- components/core/services/singleton.ts
- components/message/base.ts
- components/message/message.spec.ts
- components/notification/notification.spec.ts
Call `overlayRef.dispose()` when all instances of messages have disappeared
Resolves #7772
The current implementation of the message service leaves a `nz-message-container` element in the DOM even after all messages have been removed. This PR introduces a small change so that the DOM is cleaned up when all messages are removed, so no extra elements remain in the DOM
```
[X] Bugfix
[ ] Feature
```
Issue …
> fix(module:message): clean up DOM after usage

- components/affix/affix.spec.ts
- components/input/demo/basic.ts
- components/input/doc/index.en-US.md
- components/input/input.directive.ts
- components/input/input.spec.ts
- components/input/style/mixin.less
- components/input/style/patch.less
have the possibility to hide or show  native stepper for input of type number
```
[ ] Bugfix
[x] Feature
```
Issue Number: #7956
It's now possible to have the possibility to hide or show the stepper with the directive nz-input and the type number
```
[ ] Yes
[x] No
```
> feat(module:input): hide stepper for type number

- components/message/base.ts
- components/message/message.spec.ts
- components/style/patch.less
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8010
由于 `.cdk-global-overlay-wrapper` 是绝对定位，给 `.cdk-global-overlay-wrapper` 的子元素设置 `z-index` 是无效的。
将 `z-index` 样式设置到 `.cdk-global-overlay-wrapper` 上。
```
[ ] Yes
[x] No
```
在此之前的 nz 的 cdk-overlay 预建样式是不完整的，此 PR 将导入完整的 `@angular/cdk/overlay-prebuilt.css`，用户不再需要自行导入该样式，**我希望这点会在 CHANGELOG 中特别指出**。
> fix(module:message): fix the z-index of overlay

- scripts/site/_site/doc/style/responsive.less
```
[✔] Bugfix
[ ] Feature
```
Go to the current <a href="https://ng.ant.design/docs/introduce/en"> document site </a>,  follow these steps to …
> fix(showcase): ui bug in rtl mode inside the doc site

- components/style/patch.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8119 #8106
我们不能通过简单的删除 `~` 符号来修复这一问题：
```less
@import '~@angular/cdk/overlay-prebuilt.css';
```
修改为
```less
@import '@angular/cdk/overlay-prebuilt.css';
```
这会导致 ZORRO 文档构建失败，因为编译器将该路径视为本地路径，而非外部依赖路径（node_modules）。
此修改通过使用 `@import (inline)` 内联导入语句，将外部 CSS 直接内联到文件，解决上述问题。
```
[ ] Yes
[x] No
```
> fix: inline external css

- components/tree-select/tree-select.component.ts
> fix(module:tree-select): 修复节点为禁用状态时，back快捷键能删除bug

- components/style/patch.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8131
This question is similar to https://github.com/angular/angular-cli/issues/12981 , importing `lib.css` in a relative directory will cause some problems.
No better solution has been found yet. This modification will use the past method of manually inlining the overlay style.
We should merge it as soon as possible and release a patch version.
@OriginRing …
> fix: inline cdk-overlay style

- components/drawer/drawer.module.ts
- components/drawer/drawer.service.module.ts
- components/drawer/drawer.service.ts
- components/drawer/public-api.ts
Drawer don't open in a lazyload module
This pr is a fix.
```
[X] Bugfix
[ ] Feature
```
The drawer does not open if the NzDrawerModule is imported into a lazyloader module and one of the components of the lazyloader module injects a service also declared in the lazyloader module.
The fact that the NzDrawerService service was injected into the Root injector prevented the resolution of the Lazyloader service, simply because the parentInjector was not …
> fix(module:drawer): drawer not open

- components/form/demo/label-wrap.ts
```
[✔] Bugfix
[ ] Feature
```
Clicking of this label, would focus on a wrong input.
The reason for this behavior is that there are more than one elements with `id: password`.  Just changed the second id to a unique value fixed this behavior. Now when that label id …
> fix(module:form): ui bug when clicking a label in forms document

- components/mention/demo/form.ts
```
[✔] Bugfix
[ ] Feature
```
Currently when you navigate to <a href="https://ng.ant.design/components/mention/en">mention component</a>, you'll notice that mention page does not load at all. This behaviour is caused by a logical error in `form.ts`. 
At line number 54, …
> fix(module:mention): page not loading entirely

- components/auto-complete/autocomplete.component.ts
```
[x] Bugfix
[ ] Feature
```
Fix the problem that when the dataSource is an object array, the value of the internal nz-auto-option is set incorrectly.
```
[ ] Yes
[x] No
```
> fix(module:autocomplete): fix the wrong value of internal nz-auto-option

- components/affix/affix.component.ts
- components/affix/affix.module.ts
- components/affix/doc/index.en-US.md
- components/affix/doc/index.zh-CN.md
- scripts/site/_site/doc/style/patch.less
- scripts/site/utils/marked.js
为了生成 standalone 标签，我增加了一种后缀，用于将组件/指令/管道标记为 standalone 的，目前暂定为 `:standalone`。
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:affix): support standalone component

- components/core/tree/nz-tree-base.service.ts
- components/tree/tree.component.ts
```
[x] Bugfix
[ ] Feature
```
The `checkedKeysChange` never emits a value (`emit` is never called in the component), so two-way binding is not possible.
Upon checking or unchecking any node, the `checkedKeysChange` now emits all the checked keys present in tree nodes.
```
[ ] Yes
[x] No
```
The test cases in general do not account for `EventEmitter` emissions. I can try to add a test for …
> fix(module:tree): nzCheckBoxChange never emitting

- components/table/demo/colspan-rowspan.md
- components/table/demo/expand-icon.md
- components/table/demo/expand-icon.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/cell/td-addon.component.ts
fix: #7882
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:table): nzExpand supports custom icon

- components/table/demo/row-selection-and-operation.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/addon/selection.component.ts
- components/table/src/cell/td-addon.component.ts
- components/table/src/cell/th-selection.component.ts
- components/table/src/testing/td.spec.ts
```
[ ] Bugfix
[x] Feature
```
It's impossible to add an accessible label to the built-in checkboxes in tables, making screen readers just read "checkbox" over and over again when tabbing through a table.
It is possible to set an `aria-label` on checkboxes in `th`s and `td`s with `nzShowCheckbox` (or `nzChecked`, etc.)
```
[ ] Yes
[x] No
```
> feat(module:table): add `nzLabel` to include aria-label in checkboxes

- components/table/style/index.less
- components/table/style/patch.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): custom column styles collapse when using nzScroll

- components/notification/demo/template.md
- components/notification/demo/with-btn.ts
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/notification/notification.component.ts
- components/notification/notification.service.ts
- components/notification/typings.ts
```
[ ] Bugfix
[x] Feature
```
1. 要想自定义按钮，必须传递整个 Notification 模板。
2. 不支持 title / content 模板
1. 使用 nzButton 实现自定义按钮。
2. 支持 title / content 模板
```
[x] Yes
[ ] No
```
一个微小的破坏性变更：
在使用字符串作为 title/content 时，`ant-notification-notice-message` 与 `ant-notification-notice-description` 的内部会增加一层 div 节点
这可能会破坏用户自定义的 CSS 选择器（子节点选择器）:
```css
.ant-notification-notice-message > x { } …
```
> feat(module:notification): support for more custom templates

- components/core/config/config.ts
- components/image/demo/controlled-preview.md
- components/image/demo/controlled-preview.ts
- components/image/demo/module
- components/image/demo/preview-group.ts
- components/image/doc/index.en-US.md
- components/image/doc/index.zh-CN.md
- components/image/image-group.component.ts
- components/image/image-preview-options.ts
- components/image/image-preview.component.ts
- components/image/image.directive.ts
- components/image/image.service.ts
- components/image/image.spec.ts
```
[ ] Bugfix
[✔] Feature
```
The current version of the image component does not allow customization of the scale step, which is fixed at 1.
• …
> feat(module:image): add scale step

- components/popconfirm/popconfirm.ts
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/tooltip.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6479
cdkConnectedOverlayPush would be open for tooltip, popover and popconfirm
```
[ ] Yes
[x] No
```
> feat(module:tooltip,popover,popconfirm): make cdkConnectedOverlayPush open for tooltip

- components/slider/demo/tip-formatter.ts
- components/slider/doc/index.en-US.md
- components/slider/doc/index.zh-CN.md
- components/slider/handle.component.ts
- components/slider/slider.component.ts
- components/slider/slider.spec.ts
- components/tooltip/tooltip.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: #7469
It is possible to use `template` for tooltip slider
Bug is fixed which didn't allow to update tooltip in runtime
```
[ ] Yes
[x] No
```
> feat(module:slider): add the ability to use a template

- components/color-picker/color-format.component.ts
- components/color-picker/color-picker.component.spec.ts
- components/color-picker/color-picker.component.ts
- components/color-picker/doc/index.en-US.md
- components/color-picker/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Unlike the color picker component in <a href="https://ant.design/components/color-picker#api">antd</a>, we do not …
> feat(module:color-picker): disable alpha

- components/anchor/anchor-link.component.ts
- components/anchor/anchor.component.ts
- components/anchor/anchor.module.ts
- components/anchor/doc/index.en-US.md
- components/anchor/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Transfromed Anchor module to standalone simillar to https://github.com/NG-ZORRO/ng-zorro-antd/pull/8037
Seems `BidiModule` is unused. Didn't find any usage of this module in the anchor's module. Removed.
Imported only required directives from `@angular/common` instead of whole `CommonModule`.
> feat(module:anchor): support standalone component

- components/water-mark/doc/index.en-US.md
- components/water-mark/doc/index.zh-CN.md
- components/water-mark/style/index.less
- components/water-mark/typings.ts
- components/water-mark/water-mark.component.ts
- components/water-mark/water-mark.module.ts
fix: #8187
```
[] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:water-mark): nzWaterMark is a block element && standalone

- components/pagination/doc/index.en-US.md
- components/pagination/doc/index.zh-CN.md
- components/pagination/pagination-default.component.ts
- components/pagination/pagination-item.component.ts
- components/pagination/pagination-options.component.ts
- components/pagination/pagination-simple.component.ts
- components/pagination/pagination.component.ts
- components/pagination/pagination.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Pagination component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:pagination): support standalone component

- components/carousel/carousel-content.directive.ts
- components/carousel/carousel.component.ts
- components/carousel/carousel.module.ts
- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Carousel component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:carousel): support standalone component

- components/alert/alert.component.ts
- components/alert/alert.module.ts
- components/alert/doc/index.en-US.md
- components/alert/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Transfrom `Alert` component to standalone simillar to https://github.com/NG-ZORRO/ng-zorro-antd/pull/8037
> feat(module:alert): support standalone component

- components/message/message-container.component.ts
- components/message/message.component.ts
- components/message/message.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Message component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:message): support standalone component

- components/auto-complete/autocomplete.component.ts
- components/badge/badge-sup.component.ts
- components/badge/badge.spec.ts
- components/cascader/cascader.component.ts
- components/date-picker/date-picker.component.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
- components/dropdown/dropdown-menu.component.ts
- components/graph/demo/module
- components/menu/submenu.component.ts
- components/popconfirm/popconfirm.ts
- components/popover/popover.ts
- components/select/select.component.ts
- components/tooltip/tooltip.ts
- components/tree-select/tree-select.component.ts
- components/tree-view/demo/module
- components/tree/tree.component.ts
```
[ ] Bugfix
[X] Feature
```
NzNoAnimation Directive is not standalone
NzNoAnimation Directive is standalone and NzNoAnimationModule is replaced in component library
```
[ ] Yes
[X] No
```
> feat(module:core): make no-animation standalone

- components/calendar/calendar-header.component.ts
```
[X] Bugfix
[ ] Feature
```
In calendar component, radio have a specific class todisplay the radio input as a button. This class is applied when the NzRadioButtonDirective is injected
Unfortunatly we just import NzRadioButton so the NzRadiButton directive injection is always null and the correct class is not apply
This is due to the standalone migration
At the end NzRadioButtonDirective must have the …
> fix(module:calendar): style radio button not apply

- components/tabs/tabset.component.ts
```
[X] Bugfix
[ ] Feature
```
Since the refactor of tab component div to button to respect the accessibility, when clicking on a new tab the bubbling of event trigger the ngSubmit function
Issue Number: #8308
NgSubmit function is not trigger anymore when clicking on an other tab
```
[ ] Yes
[X] No
```
> fix(module:tabs): change tab trigger ngSubmit function

- components/tag/demo/borderless.md
- components/tag/demo/borderless.ts
- components/tag/doc/index.en-US.md
- components/tag/doc/index.zh-CN.md
- components/tag/style/index.less
- components/tag/tag.component.ts
- components/tag/tag.spec.ts
```
[ ] Bugfix
[✔] Feature
```
Ant design provides a [borderless mode](https://ant.design/components/tag) for its tag component, which is not …
> feat(module:tag): borderless mode

- components/table/src/table/table-inner-scroll.component.ts
```
[x] Bugfix
[ ] Feature
```
`NzTableInnerScrollComponent` is missing a crucial import, which is `NzTbodyComponent`. The absence of this import causes tables with virtual scrolling to have broken styles, because `ant-table-tbody` class does not get applied to the `tbody` component (and other tbody related functionality is absent as well).z
By importing  `NzTbodyComponent` inside …
> fix(module:table): styles/behavior not applied to virtual scroll 

- components/transfer/transfer-search.component.ts
```
[✔] Bugfix
[ ] Feature
[] Other... Please describe: 
```
In Ant v4, the clear icon in Transfer component's search box is filled but here we are using the outline theme.
Change …
> fix(module:transfer): use fill theme for icon instead of outline

- components/drawer/doc/index.en-US.md
- components/drawer/drawer-ref.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
```
[ ] Bugfix
[X] Feature
```
As Angular is constantly evolving, we can do now a lot of things with the componentRef. In this idea in mind, it coud be a good idea to expose the componentRef when the nzContent is a component.
Now thanks to the getContentComponentRef function expose by the drawerRef. Developer have the possibilities to retrieve the componentRef of the nzContent in a …
> feat(module:drawer): return componentRef when nzContent is a component

- components/tabs/style/patch.less
- [✔️] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
```
[✔️] Bugfix
[ ] Feature
```
Currently when you hover tabs, the mouse cursor is the default one.
Issue Number: #8385 
Now is pointer cursor
```
[ …
```
> fix(module:tabs): wrong cursor

- components/modal/doc/index.en-US.md
- components/modal/modal-ref.ts
- components/modal/modal.service.ts
- components/modal/modal.spec.ts
```
[ ] Bugfix
[X] Feature
```
Currently modalRef don't expose the componentRef of nzContent which is too restricted. With the new API of Angular, user must have he possibilities to retrieve the ref of the component of nzContent to use for exemple APIs like setInput
Now ModalRef expose the component Ref of the nzContent when nzContent is a component. This exposition is done by the mehtod …
> feat(module:modal): expose componentRef nzContent

- components/carousel/carousel.component.ts
- components/carousel/carousel.spec.ts
```
[✔] Bugfix
[ ] Feature
```
Carousel component currently does not adapt to the new size when it is resized.
Issue Number: #8359 
```
[ ] Yes
[✔] No …
```
> fix(module:carousel): not adapting to new size when resizing

- components/core/overlay/overlay-z-index.ts
- components/core/overlay/public-api.ts
- components/drawer/drawer.component.ts
- components/modal/modal.service.ts
- components/modal/modal.spec.ts
```
[✔] Bugfix
[ ] Feature
```
The modal, drawer, or any other components that are made with the Angular CDK have the `zIndex` applied to the inner …
> fix(module:cdk): zIndex is not used properly when creating overlay

- components/tabs/style/patch.less
```
[✔] Bugfix
[ ] Feature
```
Slide indicator shrinks when the inline size of tab component is decreased.
Issue Number: #8351, #8384 
The mentioned …
> fix(module:tabs): slide indicator missing in small screens

- components/segmented/demo/with-icon-only.md
- components/segmented/demo/with-icon-only.ts
- components/segmented/types.ts
```
[ ] Bugfix
[✔] Feature
```
The segmented component in Ant Design([With Icon only](https://ant.design/components/segmented)) supports icons without …
> feat(module:segmented): now supports segmented with icon only

- components/avatar/avatar.component.ts
- components/avatar/avatar.spec.ts
```
[✔] Bugfix
[ ] Feature
```
The scaling of the avatar component was previously performed by a method named `notifyCalc`. This method used a …
> fix(module:avatar): avatar not re-scaling properly

- components/upload/upload-btn.component.html
This commit addresses the CSP issue by removing the inline `style` property from the `input` element within the `nz-upload` component. The use of inline style attributes necessitates the inclusion of `unsafe-inline`.
> fix(module:upload): remove inline style to resolve CSP issue

- components/graph/graph-edge.component.ts
This commit eliminates the `NgZone` dependency from the graph edge component. Since zone.js is becoming optional, `onStable` won't emit any value when `provideZonelessChangeDetection` is used in the application config. Instead, we now use the alternative approach provided by `afterNextRender`. Most of the code that was using `onStable` should be replaced with `afterNextRender`.
> fix(module:graph): remove NgZone dependency

- components/auto-complete/autocomplete.component.ts
- components/auto-complete/autocomplete.spec.ts
- components/core/render/after-next-render.ts
- components/core/render/index.ts
- components/core/render/ng-package.json
- components/core/render/public-api.ts
This commit eliminates the `NgZone` dependency from the autocomplete component. Since zone.js is becoming optional, `onStable` won't emit any value when `provideZonelessChangeDetection` is used in the application config. Instead, we now use the alternative approach provided by `afterNextRender`. Most of the code that was using `onStable` should be replaced with `afterNextRender`.
> fix(module:autocomplete): remove NgZone dependency

- components/pagination/pagination-item.component.ts
- components/pagination/pagination-simple.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8405 
add accessible name for nz-pagination-item component (the lighthouse point is improved from 82 to 88 in https://ng.ant.design/components/pagination/zh page)
PS: to solve the second issue `Form elements do not have associated labels`, we should refactor the nz-select component to accept more aria-* props.
```
[ ] Yes
[x] No
```
I've noticed that ant-design …
> fix(module:pagination): add accessible name for nz-pagination-item

- scripts/site/_site/doc/app/footer/footer.component.ts
```
[ ] Bugfix
[ ] Feature
```
Previously, since the footer component used the popover directive internally, this would cause the footer to fail to hydrate, so we made the footer skip the hydration.
Now that the popover hydration issue is fixed by #8512, we can re-engage the footer component for hydration
```
[ ] Yes
[x] No
```
> docs: allow footer components to participate in hydration

- components/color-picker/color-format.component.ts
- components/color-picker/typings.ts
```
[X] Bugfix
[ ] Feature
```
When we change the color of color-picket nzOnChange event is emitted twice
Issue Number: #8502
When we change the color of color picker nzOnChange event is emitted only one time
```
[ ] Yes
[X] No
```
> fix(module:color-picker): avoid emitted twice nzOnChange event

- components/back-top/back-top.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> perf(module:back-top): remove the redundant changeDetectorRef

- components/i18n/languages/en_US.ts
- components/i18n/languages/zh_CN.ts
- components/i18n/nz-i18n.interface.ts
- components/qr-code/demo/status.md
- components/qr-code/demo/status.ts
- components/qr-code/qrcode.component.spec.ts
- components/qr-code/qrcode.component.ts
- [✅] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✅] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[✅] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:qrcode): qrcode supports scanned state

- angular.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
Currently, when running the application with `npm run start`, it starts in development mode without sourceMap enabled. This means that the source maps, which are useful for debugging, are not generated.
Now, when running the application with the new `npm run start:dev` command, it starts in development mode with sourceMap enabled. 
```
[ ] Yes
[x] No
```
> chore: set default server configuration to development

- components/rate/doc/index.en-US.md
- components/rate/rate.component.ts
- components/rate/rate.spec.ts
```
[ ] Bugfix
[X] Feature
```
Currently when the rate is left no event emitter is sent. This prevent customisation like changing icon
Issue Number: #8415
hoverChange event is now sent when the user left the rate
```
[ ] Yes
[X] No
```
> feat(module:rate): emit hover change when leave

- components/i18n/languages/de_DE.ts
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: i18n
```
```
[ ] Yes
[x] No
```
> fix(module:i18n) add missing german translations

- schematics/ng-generate/side-menu/standalone/src/app/app.component.ts.template
Every time 'side-menu' is chosen when adding ng-zorro-antd into Angular project, app.component.html uses RouterLink in Dashboard/welcome router, but the Routerlink is not imported in app.component.ts, I have to import RouterLink in app.component.html whenever I create a new project.
1. Choose sidemenu when import ng-zorro-antd
2. the generated app.component.html used 'RouterLink' without 'RouterLink' in import code block
3. The 'RouterLink' is missed
import RouterLink
> fix(module:schematics): import RouterLink

- .github/PULL_REQUEST_TEMPLATE.md
1. Fix a problem: add x follow the comments when I choose a PR type
(this commets doesn't work)
```
```
2. Declared as a selection box
(1) Delete the code block(```) declaration
(2) add list(-) declaration
selection box doesn't rendered 
selection box do rendered
> chore(docs): update PR template

- components/cascader/cascader.component.ts
- components/cascader/cascader.spec.ts
> fix(module:cascader): hide placeholder when trigger compositionstart

- components/transfer/demo/basic.ts
- components/transfer/transfer.component.ts
[REPRODUTION STEPS]
- take the [basic usage demo](https://ng.ant.design/components/transfer/zh#components-transfer-demo-basic) for example
- select all items in left and transfer to right
- then all the items in left are disabled, but the SELECT-ALL button in left still works
> fix(module:transfer): disabling selection does not affect selecting all

- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- components/icon/icon.module.ts
- components/icon/icon.spec.ts
- components/icon/provide-icon.ts
- components/icon/provide-icons.ts
- components/icon/public-api.ts
- schematics/ng-add/setup-project/register-locale.ts
- schematics/ng-generate/side-menu/index.ts
- schematics/ng-generate/side-menu/standalone/src/app/icons-provider.ts.template
- schematics/utils/apply-changes.ts
- scripts/site/_site/doc/app/app.config.server.ts
- scripts/site/_site/doc/app/app.config.ts
Developer can use `provideNzIcon` API in root and `provideNzIconPatch` in lazy-loading module or standalone component to provide icons now.
Of course the former `NzIconModule.forRoot` and `NzIconModule.forChild` API are still supported but not recommended in standalone mode any more.
[USAGE]
```typescript
import { provideNzIcon } from 'ng-zorro-antd/icon';
export const appConfig = {
providers: [provideNzIcon(icons)]
}
```
```typescript
import { NzIconModule, provideNzIconPatch } from 'ng-zorro-antd/icon';
// in xxx.component.ts
@Component({
standalone: true,
imports: [NzIconModule],
providers: [provideNzIconPatch([QuestionOutline])]
})
class ChildComponent {}
// or in …
```
> feat(module:icon): add `provideNzIcon` and `provideNzIconPatch` API

- components/tree-select/tree-select.component.ts
> fix(module:tree-select): clear selected nodes when user set value

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/inner-popup.component.ts
- components/date-picker/lib/abstract-panel-header.ts
- components/date-picker/lib/date-header.component.ts
- components/date-picker/lib/decade-header.component.ts
- components/date-picker/lib/month-header.component.ts
- components/date-picker/lib/quarter-header.component.ts
- components/date-picker/lib/year-header.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/standard-types.ts
Currently panel mode change event is not sent when user click on the arrow on the header panel of the datepicker.
This is not the same behavior of the ant design. When user click on the arrow we must send the new mode and the date
Issue Number: #8648
An event is sent each time user click on an arrow, and the event send the information as an object 
{ date, mode }
> feat(module:datepicker): send event emitter when panel mode change

- components/i18n/languages/hu_HU.ts
Add "DatePicker.lang.rangeQuarterPlaceholder" translation for hu_HU for avoid console warning message when use datepicker
> fix(i18n): update hu_HU language

- components/tabs/demo/guard.ts
- components/tabs/demo/lazy.md
- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/tab-body.component.ts
- components/tabs/tab.component.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
> feat(module:tabs): support destroyInactiveTabPane input

- components/modal/modal.service.ts
- components/modal/modal.spec.ts
In Angular CDK Overlay, if backdropClass is not set, the default is 'cdk-overlay-dark-backdrop', which causes a black background even when nzMask is set to false. Therefore, set the default value based on the value of nzMask.
> fix(module:modal): remove dark backdrop when nzMask is false

- components/select/select-search.component.ts
Issue Number: Close #8847 
当 select 的 nzMode 设为 multiple 或 tags 且 switch 的 nzSize 设为 small 时，switch 组件初始化时不再出现大小闪烁现象（由 default 变为 small）
When nzMode of select is multiple or tags, and nzSize of switch is small, the size flashing (change from default to small) of switch no longer occurs at initialization.
> fix(module: select): multiple select cause switch size flash when init

- components/anchor/anchor-link.component.ts
… 'a' tag problem with 'null' or 'undefined' value if templateRef provided
https://stackblitz.com/edit/stackblitz-starters-1rvbyj?file=src%2Fmain.ts
Stackblitz example added.
> fix(module:anchor): fix 'a' tag problem with 'null' or 'undefined' value if templateRef provided

- components/button/button-group.spec.ts
- components/color-picker/color-block.component.spec.ts
- components/color-picker/color-picker.component.spec.ts
- components/core/element-patch/element-patch.spec.ts
- components/core/form/nz-form-item-feedback-icon.spec.ts
- components/core/outlet/string_template_outlet.spec.ts
- components/core/testing/component-bed.ts
- components/core/testing/fake-viewport-ruler.ts
- components/core/testing/wrapped-error-message.ts
- components/core/transition-patch/transition-patch.spec.ts
- components/date-picker/date-picker.component.spec.ts
- components/flex/flex.spec.ts
- components/grid/grid.spec.ts
- components/icon/icon.spec.ts
- components/layout/layout.spec.ts
- components/qr-code/qrcode.component.spec.ts
The following methods or classes are internally used and we are not willing users to use them directly:
- component/core/testing/wrapped-error-message.ts: `wrappedErrorMessage`
- component/core/testing/component-bed.ts: `createComponentBed`
- component/core/testing/fake-viewport-ruler.ts: `FakeViewportRuler`
They are marked as DEPRECATED, and will be REMOVED in v20
> test(module:*): deprecate internal APIs and remove references

- components/transfer/interface.ts
- components/transfer/transfer-list.component.ts
- components/transfer/transfer.component.ts
- components/transfer/transfer.spec.ts
**REPRODUTION STEPS**
+ take the [basic usage demo](https://ng.ant.design/components/transfer/zh#components-transfer-demo-basic) for example
+ select all items in left
+ cancel selecting all items in left
+ **result**: selecting all items can trigger `nzSelectChange` callback (`console.log('nzSelectChange', ret);`), but cancel selecting all can not
select all or cancel will both trigger `nzSelectChange` callback
> fix(module:transfer): fix transfer all selecting cancel event

- components/cascader/cascader.component.ts
- components/cascader/cascader.service.ts
- components/cascader/cascader.spec.ts
> fix(module:cascader): correct menu display level

- components/avatar/avatar.component.ts
- components/avatar/avatar.spec.ts
当 文字类型的头像 在像 dropdown 这种 overlay 组件中渲染时，无法正确计算文本尺寸：
通过使用 `afterRender` 来确保可以正确 读/写 DOM 来解决该问题：
> fix(module:avatar): calculate size at the right time

- components/card/card.component.ts
- components/card/doc/index.en-US.md
- components/card/doc/index.zh-CN.md
- components/core/config/config.ts
Card 组件应该只有 bordered 属性，没有 borderless 属性：https://4x.ant.design/components/card-cn/#API:~:text=%2D-,bordered,-%E6%98%AF%E5%90%A6%E6%9C%89%E8%BE%B9%E6%A1%86
不清楚什么原因添加了 borderless 来替代 bordered：https://github.com/NG-ZORRO/ng-zorro-antd/pull/5796/files
> fix(module:card): remove borderless input

- components/message/doc/index.en-US.md
- components/message/doc/index.zh-CN.md
- components/message/message.module.ts
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/notification/notification.module.ts
- components/notification/notification.service.module.ts
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/app.config.ts
更新了这两个组件的导入用法。
由于 NzMessageService 与 NzNotificationService 都是在 root 中提供的（`providedIn: 'root'`），并且这两个组件都是 standalone 的，因此不再需要导入对应的 NgModule 即可使用。
弃用这两个组件对应的 NgModule，无论是在 standalone 还是非 standalone 的应用中，这两个 NgModule 都是不必要的。
> docs(module:message,notification): update import usages

- components/transfer/demo/advanced.md
- components/transfer/demo/can-move.md
- components/transfer/demo/custom-item.md
- components/transfer/demo/one-way.md
- components/transfer/demo/one-way.ts
- components/transfer/demo/search.md
- components/transfer/demo/status.md
- components/transfer/demo/table-transfer.md
- components/transfer/demo/tree-transfer.md
- components/transfer/doc/index.en-US.md
- components/transfer/doc/index.zh-CN.md
- components/transfer/transfer-list.component.ts
- components/transfer/transfer.component.ts
- components/transfer/transfer.spec.ts
> feat(module:transfer): use nzOneWay to make Transfer the one way style

- components/affix/affix.component.ts
- components/anchor/anchor.component.ts
- components/breadcrumb/breadcrumb.component.ts
- components/core/config/config.service.ts
- components/dropdown/dropdown.directive.ts
- components/float-button/float-button-top.component.ts
- components/graph/graph.component.ts
- components/image/image-preview.component.ts
- components/select/select.component.ts
- components/table/src/addon/filter-trigger.component.ts
- components/tabs/tabset.component.ts
- components/time-picker/time-picker-panel.component.ts
- components/time-picker/time-picker.component.ts
- components/tree-view/node.ts
- components/tree-view/outlet.ts
- components/tree-view/padding.ts
- components/tree-view/toggle.ts
- components/tree-view/tree-view.ts
- components/tree-view/tree-virtual-scroll-view.ts
- schematics/ng-update/test-cases/config.ts
- scripts/gulp/tsconfig.json
- scripts/prerender/tsconfig.json
- tsconfig.json
`@WithConfig()` 装饰器现在是标准装饰器，关闭 `experimentalDecorators` 选项。
该 API 从未在文档中公开，应该属于 ZORRO 私有 API，因此不会对用户造成 "breaking change"，
但如果用户也使用了该 API，则需要关闭 `experimentalDecorators` 选项。
不太确定是否需要添加 "breaking change" label。
> refactor: migrate to standard decorators

- components/flex/demo/align.ts
- components/flex/demo/gap.ts
- components/flex/demo/wrap.ts
- components/qr-code/demo/error-level.ts
- components/segmented/demo/basic.ts
- components/segmented/demo/custom.md
- components/segmented/demo/custom.ts
- components/segmented/demo/disabled.ts
- components/segmented/demo/dynamic.ts
- components/segmented/demo/size.ts
- components/segmented/demo/value.md
- components/segmented/demo/value.ts
- components/segmented/doc/index.en-US.md
- components/segmented/doc/index.zh-CN.md
- components/segmented/public-api.ts
- components/segmented/segmented-item.component.ts
- components/segmented/segmented.component.ts
- components/segmented/segmented.module.ts
- components/segmented/segmented.service.ts
- components/segmented/segmented.spec.ts
- components/segmented/types.ts
1. ngModel 的值是 index
2. 自定义渲染用法不符合人体工学
```html
<nz-segmented [nzLabelTemplate]="templateRef" [nzOptions]="options"></nz-segmented>
<ng-template #temp let-index="index">
@switch (index) {
@case (0) {
<nz-avatar nzSrc="https://joeschmoe.io/api/v1/random"></nz-avatar>
<div>User 1</div>
}
@case (1) {
<nz-avatar nzText="K"></nz-avatar>
<div>User 2</div>
}
@case (2) {
<nz-avatar nzIcon="user"></nz-avatar>
<div>User 3</div>
}
}
</ng-template>
```
1. 将 ngModel 的值改为 `option.value`
2. 新增 `[nz-segmented-item]` 组件，提供直接的自定义渲染功能
```html
<nz-segmented>
<label nz-segmented-item nzValue="user1">
<div [style.padding.px]="4">
<nz-avatar nzSrc="https://joeschmoe.io/api/v1/random" /> …
```
> feat(module:segmented): redesign the segmented component

- components/core/config/config.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/cell/th-addon.component.ts
add nzSortDirections to table global config
We can't change nzSortDirections for table component globally
Issue Number: #6613
We can now change nzSortDirections for table component globally in the TableConfig object
> feat(module:table): add nzSortDirections to table global config (#6613)

- components/i18n/languages/vi_VN.ts
Add rangeQuarterPlaceholder: ['Quý bắt đầu', 'Quý kết thúc'], in vi_VN.ts
Add rangeQuarterPlaceholder: ['Quý bắt đầu', 'Quý kết thúc'], in vi_VN.ts
> fix(module:i18n): add missing translations to `vi_VN`

- components/auto-complete/autocomplete.spec.ts
- components/input-number/style/index.less
- components/input/style/index.less
- components/mention/mention.spec.ts
- components/space/demo/compact.ts
- components/space/space-compact-item.directive.ts
- components/space/space-compact.component.ts
- components/style/mixins/compact-item.less
antd4 对于附带 affixes 与 addons 的 input 与 input-number 的 compact 样式并不完整，[查看 DEMO](https://stackblitz.com/edit/react-y4avnr?file=demo.tsx)
此 PR 通过更新样式以支持这些情况。
此外，这个 PR 还修复了：
- 支持 RTL 模式
- 当 `space-compact` 作为**祖先**组件但不是**直接**父组件时，应该判定为非 compact 模式。
> fix(module:space): fix style of compact mode of input & input-number

- .github/CODEOWNERS
- components/cascader/cascader-option.component.ts
- components/cascader/cascader-tree.service.ts
- components/cascader/cascader.component.ts
- components/cascader/cascader.module.ts
- components/cascader/cascader.service.ts
- components/cascader/cascader.spec.ts
- components/cascader/demo/basic.ts
- components/cascader/demo/custom-render.md
- components/cascader/demo/multiple.md
- components/cascader/demo/multiple.ts
- components/cascader/demo/search.ts
- components/cascader/demo/size.md
- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
- components/cascader/public-api.ts
- components/cascader/typings.ts
- components/cascader/utils.ts
- components/core/tree/nz-tree-base-node.ts
- components/core/tree/nz-tree-base.service.ts
- components/select/select-item.component.ts
- components/select/select-placeholder.component.ts
- components/select/select-top-control.component.ts
- components/select/select.component.ts
- components/space/demo/compact.ts
Issue Number: close #6981 #8853
Redesign the cascader component (which option list is now based on `NzTreeBase`) and support multiple selection
**BREAKING CHANGE**
In the past, the cascader component kept a trick that if you wrote value with `NzCascaderOption[]` type, it extracted value by mapping each item to its value property, for example:
```ts
@Component({
template: `<nz-cascader [nzOptions]="options" [ngModel]="value"></nz-cascader>`
})
export class ExampleComponent {
value = [{ label: 'NG ZORRO', value: 'ng-zorro-antd' }]
}
```
then the value of cascader would be `'ng-zorro-antd'`.
It's strange that the input and output values don't match when we haven't changed the values and …
> feat(module:cascader): support multiple selection

- components/input-number/input-number.component.ts
在 antd 中，feedback icon 也属于 suffix，需要将它渲染到正确的位置。
https://4x-ant-design.antgroup.com/components/form-cn/#:~:text=%E8%AF%B7%E9%80%89%E6%8B%A9%E6%97%A5%E6%9C%9F-,Success,-Success
> fix(module:input-number): correctly render the feedback icon

- components/tree-view/tree-virtual-scroll-view.ts
Issue Number: close #8915 
nzTreeNodePadding works in virtual scroll
> fix(module:tree-view): nzTreeNodePadding not works in virtual scroll

- components/select/select-top-control.component.ts
when select component nzMode is multiple or tags,  search input will allways show.
> fix(module:select): multiple selection don't show search input

- components/checkbox/checkbox-group.component.ts
- components/checkbox/checkbox-group.spec.ts
- components/checkbox/checkbox-wrapper.component.ts
- components/checkbox/checkbox.component.ts
- components/checkbox/checkbox.spec.ts
- components/checkbox/demo/basic.ts
- components/checkbox/demo/check-all.ts
- components/checkbox/demo/controller.ts
- components/checkbox/demo/group.ts
- components/checkbox/demo/layout-legacy.md
- components/checkbox/demo/layout-legacy.ts
- components/checkbox/demo/layout.md
- components/checkbox/doc/index.en-US.md
- components/checkbox/doc/index.zh-CN.md
- components/checkbox/public-api.ts
- components/checkbox/tokens.ts
Issue Number: #4883
- `<nz-checkbox-group>` 的 `ngModel` 的类型为 `NzCheckBoxOptionInterface[]`，与 antd 不一致
- `<nz-checkbox-group>` 无法像 [antd](https://4x-ant-design.antgroup.com/components/checkbox-cn/#components-checkbox-demo-layout) 那样自定义布局，需要借助 `<nz-checkbox-wrapper>` 组件实现自定义布局，但 `<nz-checkbox-wrapper>` 又不是一个控件组件，用途不大。实际上 `<nz-checkbox-wrapper>` 应该被实现为 `<nz-checkbox-group>`。
- 将 `<nz-checkbox-group>` 的 `ngModel` 的类型修正为 `NzCheckBoxOptionInterface['value'][]`
- `<nz-checkbox-group>` 支持自定义布局
- `<nz-checkbox-group>` 新增 `[nzName]`
- `[nz-checkbox]` 新增 `[nzName]`
- 弃用 `<nz-checkbox-wrapper>`
- 弃用 `NzCheckBoxOptionInterface`，使用 `NzCheckBoxOption` 替代
```html
<nz-checkbox-group [ngModel]="['A', …
```
> feat(module:checkbox): redesign the checkbox group component

- components/cascader/cascader.component.ts
- components/cascader/cascader.spec.ts
- components/cascader/demo/multiple.ts
When click the checkbox, the check state changes, but ngModelChange not triggered
Issue Number: close #8930 
When check state changes, trigger ngModelChange
> fix(module:cascader): should change check state trigger ngModelChange

- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/inner-popup.component.ts
- components/date-picker/lib/date-table.component.ts
Issue Number: #8743 
The cell title of the date picker reflects `nzFormat` instead of relying on the locale setting.
> fix(module:date-picker): cell title should reflect nzFormat

- components/input-number/input-number.component.ts
> fix(module:input-number): fix NG0600 error

- components/ng-package.json
- components/package.json
@ctrl/tinycolor 是 color-picker 和 core 的依赖，但没有在 package.json 中声明，导致了 stackblitz demo 无法正常工作。
```
./node_modules/ng-zorro-antd/fesm2022/ng-zorro-antd-core-color.mjs:1:0-65 - 
Error: Module not found: Error: Can't resolve '@ctrl/tinycolor' in '/node_modules/ng-zorro-antd/fesm2022'
```
> chore: add @ctrl/tinycolor to dependencies

- components/transfer/transfer-list.component.ts
> fix(module:transfer): correctly set the transfer-list-body class

- components/progress/progress.component.ts
NG0956: The configured tracking expression (track by identity) caused re-creation of the entire collection of size 1. This is an expensive operation requiring destruction and subsequent creation of DOM nodes, directives, components etc. Please review the "track expression" and make sure that it uniquely identifies items in a collection. Find more at https://angular.dev/errors/NG0956
> fix(module:progress): fix NG0956 error

- components/popconfirm/popconfirm.spec.ts
- components/popover/popover.spec.ts
- components/tooltip/base.ts
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
…ace delimited classes string
Issue Number: close #8952 
overlayClassName only supports a single class
```ts
// works
nzPopoverOverlayClassName="testClass"
// doesn't work
nzPopoverOverlayClassName="testClass1 testClass2"
```
`nzPopconfirmOverlayClassName` `nzTooltipPopoverOverlayClassName` `nzPopoverOverlayClassName` support space delimited classes
```ts
// works
nzPopoverOverlayClassName="testClass"
// works too
nzPopoverOverlayClassName="testClass1 testClass2"
```
> feat(module:popover,popconfirm,tooltip): overlayClassName supports space delimited classes

- components/tree-select/tree-select.component.ts
> fix(module:tree-select): fix tree select error

- components/checkbox/checkbox-group.component.ts
- components/checkbox/checkbox-group.spec.ts
- components/input-number/input-number.component.spec.ts
- components/input-number/input-number.component.ts
> fix(module:input-number,checkbox): accept the disabled change from ng control

- components/hash-code/hash-code.component.spec.ts
- components/hash-code/hash-code.component.ts
- components/hash-code/style/index.less
> refactor(module:hash-code): modify component style name

- components/tree-select/tree-select.component.ts
An error is reported when judging multiple instance conditions
https://stackblitz.com/edit/kzn1gfa7-2qtub7c7?file=src%2Fapp%2Fapp.component.ts
Issue Number: #8983
Multiinstance normal
- [ x] No
> fix(module:nz-tree-select): fix error when judging multiple instance condition

- components/message/demo/template.md
- components/message/demo/template.ts
- components/message/doc/index.en-US.md
- components/message/doc/index.zh-CN.md
- components/message/message.component.ts
- components/message/message.service.ts
- components/message/message.spec.ts
- components/message/typings.ts
- components/notification/demo/custom-icon.ts
- components/notification/demo/template.ts
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/notification/notification.component.ts
- components/notification/notification.service.ts
- components/notification/notification.spec.ts
- components/notification/typings.ts
nzData are not passed when content is custom template
Issue Number: 8997
nzData are  passed when content is custom template
> feat(module:message,notification): display nzData when content is a template

- .github/CODEOWNERS
- components/check-list/check-list-button.component.ts
- components/check-list/check-list-content.component.ts
- components/check-list/check-list.component.spec.ts
- components/check-list/check-list.component.ts
- components/check-list/check-list.module.ts
- components/check-list/demo/basic.md
- components/check-list/demo/basic.ts
- components/check-list/demo/custom.md
- components/check-list/demo/custom.ts
- components/check-list/doc/index.en-US.md
- components/check-list/doc/index.zh-CN.md
- components/check-list/index.ts
- components/check-list/ng-package.json
- components/check-list/public-api.ts
- components/check-list/style/entry.less
- components/check-list/style/index.less
- components/check-list/typings.ts
- components/components.less
- components/i18n/languages/en_US.ts
- components/i18n/languages/zh_CN.ts
- components/i18n/nz-i18n.interface.ts
- scripts/prerender/route-paths.txt
> feat(module:check-list): add check-list component

- components/input-number-legacy/input-number.component.ts
- components/input-number/demo/formatter.ts
- components/input-number/input-number.component.spec.ts
- components/input-number/input-number.component.ts
Issue Number: #8985 
通过此 PR 修正一系列问题，并将组件行为进一步对齐 antd
- 支持键入空字符串以将值置为 null
- 在用户输入期间也会触发 ngModelChange
- 在用户输入期间调用 formatter
- 输入非法值，或超出范围的值，不会触发 ngModelChange，并在失焦时恢复到上一个合法值
- writeValue 触发期间不会触发多余的 ngModelChange
- 在失焦时修正数字精度
> fix(module:input-number): use input event instead of change event

- components/segmented/segmented-item.component.ts
- components/segmented/segmented.spec.ts
NzSegmented with FormControl first change doesnt work
https://stackblitz.com/edit/duxusgu5?file=src%2Fapp%2Fapp.component.ts
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/9031
Segmented item is selected when the first change with FormControl
> fix(module:segmented): fix error with the FormControl first change

- components/input-number/input-number.component.spec.ts
- components/input-number/input-number.component.ts
input value like `/[.。]$/` is considered as not completed, resulting in `3.0` being considered as completed number and being format to 3.
Issue Number: close #9049
1. typing 0
| typing | display (before) | display (now) |
| - | - | -|
| 3.**0** | 3.0 | 3 |
| 3.1**0** | 3.10 | 3.1 |
| 3.0**0** | 3.00 | 3 |
2. backspace the last character
| backspace | display (before) | display (now) |
| - | - | -|
| 3.0~1~ | 3.0 | 3 |
| 3.10~1~ | 3.10 | 3.1 |
| 3.00~1~ | 3.00 | 3 |
> fix(module:input-number): consider input value ends with 0 as incomplete

- components/page-header/page-header.component.ts
paheHeader use observed getter insteadr observers which is not compatible with RxJs 6 still suppoprt by Angular core 
pagheHeader usethe oberservers property
> refactor(module:pageheader): insure compatibility RxJs 6

- components/tabs/demo/link-router.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
```
[x] Bugfix
[x] Application (the showcase website)
```
Tabs with Router always select the first tab after a refresh 
Issue Number: #4773
Tabs with Router will select the tab match the route after a refresh
```
[ ] Yes
[x] No
```
I have added an `ADD` button to the demo of link router tab which will add a new tab after click; you can try refresh demo page with query params `tab=1` (the full path should be `/components/tabs/en?tab=1`), and click the `ADD` button on link router demo, the active tab should switch to the newly added tab with title `NewTab1`
> fix(module:tabs): update active router tab after tabs changed

- components/select/option-container.component.ts
- components/select/select-arrow.component.ts
- components/select/select.component.ts
- components/select/select.spec.ts
Issue Number: close #9055 
when change ngModel value of the select component, the disabled status of options will match expectation
> fix(module:select): bugfix for changing ngModel value of mutilple select with nzMaxMultipleCount

- components/tree-select/style/patch.less
- components/tree-select/tree-select.spec.ts
Issue Number: close #9044 
support x-scroll when item title is too long
> fix(module:tree-select): enable overflow-x for virtual scroll

- components/core/util/convert.ts
- components/select/select-arrow.component.ts
- components/select/select.component.ts
- components/select/select.spec.ts
Issue Number: fix #9057
`default` 模式下（非多选模式下），设置 `nzMaxMultipleCount` 将不生效
> fix(module:select): disable `nzMaxMultipleCount` in default mode

- scripts/site/_site/doc/app/components-overview/components-overview.component.less
Consistent with the default theme, no borders
> docs: fix input borderless style for website in non-dafult theme

- components/select/select-top-control.component.ts
- components/select/select.component.ts
- components/select/select.spec.ts
Issue Number: fix #9078 
多选模式下，设置了 `nzMaxMultipleCount` 以及 `nzTokenSeparators` 时，粘贴的选项受到最大数量的限制
> fix(module:select): limit number of pasted item to nzMaxMultipleCount

- components/checkbox/checkbox-group.component.ts
> fix(module:checkbox): fix type of options

- components/tabs/demo/extra.md
- components/tabs/demo/extra.ts
- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/public-api.ts
- components/tabs/tab-bar-extra-content.directive.ts
- components/tabs/tab-nav-bar.component.ts
- components/tabs/tabs.module.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
Only extra content at the end is supported.
```html
<nz-tabset [(nzSelectedIndex)]="selectedIndex">
<button *nzTabBarExtraContent="'start'">Start Extra Action</button>
<button *nzTabBarExtraContent="'end'">End Extra Action</button>
<nz-tab nzTitle="Tab 0">Content of Tab Pane 0</nz-tab>
<nz-tab nzTitle="Tab 1">Content of Tab Pane 1</nz-tab>
<nz-tab nzTitle="Tab 2">Content of Tab Pane 2</nz-tab>
</nz-tabset>
```
Supports extra content at the start and end.
> feat(module:tabs): support for start and end extra content

- components/tabs/tab.component.ts
- components/tabs/tabset.component.ts
> fix(module:tabs): nzLinkRouter not work for the first time

- components/transfer/transfer.component.ts
- components/transfer/transfer.spec.ts
- [ x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Feature
It is not possible to select multiple row by using keyboard key SHIFT
The new behavior allow to select multiple row by using the keyboard key SHIFT
- [ x] No
ANT DESIGN support this feature in their React component: https://ant.design/components/transfer
> feat(module:transfer): support multiple row selection with Shift key

- components/i18n/languages/es_ES.ts
Add spanish translations for quarter datepicker option, checklist component, cron and qr
> fix(i18n): update es_ES language

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
Issue Number: close #7783 
when the `nzFormat` changed, the input value will rerender.
> fix(module:date-picker): update input value when nzFormat changed

- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
> fix(module:tabs): `nzLinkRouter` not work for the first time load

- components/modal/modal-ref.ts
Angular has a local compilation mode, intended for use with the TypeScript compiler option `isolatedModules`, which disallows importing `const enum`. In such cases, we replace it with a `const` object.
> refactor(module:modal): replace `const enum`

- components/pagination/pagination.component.ts
The new validatePageIndex funciton "Math.min(Math.max(value, 1), lastIndex)" will return 0 when lastIndex is 0. This will result in the pageIndexChange being triggered incorrectly when nzTotal changes from 0 to a value greater than 0. So, back to the old version
> revert(module:pagination): rollback validatePageIndex to old version

- components/icon/icon.directive.ts
> fix(module:icon): debounce icon rendering on animation frame

- components/alert/alert.component.ts
- components/button/button.component.ts
- components/card/card.component.ts
- components/cascader/cascader.component.ts
- components/code-editor/code-editor.service.ts
- components/collapse/collapse-panel.component.ts
- components/collapse/collapse.component.ts
- components/core/config/config.service.ts
- components/empty/embed-empty.component.ts
- components/experimental/image/image.component.ts
- components/icon/icon.service.ts
- components/message/base.ts
- components/message/message-container.component.ts
- components/modal/modal-container.directive.ts
- components/notification/notification-container.component.ts
- components/progress/progress.component.ts
- components/rate/rate.component.ts
- components/select/select.component.ts
- components/spin/spin.component.ts
- components/table/src/table/table.component.ts
- components/tree-select/tree-select.component.ts
In this commit, we introduce the `onConfigChangeEventForComponent` utility to reduce repetitive subscription logic across components that depend on configuration changes from `NzConfigService`.
> refactor: reduce config service boilerplate

- components/cascader/cascader.component.ts
- components/select/select-item.component.ts
- components/select/select-top-control.component.ts
- components/tree-select/tree-select.component.ts
Issue Number: close #6477 
由于 tree-node-title 组件支持在 innerHTML 中渲染 node.title，而 tree-select 对已选择项的展示仅支持原始 string，此 PR 支持对已选择项在 innerHTML 中渲染 node.title
> feat(module:tree-select): render title of selected node in innerHTML

- components/popconfirm/popconfirm.spec.ts
- components/popconfirm/popconfirm.ts
the close button for the pop confirm component does not support nzDanger
the close button for the pop confirm component now support nzDanger
> feat(module:popconfirm): add nzDanger support to cancel button

- components/empty/embed-empty.component.ts
> fix(module:select): shaking when closing dropdown if use a TemplateRef as notFoundContent (#8931)

- components/dropdown/demo/arrow.md
- components/dropdown/demo/arrow.ts
- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
- components/dropdown/dropdown-menu.component.ts
- components/dropdown/dropdown.directive.spec.ts
- components/dropdown/dropdown.directive.ts
Drowpdown component miss the displaying of an arrow on the contend dropdown menu
Dropdown component displayed an arrow on the content dropdown menu as the andt-design do: 
https://ant.design/components/dropdown#dropdown-demo-arrow-center
> feat(module:dropdown): display arrow for content dropdown

- components/segmented/segmented-item.component.ts
- components/segmented/segmented.spec.ts
> fix(module:segmented): correctly render with-icon & icon-only

- components/core/config/config.service.ts
- components/core/config/config.spec.ts
`@WithConfig` have been widely used to decorate on `@Input` properties, but it is not compatible with the `input` properties.
In this PR, we introduce a new `withConfigFactory` function, which can be used to generate a `withConfig` function, and its logic is same with `@WithConfig`.
Firstly you should create a `withConfig` function with the factory and specific a `_nzModuleName`.
Then, add `input` property (or transform from the previous `@Input` property).
The last step is to declare a inner (**private** or **protected**) state with the `withConfig` function.
```ts
const withConfig = withConfigFactory('button');
class ExampleComponent {
readonly nzSize = …
```
> feat(module:core): support `withConfigFactory` for `input` properties

- components/carousel/carousel.component.ts
- components/carousel/carousel.spec.ts
- components/carousel/demo/arrow.md
- components/carousel/demo/arrow.ts
- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- components/carousel/style/index.less
- components/carousel/style/rtl.less
Carousel component now support nzArrows input which let the user to display arrow for swipping
Related: #8826
> feat(module:carousel): support nzArrows

- components/i18n/nz-i18n.service.spec.ts
- components/i18n/nz-i18n.token.ts
The previous `provideNzI18n` API only supported passing a static locale object, which was not friendly for multilingual projects, which need to determine the locale dynamically, such as based on `LOCALE_ID`. This limitation made it difficult to implement flexible i18n strategies and dynamic language switching.
The developers have to fall back to the original Angular provider syntax:
```ts
// app.config.ts
// you cannot do tihs
provideNzIcon(inject(LOCALE_ID) === 'en' ? en_US : zh_CN);
// fallback to
{
provide: NZ_I18N,
useFactory: () => {
const localeId = inject(LOCALE_ID);
switch (localeId) {
case 'en':
return en_US;
case 'zh':
return zh_CN;
default:
return en_US;
} …
```
> feat(module:i18n): enhance provideNzI18n to support factory function
