- src/components/pagination/nz-pagination.component.ts
> fix(pagination): quick jumper not highlighted

- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README-zh_CN.md
- README.md
add CONTRIBUTING.md, docs/*, .github/PULL_REQUEST_TEMPLATE.md
> docs(infrastructure): add markdown docs for contributing and PR

- src/showcase/nz-demo-carousel/nz-demo-carousel.html
```
[] Bugfix
[ ] Feature
```
Issue Number:  #63 
```
[ ] Yes
[x] No
```
> docs(carousel): fix the property name of the nzAutoPlay

- src/components/dropdown/nz-dropdown-button.component.ts
- src/components/dropdown/nz-dropdown.component.ts
- src/components/menu/nz-submenu.component.ts
- src/components/modal/nz-modal-subject.service.ts
- src/components/slider/nz-slider.component.ts
- src/showcase/nz-demo-form/nz-demo-form-validate-dynamic.component.ts
- src/showcase/nz-demo-select/nz-demo-select-multiple-change.component.ts
- src/showcase/nz-demo-select/nz-demo-select-search-change.component.ts
- src/showcase/nz-demo-table/randomUser.service.ts
`import {} from 'rxjs/Rx'` will include the entire RxJS library.
Fixes #50 .
Relates to #18 .
> perf(all): improve rxjs imports

- src/showcase/nz-demo-input/nz-demo-input.html
relate #73
pr https://github.com/NG-ZORRO/ng-zorro-antd/pull/80
[ ] Bugfix
[ ] Feature
```
[ ] Yes
[ ] No
```
> docs(module:input):add nzBlur & nzFocus property to the API table

- src/showcase/nz-demo-message/nz-demo-message.html
The most component pages used the `Boolean`  and the Message component use the `bool`.
So make them uniform.
> docs(message): unify API type bool to Boolean

- src/components/pagination/nz-pagination.component.spec.ts
- src/components/pagination/nz-pagination.component.ts
close #17
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:pagination): remove active class when reach first and last page index

- src/components/steps/nz-step.component.ts
close #83
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:steps): fix steps width bug in tab component

- .travis.yml
- package.json
- src/showcase/nz-intro-changelog/README.md
- src/showcase/nz-intro-index/README.md
pre release
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:release
```
```
[ ] Yes
[ ] No
```
> release(0.5.0-rc.1): release 0.5.0-rc.1

- .travis.yml
- package.json
- src/showcase/nz-intro-changelog/README.md
- src/showcase/nz-intro-index/README.md
Reverts NG-ZORRO/ng-zorro-antd#95
> Revert "release(0.5.0-rc.1): release 0.5.0-rc.1"

- .travis.yml
- package.json
- src/showcase/nz-intro-changelog/README.md
- src/showcase/nz-intro-index/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.5.0-rc.1): release 0.5.0-rc.1 pre release

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.5.0-rc.2): release(0.5.0-rc.2)

- src/showcase/app.component.ts
- src/showcase/share/nz-codebox/nz-codebox.component.ts
- src/showcase/share/nz-codebox/nz-codebox.less
close #26
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(showcase): auto scroll to top when router change & sync code icon with antd

- src/components/input/nz-input.component.ts
close #65 close #117
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:input): fix input touched property

- src/components/pagination/nz-pagination.component.spec.ts
- src/components/pagination/nz-pagination.component.ts
- src/components/table/nz-table.component.ts
close #107
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:pagination) fix pagination double binding

- src/components/select/nz-select.component.ts
close #128
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select reset bug in form

- src/components/affix/nz-affix.component.ts
- src/components/anchor/nz-anchor-link.component.ts
- src/components/anchor/nz-anchor.component.ts
- src/components/back-top/nz-back-top.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:affix,anchor,back-top): fix and improve rxjs usage

- src/components/input/nz-input.component.ts
- src/components/input/nz-input.directive.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:input): fix input disabled style bug

- src/components/carousel/nz-carousel.component.ts
close #161
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:carousel): fix carousel auto play bug

- package.json
close #191
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build(packaging:cdk): specified @angular/cdk version

- src/showcase/nz-demo-form/nz-demo-form-dynamic.component.ts
close #163
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #163 
Fix the bug described in #163 
```
[x] Yes
[ ] No
```
```js
{
"id":1,
"controlInstance":"passenger1"
}
```
> docs(form): fix an incorrect effect in nz-demo-form-dynamic

- src/showcase/nz-demo-modal/nz-demo-modal.html
relate pr #125
```
[ ] Yes
[ ] No
```
> docs(module:modal): add open & close & setConfirmLoading property

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(release:0.5.0-rc.4): pre release 0.5.0-rc.4

- src/components/datepicker/nz-datepicker.component.ts
- src/components/select/nz-select.component.ts
- src/components/time-picker/nz-timepicker.component.ts
```
[x] Bugfix
[ ] Feature
```
#190 
Close dropdown modal when change to disable status
```
[ ] Yes
[x] No
```
> fix(module:select, datepicker, timepicker): close dropdown when change to disable status

- src/components/input-number/nz-input-number.component.spec.ts
- src/components/input-number/nz-input-number.component.ts
close #42 close #203
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:inputnumber): validate inputnumber value & rewrite strategy

- src/components/input-number/nz-input-number.component.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: test fix
```
```
[ ] Yes
[x] No
```
> test(module:inputnumber): fix test case in input number

- src/components/input/nz-input.component.ts
- src/components/input/nz-input.directive.component.ts
- src/showcase/nz-demo-input/nz-demo-input.html
Close #231 
```
[ ] Bugfix
[x] Feature
```
Issue Number:  #231 
```
[ ] Yes
[x] No
```
> feat(module:input): support nzReadonly property

- src/components/dropdown/nz-dropdown-button.component.ts
- src/components/dropdown/nz-dropdown.component.ts
```
[ x ] Bugfix
[ ] Feature
```
```
- [ x ] No
```
resolve https://github.com/NG-ZORRO/ng-zorro-antd/issues/234
> fix(module:dropdown): should always debouce before visible change

- src/components/carousel/nz-carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:carousel): carousel slide height depend on inner content

- src/components/grid/nz-col.component.ts
- src/components/grid/nz-grid.component.spec.ts
- src/showcase/nz-demo-grid/nz-demo-grid-responsive-more.component.ts
- src/showcase/nz-demo-grid/nz-demo-grid.component.ts
- src/showcase/nz-demo-grid/nz-demo-grid.html
- src/showcase/nz-demo-grid/nz-demo-grid.module.ts
close #101
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:grid): support embedded col option

- src/components/checkbox/nz-checkbox.component.ts
- src/components/datepicker/nz-datepicker.component.ts
- src/components/input-number/nz-input-number.component.ts
- src/components/radio/nz-radio.component.ts
- src/components/select/nz-select.component.ts
- src/components/time-picker/nz-timepicker.component.ts
```
[x] Bugfix
[ ] Feature
```
#228 
Fix these module:
- select
- datepicker
- timepicker
- radio
- checkbox
- input-number
```
[ ] Yes
[x] No
```
> fix(module:select, datepicker, timepicker, radio, checkbox, input-number) fix touched state

- src/showcase/nz-demo-select/nz-demo-select.html
Close #278 
```
[ ] Bugfix
[ ] Feature
```
Issue Number:  #278 
```
[ ] Yes
[x] No
```
> docs(select): add nzShowSearch property

- src/components/pagination/nz-pagination.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #280 
```
[ ] Yes
[X] No
```
> fix(module:pagination): prevent repeated emit events

- src/components/pagination/nz-pagination.component.ts
- src/components/pagination/style/patch.less
```
[X] Bugfix
[ ] Feature
```
Issue Number: #267
```
[ ] Yes
[X] No
```
> fix(module:pagination): prevent selection after double click

- src/components/input/nz-input.component.ts
- src/components/input/nz-input.directive.component.ts
```
[x] Bugfix
[ ] Feature
```
#282 
```
[ ] Yes
[ ] No
```
> fix(module:input): fix type error

- src/components/datepicker/nz-datepicker.component.ts
close #300
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:datepicker): end decade cell text

- src/showcase/nz-demo-badge/nz-demo-badge-dot.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(module:badge): nz-demo-badge-dot parameter error

- src/components/layout/nz-sider.component.ts
close #292
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:layout): fix slider breakpoint in mobile device

- index.showcase.ts
- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release v0.5.1

- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(release:0.5.1): release 0.5.1

- README-zh_CN.md
- README.md
- src/showcase/nz-demo-breadcrumb/nz-demo-breadcrumb.html
- src/showcase/nz-demo-form/nz-demo-form.html
- src/showcase/nz-demo-table/nz-demo-table.html
```
[ ] Bugfix
[ ] Feature
```
angular.cn的文档更新到了 5.0.0 的版本，目前 zorro 文档中的许多链接都没有相应的更新。
目前主要有 3 种相关错误：
1. 指向一个“PAGE NOT FOUND”的提示页，有 2 处这种错误，例如：`nz-demo-form.html`中的“当使用 [响应式表单(Reactive Form)](https://angular.cn/docs/ts/latest/cookbook/form-validation.html#!#reactive) 时” 和 “form表单组件的核心基于Angular的form表单规则，建议先了解[相关内容](https://angular.cn/docs/ts/latest/guide/forms.html)”
2. 指向新的5.0.0版本的angular.cn的文档，有 6 …
> docs(showcase): correct the url to angular docs

- src/components/anchor/nz-anchor.component.ts
issue: #322
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:anchor) remove history.pushState

- .github/ISSUE_TEMPLATE.md
```
[ ] Bugfix
[ ] Feature
```
There is a link for plunker seed in issue template.
```
[ ] Yes
[x] No
```
> docs(*): add plunker seed to issue template

- src/components/table/nz-table.component.ts
- src/components/table/nz-th.directive.ts
close #302
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix nzWidth with ngIf

- src/components/select/nz-option.component.ts
- src/components/select/nz-select.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #326
```
[ ] Yes
[X] No
```
>  fix(module:select): error caused by value of sync

- src/components/form/style/patch.less
close #306
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:select): fix select style in inline form

- .github/ISSUE_TEMPLATE.md
- package.json
- src/showcase/nz-demo-table/nz-demo-table.html
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.5.2): release 0.5.2

- src/components/table/nz-table.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: [#372](https://github.com/NG-ZORRO/ng-zorro-antd/issues/372)
I wrote a bug...
```
[ ] Yes
[x] No
```
> fix(module:table): fix nzIsPageIndexReset for wrong display (#372)

- src/showcase/nz-demo-input/nz-demo-input.html
```
[ ] Bugfix
[ ] Feature
```
add "nzPlaceHolder" in nz-input
```
[ ] Yes
[X] No
```
r? @vthinkxie
> docs(API): add "nzPlaceHolder" in nz-input

- src/components/collapse/nz-collapse.component.ts
- src/showcase/nz-demo-collapse/nz-demo-collapse.html
Close #382 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #382 
```
[ ] Yes
[x] No
```
```typescript
import {Component, OnInit} from '@angular/core';
@Component({
selector: 'nz-demo-collapse-basic',
template: `
<nz-collapseset>
<nz-collapse *ngFor="let panel of panels" [nzActive]="panel.active"
[nzDisabled]="panel.disabled">
<p collapse-title>{{panel.name}}</p>
<p>{{panel.name}}内容</p>
<div>papapap</div> …
```
> feat(module:collapse): support custom header

- src/showcase/style/common.less
related #187
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:demo): fix demo site performance

- src/components/select/nz-select.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #352 
```
[ ] Yes
[X] No
```
>  feat(module:select): support focus navigation & open by enter/down arrow

- src/components/datepicker/nz-datepicker.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker-formatter.component.ts
- src/showcase/nz-demo-datepicker/nz-demo-datepicker.html
```
[ ] Bugfix
[X] Feature
```
Issue Number: #351 
```
[ ] Yes
[X] No
```
> feat(module:datepicker): support month picker

- src/components/datepicker/nz-datepicker.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #419 
```
[ ] Yes
[X] No
```
> fix(module:datepicker): data binding not work when mode is month

- src/components/modal/nz-confirm.component.ts
- src/components/modal/nz-modal.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #412 
```
[ ] Yes
[X] No
```
> fix(module:modal): restore body overflow before destroyed the component

- src/showcase/nz-demo-dropdown/nz-demo-dropdown.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:dropdown): fix nzClickHide default value

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: RELEASE
```
```
[ ] Yes
[x] No
```
> release(0.5.4): release 0.5.4

- src/components/dropdown/nz-dropdown.component.ts
close #269
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:dropdown): fix unsubscribe undefined bug

- src/components/calendar/nz-calendar.component.ts
- src/showcase/nz-demo-calendar/nz-demo-calendar.html
close #461
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:calendar): add year number to month template

- src/components/dropdown/nz-dropdown-button.component.ts
- src/components/dropdown/nz-dropdown.component.ts
close #390
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:dropdown): fix dropdown trigger events

- src/components/steps/style/patch.less
```
[ ] Bugfix
[X] Feature
```
Issue Number: #420 
```
[ ] Yes
[X] No
```
> feat(module:steps): support [nzProgressDot] property in vertical mode

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.5.5): release 0.5.5

- src/components/dropdown/nz-dropdown-button.component.ts
- src/components/dropdown/nz-dropdown.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release fix
```
```
[ ] Yes
[x] No
```
> release(0.5.5): fix release 0.5.5

- package.json
- src/components/calendar/nz-calendar.component.ts
- src/components/dropdown/nz-dropdown-button.component.ts
- src/components/dropdown/nz-dropdown.component.ts
- src/components/steps/style/patch.less
- src/showcase/nz-demo-calendar/nz-demo-calendar.html
- src/showcase/nz-demo-input/nz-demo-input.html
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> merge(): merge master into 0.5.x

- package.json
- src/showcase/nz-intro-changelog/README.md
- src/showcase/nz-intro-index/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.0): release 0.6.0

- package.json
close #494
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.0-rc.2): put forward misoperating measures of publishing

- src/components/affix/nz-affix.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #477 
```
[ ] Yes
[x] No
```
> fix(module:affix): fix FPS drops

- src/components/pagination/nz-pagination.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #482
```
[ ] Yes
[X] No
```
> fix(module:pagination): wrong event by changing the [nzPageSize]

- src/components/affix/nz-affix.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:affix): remove unpass test

- src/components/core/polyfill/request-animation.ts
- src/components/core/scroll/nz-scroll.service.ts
- src/components/tabs/nz-tabs-ink-bar.directive.ts
- src/components/time-picker/nz-timepicker-inner.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(polyfill): polyfill all request animation

- src/components/alert/nz-alert.component.ts
- src/components/button/nz-button-group.component.ts
- src/components/checkbox/nz-checkbox.component.ts
- src/components/core/polyfill/request-animation.ts
- src/components/core/scroll/nz-scroll.service.ts
- src/components/tabs/nz-tabs-ink-bar.directive.ts
- src/components/time-picker/nz-timepicker-inner.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(classMap): improve classMap performance

- package.json
- src/showcase/nz-demo-locale/README.md
- src/showcase/nz-intro-changelog/README.md
- src/showcase/nz-intro-i18n/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.0-rc.3): release 0.6.0-rc.3

- src/components/popover/nz-popover.component.ts
- src/components/steps/nz-step.component.ts
- src/showcase/nz-demo-steps/index.html
- src/showcase/nz-demo-steps/nz-demo-steps-basic.component.ts
- src/showcase/nz-demo-steps/nz-demo-steps.module.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: #555 #523
```
[ ] Yes
[x] No
```
> fix(module:popover,steps): fix popover always show title placeholder & steps nzDescription property support TemplateRef

- src/components/time-picker/nz-timepicker-inner.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #286
```
[ ] Yes
[X] No
```
> feat(module:timepicker): support dynamic binding the [nzDisabledHours]  property 

- src/components/select/nz-select.component.ts
close #560
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix multiple select width

- src/components/menu/nz-submenu.component.ts
close #454
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:menu): do not remove submenu when click title

- src/showcase/app.component.html
- src/showcase/app.component.ts
- src/showcase/nz-intro-index/README.md
- src/showcase/style/header.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(showcase): add version list to header

- src/components/transfer/nz-transfer-list.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #599 
```
[ ] Yes
[x] No
```
> fix(module:transfer): fix select all items in search

- src/components/select/nz-select.component.ts
close #590
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:select): fix duplicated option bug

- src/components/datepicker/nz-datepicker.component.ts
- src/components/util/nz-date.pipe.ts
close #604
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:datepicker): fix disabled today button

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.1): release 0.6.1

- src/components/slider/nz-slider-marks.component.ts
- src/components/slider/nz-slider-step.component.ts
- src/components/slider/nz-slider.component.ts
- src/showcase/nz-demo-slider/nz-demo-slider-mark.component.ts
close #624
```
[ ] Bugfix
[x] Feature
```
Issue Number: #624 
```
[ ] Yes
[x] No
```
> feat(module:slider): support dynamic update nzMarks from outside

- package.json
- src/showcase/app.component.ts
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 0.6.2
```
```
[ ] Yes
[x] No
```
> release(0.6.2): release 0.6.2

- src/showcase/nz-demo-avatar/nz-demo-avatar.html
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #619 
```
[ ] Yes
[x] No
```
> docs(module:avatar): remove [When To Use] part.

- src/components/affix/nz-affix.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #671 
```
[ ] Yes
[x] No
```
> fix(module:affix): position offset when has deferred render componets.

- src/components/select/nz-select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #674 
```
[ ] Yes
[x] No
```
> fix(module:select): fix choose disabled item via direction key control

- src/components/select/nz-select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: CI is down due to merge conflict.
Fix the CI.
```
[ ] Yes
[x] No
```
> fix(module:select): usage public property in accessing other components

- src/components/locale/locales/tr-TR.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(i18n:turkish): create tr-TR.ts

- src/components/radio/nz-radio-group.component.ts
- src/components/radio/nz-radio.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #668 
```
[ ] Yes
[X] No
```
> fix(module:radio): value can not be dynamically update

- src/components/locale/locales/index.ts
- src/components/locale/locales/zh-TW.ts
- src/showcase/nz-demo-locale/nz-demo-locale-all.component.ts
- src/showcase/nz-intro-i18n/README.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(i18n:zh-tw): support zh-TW

- src/components/carousel/nz-carousel.component.ts
- src/showcase/nz-demo-carousel/nz-demo-carousel.html
```
[ ] Bugfix
[X] Feature
```
Issue Number: #652 
Added the following API & methods
| 参数 | 说明 | 类型 | 默认值 |
| --- | -- | -- | -- |
| nzAutoPlaySpeed | 自动切换速度, 单位毫秒 | Number | 3000 |
| nzPauseOnHover | 鼠标悬停暂停 | Boolean | true |
| nzAfterChange | 切换面板后的回调, 参数为当前索引 | Function(number) | 无 |
| nzBeforeChange | 切换面板前的回调, 参数为当前的索引与被切换到的索引 | Function({ form: number; to: number}) | 无 |
| 方法名 | 参数 | 说明 | 返回值值 |
| …
> feat(module:carousel): add enhancement API and methods

- package.json
- src/showcase/nz-intro-changelog/README.md
- src/showcase/nz-intro-getting-started/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.6.3): release 0.6.3

- src/components/form/nz-form-control.component.ts
- src/showcase/nz-demo-form/nz-demo-form-dynamic.component.ts
- src/showcase/nz-demo-form/nz-demo-form-horizontal.component.ts
- src/showcase/nz-demo-form/nz-demo-form-inline.component.ts
- src/showcase/nz-demo-form/nz-demo-form-layout.component.ts
- src/showcase/nz-demo-form/nz-demo-form-login.component.ts
- src/showcase/nz-demo-form/nz-demo-form-validate-dynamic.component.ts
- src/showcase/nz-demo-form/nz-demo-form.html
close #693 close #692
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:form): support default nzValidateStatus & support more error status

- src/components/select/nz-select.component.ts
- src/showcase/nz-demo-select/nz-demo-select-basic.component.ts
close #413
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:select): support placeholder for basic select

- src/components/grid/nz-col.component.ts
- src/components/grid/nz-grid.component.spec.ts
- src/components/util/check.ts
close #702
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:grid): support zero input in grid

- src/showcase/nz-demo-table/nz-demo-table-ajax.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(showcase): correct the table header

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.6.4): release 0.6.4

- package.json
- src/components/calendar/nz-calendar.component.ts
- src/components/locale/nz-locale.service.ts
- src/components/modal/nz-modal-subject.service.ts
- src/showcase/nz-intro-changelog/README.md
close #720 close #719
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.5): hot fix modal type & i18n error

- src/components/rate/nz-rate.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: fixes #725
```
[ ] Yes
[x] No
```
> fix(module:rate): ensure value to be number

- src/components/slider/nz-slider.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #727 
```
[ ] Yes
[x] No
```
> fix(module:slider): rectify return value

- src/components/input-number/nz-input-number.component.ts
close #730 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:input-number): use boundary value instead of previous value

- src/components/badge/nz-badge.component.ts
- src/components/slider/nz-slider.component.ts
- src/components/slider/nz-slider.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:slider): fix slider min & max

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: hot fix release
```
```
[ ] Yes
[x] No
```
> release(0.6.6): hotfix release 0.6.6

- src/components/datepicker/nz-datepicker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:datepicker): check user input with nzDisabledDate

- src/components/datepicker/nz-datepicker.component.ts
- src/components/input-number/nz-input-number.component.ts
- src/components/slider/nz-slider.component.ts
- src/showcase/nz-demo-input-number/nz-demo-input-number-formatter.component.ts
- src/showcase/nz-demo-input-number/nz-demo-input-number.component.ts
- src/showcase/nz-demo-input-number/nz-demo-input-number.html
- src/showcase/nz-demo-input-number/nz-demo-input-number.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:slider): fix set value in slider

- src/components/select/nz-select.component.ts
```
[ x ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x ] No
```
> fix(module:select): update this._value

- src/components/calendar/nz-calendar.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #736 
use short format
```
[ ] Yes
[X] No
```
> feat(module:calendar): use months short format

- src/components/table/nz-table-sort.component.ts
close #771
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix the missing of init table sort class

- src/components/affix/nz-affix.component.ts
- src/components/core/scroll/nz-scroll.service.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #647
```
[ ] Yes
[x] No
```
> refactor(module:affix): using pure setter

- src/components/modal/nz-modal-subject.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:modal): fix modal type error

- src/components/popconfirm/nz-popconfirm.component.ts
close #785
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:popconfirm): fix backdrop of popconfirm

- rollup.config.js
- src/components/dropdown/nz-dropdown.component.ts
close #760
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> enhance(module:dropdown): reduce debounce time of dropdown

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.8): release 0.6.8

- src/components/radio/nz-radio.component.ts
- src/showcase/nz-demo-radio/nz-demo-radio-group-disabled.component.ts
- src/showcase/nz-demo-radio/nz-demo-radio-group.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #770 
```
[ ] Yes
[x] No
```
> feat(module:radio): use nz-radio components alone

- src/showcase/nz-demo-locale/nz-demo-locale-all.component.ts
- src/showcase/nz-demo-message/nz-demo-message-loading.component.ts
- src/showcase/nz-demo-spin/nz-demo-spin-nested.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> docs(showcase): optimization docs

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release
```
```
[ ] Yes
[ ] No
```
> release(0.6.9): release 0.6.9

- src/components/calendar/nz-calendar.component.ts
Reverts NG-ZORRO/ng-zorro-antd#768
> Revert "fix(module:calendar): fix month/year view switched"

- src/components/calendar/nz-calendar.component.ts
- src/components/locale/locales/index.ts
- src/components/locale/locales/ru-RU.ts
- src/showcase/nz-demo-locale/nz-demo-locale-all.component.ts
- src/showcase/nz-intro-i18n/README.md
```
[ ] Bugfix
[ x ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:locale): support russian locale

- src/components/affix/nz-affix.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:affix): fix affix nzOffsetTop bug

- src/components/radio/nz-radio-button.component.ts
- src/components/radio/nz-radio.component.ts
close #854
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:radio): fix radio button click bug

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.10): release 0.6.10

- src/components/datepicker/nz-datepicker.component.ts
- src/components/time-picker/nz-timepicker.component.ts
```
[x] Bugfix
[ ] Feature
```
The user can modify the contents of the datepicker & timepicker input box.
Set readonly for the input box.
```
[ ] Yes
[x] No
```
> fix(module: datepicker & timepicker):Set readonly for the input box

- src/components/progress/nz-progress.component.ts
- src/showcase/nz-demo-progress/nz-demo-progress-basic.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #903 
```
[ ] Yes
[x] No
```
> fix(module:progress): fix 100% when specify invalid value

- src/components/back-top/nz-back-top.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
no tests for back-top module.
add missing tests for back-top module to improve the reliability of the project.
```
[ ] Yes
[x] No
```
> test(module:back-top): add back-top tests

- src/components/collapse/nz-collapse.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #862 
```
[ ] Yes
[x] No
```
> feat(module:collapse) update collapse class

- src/components/locale/locales/en-US.ts
- src/components/locale/locales/ru-RU.ts
- src/components/locale/locales/tr-TR.ts
- src/components/locale/locales/zh-CN.ts
- src/components/locale/locales/zh-TW.ts
- src/components/locale/nz-locale.class.ts
- src/components/ng-zorro-antd.module.ts
- src/components/upload/interface.ts
- src/components/upload/nz-upload-btn.component.ts
- src/components/upload/nz-upload-btn.spec.ts
- src/components/upload/nz-upload-list.component.ts
- src/components/upload/nz-upload.component.ts
- src/components/upload/nz-upload.module.ts
- src/components/upload/nz-upload.spec.ts
- src/components/upload/style/index.less
- src/components/upload/style/patch.less
- src/showcase/nz-demo-upload/nz-demo-upload-avatar.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload-basic.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload-drag.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload-file-list.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload-filter.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload-manually.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload-picture-card.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload-picture-style.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload.component.ts
- src/showcase/nz-demo-upload/nz-demo-upload.html
- src/showcase/nz-demo-upload/nz-demo-upload.module.ts
- src/showcase/nz-demo-upload/nz-demo-upload.routing.module.ts
- src/showcase/router.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:upload): add nz-upload component

- scripts/template/demo-module.template.ts
- scripts/utils/generate-demo.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build(packaging): support entryComponents from demos

- src/components/radio/nz-radio-group.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #902 
```
[ ] Yes
[x] No
```
> fix(module:radio): fix radio group trigger unnecessary ngModelChange

- src/components/input/nz-input.component.ts
- src/showcase/nz-demo-input/nz-demo-input-search.component.ts
- src/showcase/nz-demo-input/nz-demo-input.html
```
[ ] Bugfix
[X] Feature
```
Issue Number: #813
| 参数 | 说明 | 类型 |  默认值 |
| --- | --- | --- | --- |
| nzOnSearch | 回车或点击搜索按钮时的回调 | `EventEmitter<string>` | - |
```
[ ] Yes
[X] No
```
> feat(module:input): add nzOnSearch property

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.11): release 0.6.11

- components/list/nz-list.component.ts
- components/spin/nz-spin.component.ts
- components/spin/nz-spin.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:spin): support dynamic ng-content in spin

- package.json
- src/showcase/share/nz-highlight/nz-highlight.component.ts
- src/showcase/share/nz-markdown/nz-markdown.component.ts
- src/showcase/style/common.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(ci): fix travic ci error

- src/components/upload/nz-upload-btn.component.ts
- src/components/upload/nz-upload.module.ts
- src/components/upload/nz-upload.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #926 
```
[ ] Yes
[x] No
```
> feat(module:upload): using optional HttpClientModule

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.12): hotfix 0.6.12

- README.md
- components/menu/demo/inline-collapsed.ts
- components/menu/nz-menu.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> doc: add progress in readme

- .editorconfig
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- PROGRESS.md
- README-zh_CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc: move back some md file

- src/components/select/nz-select.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #889
```
[ ] Yes
[X] No
```
> fix(module:select): should use label as the title

- src/components/menu/nz-menu.component.ts
close #949
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:menu): fix collapse menu

- src/components/alert/nz-alert.component.ts
close #960
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:alert): fix [alert-description] bug

- src/components/datepicker/nz-rangepicker.component.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #963 #914
automatic reposition
```
[ ] Yes
[X] No
```
> feat(module:datepicker): reposition the position when the window resize

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.13): release 0.6.13

- src/components/input-number/nz-input-number.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #992
```
[ ] Yes
[X] No
```
> fix(module:input-number): properly display zero value

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.14): release 0.6.14

- src/components/datepicker/nz-rangepicker.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1041
```
[ ] Yes
[X] No
```
> fix:(module:datepicker): fix the range-picker the input style

- PROGRESS.md
- components/index.ts
- components/radio/demo/disable.md
- components/radio/demo/radiobutton.md
- components/rate/demo/basic.ts
- components/rate/demo/character.ts
- components/rate/demo/clear.ts
- components/rate/demo/half.ts
- components/rate/demo/text.ts
- components/rate/doc/index.en-US.md
- components/rate/doc/index.zh-CN.md
- components/rate/index.ts
- components/rate/nz-rate.component.ts
- components/rate/nz-rate.spec.ts
- components/rate/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:rate): refactor rate

- PROGRESS.md
- components/index.ts
- components/input-number/nz-input-number.component.ts
- components/rate/nz-rate.component.ts
- components/switch/demo/basic.ts
- components/switch/demo/disabled.ts
- components/switch/demo/loading.ts
- components/switch/demo/size.md
- components/switch/demo/size.ts
- components/switch/demo/text.ts
- components/switch/doc/index.en-US.md
- components/switch/doc/index.zh-CN.md
- components/switch/index.ts
- components/switch/nz-switch.component.ts
- components/switch/nz-switch.spec.ts
- components/switch/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:switch): refactor switch

- PROGRESS.md
- components/badge/demo/basic.md
- components/badge/demo/basic.ts
- components/badge/demo/change.ts
- components/badge/demo/dot.ts
- components/badge/demo/link.ts
- components/badge/demo/no-wrapper.ts
- components/badge/demo/overflow.md
- components/badge/demo/overflow.ts
- components/badge/demo/status.ts
- components/badge/doc/index.en-US.md
- components/badge/doc/index.zh-CN.md
- components/badge/index.ts
- components/badge/nz-badge.component.ts
- components/badge/nz-badge.module.ts
- components/badge/nz-badge.spec.ts
- components/badge/public-api.ts
- components/core/util/check.ts
- components/index.ts
- components/spin/nz-spin.component.ts
- components/switch/nz-switch.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:badge): refactor badge

- .angular-cli.json
- PROGRESS.md
- components/card/demo/basic.ts
- components/card/demo/border-less.ts
- components/card/demo/flexible-content.md
- components/card/demo/flexible-content.ts
- components/card/demo/grid-card.ts
- components/card/demo/in-column.ts
- components/card/demo/inner.ts
- components/card/demo/loading.ts
- components/card/demo/meta.ts
- components/card/demo/simple.ts
- components/card/demo/tabs.ts
- components/card/doc/index.en-US.md
- components/card/doc/index.zh-CN.md
- components/card/index.ts
- components/card/nz-card-loading.component.ts
- components/card/nz-card-meta.component.ts
- components/card/nz-card-tab.component.ts
- components/card/nz-card.component.ts
- components/card/nz-card.module.ts
- components/card/nz-card.spec.ts
- components/card/public-api.ts
- components/index.ts
- docs/contributing.en-US.md
- docs/contributing.zh-CN.md
- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
- docs/recommendation.en-US.md
- docs/recommendation.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:card): refactor card

- package.json
- src/showcase/nz-intro-changelog/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.6.15): release 0.6.15

- components/card/nz-card.spec.ts
- components/carousel/demo/autoplay.md
- components/carousel/demo/autoplay.ts
- components/carousel/demo/basic.md
- components/carousel/demo/basic.ts
- components/carousel/demo/fade.md
- components/carousel/demo/fade.ts
- components/carousel/demo/vertical.md
- components/carousel/demo/vertical.ts
- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- components/carousel/index.ts
- components/carousel/nz-carousel-content.directive.ts
- components/carousel/nz-carousel.component.ts
- components/carousel/nz-carousel.spec.ts
- components/carousel/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:carousel): refactor carousel

- PROGRESS.md
- components/alert/demo/banner.md
- components/alert/demo/basic.ts
- components/alert/demo/closable.ts
- components/alert/demo/close-text.md
- components/alert/demo/close-text.ts
- components/alert/demo/description.ts
- components/alert/demo/icon.ts
- components/alert/demo/style.ts
- components/alert/doc/index.en-US.md
- components/alert/doc/index.zh-CN.md
- components/alert/index.ts
- components/alert/nz-alert.component.ts
- components/alert/nz-alert.spec.ts
- components/alert/public-api.ts
- components/card/nz-card-meta.component.ts
- components/card/nz-card.component.ts
- components/collapse/nz-collapse-panel.component.ts
- components/input/nz-input-group.component.ts
- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
- components/steps/nz-step.component.ts
- components/switch/nz-switch.component.ts
- components/timeline/nz-timeline-item.component.ts
- components/timeline/nz-timeline.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:alert): refactor alert

- components/button/demo/basic.ts
- components/button/demo/button-group.ts
- components/button/demo/disabled.ts
- components/button/demo/ghost.ts
- components/button/demo/icon.ts
- components/button/demo/loading.ts
- components/button/demo/multiple.ts
- components/button/demo/size.ts
- components/button/nz-button.component.ts
- components/button/nz-button.module.ts
- components/core/util/check.ts
- components/test.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:button): refactor button

- components/calendar/nz-calendar-header.component.html
- components/calendar/nz-calendar.component.ts
```
[ ] Bugfix
[ ] Feature
```
Removed unused `(ngModelChange)` binding;
Improved performance when date not changed;
```
[ ] Yes
[x] No
```
> refactor(module:calendar): remove used listener and improve perf

- PROGRESS.md
- components/auto-complete/demo/basic.md
- components/auto-complete/demo/basic.ts
- components/auto-complete/demo/certain-category.md
- components/auto-complete/demo/certain-category.ts
- components/auto-complete/demo/custom.md
- components/auto-complete/demo/custom.ts
- components/auto-complete/demo/non-case-sensitive.md
- components/auto-complete/demo/non-case-sensitive.ts
- components/auto-complete/demo/options.md
- components/auto-complete/demo/options.ts
- components/auto-complete/demo/uncertain-category.md
- components/auto-complete/demo/uncertain-category.ts
- components/auto-complete/doc/index.en-US.md
- components/auto-complete/doc/index.zh-CN.md
- components/auto-complete/index.ts
- components/auto-complete/nz-autocomplete-optgroup.component.ts
- components/auto-complete/nz-autocomplete-option.component.ts
- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.component.ts
- components/auto-complete/nz-autocomplete.module.ts
- components/auto-complete/nz-autocomplete.spec.ts
- components/auto-complete/public-api.ts
- components/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:autocomplete): add autocomplete component

- components/components.less
- components/ng-zorro-antd.module.ts
- components/tree/demo/basic.md
- components/tree/demo/basic.ts
- components/tree/demo/customized-icon.md
- components/tree/demo/customized-icon.ts
- components/tree/demo/draggable.md
- components/tree/demo/draggable.ts
- components/tree/demo/dynamic.md
- components/tree/demo/dynamic.ts
- components/tree/demo/line.md
- components/tree/demo/line.ts
- components/tree/demo/search.md
- components/tree/demo/search.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/index.ts
- components/tree/interface.ts
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree-node.ts
- components/tree/nz-tree.component.spec.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.module.ts
- components/tree/nz-tree.service.ts
- components/tree/public-api.ts
- components/tree/style/index.less
- components/tree/style/mixin.less
- [ √ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ √ ] Tests for the changes have been added (for bug fixes / features)
- [ √ ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ √ ] Feature
```
```
[ √ ] Yes
[ ] No
```
> feat(module:tree): add tree component

- docs/changelog.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- package.json
- release-helper.sh
- site_scripts/_site/src/app/app.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.7.0-beta.1): release 0.7.0-beta.1

- components/core/style/index.less
- components/i18n/public-api.ts
- components/table/nz-table.component.ts
- components/table/nz-table.spec.ts
- components/table/nz-th.component.ts
```
[x] Bugfix
[ ] Feature
```
close #1160 close #1154 
```
[ ] Yes
[ ] No
```
> fix(module:table & i18n): fix table style & export i18n interface

- components/form/demo/coordinated.ts
- components/form/demo/dynamic-form-item.ts
- components/form/demo/dynamic-rule.ts
- components/form/demo/horizontal-login.ts
- components/form/demo/layout.ts
- components/form/demo/normal-login.ts
- components/form/demo/register.ts
- components/form/demo/validate-reactive.ts
- components/form/nz-form-control.component.ts
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.7.0-beta.2): release 0.7.0-beta.2

- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(doc:i18n): fix doc

- components/card/nz-card.component.ts
```
[x] Bugfix
[ ] Feature
```
close #1191 
```
[ ] Yes
[ ] No
```
> fix(module:card): fix card style

- components/core/util/convert.ts
- components/modal/demo/basic.ts
- components/modal/nz-modal.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:modal): provide InputBoolean decorator to offer comfort

- components/cascader/demo/default-value-and-asyn-options.md
- components/cascader/demo/default-value-and-asyn-options.ts
- components/cascader/demo/default-value-and-lazyload.md
- components/cascader/demo/default-value-and-lazyload.ts
- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1210 #399 
```
[ ] Yes
[x] No
```
> refactor(module:cascader):fix bug on asyn nzOptions setting or lazy load

- docs/introduce.zh-CN.md
In the project named [How-To-Ask-Questions-The-Smart-Way](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md), the author wish us add `'This guide does not provide actual support services for this project!'` in where we used his project's url.
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
```
[ ] Yes
[ x ] No
```
> doc: update introduce.zh-CN.md

- components/i18n/nz-i18n.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:i18n): fix i18n error without locale

- components/tag/nz-tag.component.ts
- components/tag/nz-tag.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1176
```
[ ] Yes
[x] No
```
> fix(module:tag): fix default color when empty color values

- components/card/nz-card-meta.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1206
```
[ ] Yes
[x] No
```
> fix(module:card): fix avatar and detail alignment

- components/transfer/nz-transfer-list.component.ts
- components/transfer/nz-transfer.component.ts
- components/transfer/transfer.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #996 
```
[ ] Yes
[x] No
```
> fix(module:transfer): removed change detection

- components/card/demo/flexible-content.ts
- components/card/demo/meta.ts
- components/card/nz-card-meta.component.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1204
```
[x] Yes
[ ] No
```
> refactor(module:card): nz-card-meta use element style

- README-zh_CN.md
- README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
In the project named [How-To-Ask-Questions-The-Smart-Way](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md), the author wishes us to add 'This guide does not provide actual support services for this project!' near by where we have used his project's url.
> doc: add a statement near by a quote

- components/upload/doc/index.en-US.md
- components/upload/doc/index.zh-CN.md
- site_scripts/_site/src/app/app.component.ts
- fix scroll to top when changed router
- support `/divider/zh#api` link scroll to api view
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix upload format

- site_scripts/_site/src/app/app.component.html
> fix: change the homepage url of angular.cn

- components/select/nz-option-container.component.ts
- components/select/nz-option-li.component.ts
- components/select/nz-option-li.spec.ts
- components/select/nz-select-top-control.component.ts
- package.json
close #1229 close #1245
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:select): fix select zero value & scroll bug

- components/core/util/getMentions.ts
- components/mention/mention.spec.ts
```
[ ] Bugfix
[X] Feature
```
没有保留前缀，无法区分类型。
```ts
getMention("... @vthinkxie ... #1142") // ["vthinkxie",  "1142"]
```
保留前缀，能够区分类型。
```ts
getMention("... @vthinkxie ... #1142") // ["@vthinkxie",  "#1142"]
```
```
[ ] Yes
[ ] No
```
> fix(module:mention): getMention method should kepp the mention prefix

- components/menu/nz-menu-item.directive.ts
- components/menu/nz-menu.directive.ts
- components/menu/nz-submenu.component.ts
close #1216
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:menu): fix menu ExpressionChangedAfterItHasBeenCheckedError

- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
close #1227
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc(i18n): add description for angular locale i18n

- README.md
- components/timeline/nz-timeline.component.ts
- docs/changelog.zh-CN.md
- package.json
- site_scripts/_site/src/index.html
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> release(0.7.0-beta.4): release 0.7.0-beta.4

- components/cascader/nz-cascader.component.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1366 
```
[ ] Yes
[x] No
```
> enhancement(module:cascader): fix CascaderOption value type to any

- components/tree/demo/basic.ts
- components/tree/demo/customized-icon.ts
- components/tree/demo/line.ts
- components/tree/demo/method.md
- components/tree/demo/method.ts
- components/tree/demo/search.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.service.ts
- components/tree/nz-tree.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feature(module: tree): provide some quick methods & support nzCheckStrictly

- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.7.0-beta.5): release

- components/auto-complete/nz-autocomplete.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1384
```
[ ] Yes
[x] No
```
> fix(module:autocomplete): fix styles

- LICENSE
- README-zh_CN.md
- README.md
- build.sh
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/week-picker.component.spec.ts
- docs/changelog.zh-CN.md
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(0.7.0): release 0.7.0

- components/layout/nz-sider.component.ts
```
[x] Bugfix
[ ] Feature
```
fix typo in nz-sider component
```
[ ] Yes
[x] No
```
> fix(module:sider): fix typo isSiderTrgger to isSiderTrigger

- components/popconfirm/nz-popconfirm.component.html
- components/popconfirm/nz-popconfirm.component.ts
- components/popconfirm/nz-popconfirm.spec.ts
close #1312
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1312 
```
[ ] Yes
[x] No
```
> fix(module:popconfirm): add nzOkType support

- components/modal/nz-modal.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:modal): show/hide scrollbar more smoothly

- components/auto-complete/demo/certain-category.ts
- components/auto-complete/doc/index.en-US.md
- components/auto-complete/doc/index.zh-CN.md
- components/auto-complete/nz-autocomplete-option.component.ts
- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number:  #1298
```
[ ] Yes
[x] No
```
> feat(module:autocomplete): support bind any types to the nzModule of trigger element

- components/switch/demo/control.md
- components/switch/demo/control.ts
- components/switch/doc/index.en-US.md
- components/switch/doc/index.zh-CN.md
- components/switch/nz-switch.component.ts
- components/switch/nz-switch.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
close #1481
> feat(module:switch): support fully control by user

- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- components/select/doc/index.en-US.md
- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc: fix docs

- components/menu/nz-menu.spec.ts
- components/menu/nz-submenu.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
close #1500 
```
[ ] Yes
[x] No
```
> fix(module:menu): fix menu ngfor bug

- README-zh_CN.md
- README.md
- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
- components/date-picker/doc/index.en-US.md
- docs/changelog.zh-CN.md
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
- package.json
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.7.1): release 0.7.1

- components/table/public-api.ts
Fixes #1532
```
[x] Bugfix
[ ] Feature
```
`NzTableComponent` is NOT exported from `ng-zorro-antd`
Issue Number: #1532 
`NzTableComponent` is exported from `ng-zorro-antd`
```
[ ] Yes
[x] No
```
> fix(module:table) Add export of NzTableComponent

- components/modal/nz-modal.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:modal): miss returned value from nzOnOk or nzOnCancel

- components/core/style/index.less
- components/tree/demo/basic.ts
- components/tree/demo/customized-icon.ts
- components/tree/demo/dir-tree.md
- components/tree/demo/dir-tree.ts
- components/tree/demo/draggable-confirm.ts
- components/tree/demo/draggable.ts
- components/tree/demo/dynamic.md
- components/tree/demo/line.ts
- components/tree/demo/method.md
- components/tree/demo/search.md
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.spec.ts
- components/tree/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x ] No
```
> feat(module: tree): sync ant style & add dir demo

- components/auto-complete/nz-autocomplete-option.component.ts
- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.spec.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1480
```
[ ] Yes
[x] No
```
> feat:(module:auto-complete): support active option will scrollable to visible area

- components/spin/nz-spin.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:spin): fix spin error in antd 3.6.1

- components/popover/nz-popover.component.ts
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:popover): fix popover nzTemplate value

- docs/customize-theme.en-US.md
docs(): Corrected path to less entry file
> docs: corrected path to less entry file

- release-helper.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc: add 0.7.x doc

- site_scripts/_site/src/app/app.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc: change bug report link

- schematics/ng-add/index.ts
- schematics/utils/devkit-utils/ast-utils.ts
- schematics/utils/devkit-utils/change.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(schematic:ng-add): duplicate add bugs

- components/select/nz-select.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:select): move select ovarlay to the last of container

- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: cascader): fix custom render with nzClear

- components/tree/demo/dir-tree.md
- components/tree/demo/dir-tree.ts
- components/tree/demo/method.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.service.ts
- components/tree/nz-tree.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feature(module: tree): add getHalfCheckedNodeList & change dir tree demo

- components/tree-select/nz-tree-select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1681
reposition when open.
```
[ ] Yes
[x] No
```
> fix(module:tree-select): position error when in the modal-box

- components/auto-complete/nz-autocomplete-trigger.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1683
public template properties
```
[ ] Yes
[x] No
```
> fix(module:autocomplete): AOT compiler requires public properties

- components/card/demo/loading.ts
- components/card/nz-card-loading.component.html
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
close #1695
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:card): fix card loading style

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
- site_scripts/replace-scope-prefix.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.1.0): release 1.1.0

- components/radio/nz-radio-group.component.ts
- components/radio/nz-radio.spec.ts
close #1734
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:radio): fix radio disabled bug in group

- components/radio/nz-radio-group.component.ts
- components/radio/nz-radio.component.ts
- components/radio/nz-radio.spec.ts
close #1735
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:radio): fix radio in reactive form

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1740
```
[ ] Yes
[x] No
```
> fix(module:tree-select): fix unable to set null

- components/tree/doc/index.en-US.md
- components/tree/nz-tree.service.ts
- components/tree/nz-tree.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): fix disabled node status & doc

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1772
```
[ ] Yes
[x] No
```
> fix(module:tree-select): width is 0 when trigger element is invisible

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.1.1): release 1.1.1

- components/dropdown/nz-dropdown.spec.ts
```
[ ] Bugfix
[ ] Feature
```
success test in cdk 6.4.0
```
[ ] Yes
[x] No
```
> test(module:dropdown): fix the test

- components/tree-select/demo/basic.ts
- components/tree-select/demo/checkable.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1823
```diff
+   @Input() nzDisplayWith: (node: NzTreeNode) => string = (node: NzTreeNode) => node.title;
```
```
[ ] Yes
[x] No
```
> feta(module:tree-select): support custom display value

- components/carousel/nz-carousel.component.ts
- components/carousel/nz-carousel.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1811 
The contents would be resized when `window` is resizing.
```
[ ] Yes
[x] No
```
> fix(carousel): resize content after window resized

- components/input-number/nz-input-number.component.ts
- components/input-number/nz-input-number.spec.ts
close #1785
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:input-number): fix touched event

- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- components/carousel/nz-carousel.component.html
- components/carousel/nz-carousel.component.ts
- components/carousel/nz-carousel.spec.ts
close #1743 
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:carousel): support dot render template

- components/form/nz-form-control.component.ts
close #1665
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:form): support touched status update

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- site_scripts/_site/src/app/app.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.2.0): release 1.2.0

- components/auto-complete/nz-autocomplete-trigger.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1840
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): reposition when open the first time

- CHANGELOG.md
- site_scripts/_site/src/app/app.component.html
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/index.html
- site_scripts/_site/src/style/docsearch.less
- site_scripts/_site/src/style/header.less
- site_scripts/_site/src/style/index.less
- site_scripts/replace-scope-prefix.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(showcase): add algolia search

- CHANGELOG.md
- README-zh_CN.md
- README.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.3.0): release 1.3.0

- components/radio/demo/solid.md
- components/radio/demo/solid.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add demo
```
Add solid button style demo to `nz-radio-group`.
```
[ ] Yes
[x] No
```
> docs(module:radio): add solid button style demo

- components/avatar/avatar.spec.ts
- components/avatar/nz-avatar.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2004 
NzAvatar tolerates error src. If user correct src, it would try to render an image.
```
[ ] Yes
[x] No
```
> fix(module:avatar): tolerate error src

- components/modal/nz-modal.component.ts
- components/modal/nz-modal.spec.ts
close #1422
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1422
```
[ ] Yes
[x] No
```
> feat(module:modal): smart to determine whether to add padding-right

- components/popconfirm/nz-popconfirm.directive.ts
- components/popconfirm/nz-popconfirm.spec.ts
- components/popover/nz-popover.spec.ts
- components/tooltip/nz-tooltip.directive.ts
- components/tooltip/nz-tooltip.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1967
```
[ ] Yes
[x] No
```
> fix(module:tooltip,popconfirm,popover): not create element when use directive

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: release
```
```
[ ] Yes
[X] No
```
> release(1.4.0): release 1.4.0

- components/tabs/nz-tabs.spec.ts
- components/tabs/style/index.less
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix test
```
Issue Number: #2007
```
[ ] Yes
[x] No
```
> test(module:tabs): fix test error caused by style

- README-zh_CN.md
- README.md
- components/divider/demo/vertical.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add links and fix docs typo

- docs/faq.en-US.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number:  #1993 
```
[ ] Yes
[x] No
```
> docs: add faq's English version

- site_scripts/_site/src/app/app.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix version selector style

- components/button/nz-button.component.ts
- components/button/nz-button.module.ts
- components/core/wave/index.ts
- components/core/wave/nz-wave-renderer.ts
- components/core/wave/nz-wave.directive.ts
- components/core/wave/nz-wave.module.ts
- components/core/wave/nz-wave.spec.ts
- components/core/wave/public-api.ts
- components/ng-zorro-antd.module.ts
- components/switch/nz-switch.component.html
- components/switch/nz-switch.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:core): add wave directive

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.4.1): release 1.4.1

- .editorconfig
- package.json
- publish_scripts/publish.js
close #1925 
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Add publish helper
```
```
[ ] Yes
[x] No
```
> feat(publish): add publish script

- components/alert/nz-alert.component.html
- components/calendar/nz-calendar.component.html
- components/card/nz-card-meta.component.ts
- components/date-picker/lib/popups/inner-popup.component.ts
- components/date-picker/picker.component.ts
- components/list/interface.ts
- components/mention/mention.component.ts
- components/modal/nz-modal.component.html
- components/modal/nz-modal.component.ts
- components/select/nz-option-container.component.ts
- components/select/nz-option.pipe.ts
- components/select/nz-select.component.ts
- components/table/demo/dynamic-settings.ts
- components/table/demo/row-selection-and-operation.ts
- components/table/demo/row-selection-custom.ts
- components/table/demo/row-selection.ts
- components/tree-select/nz-tree-select.component.html
- components/tree/demo/dir-tree.ts
- components/tree/nz-tree.service.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
- site_scripts/_site/src/app/share/nz-copy-icon/nz-copy-icon.directive.ts
- site_scripts/_site/src/tsconfig.app.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: support more strict angularCompilerOptions

- components/input/demo/textarea.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:input): fix textarea demo

- components/calendar/nz-calendar-header.component.html
- components/calendar/nz-calendar-header.component.ts
- components/calendar/nz-calendar-header.spec.ts
close #2091
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:calendar): fix calendar year list

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/nz-drawer.component.html
- components/drawer/nz-drawer.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2119
```
[ ] Yes
[x] No
```
> fix(module:drawer): drawer content cannot scroll

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(test): fix test coverage dependency

- README-zh_CN.md
- README.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test: fix test configure dependency

- components/steps/nz-steps.component.ts
- components/steps/nz-steps.spec.ts
close #2148
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:steps): fix dynamic steps error

- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/table/demo/edit-row.ts
close #1922
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc(module:table&notification): fix doc demo & api error

- components/table/nz-table.component.html
- components/table/nz-table.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: perf
```
```
[ ] Yes
[x] No
```
> perf(module:table): improve table performance

- components/core/overlay/scroll/nz-block-scroll-strategy.ts
- components/core/overlay/scroll/nz-scroll-strategy-options.ts
- components/core/services/nz-measure-scrollbar.service.ts
- components/drawer/demo/service.md
- components/drawer/demo/service.ts
- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/nz-drawer-options.ts
- components/drawer/nz-drawer-ref.ts
- components/drawer/nz-drawer.component.html
- components/drawer/nz-drawer.component.ts
- components/drawer/nz-drawer.module.ts
- components/drawer/nz-drawer.service.ts
- components/drawer/nz-drawer.spec.ts
- components/drawer/public-api.ts
- components/ng-zorro-antd.module.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1937
support service 
```
[ ] Yes
[x] No
```
> feat(module:drawer): support service to create drawer

- package.json
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/jakubpawlowicz/clean-css/issues/1050
```
[ ] Yes
[x] No
```
> build: downgraded clean-css to fix transition minify error

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- site_scripts/_site/src/app/app.component.ts
- site_scripts/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.6.0): release 1.6.0

- components/skeleton/doc/index.en-US.md
- components/skeleton/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ant-design/ant-design/issues/12469
```
[ ] Yes
[x] No
```
> docs(showcase): fix skeleton type

- components/steps/nz-steps.spec.ts
- components/time-picker/nz-time-value-accessor.directive.ts
- tslint.json
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #660
```
[ ] Yes
[x] No
```
> build: support more strict tslint

- package.json
- scripts/git/commit-message.json
- scripts/git/commit-msg.js
- scripts/git/validate-commit-message.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: validate commit script
```
```
[ ] Yes
[x] No
```
> chore: add git hook to check commit messages

- components/list/nz-list.component.ts
- components/spin/nz-spin.component.ts
close #1819
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:spin): fix cdk change detection

- README-zh_CN.md
- README.md
- docs/contributing.en-US.md
- docs/contributing.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc: change README.md

- components/core/style/index.less
- components/dropdown/nz-dropdown.component.html
- components/dropdown/nz-dropdown.component.ts
- components/table/demo/custom-filter-panel.ts
- components/table/demo/grouping-columns.ts
- components/table/nz-th.component.html
- components/table/nz-th.component.ts
- components/table/nz-th.spec.ts
- components/table/nz-thead.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix filter table header in ant design 3.10

- components/select/nz-select.component.ts
- components/select/nz-select.spec.ts
close #2201
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2201
```
[ ] Yes
[x] No
```
> fix(module:select): fix space closing select panel

- docs/recommendation.zh-CN.md
- scripts/site/_site/src/app/app.component.html
```
[ ] Bugfix
[] Feature
```
```
[ ] Yes
[x] No
```
> feat(showcase): add link to NG-ZORRO-MOBILE

- README-zh_CN.md
- README.md
- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add the SVG icon related content in getting started docs

- components/icon/nz-icon.service.ts
- components/package.json
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:icon): upgrade icon dependency to avoid interceptor

- components/modal/nz-modal.component.html
- components/modal/nz-modal.service.ts
- components/modal/nz-modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:modal): fix modal confirm style

- components/tabs/nz-tabs-nav.component.html
- components/tabs/nz-tabs.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tabs): fix tabs icon

- components/icon/nz-icon.directive.ts
- components/tabs/nz-tabs-nav.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tabs): fix icons position

- schematics/fix-icon/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(schematics): fix object comparisons method

- components/badge/demo/dot.ts
- components/dropdown/nz-dropdown.directive.ts
- components/form/demo/advanced-search.ts
- components/form/demo/horizontal-login.ts
- components/form/demo/normal-login.ts
- components/form/demo/register.ts
- components/icon/demo/basic.ts
- components/icon/demo/custom.ts
- components/icon/demo/iconfont.ts
- components/input/demo/addon.ts
- components/input/demo/presuffix.ts
- components/input/demo/search-input.ts
- components/input/doc/index.en-US.md
- components/input/doc/index.zh-CN.md
- components/layout/demo/custom-trigger.ts
- components/menu/demo/inline-collapsed.ts
- components/package.json
- components/popover/nz-popover.component.ts
- components/select/nz-option-container.component.html
- components/select/nz-option-li.component.html
- components/select/nz-option-li.component.ts
- components/slider/demo/icon-slider.ts
- components/table/demo/default-filter.ts
- components/tabs/demo/editable-card.ts
- components/tabs/demo/icon.ts
- package.json
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
- tslint.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:icon): fix icon miss in components

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.7.1): release 1.7.1

- components/layout/demo/responsive.ts
- components/layout/nz-layout.spec.ts
- components/layout/nz-sider.component.ts
close #2343
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:layout): fix layout init breakpoint nzCollapsed value

- components/calendar/nz-calendar-header.component.ts
- components/calendar/nz-calendar-header.spec.ts
close #2351
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:calendar): fix calendar year picker

- components/menu/demo/inline.ts
- components/menu/nz-submenu.component.ts
close #2327
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:menu): fix menu level 4 padding error

- components/tree/demo/basic.ts
- components/tree/demo/directory.ts
- components/tree/nz-tree-node.component.html
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.html
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.service.ts
- components/tree/nz-tree.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2332   #2205 #2336
```
[ ] Yes
[x] No
```
> fix(module:tree): fix icon to svg & draggable event listener

- components/checkbox/nz-checkbox-group.component.ts
- components/collapse/nz-collapse-panel.component.html
- components/collapse/nz-collapse-panel.component.ts
- components/collapse/nz-collapse.component.ts
- components/collapse/nz-collapse.module.ts
- components/core/addon/string_template_outlet.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:collapse): support onPush in collapse

- components/i18n/languages/da_DK.ts
- components/i18n/languages/date-picker/da_DK.ts
- components/i18n/languages/time-picker/da_DK.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #2485 
Danish locale is added.
```
[ ] Yes
[X] No
```
> feat: Adds danish locale

- components/form/demo/register.ts
- components/form/demo/validate-reactive.ts
- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/nz-form-control.component.ts
- components/form/nz-form-explain.component.ts
- components/form/nz-form-extra.component.ts
- components/form/nz-form-item.component.ts
- components/form/nz-form-label.component.ts
- components/form/nz-form-split.component.ts
- components/form/nz-form-text.component.ts
- components/form/nz-form.directive.ts
- scripts/site/_site/src/style/patch.less
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2381 
```
[ ] Yes
[x] No
```
> refactor(module:form): refactor form

- components/form/nz-form-control.component.ts
- components/form/nz-form-item.component.ts
- components/form/nz-form-label.component.ts
- components/form/nz-form.module.ts
- components/grid/nz-col.component.ts
- components/grid/nz-col.directive.ts
- components/grid/nz-grid.module.ts
- components/grid/nz-row.component.ts
- components/grid/nz-row.directive.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2381 
```
[ ] Yes
[x] No
```
> refactor(module:grid): refactor grid module

- components/dropdown/nz-dropdown.spec.ts
- components/menu/nz-menu-item.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2433
```
[ ] Yes
[x] No
```
> fix(module:menu): fix dropdown menu item selected className

- components/progress/doc/index.en-US.md
- components/progress/doc/index.zh-CN.md
- components/progress/nz-progress.component.html
- components/progress/nz-progress.component.ts
- components/progress/nz-progress.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2378
Add `strokeColor` and `strokeLinecap` API.
```
[ ] Yes
[x] No
```
> feat(module:progress): support custom strokeColor and strokeLinecap

- components/avatar/avatar.spec.ts
- components/avatar/demo/badge.ts
- components/avatar/demo/basic.ts
- components/avatar/demo/type.ts
- components/avatar/doc/index.en-US.md
- components/avatar/doc/index.zh-CN.md
- components/avatar/nz-avatar.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2380
```
[ ] Yes
[x] No
```
> feat(module:avatar): support custom size

- components/timeline/nz-timeline.component.html
- components/timeline/nz-timeline.module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2377
```
[ ] Yes
[x] No
```
> fix(module:timeline): fix loading icon

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:modal): add missing nzClassName property

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/nz-drawer-ref.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2403
```
[ ] Yes
[x] No
```
> feat(module:drawer): add input property in NzDrawerRef

- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add faq in icons docs

- components/menu/nz-submenu.component.html
fix accidentally closed submenu bug
close #2449
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:menu): fix fold menu

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 1.8.1
```
```
[ ] Yes
[ ] No
```
> release(1.8.1): release 1.8.1

- components/collapse/nz-collapse.component.ts
- components/layout/nz-sider.component.html
- components/layout/nz-sider.component.ts
- components/radio/nz-radio-button.component.html
- components/radio/nz-radio-button.component.ts
- components/radio/nz-radio-group.component.ts
- components/radio/nz-radio.component.html
- components/radio/nz-radio.component.ts
- components/radio/nz-radio.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2381 
```
[ ] Yes
[x] No
```
> refactor(module:radio): refactor radio to support OnPush

- components/spin/nz-spin.component.html
- components/spin/nz-spin.component.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2381 
```
[ ] Yes
[x] No
```
> refactor(module:spin): refactor spin

- components/checkbox/nz-checkbox-group.component.ts
- components/checkbox/nz-checkbox.component.html
- components/checkbox/nz-checkbox.component.ts
- components/switch/nz-switch.component.html
- components/switch/nz-switch.component.ts
- components/switch/nz-switch.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:switch & checkbox): refactor switch & checkbox

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/nz-modal.component.ts
- components/modal/nz-modal.spec.ts
- components/modal/nz-modal.type.ts
close #1999 
```
[ ] Bugfix
[x] Feature
```
Issue Number: N/A 
```
[ ] Yes
[x] No
```
> feat(module:modal): support clicking ESC to close modal

- components/skeleton/nz-skeleton.component.html
- components/skeleton/nz-skeleton.component.ts
- components/skeleton/nz-skeleton.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:skeleton): refactor skeleton

- components/tree-select/nz-tree-select.component.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2381
```
[ ] Yes
[x] No
```
> refactor(module:tree-select): refactor tree-select

- integration/webpack/package.json
- integration/webpack/webpack.config.js
```
[ ] Bugfix
[ ] Feature
```
The webpack integration test uses a webpack config with uglify-webpack-plugin
Replace with terser-webpack-plugin.
```
[ ] Yes
[x] No
```
A revised version of #2520 but targeted to the `next` branch. cc @vthinkxie
> build: bump webpack integration

- components/auto-complete/nz-autocomplete-optgroup.component.html
- components/auto-complete/nz-autocomplete-optgroup.component.ts
- components/auto-complete/nz-autocomplete-option.component.ts
- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.component.ts
- components/auto-complete/nz-autocomplete.module.ts
- components/core/types/drop-down-position.ts
- components/core/util/scroll-into-view-if-needed.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2381
```
[ ] Yes
[x] No
```
> refactor(module:autocomplete): refactor autocomplete

- components/list/demo/infinite-load.md
- components/list/demo/infinite-load.ts
- components/list/demo/vertical.ts
- components/list/list.spec.ts
- components/list/nz-list-item-meta.component.html
- components/list/nz-list-item-meta.component.ts
- components/list/nz-list-item.component.html
- components/list/nz-list-item.component.ts
- components/list/nz-list.component.html
- components/list/nz-list.component.ts
- components/list/nz-list.module.ts
- scripts/site/_site/src/app/share/share.module.ts
- merge pull #2415
- used cdk-virtual-scroll instead of ngx-infinite-scroll
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:list): refactor list

- README-zh_CN.md
- README.md
fix a misspelling of README.md
> fix(readme): fix misspelling

- components/layout/demo/responsive.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:layout): fix responsive demo

- components/button/nz-button.component.ts
- components/core/wave/nz-wave-renderer.ts
- components/core/wave/nz-wave.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:core): support provide wave config with DI

- components/drawer/nz-drawer.component.ts
- components/drawer/nz-drawer.service.ts
- components/modal/nz-modal.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2388
```
[ ] Yes
[x] No
```
> fix(module: drawer, modal): fix focus bug of IE

- scripts/publish/publish.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: publish support pre-release version

- components/message/nz-message-container.component.ts
- components/message/nz-message.component.ts
- components/notification/demo/update.md
- components/notification/demo/update.ts
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/notification/nz-notification-container.component.ts
- components/notification/nz-notification.component.ts
- components/notification/nz-notification.definitions.ts
- components/notification/nz-notification.service.ts
- components/notification/nz-notification.spec.ts
* feat(module:notification): support update by key
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:notification,message): refactor

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/publish/publish.js
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.1): release 7.0.0-rc.1

- components/back-top/nz-back-top.component.ts
- components/breadcrumb/nz-breadcrumb.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2642 
```
[ ] Yes
[x] No
```
> fix(module:back-top,breadcrumb) use markForCheck replace detectChanges when use OnPush

- components/radio/nz-radio-group.component.ts
- components/radio/nz-radio.spec.ts
close #2206 close #2611
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:radio): fix radio ContentChildren error

- components/input/nz-autoresize.directive.ts
- components/layout/nz-sider.component.ts
close #2603
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:layout): fix sider nzBreakPoint

- components/popconfirm/nz-popconfirm.component.html
- components/popconfirm/nz-popconfirm.component.ts
- components/popconfirm/nz-popconfirm.directive.ts
- components/popconfirm/nz-popconfirm.module.ts
- components/popover/nz-popover.component.html
- components/popover/nz-popover.component.ts
- components/popover/nz-popover.directive.ts
- components/popover/nz-popover.module.ts
- components/popover/nz-popover.spec.ts
- components/tooltip/nz-tooltip.component.html
- components/tooltip/nz-tooltip.component.ts
- components/tooltip/nz-tooltip.directive.ts
- components/tooltip/nz-tooltip.module.ts
- components/tooltip/nz-tooltip.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:tooltip,popover,popconfirm): refactor

- components/tabs/nz-tabs-nav.component.html
- components/tabs/nz-tabs-nav.component.ts
- components/tabs/nz-tabs.spec.ts
- components/tabs/nz-tabset.component.html
- components/tabs/nz-tabset.component.ts
- scripts/site/_site/src/theme.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tabs): fix tabs style error

- docs/schematics.en-US.md
- docs/schematics.zh-CN.md
- scripts/schematics/template/index.ts
- scripts/schematics/template/schema.json
- scripts/schematics/template/schema.ts
- scripts/site/utils/generate-code-box.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: schematics
```
```
[ ] Yes
[x] No
```
> refactor(schematics): update API and schema options

- .github/ISSUE_TEMPLATE.md
- ngsw-config.json
- scripts/site/_site/src/app/app.component.html
- scripts/site/_site/src/manifest.json
- scripts/site/_site/src/style/responsive.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix some styles and service worker config

- components/transfer/nz-transfer-list.component.html
- components/transfer/transfer.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2686
```
[ ] Yes
[x] No
```
> fix(module:transfer): fix the `Not Found` display condition

- components/core/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix table sticky style

- components/i18n/public-api.ts
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
- schematics/ng-add/schema.json
- schematics/ng-add/schema.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #2598
Danish locale is actually exported
```
[ ] Yes
[X] No
```
> fix(module:i18n): Danish locale is exported and mentioned in i18n docs

- docs/changelog.en-US.md
- docs/contributing.en-US.md
- docs/faq.en-US.md
> docs: fix typos

- components/table/demo/edit-row.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:table): reset edit cache when cancel

- components/table/demo/edit-cell.ts
icon图标书写错误
```
[x] Bugfix
[ ] Feature
```
Issue Number: 2766
```
[ ] Yes
[x] No
```
> fix icon error

- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
Issue Number:#2730
```
[ ] Yes
[x] No
```
tmp solution to solve the problem that the overlay created before  will …
> fix(module:tree-select): fix tree-select overlay's index problem

- components/core/util/convert.ts
- components/pagination/doc/index.en-US.md
- components/pagination/doc/index.zh-CN.md
- components/pagination/nz-pagination.component.html
- components/pagination/nz-pagination.component.ts
- components/pagination/nz-pagination.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:pagination): refactor pagination to support OnPush

- components/popover/nz-popover.component.html
- components/popover/nz-popover.component.ts
- components/tooltip/nz-tooltip.component.ts
- components/tooltip/nz-tooltip.directive.ts
- components/tooltip/nz-tooltip.spec.ts
close #2695, #2800
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2695, #2800 
`setTitle` is proxy to `nzTitle`, so `nzTitle` of `nzTooltipCopmonent` is updated.
```
[ ] Yes
[x] No
```
> fix(module:tooptip): fix setTitle proxy to nzTitle

- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
I have succeed in run 'npm run lint' and failed to run test suite,But I don't think there will be any negative impact.
> docs(module:steps): remove extra semicolons

- docs/getting-started.en-US.md
```
[ ] Bugfix
[ ] Feature
```
> doc: clarify root module import strategy

- components/calendar/nz-calendar-header.component.ts
- components/calendar/nz-calendar.component.ts
ref #2381
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
TODO: Breaking Changes Descriptions....
> refactor(module:calendar): use OnPush by default

- components/carousel/demo/basic.ts
- components/carousel/nz-carousel-content.directive.ts
- components/carousel/nz-carousel.component.html
- components/carousel/nz-carousel.component.ts
- components/carousel/nz-carousel.spec.ts
- components/core/util/convert.ts
close #2631, #2387, #2158, #2226
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:carousel): refactor

- components/switch/nz-switch.component.ts
- components/switch/nz-switch.spec.ts
close #2787
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:switch): fix switch error when loading or disabled

- components/icon/demo/basic.md
- components/icon/demo/basic.ts
- components/icon/demo/iconfont.ts
- components/icon/demo/twotone.md
- components/icon/demo/twotone.ts
- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.spec.ts
close #2888
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:icon): support rotate

- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.spec.ts
```
[ ] Bugfix
[ ] Feature
```
SVG element rotates.
```
[ ] Yes
[x] No
```
> refactor(module:icon): move transform to svg

- components/collapse/demo/custom.ts
- components/collapse/nz-collapse-panel.component.html
- components/icon/nz-icon.directive.ts
```
[x] Bugfix
[ ] Feature
```
Icon would not be re-rendered unless it's necessary.
```
[ ] Yes
[x] No
```
> feat(module:icon): fix falsy render

- components/tree/nz-tree-node.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: word misspelling
```
```
[ ] Yes
[x] No
```
> fix(module:tree): word misspelling(destory -> destroy)

- .github/lock.yml
ref #2889
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add lock threads robot config
```
Issue Number: #2889
```
[ ] Yes
[x] No
```
> chore: add lock threads robot config

- components/core/util/logger/logger.service.ts
- components/slider/nz-slider-marks.component.ts
close #2893
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: fix es6 build target

- components/collapse/demo/custom.ts
- components/collapse/doc/index.en-US.md
- components/collapse/doc/index.zh-CN.md
- components/collapse/nz-collapse-panel.component.html
- components/collapse/nz-collapse-panel.component.ts
- components/collapse/nz-collapse.spec.ts
- components/collapse/style/index.less
close #1911
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
Ref ant design: https://github.com/ant-design/ant-design/pull/14820.
> feat(module:collapse): add extra field

- .github/no-response.yml
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2889
```
[ ] Yes
[x] No
```
> chore: add no-response robot config

- .github/no-response.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update `responseRequiredLabel` for no-response config

- components/table/nz-table.spec.ts
- components/table/nz-td.component.ts
- components/table/nz-td.spec.ts
- components/table/nz-th.component.ts
- components/table/nz-th.spec.ts
- components/tag/demo/basic.ts
- components/tag/demo/control.ts
- components/tag/doc/index.en-US.md
- components/tag/doc/index.zh-CN.md
- components/tag/nz-tag.component.html
- components/tag/nz-tag.component.ts
- components/tag/nz-tag.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:tag): refactor tag

- components/cascader/nz-cascader.component.html
- components/cascader/nz-cascader.module.ts
- components/core/overlay/nz-connected-overlay.ts
- components/core/overlay/nz-overlay-config.ts
- components/core/overlay/nz-overlay.module.ts
- components/core/style/index.less
- components/date-picker/date-picker.module.ts
- components/date-picker/picker.component.html
- components/popconfirm/nz-popconfirm.component.html
- components/popconfirm/nz-popconfirm.module.ts
- components/popover/nz-popover.component.html
- components/popover/nz-popover.module.ts
- components/select/nz-select.component.html
- components/select/nz-select.module.ts
- components/time-picker/nz-time-picker.component.html
- components/time-picker/nz-time-picker.module.ts
- components/tooltip/nz-tooltip.component.html
- components/tooltip/nz-tooltip.module.ts
- components/tree-select/nz-tree-select.module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2874
```
[ ] Yes
[x] No
```
> fix(module:core): fix the style of CDK conflicts

- components/date-picker/demo/disabled-date.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/header-picker.component.html
- components/date-picker/lib/calendar/calendar-header.component.html
- components/date-picker/lib/calendar/calendar-header.component.ts
- components/date-picker/lib/year/year-panel.component.html
- components/date-picker/lib/year/year-panel.component.ts
- components/date-picker/year-picker.component.spec.ts
close #2194
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2194
```
[ ] Yes
[x] No
```
> feat(module:date-picker): support nzDisabledDate for year-picker

- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
- components/cascader/nz-cascader.component.ts
- components/popconfirm/demo/custom-icon.md
- components/popconfirm/demo/custom-icon.ts
- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/nz-popconfirm.component.html
- components/popconfirm/nz-popconfirm.component.ts
- components/popconfirm/nz-popconfirm.directive.ts
- components/popconfirm/nz-popconfirm.module.ts
- components/popconfirm/nz-popconfirm.spec.ts
close #2196
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:popconfirm): support custom icon

- components/tabs/demo/lazy.md
- components/tabs/demo/lazy.ts
- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/nz-tab.component.ts
- components/tabs/nz-tab.directive.ts
- components/tabs/nz-tabs.module.ts
- components/tabs/nz-tabset.component.html
- scripts/site/_site/doc/style/toc.less
- scripts/site/utils/generate-demo.js
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2716 
```
[ ] Yes
[x] No
```
> feat(module:tabs): support lazy load tabs

- components/input/demo/password-input.md
- components/input/demo/password-input.ts
- components/input/demo/search-input.ts
- components/input/nz-input-group.component.ts
close #2945 close #2956
```
[x] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> fix(module:input): fix antd input style change & input password demo

- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
- schematics/README.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #2971
```
[ ] Yes
[x] No
```
> docs(module:customize-theme): fix the path for the theme variables

- components/calendar/demo/card.ts
- components/calendar/demo/select.ts
- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:calendar): fix calendar doc

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/tree-select/demo/multiple.md
- components/tree-select/demo/multiple.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
- components/tree-select/nz-tree-select.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2488
```
[ ] Yes
[x] No
```
> feat(module:tree-select): support set the max count for tags

- components/auto-complete/demo/uncertain-category.ts
- components/auto-complete/nz-autocomplete-option.component.ts
- components/drawer/nz-drawer-ref.ts
- components/mention/nz-mention.component.html
- components/select/nz-option-li.component.ts
- components/select/nz-select-top-control.component.html
- components/tree-select/nz-tree-select.component.html
- components/tree/nz-tree-node.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2448
```
[ ] Yes
[x] No
```
https://github.com/react-component/select/blob/master/src/Select.tsx#L1356
> feat(module:auto-complete,mention,select,tree-select): prevent loss of focus when the options click

- components/back-top/demo/custom.ts
- components/back-top/demo/target.ts
- components/tree/demo/draggable-confirm.ts
- components/tree/demo/draggable.ts
- components/tree/nz-tree-node.component.ts
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
- scripts/site/_site/doc/app/share/nz-highlight/nz-highlight.component.ts
- scripts/site/_site/doc/app/share/nz-nav-bottom/nz-nav-bottom.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: switch to onPush

- components/slider/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: fix slider definition not exported

- components/auto-complete/nz-autocomplete.component.ts
- components/cascader/nz-cascader.component.ts
- components/date-picker/abstract-picker.component.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-picker.component.ts
- components/date-picker/header-picker.component.ts
- components/date-picker/month-picker.component.ts
- components/date-picker/range-picker.component.ts
- components/date-picker/week-picker.component.ts
- components/date-picker/year-picker.component.ts
- components/dropdown/nz-dropdown-button.component.ts
- components/dropdown/nz-dropdown.component.ts
- components/menu/nz-submenu.component.ts
- components/popconfirm/nz-popconfirm.component.ts
- components/popconfirm/nz-popconfirm.directive.ts
- components/popover/nz-popover.component.ts
- components/popover/nz-popover.directive.ts
- components/select/nz-select-top-control.component.ts
- components/select/nz-select.component.ts
- components/tooltip/nz-tooltip.component.ts
- components/tooltip/nz-tooltip.directive.ts
- components/tree-select/nz-tree-select.component.ts
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:no-animation): make the `noAnimation` parameter be optional

- components/tree/nz-tree-node.component.html
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): fix animation of expand method

- components/tree/nz-tree-node.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): fix remove and clearChildren missing origin

- components/tree/nz-tree-node.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): fix expand state bug for tree-select

- components/icon/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
Remove exportation of `NzIconTestModule`.
```
[ ] Yes
[x] No
```
> fix(module:icon): remove icon test module export

- schematics/collection.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:schematics): fix `add-icon-assets` schema path

- components/table/nz-table.component.ts
- components/table/nz-table.spec.ts
close #3004
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix table crash with double binding

- components/checkbox/nz-checkbox.component.html
- components/checkbox/nz-checkbox.component.ts
- components/checkbox/nz-checkbox.spec.ts
close #3000
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:checkbox): fix checkbox a11y error

- components/select/nz-select.component.spec.ts
- components/select/nz-select.component.ts
- components/select/nz-select.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3014 
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select reset in form

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(7.0.1): release 7.0.1

- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
docs(Calendar): add sample usage of TemplateRef
Add sample usage of TemplateRef,  show date in the tempate.
> docs(module:calendar): add sample usage of `TemplateRef`

- integration/rollup/package.json
```
[ ] Bugfix
[ ] Feature
```
Locked up rollup's version to avoid its bug.
```
[ ] Yes
[x] No
```
> build: fix rollup version

- components/core/style/index.less
close #3050
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): fix table small size virtual scroll style

- components/pagination/nz-pagination.component.ts
- components/pagination/nz-pagination.spec.ts
close #3049
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:pagination): fix pagination bug

- components/table/demo/edit-cell.ts
- docs/faq.en-US.md
- docs/faq.zh-CN.md
close #3043 close #3024
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix some doc errors

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
- scripts/site/utils/generate-code-box.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(7.0.2): release 7.0.2

- components/select/nz-select.component.spec.ts
- components/select/nz-select.component.ts
close #3059
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:select): fix select init touched state error when disabled

- components/package.json
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update dependency
```
This would make the package rely on `@ant-design/icons-angular` 2.0.2, which would not require TypeScript as a peer dependency. So TypeScript mismatching gets fixed.
```
[ ] Yes
[ ] No
```
> feat: upgrade icon to 2.0.2

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(7.0.3): release 7.0.3

- components/tooltip/nz-tooltip.directive.ts
- components/tooltip/nz-tooltip.spec.ts
```
[x] Bugfix
[ ] Feature
```
Though directive updated properties to a component, the component's change detection is not triggered.
The directive would trigger component's change detection.
```
[ ] Yes
[x] No
```
> fix(module:tooltip): fix tooltip not render after set

- README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(readme): fix typo 

- components/modal/nz-modal.component.ts
- components/modal/nz-modal.service.ts
- components/modal/nz-modal.spec.ts
- components/modal/nz-modal.type.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3107
```
[ ] Yes
[x] No
```
> fix(module:modal): simple confirm should not have cancel button

- components/date-picker/public-api.ts
```
[x] Bugfix
[ ] Feature
```
Not able to import NzYearPickerComponent in other component. 
Able to import NzYearPickerComponent in another component
> fix(module:DatePicker): add year picker component in public-api.ts

- components/cascader/nz-cascader-definitions.ts
- components/cascader/nz-cascader-li.component.html
- components/cascader/nz-cascader-li.component.ts
- components/cascader/nz-cascader-utils.ts
- components/cascader/nz-cascader.component.html
- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.service.ts
- components/cascader/nz-cascader.spec.ts
- components/cascader/public-api.ts
close #3027 
refactor(module:cascader): refactor cascader
```
[x] Bugfix
[ ] Feature
```
When you click an option in the second column, the third column would be removed. So the bug in that issue gets resolved.
I also refactored the component for less maintenance cost in the future. Not UI directly related logic was moved to `NzCascaderService`. Lots of redundant code and logic were …
> fix(module:cascader): fix columns not dropped

- components/tree-select/demo/async.ts
- components/tree/demo/basic.ts
- components/tree/demo/directory.ts
- components/tree/demo/draggable.ts
- components/tree/demo/dynamic.ts
- components/tree/demo/search.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/interface.ts
- components/tree/nz-tree-base.service.ts
- components/tree/nz-tree-node.component.html
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree-node.ts
- components/tree/nz-tree.component.html
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.module.ts
- components/tree/nz-tree.spec.ts
- components/tree/public-api.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3076 
```
[ ] Yes
[x] No
```
> fix(module: tree): fix nzMultiple and rollback code

- CHANGELOG.md
- components/package.json
- components/tree/demo/basic.ts
- components/version.ts
- docs/animations.en-US.md
- docs/animations.zh-CN.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/publish/publish.js
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(7.1.0): release 7.1.0

- components/dropdown/nz-dropdown-button.component.html
- components/dropdown/nz-dropdown.component.html
- components/dropdown/nz-dropdown.module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #3075
```
[ ] Yes
[x] No
```
> fix(module:dropdown): fix the style of CDK conflicts

- components/icon/page/index.ts
- components/modal/nz-modal.component.ts
- components/modal/nz-modal.type.ts
- components/table/nz-table.component.ts
- components/tooltip/nz-tooltip.component.ts
- components/tooltip/nz-tooltip.directive.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Fix type of some API. Otherwise some editors would complain about incorrect types
```
```
[ ] Yes
[x] No
```
> fix: fix type of some API

- schematics/ng-add/schema.json
- schematics/ng-generate/boot-page/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): do not set boot page when the target file is modified

- components/menu/doc/index.en-US.md
- components/menu/doc/index.zh-CN.md
- components/menu/nz-menu.spec.ts
- components/menu/nz-submenu.component.html
- components/menu/nz-submenu.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:menu): support `nzMenuClassName` for the submenu

- components/breadcrumb/nz-breadcrumb.component.ts
close #2538 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Test is still blocked due to Angular's bug.
> fix(module:breadcrumb): fix auto generate not working in lazy modules

- CHANGELOG.md
- components/menu/nz-submenu.component.ts
- components/package.json
- components/select/demo/automatic-tokenization.ts
- components/select/demo/custom-content.ts
- components/select/demo/scroll-load.ts
- components/select/demo/search-box.ts
- components/select/demo/search.ts
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(7.2.0): release 7.2.0

- components/drawer/nz-drawer.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3200
```
[ ] Yes
[x] No
```
> fix(module:drawer): create focus trap error when `nzVisible` default value is true

- components/tree/demo/draggable-confirm.ts
- components/tree/demo/draggable.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: tree): support nzBlockNode

- components/steps/nz-steps.component.ts
- components/steps/nz-steps.spec.ts
close #3193 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:steps):`updateChildrenSteps` bug

- components/form/demo/validate-reactive.ts
fix(demo): Observable.create is deprecated use new Observable() instead
```
[ x ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x ] No
```
> fix(docs): Observable.create is deprecated use new Observable() instead

- components/core/style/index.less
close #3268
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:dropdown): fix dropdown ul list-style

- components/select/demo/automatic-tokenization.ts
- components/select/demo/select-users.ts
- components/select/nz-option-container.component.ts
close #3258
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select scroll top trigger

- components/tree/nz-tree.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tree): duplicated module import

- components/select/nz-select-top-control.component.html
close #3246 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select disable cursor

- components/tree-select/nz-tree-select.component.ts
- components/tree/nz-tree-base.service.ts
- components/tree/nz-tree-node.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3163
```
[ ] Yes
[x] No
```
> fix(module:tree, tree-select): fix the key validity check

- components/core/style/index.less
- components/dropdown/nz-dropdown.service.ts
close #3241
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:dropdown): fix dropdown style conflict with material style

- components/core/style/index.less
- components/table/nz-table.component.html
- components/table/nz-th.component.html
close #3164
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table border in firefox

- components/table/demo/virtual.md
- components/table/demo/virtual.ts
- components/table/nz-table.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
close #3144 close #3073 close #2886
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:table): expose CdkVirtualScrollViewport

- README-zh_CN.md
- README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
💰💰💰
> docs: add issue hunt badge

- components/spin/doc/index.en-US.md
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/nz-table.component.html
- components/table/nz-table.component.ts
close #3008
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:table): support nzLoadingIndicator

- components/rate/nz-rate-item.component.html
close #3252
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3252 
```
[ ] Yes
[ ] No
```
> fix: click event is stopped

- README-zh_CN.md
- README.md
- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/nz-form-control.component.ts
close #3211
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:form): fix form control template driven

- components/date-picker/date-range-picker.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/lib/popups/date-range-popup.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/standard-types.ts
```
[ ] Bugfix
[x] Feature
```
[Issue](https://github.com/NG-ZORRO/ng-zorro-antd/issues/1629)
Issue Number: #1629
nzRanges support callback
```
[ ] Yes
[x] No
```
> feat(module:date-picker): `nzRanges` support callback

- components/select/nz-option.component.ts
- components/select/nz-select.component.ts
close #3029
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:select): fix select not change after option input changes

- components/components.less
- components/ng-zorro-antd.less
- components/style/entry.less
- components/style/patch.less
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- scripts/build/compile-styles.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: fix patch not included

- CHANGELOG.md
- components/package.json
- components/table/demo/virtual.ts
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/faq.en-US.md
- docs/faq.zh-CN.md
- docs/universal.en-US.md
- docs/universal.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(7.3.0): release 7.3.0

- components/select/nz-select-top-control.component.ts
- components/select/nz-select-top-control.spec.ts
close #3322
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select search display

- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update more environment support explain

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/build/prerender.sh
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(7.3.1): release 7.3.1

- components/card/doc/index.zh-CN.md
- components/components.less
- scripts/build/compile-styles.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: fix compile style-script

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.3.2
```
```
[ ] Yes
[x] No
```
> release(7.3.2): release 7.3.2

- docs/contributing.en-US.md
- docs/contributing.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #3179 
```
[ ] Yes
[ ] No
```
> docs: update the template link for contributing page

- components/tag/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:tag): fix typo

- components/core/tree/nz-tree-base.ts
- components/core/tree/public-api.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.ts
- components/tree/nz-tree.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:tree-select): add the public methods

- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-github-btn/index.ts
- scripts/site/_site/doc/app/share/nz-github-btn/nz-github-btn.component.html
- scripts/site/_site/doc/app/share/nz-github-btn/nz-github-btn.component.less
- scripts/site/_site/doc/app/share/nz-github-btn/nz-github-btn.component.ts
- scripts/site/_site/doc/app/share/nz-github-btn/nz-github-btn.module.ts
- scripts/site/_site/doc/app/share/share.module.ts
- scripts/site/template/title.template.html
- scripts/site/utils/generate-demo.js
- scripts/site/utils/generate-docs.js
- scripts/site/utils/generate.title.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add Github button widget in introduce

- components/auto-complete/nz-autocomplete-trigger.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3340
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): enter-keydown event should not be prevent when the panel is closed

- CHANGELOG.md
- README-zh_CN.md
- README.md
- angular.json
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- package.json
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
- scripts/site/_site/doc/robots.txt
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(7.3.3): release 7.3.3

- components/progress/doc/index.en-US.md
- components/progress/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:progress): add missing optional value for the `[nzStatus]` property

- docs/recommendation.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
你好，我是 30 天精通 RxJS  的作者
最近已經更新個人網站，並把文章搬到個人網站內，希望能更新資訊，感謝🙏
> docs: update rxjs thirty days link

- components/carousel/public-api.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: fix definitions not exported

- components/card/doc/index.en-US.md
- components/card/doc/index.zh-CN.md
- components/card/nz-card.component.ts
- components/card/nz-card.spec.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:card): support setting size

- components/modal/nz-modal.component.html
- components/modal/nz-modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3407
```
[ ] Yes
[x] No
```
> fix(module:modal): content not work in confirm mode when the type is component

- components/progress/demo/circle-dynamic.ts
- components/progress/nz-progress.component.ts
close #3441
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3441
```
[ ] Yes
[x] No
```
> fix(module:progress): fix stroke color is not updated

- components/drawer/nz-drawer.component.html
- components/drawer/nz-drawer.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3402
```
[ ] Yes
[x] No
```
> fix(module:drawer): fix z-index level

- components/modal/nz-modal.component.ts
- components/modal/nz-modal.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3338
```
[ ] Yes
[x] No
```
> fix(module:modal): cannot to close in order of overlay opens when using esc

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/nz-drawer-options.ts
- components/drawer/nz-drawer.component.ts
- components/drawer/nz-drawer.service.ts
- components/drawer/nz-drawer.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #3372
```
[ ] Yes
[x] No
```
> feat(module:drawer): support `nzOnCancel` for service mode

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(7.4.0): release 7.4.0

- README-zh_CN.md
- README.md
- components/page-header/doc/index.en-US.md
- components/page-header/doc/index.zh-CN.md
- components/tree-select/demo/customized-icon.ts
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix some errors and update users

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(7.4.1): release 7.4.1

- scripts/site/_site/doc/app/share/share.module.ts
- ~~[ ] Tests for the changes have been added (for bug fixes / features)~~
- ~~[ ] Docs have been added / updated (for bug fixes / features)~~
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/3266#issuecomment-494036589
Because of this bug https://github.com/ng-packagr/ng-packagr/issues/594, metadata of submodules may not be exported from …
> build: hack to prevent bug of ng-packagr

- components/input-number/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
Typo
No more typo
```
[ ] Yes
[x] No
```
N/A
> docs(module:input-number): typo correction

- components/page-header/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
Typo
N/A
```
[ ] Yes
[x] No
```
N/A
> docs(typo): changing nz-page-header nzBack binding

- scripts/build/migration-styles.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: fix migration style file path

- components/i18n/date-helper.service.ts
- components/i18n/nz-i18n.module.ts
Close #3487 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): replace DatePipe with formatDate function

- components/drawer/nz-drawer.component.ts
- components/drawer/nz-drawer.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/ant-design/ant-design/pull/16694
```
[ ] Yes
[x] No
```
> feat(module:drawer): support pressing ESC to close drawer

- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
- components/dropdown/nz-dropdown-button.component.html
- components/dropdown/nz-dropdown-button.component.ts
- components/dropdown/nz-dropdown.module.ts
- components/dropdown/nz-dropdown.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:dropdown): support customize icons

- components/select/nz-select.service.spec.ts
- components/select/nz-select.service.ts
Close #3424
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:select): display error when in tag and search mode

- components/layout/demo/side.ts
- components/layout/nz-sider.component.html
- components/layout/nz-sider.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:layout): fix width type

- CHANGELOG.md
- README.md
- components/package.json
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(7.5.0): release 7.5.0

- components/cascader/nz-cascader.spec.ts
- components/core/testing/event-objects.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test: sync CDK testing code

- components/button/nz-button.component.ts
- components/core/wave/nz-wave-renderer.ts
- components/core/wave/nz-wave.directive.ts
- components/core/wave/nz-wave.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:button): disable wave animation when the type is link

- components/badge/nz-badge.component.html
- components/button/nz-button.component.html
- components/button/nz-button.component.ts
- components/button/nz-button.spec.ts
- components/dropdown/nz-dropdown.spec.ts
close #3079
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:button): fix order of DOM nodes in button

- .github/nz-boot.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update bot config

- components/affix/affix.spec.ts
- components/anchor/nz-anchor.component.ts
- components/cascader/nz-cascader.spec.ts
- components/core/scroll/nz-scroll.service.ts
- components/core/tree/nz-tree-base-node.ts
- components/core/tree/nz-tree-base.service.ts
- components/form/style/index.less
- components/i18n/languages/date-picker/et_EE.ts
- components/i18n/languages/date-picker/sk_SK.ts
- components/tree/nz-tree-node.component.ts
- components/upload/demo/custom-request.ts
- components/upload/interface.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: replace Chinese comments for English ones

- components/dropdown/nz-dropdown.directive.ts
- components/dropdown/nz-dropdown.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:dropdown): fix dropdown SSR bug

- components/divider/divider.spec.ts
- components/divider/doc/index.en-US.md
- components/divider/doc/index.zh-CN.md
- components/divider/nz-divider.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:divider): sync style with antd

- components/form/nz-form-control.component.ts
close #3607
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:form): fix form overlap

- components/mention/doc/index.en-US.md
- components/mention/doc/index.zh-CN.md
```
```
```
[ ] Yes
[x] No
```
> bugfix: nz-mention's doc error

- components/grid/nz-col.directive.ts
```
[x] Bugfix
[ ] Feature
```
All properties in EmbeddedProperty are not optional.
All properties in EmbeddedProperty are optional.
```
[ ] Yes
[x ] No
```
> fix(module:grid): Make all properties in EmbeddedProperty optional

- README-zh_CN.md
- README.md
- components/carousel/doc/index.en-US.md
- components/carousel/doc/index.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update ng-zorro-antd users list

- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add customized theme via custom-webpack builder

- components/core/trans-button/nz-trans-button.module.ts
- components/core/trans-button/public-api.ts
- components/input/nz-autosize.directive.ts
- components/ng-zorro-antd.module.ts
- components/typography/nz-typography.component.ts
- components/typography/nz-typography.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:typography): not render when the edit text has no changes

- components/typography/demo/interactive.ts
- components/typography/nz-typography.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:typography): fix the actions button order

- README-zh_CN.md
- README.md
- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- components/menu/nz-submenu.component.ts
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/contributing.en-US.md
- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- docs/recommendation.en-US.md
- docs/recommendation.zh-CN.md
- scripts/release-helper.sh
- scripts/site/_site/doc/app/app.component.html
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/style/index.less
- scripts/site/_site/doc/style/resource.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update 8.0 docs

- CHANGELOG.md
- angular.json
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
- scripts/site/_site/doc/tsconfig.es5.json
- scripts/site/_site/iframe/browserslist
- scripts/site/_site/tsconfig.app.json
- tsconfig-build.json
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.0.0): release 8.0.0

- components/breadcrumb/nz-breadcrumb.component.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number:  #3684
```
[ ] Yes
[x] No
```
> fix(module:breadcrumb): fix warning startWith operators

- scripts/site/_site/doc/app/app.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(site): zorro twitter connection error

- components/tree/demo/basic.ts
- components/tree/demo/directory.ts
- components/tree/nz-tree-node.component.html
- components/tree/nz-tree.component.html
- components/tree/nz-tree.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3690 
```
[ ] Yes
[x] No
```
> fix(module: tree): fix warning bug

- schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome-routing.module.ts.template
- schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome.module.ts.template
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(schematics): missing routing module in sidemenu template

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.0.1): release 8.0.1

- components/icon/nz-icon.service.ts
- components/package.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: update icon dependency

- components/icon/nz-icon.service.ts
- components/package.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> revert: revert update icon dependency

- components/switch/nz-switch.component.ts
close #3760
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:switch): fix switch ViewChild static

- components/menu/nz-menu-item.directive.ts
close #3736
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:menu): fix menu nzMatchRouter in nested menu

- components/table/nz-th.component.html
close #3721
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table custom filter panel

- components/breadcrumb/demo/module
- components/icon/nz-icon.service.ts
- components/rate/demo/module
- components/slider/demo/module
- components/timeline/demo/module
- docs/faq.en-US.md
- docs/faq.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update faq and fix module list of breadcrumb

- components/input/nz-input.directive.ts
- components/input/nz-input.module.ts
- components/input/nz-input.spec.ts
close #3732
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:input): fix input disabled OnPush

- CHANGELOG.md
- components/package.json
- components/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(8.0.3): release 8.0.3

- components/descriptions/demo/responsive.ts
- components/descriptions/nz-descriptions.component.html
- components/descriptions/nz-descriptions.component.ts
- components/descriptions/nz-descriptions.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:descriptions): fix span calculation

- components/table/nz-table.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table header scroll when fixed change

- README-zh_CN.md
- README.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update users list

- components/descriptions/demo/vertical-border.md
- components/descriptions/demo/vertical-border.ts
- components/descriptions/demo/vertical.md
- components/descriptions/demo/vertical.ts
- components/descriptions/nz-descriptions-definitions.ts
- components/descriptions/nz-descriptions.component.html
- components/descriptions/nz-descriptions.component.ts
please merge this after #3799
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
>  feat(module:descriptions): support vertical mode

- components/descriptions/nz-descriptions.component.html
- components/tabs/demo/link-router.md
- components/tabs/demo/link-router.ts
- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/nz-tab-link.directive.ts
- components/tabs/nz-tab.component.html
- components/tabs/nz-tab.component.ts
- components/tabs/nz-tabs.module.ts
- components/tabs/nz-tabs.spec.ts
- components/tabs/nz-tabset.component.html
- components/tabs/nz-tabset.component.ts
- components/tabs/public-api.ts
- components/tabs/style/entry.less
- components/tabs/style/patch.less
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/app.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:tabs): support link router

- components/core/tree/nz-tree-base-node.ts
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.spec.ts
Issue Number: 
To close https://github.com/NG-ZORRO/ng-zorro-antd/issues/3739
I'm a new of ng and nz, and I'm working on how to complete test case, maybe take lots of time...
> fix(module:tree): unexpected disappear of tree-node

- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:tree-select): add [nzHideUnMatched] property

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.1.0
```
```
[ ] Yes
[x] No
```
> release(8.1.0): release 8.1.0

- components/input/demo/module
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes: add missing import
```
```
[ ] Yes
[x] No
```
> docs: fix input demo

- components/result/demo/module
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix result import

- scripts/release/git-client.ts
- scripts/release/release-site.ts
- scripts/release/release.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: fix release scripts

- components/table/style/patch.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table small sticky style

- components/form/nz-form-control.component.ts
- components/form/nz-form-item.component.ts
close #3865
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:form): fix form feedback error when init with tips

- components/select/nz-select-top-control.component.ts
close #3825
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select with tokenization bug

- scripts/schematics/copy-resources.ts
```
[x] Bugfix
[ ] Feature
```
schematic resources not copied correctly in windows.
schematic resources copied correctly in windows.
```
[ ] Yes
[x] No
```
> fix(schematics): update copy-resources script to support Windows path

- components/affix/nz-affix.module.ts
- components/anchor/nz-anchor.module.ts
- components/avatar/nz-avatar.module.ts
- components/back-top/nz-back-top.module.ts
- components/carousel/nz-carousel.module.ts
- components/descriptions/nz-descriptions.module.ts
- components/icon/nz-icon.module.ts
- components/menu/nz-menu.module.ts
- components/select/nz-select.module.ts
- components/slider/nz-slider.module.ts
- components/statistic/nz-statistic.module.ts
- components/table/nz-table.module.ts
- components/timeline/nz-timeline.module.ts
- components/typography/nz-typography.module.ts
- components/upload/nz-upload.module.ts
```
[ ] Bugfix
[ ] Feature
```
import PlatformModule when use platform in component
```
[ ] Yes
[ ] No
```
@vthinkxie According to pull request (#3709) [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/pull/3709#issuecomment-511737300), i check all the module.
> fix(module:*): import PlatformModule when use platform in component

- components/tooltip/nz-tooltip.component.ts
close #3467
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3467 
```
[ ] Yes
[x] No
```
> fix(module:tooltip): fix position change not set back

- .github/nz-boot.yml
- schematics/utils/build-component.ts
- scripts/schematics/demo2schematics.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3844
```
[ ] Yes
[x] No
```
> fix(schematics): fix parse module name error

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.1.1): release 8.1.1

- components/slider/nz-slider-marks.component.ts
close #3876
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3876
Use `transform` instead of `width` and `marginLeft`.
```
[ ] Yes
[x] No
```
> fix(module:slider): change mark style in horizontal mode

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(8.1.2): release 8.1.2

- components/checkbox/nz-checkbox-group.component.html
- components/radio/demo/module
- components/table/style/patch.less
- components/upload/nz-upload.component.ts
- scripts/site/_site/doc/theme.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> style: fix styles error after sync with antd-3.20.7

- components/time-picker/time-holder.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:time-picker): fix time-picker test

- components/radio/demo/module
```
[ ] Bugfix
[ ] Feature
```
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3937
Issue Number: #3937 
```
[ ] Yes
[ ] No
```
> docs: fix style of components in nz-radio demo(#3937)

- components/descriptions/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Fix `nzBorderer` to `nzBordered`.
```
[ ] Yes
[ ] No
```
> docs(module:description): fix `nzBorderer` typo to `nzBordered`

- components/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: add missing dependencies

- components/statistic/doc/index.en-US.md
- components/statistic/doc/index.zh-CN.md
- components/statistic/nz-countdown.component.ts
- components/statistic/nz-countdown.spec.ts
- components/statistic/nz-time-range.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:statistics): countdown support finish event

- components/steps/demo/clickable.md
- components/steps/demo/clickable.ts
- components/steps/demo/module
- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
- components/steps/nz-step.component.ts
- components/steps/nz-steps.component.ts
- components/steps/nz-steps.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:steps): support for clickable steps

- components/core/wave/nz-wave-renderer.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update the wave animation styles

- components/badge/nz-badge.component.html
- components/badge/nz-badge.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3686
```
[ ] Yes
[x] No
```
> fix(module:badge): fix init animations

- components/table/nz-table.component.ts
close #3957
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix nzWidthConfig in nzTemplateMode

- components/input/nz-autosize.spec.ts
- components/select/nz-select.component.spec.ts
- components/tree-select/nz-tree-select.spec.ts
- docs/schematics.en-US.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test: fix test error in karma 4

- components/collapse/demo/extra.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:collapse): stop propagation in demo "extra"

- components/auto-complete/nz-autocomplete.spec.ts
- components/select/nz-select.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:select): fix select test error

- .travis.yml
- package.json
- schematics/ng-add/index.spec.ts
- schematics/ng-component/index.spec.ts
- schematics/ng-generate/blank/index.spec.ts
- schematics/ng-generate/blank/index.ts
- schematics/ng-generate/side-menu/index.spec.ts
- schematics/ng-generate/topnav/files/src/app/pages/welcome/welcome-routing.module.ts.template
- schematics/ng-generate/topnav/files/src/app/pages/welcome/welcome.module.ts.template
- schematics/ng-generate/topnav/index.spec.ts
- schematics/testing/test-app.ts
- schematics/tsconfig.json
- scripts/gulp/tasks/schematic.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(schematics): add test cases

- components/alert/nz-alert.component.html
- components/alert/nz-alert.component.ts
- components/alert/nz-alert.spec.ts
- components/avatar/nz-avatar.component.html
- components/cascader/nz-cascader.component.html
- components/icon/nz-icon.directive.ts
- components/input/nz-input-group.spec.ts
- components/layout/nz-layout.spec.ts
- components/steps/nz-steps.spec.ts
- components/tree/demo/customized-icon.ts
- components/tree/nz-tree-node.component.html
- components/tree/nz-tree.spec.ts
- scripts/site/_site/doc/app/app.component.html
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.html
- scripts/site/_site/doc/app/share/nz-nav-bottom/nz-nav-bottom.component.ts
- scripts/site/template/title.template.html
- scripts/site/utils/generate-demo.js
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes): remove usage of old icon API in our own codebase
```
```
[ ] Yes
[x] No
```
> refactor: remove old icon api

- components/popover/nz-popover.component.ts
- components/tooltip/base/nz-tooltip-base-legacy.component.ts
- components/tooltip/base/nz-tooltip-base.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip): empty judgement

- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- docs/getting-started.en-US.md
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:*): use secondary entry as much

- angular.json
- components/code-editor/demo/basic.md
- components/code-editor/demo/basic.ts
- components/code-editor/demo/complex.md
- components/code-editor/demo/complex.ts
- components/code-editor/demo/config.md
- components/code-editor/demo/config.ts
- components/code-editor/demo/diff.md
- components/code-editor/demo/diff.ts
- components/code-editor/demo/full-control.md
- components/code-editor/demo/full-control.ts
- components/code-editor/demo/module
- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
- components/code-editor/index.ts
- components/code-editor/nz-code-editor.component.html
- components/code-editor/nz-code-editor.component.ts
- components/code-editor/nz-code-editor.definitions.ts
- components/code-editor/nz-code-editor.module.ts
- components/code-editor/nz-code-editor.service.ts
- components/code-editor/nz-code-editor.spec.ts
- components/code-editor/package.json
- components/code-editor/public-api.ts
- components/code-editor/style/entry.less
- components/code-editor/style/index.less
- components/components.less
- components/core/util/public-api.ts
- components/core/util/tick.ts
- package.json
- scripts/site/_site/doc/styles.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:code-editor): add code editor component

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/release/release.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.2.0): release 8.2.0

- components/date-picker/picker.component.html
```
[ ] Bugfix
[ ] Feature
```
replace deprecated API
```
[ ] Yes
[x] No
```
> perf(module:date-picker): change the type of the icon to nzType

- components/auto-complete/nz-autocomplete.spec.ts
- components/input/nz-autosize.spec.ts
- components/resizable/nz-resizable.spec.ts
- components/select/nz-select.component.spec.ts
- components/tree-select/nz-tree-select.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module:*): fix test

- components/typography/nz-typography.spec.ts
- package.json
- scripts/site/_site/doc/app/app.component.html
- scripts/site/_site/doc/style/patch.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add top menus for mobile

- components/calendar/date-table-cell.component.ts
- components/code-editor/nz-code-editor.component.ts
- components/dropdown/nz-dropdown-a.directive.ts
- components/modal/nz-modal-footer.directive.ts
- components/resizable/nz-resizable.directive.ts
- components/resizable/nz-resize-handle.component.ts
- components/resizable/nz-resize-handles.component.ts
- components/result/nz-result.component.ts
- components/result/partial/not-found.ts
- components/result/partial/server-error.component.ts
- components/result/partial/unauthorized.ts
- components/typography/nz-text-copy.component.ts
- components/typography/nz-text-edit.component.ts
- components/typography/nz-typography.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: defines export name for components

- components/affix/affix.spec.ts
- components/core/scroll/nz-scroll.service.spec.ts
- components/typography/nz-typography.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test: fix window size test

- components/descriptions/nz-descriptions.component.html
close #4013
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:description): fix colspan calcuation in horizontal bordered

- components/typography/nz-typography.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module:typography): skip error case in CI

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Add a notifcation because some users use new API in old versions.
```
[ ] Yes
[x] No
```
> docs(module:toolip etc): add reminder of new api

- components/code-editor/demo/complex.ts
- components/code-editor/demo/module
- components/code-editor/nz-code-editor.component.ts
- components/code-editor/nz-code-editor.definitions.ts
- components/code-editor/package.json
- components/code-editor/style/index.less
```
[x] Bugfix
[ ] Feature
```
The context menu of monaco editor is cropped by borders of the container.
```
[ ] Yes
[x] No
```
> fix(module:code-editor): remove overflow styles

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.2.1): release 8.2.1

- scripts/gulp/tasks/site.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> ci: build with ES5 in CI

- components/message/demo/module
- components/modal/demo/module
- components/steps/demo/module
```
[ ] Bugfix
[ ] Feature
```
IconModule are not imported in some demo modules so some icons are not rendered.
```
[ ] Yes
[x] No
```
> docs: fix missing icon in some demos

- .travis.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> ci: remove google-chrome-beta

- components/cascader/nz-cascader-li.component.html
- components/cascader/nz-cascader-li.component.ts
- components/cascader/nz-cascader.module.ts
- components/core/highlight/highlight.module.ts
- components/core/highlight/highlight.pipe.spec.ts
- components/core/highlight/highlight.pipe.ts
- components/core/highlight/index.ts
- components/core/highlight/public-api.ts
- components/core/public-api.ts
- components/tree/nz-tree-node.component.html
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: add pipe to create highlights in components

- components/i18n/languages/zh_CN.ts
- components/i18n/languages/zh_TW.ts
- components/i18n/nz-i18n.interface.ts
close #4080
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:i18n): fix i18n interface and Traditional Chinese

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/nz-modal.component.html
- components/modal/nz-modal.component.ts
- components/modal/nz-modal.module.ts
- components/modal/nz-modal.spec.ts
- components/modal/nz-modal.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:modal): support for custom close icons

- components/alert/demo/banner.md
- components/auto-complete/demo/options.md
- components/calendar/demo/notice-calendar.md
- components/date-picker/demo/time.md
- components/mention/demo/avatar.md
- components/mention/demo/custom-tag.md
- components/popconfirm/demo/placement.md
- components/popover/demo/arrow-point-at-center.md
- components/popover/demo/template.md
- components/select/demo/module
- components/spin/demo/delayAndDebounce.md
- components/spin/demo/nested.md
- components/tooltip/demo/arrow-point-at-center.md
- components/tooltip/demo/template.md
- components/tree/demo/directory.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix some demo descriptions

- components/cascader/nz-cascader.spec.ts
close #3943
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes): refactoring test
```
```
[ ] Yes
[x] No
```
Just to make the test more readable.
> refactor(module:cascader): refactor test

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release
```
```
[ ] Yes
[x] No
```
> release(8.3.0): release 8.3.0

- components/select/nz-select.component.ts
- components/select/nz-select.service.ts
close #4139
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select compareWith array not work

- components/table/nz-table.component.html
- components/table/nz-table.spec.ts
- components/table/nz-th.spec.ts
close #4083 close #4142 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix nzWidthConfig conflict with nzWidth & firefox scrollbar style bug

- docs/contributing.en-US.md
- docs/contributing.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: change contributing guide

- components/code-editor/nz-code-editor.component.ts
- components/statistic/nz-countdown.component.ts
- components/table/nz-table.component.ts
- components/tabs/nz-tabset.component.ts
- components/tooltip/base/nz-tooltip-base.component.ts
- components/tooltip/base/nz-tooltip-base.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:*): use emit instead next

- components/time-picker/nz-time-picker-panel.component.ts
This PR fixes an issue with Ivy compatibility.
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> fix(module:time-picker): place ViewChild decorator on correct field

- components/affix/nz-affix.component.ts
- components/affix/utils.ts
- components/core/util/public-api.ts
- components/core/util/style.ts
- components/i18n/nz-i18n.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:affix): fix affix not working in Safari

- components/steps/demo/progress-dot.ts
- components/steps/style/progress-dot.less
```
[ x Bugfix
[ ] Feature
```
Issue Number: #4184
```
[ ] Yes
[x] No
```
> fix(module:steps): fix progress dot in vertical mode

- components/core/highlight/highlight.pipe.spec.ts
- components/core/highlight/highlight.pipe.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4152
```
[ ] Yes
[x] No
```
> fix(module:core): fix HTML entities highlight error

- components/dropdown/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
x
Issue Number: #4194 
x
```
[ ] Yes
[x] No
```
> chore: change error description of  dorpdown api

- components/cascader/nz-cascader.component.html
- components/core/logger/logger.ts
- components/i18n/nz-i18n.service.spec.ts
- components/i18n/nz-i18n.service.ts
- components/modal/nz-modal.component.ts
```
[x] Bugfix
[ ] Feature
```
对于暂时没有翻译的字段，会留空并提示用户，同时欢迎用户 contribute 翻译。
```
[ ] Yes
[x] No
```
> fix(module:i18n): add fallback mechanism

- components/core/pipe/index.ts
- components/core/pipe/nz-css-unit.pipe.ts
- components/core/pipe/nz-pipe.module.ts
- components/core/pipe/nz-time-range.pipe.ts
- components/core/pipe/nz-time-range.spec.ts
- components/core/pipe/public-api.ts
- components/core/public-api.ts
- components/modal/nz-modal.component.html
- components/modal/nz-modal.module.ts
- components/modal/nz-modal.spec.ts
- components/modal/public-api.ts
- components/statistic/nz-statistic.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:core): move pipes to a new module to share them

- scripts/prerender/sitemap.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix sitemap hreflang

- components/calendar/date-table.component.ts
- components/core/time/candy-date.ts
- components/date-picker/abstract-picker.component.ts
- components/date-picker/date-range-picker.component.html
- components/date-picker/date-range-picker.component.ts
- components/date-picker/lib/calendar/calendar-input.component.html
- components/date-picker/lib/calendar/calendar-input.component.ts
- components/date-picker/lib/lib-packer-supplements.spec.ts
- components/date-picker/lib/popups/date-range-popup.component.html
- components/date-picker/lib/popups/date-range-popup.component.ts
- components/date-picker/nz-date-picker.component.spec.ts
- components/date-picker/nz-range-picker.component.spec.ts
- components/date-picker/standard-types.ts
- components/test.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4130
```
[ ] Yes
[x] No
```
- 输入正确格式的 input 之后日历面板会高亮显示该日期，range picker 需要左右 input 都有值才会在日历面板中显示，此时不会触发 ngModelChange。
- 输入 enter 或者鼠标点击日期，遮罩关闭，触发 ngModelChange。
- 通过 esc 或直接点击遮罩关闭不会保存 input 值。
> fix(module:date-picker): optimized interaction by using input box

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.3.1): release 8.3.1

- components/calendar/date-table.component.ts
- components/calendar/month-table.component.ts
- components/calendar/nz-calendar.component.ts
- components/date-picker/lib/calendar/today-button.component.ts
- components/date-picker/lib/popups/inner-popup.component.ts
- components/date-picker/picker.component.ts
- components/page-header/nz-page-header.component.ts
- components/tree-select/demo/async.ts
- components/tree-select/demo/checkable.ts
- components/tree-select/demo/multiple.ts
- components/tree/demo/basic-controlled.ts
- components/tree/demo/basic.ts
- components/tree/demo/customized-icon.ts
- components/tree/demo/draggable-confirm.ts
- components/tree/demo/draggable.ts
- components/tree/demo/dynamic.ts
- components/tree/demo/line.ts
- components/tree/demo/search.ts
```
[ ] Bugfix
[ ] Feature
```
`ng build --prod`
```js
let AppComponent = class AppComponent {
constructor() {
this.title = 'ng';
}
ngOnInit() {
}
};
```
`ng build --prod`
```js
let AppComponent = class AppComponent {
constructor() {
this.title = 'ng';
}
};
```
```
[ ] Yes
[x] No
```
> refactor: clear unused lifecycle hooks

- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #4212
```
[ ] Yes
[x] No
```
> docs: add missing API for tree and tree-select

- components/i18n/languages/de_DE.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18n translations added and updated (de_DE)
```
Console warning "Missing translations for "Text" in language "de".You can use 
NzI18nService.setLocale" as a temporary fix. Welcome to submit a pull request to help us optimize the translations!"
Translations added and updated
```
[ ] Yes
[x] No
```
> Update and add translations for de_DE

- README-zh_CN.md
- README.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
https://github.com/NG-ZORRO/ng-zorro-antd/issues/1142#issuecomment-536197716
> docs: update ng-zorro-antd users

- components/select/demo/default-value.md
- components/select/demo/default-value.ts
- components/select/demo/hide-selected.md
- components/select/demo/hide-selected.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/nz-option-container.component.html
- components/select/nz-option.component.ts
- components/select/nz-option.pipe.ts
close #3672 close #4000
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:select): support default value not in the option list

- docs/animations.en-US.md
- docs/animations.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update animations docs

- components/select/nz-select-top-control.component.html
- components/select/nz-select-top-control.component.ts
- components/select/nz-select.component.ts
- components/select/nz-select.service.ts
close #3855
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select dropdown position error

- components/select/nz-select.component.html
- components/select/nz-select.component.spec.ts
- components/select/nz-select.component.ts
close #3991 close #3757 close #3708
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select focus & blur & autoFocus event

- components/select/nz-option-container.component.ts
close #3777
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select scroll bottom not emit with search

- components/tabs/nz-tabset.component.ts
- components/typography/nz-text-copy.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(module:typography, tabs): make the `destroy$` complete when destroy

- components/table/demo/break-word.md
- components/table/demo/break-word.ts
- components/table/demo/dynamic-settings.md
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/nz-td.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:table): support td break-word display

- components/table/demo/custom-filter-panel.ts
- components/table/nz-th.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:table): support extra panel with nz-th-extra selector

- components/table/nz-table.component.ts
close #4253
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table fixed style when nzData change

- components/cascader/demo/custom-template.md
- components/cascader/demo/custom-template.ts
- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
- components/cascader/nz-cascader-definitions.ts
- components/cascader/nz-cascader-li.component.html
- components/cascader/nz-cascader-li.component.ts
- components/cascader/nz-cascader-utils.ts
- components/cascader/nz-cascader.component.html
- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.module.ts
- components/cascader/nz-cascader.service.ts
- components/cascader/nz-cascader.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:cascader): support option render template

- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/nz-tree-select.component.html
- components/tree-select/nz-tree-select.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4120
```
[ ] Yes
[x] No
```
> feat(module:tree-select): support `nzCheckStrictly` property

- components/tag/demo/basic.md
- components/tag/demo/basic.ts
- components/tag/demo/control.md
- components/tag/demo/module
- components/tag/doc/index.en-US.md
- components/tag/doc/index.zh-CN.md
- components/tag/nz-tag.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4244
```
[ ] Yes
[x] No
```
> fix(module:tag): nzNoAnimation not working

- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): not emit changes when retype same value while open

- components/pagination/nz-pagination.component.html
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4038
```
[ ] Yes
[x] No
```
> fix(module:pagination): add space between page size and slash

- components/core/overlay/overlay-position.ts
- components/mention/nz-mention.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4260
```
[ ] Yes
[x] No
```
> feat(module:mention): support for adaptive boundary

- components/tooltip/base/nz-tooltip-base.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip): fix properties updated before origin is set

- scripts/site/_site/doc/app/app.component.html
- scripts/site/_site/doc/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add ng-china-2019 link

- components/code-editor/nz-code-editor.component.ts
- components/code-editor/nz-code-editor.definitions.ts
- components/code-editor/nz-code-editor.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix type definitions
```
```
[x] Yes
[ ] No
```
> chore(module:editor): fix types

- components/core/tree/nz-tree-base-node.ts
close #4037
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: tree): update when property isLeaf is changed

- components/core/tree/nz-tree-base.service.ts
close #3970 
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3970 
```
[ ] Yes
[x] No
```
> fix(module: tree): fix nzHideUnMatched bug

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.4.0): release 8.4.0

- components/select/demo/frontend-search.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> typo: font-end --> front-end

- components/table/nz-table.component.html
- components/table/nz-table.spec.ts
- components/table/nz-th.spec.ts
close #4312
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table nzWidth bug without the first column

- docs/global-config.en-US.md
- docs/global-config.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add template providing cn

- components/message/doc/index.en-US.md
- components/message/doc/index.zh-CN.md
- components/message/nz-message-base.service.ts
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:message,notification): use global configuration service

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.4.1): release 8.4.1

- components/code-editor/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:code-editor): fix component type

- components/calendar/nz-calendar.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:calendar): change expected class name

- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
- components/code-editor/nz-code-editor.definitions.ts
- components/code-editor/nz-code-editor.service.ts
- components/code-editor/style/entry.less
- components/core/config/config.ts
- docs/global-config.en-US.md
- docs/global-config.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:monaco-editor): support static loading

- components/modal/nz-modal.service.ts
- components/modal/nz-modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4344
```
[ ] Yes
[x] No
```
> fix(module:modal): `nzMaskClosable` not working in the confirm mode

- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/nz-table.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): support nzWidthConfig null undefined value

- components/mention/nz-mention.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4281 
```
[ ] Yes
[x] No
```
> fix(module:mention): unable to select on mobile device

- components/tooltip/base/nz-tooltip-base.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip): fix not undefined value not updated

- components/auto-complete/demo/certain-category.ts
- components/auto-complete/demo/non-case-sensitive.ts
- components/auto-complete/demo/options.ts
- components/auto-complete/demo/uncertain-category.ts
- components/auto-complete/nz-autocomplete-option.component.ts
- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.component.html
- components/auto-complete/nz-autocomplete.component.ts
- components/auto-complete/nz-autocomplete.spec.ts
- components/core/types/compare-with.ts
- components/core/types/public-api.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4362
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): default value not selected

- components/core/config/config.ts
- components/page-header/demo/actions.md
- components/page-header/demo/breadcrumb.md
- components/page-header/demo/content.md
- components/page-header/demo/ghost.md
- components/page-header/demo/ghost.ts
- components/page-header/demo/responsive.md
- components/page-header/doc/index.en-US.md
- components/page-header/doc/index.zh-CN.md
- components/page-header/nz-page-header.component.ts
- components/page-header/nz-page-header.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
ref  #4303
> feat(module:page-header): add `nzGhost` property

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.5.0): release 8.5.0

- README-zh_CN.md
- README.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- scripts/site/_site/doc/app/app.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update users

- components/tooltip/base/nz-tooltip-base.directive.ts
close #4417
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip): fix hiding when hover popover

- components/tree-select/nz-tree-select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4422
```
[ ] Yes
[x] No
```
> fix(module:tree-select): click label behavior is incorrect in strict mode

- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
- components/code-editor/nz-code-editor.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:code-editor): fix config

- components/drawer/nz-drawer.component.html
- components/drawer/nz-drawer.spec.ts
- components/drawer/style/drawer.less
close #4354
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #4354
```
[ ] Yes
[x] No
```
> fix(module:drawer): content overflow when placement is top or bottom

- components/core/util/check.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> add type guard for isNotNil

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.5.1): release 8.5.1

- components/calendar/nz-calendar.component.ts
- components/calendar/nz-calendar.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> chore(module:calendar): delete deprecated input nzCard

- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
- components/icon/nz-icon.directive.ts
- components/icon/nz-icon.service.ts
- components/icon/nz-icon.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: deprecation: remove old API
```
```
[x] Yes
[ ] No
```
* Old usage like `anticon-xxx` is removed.
* Auto correction of misspelling is removed.
* Inputs without `nz` prefix are removed.
> chore(module:icon): remove old api

- scripts/site/_site/doc/app/app.module.ts
- scripts/site/_site/doc/app/share/share.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix docs size

- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
The link jumps to the documentation for React Ant Design project(zh_cn).
The link now jumps to the documentation for Angular Ant Design project(en).
```
[ ] Yes
[x] No
```
[Related pr](https://github.com/NG-ZORRO/ng-zorro-antd/pull/4445)
> docs: fix icon link

- components/code-editor/nz-code-editor.component.ts
```
[x] Bugfix
[ ] Feature
```
wrong initialization with diff mode
```
[ ] Yes
[x] No
```
> fix(module: code-editor): fix wrong initialization with diff mode

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/doc/app/app.component.html
- scripts/site/_site/doc/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.5.2): release 8.5.2

- components/core/time/candy-date.ts
- components/date-picker/lib/popups/inner-popup.component.html
- components/date-picker/lib/popups/inner-popup.component.ts
- components/date-picker/nz-date-picker.component.spec.ts
- components/date-picker/standard-types.ts
Close #4454
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): select date but nzDefaultOpenValue not work

- .github/auto_assign.yml
- .github/nz-boot.yml
- README-zh_CN.md
- README.md
- docs/getting-started.en-US.md
- docs/introduce.en-US.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: update contributor assign

- .github/auto_assign.yml
- .github/nz-boot.yml
- components/carousel/nz-carousel.spec.ts
- components/core/types/size.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: change maintainer's username

- components/result/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Greek small letter `theta` θ(U+03B8) => Latin small letter `barred` ɵ(U+0275)
> refactor: rename private theta APIs

- scripts/release/release-site.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: remove the old builds for the site

- components/layout/doc/index.en-US.md
close #4510
```
[ ] Bugfix
[ ] Feature
```
Incorrect documentation
Issue Number: #4510
Correct documentation
```
[ ] Yes
[x] No
```
> docs(module:layout): update breakpoint width

- components/core/util/is-promise.ts
- components/modal/nz-modal.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:core): add isPromise generic

- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
- components/notification/nz-notification.component.html
- components/notification/nz-notification.definitions.ts
- components/notification/nz-notification.module.ts
- components/notification/nz-notification.spec.ts
close #4494
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4494
```
[ ] Yes
[x] No
```
> feat(module:notification): add close icon prop

- angular.json
- components/empty/nz-empty.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix a test broke by some upgraded dependency
```
```
[ ] Yes
[x] No
```
If users don't write CSS like
```css
nz-embed-empty + custom-empty-component {}
```
then it will be fine.
> test: fix broken test

- .circleci/config.yml
- components/karma.conf.js
- integration/angular-cli/package.json
- integration/rollup/package.json
- integration/webpack/package.json
- package.json
- scripts/gulp/util/task-helpers.ts
- setup-shared-libs.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: add circleci

- .circleci/config.yml
- package.json
- setup-shared-libs.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: fix coverage

- .gitignore
- .travis.yml
- README-zh_CN.md
- README.md
- azure-pipelines.yml
- components/karma.conf.js
- package.json
- scripts/gulp/tasks/site.ts
- scripts/surge.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: azure-ci rename

- components/auto-complete/demo/basic.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:autocomplete): fix basic demo

- README-zh_CN.md
- README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix development instructions

- bundlesize.config.json
- components/table/nz-table.component.ts
close #4593
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table data type

- components/table/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #4610 
```
[ ] Yes
[X] No
```
I've only added translations for en-US and the zh-CN needs to be added. @vthinkxie
> docs(module:table): document sort properties

- components/progress/doc/index.en-US.md
- components/progress/doc/index.zh-CN.md
- components/progress/nz-progress.component.html
- components/progress/nz-progress.definitions.ts
- components/progress/nz-progress.module.ts
- components/progress/nz-progress.spec.ts
close #4596
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:progress): support TemplateRef for nzFormat

- components/empty/nz-embed-empty.component.ts
- components/empty/nz-empty.service.ts
- components/empty/nz-empty.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: remove an injection token that has been deprecated in v8
```
```
[ ] Yes
[ ] No
```
> chore(module:empty): remove injection token

- components/drawer/nz-drawer.component.html
- components/drawer/nz-drawer.component.ts
- components/drawer/nz-drawer.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4224
```
[ ] Yes
[x] No
```
> fix(module:drawer): disable transition animation when placement change

- components/table/nz-th.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): `nzFilters` can is not null

- angular.json
- components/progress/demo/step.md
- components/progress/demo/step.ts
- components/progress/doc/index.en-US.md
- components/progress/doc/index.zh-CN.md
- components/progress/nz-progress.component.html
- components/progress/nz-progress.component.ts
- components/progress/nz-progress.definitions.ts
- components/progress/nz-progress.spec.ts
- components/progress/style/index.less
- components/style/themes/default.less
close #4635
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:progress): support steps

- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
- components/resizable/doc/index.en-US.md
- components/resizable/doc/index.zh-CN.md
- package.json
- scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number:  #4656
```
[ ] Yes
[x] No
```
> docs(module:resizable): add Stackblitz config

- angular.json
- components/cascader/nz-cascader.component.html
- components/cascader/nz-cascader.component.ts
- components/cascader/nz-cascader.service.ts
- components/core/overlay/overlay-position.ts
close #4562
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4562
```
[ ] Yes
[ ] No
```
> fix(module:cascader): fix not showing empty when there's no options

- .github/nz-boot.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: add the pull request preview config

- .github/nz-boot.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: fix bot config

- components/auto-complete/nz-autocomplete-trigger.directive.ts
- components/auto-complete/nz-autocomplete.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4333
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): close the panel when tapping scrollbar on Windows

- components/layout/demo/custom-trigger.ts
- components/layout/demo/responsive.ts
- components/layout/demo/side.ts
- components/layout/demo/top-side.ts
- components/layout/sider.component.ts
- components/menu/demo/vertical.ts
- components/menu/menu.directive.ts
- components/menu/menu.spec.ts
- components/menu/submenu.component.ts
close #4680
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:menu): auto nzInlineCollapsed when sider collapsed

- components/layout/sider.component.ts
- components/menu/demo/inline-collapsed.ts
- components/menu/menu.directive.ts
- components/menu/submenu.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:layout): fix responsive sider not work

- schematics/ng-update/test-cases/config.ts
- schematics/ng-update/test-cases/v9/deprecated-class-dropdown.spec.ts
- schematics/ng-update/test-cases/v9/deprecated-component-dropdown.spec.ts
- schematics/ng-update/test-cases/v9/deprecated-component-tooltip-like.spec.ts
- schematics/ng-update/test-cases/v9/input-names-calendar.spec.ts
- schematics/ng-update/test-cases/v9/input-names-icon.spec.ts
- schematics/ng-update/test-cases/v9/input-names-tooltip-like.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module:schematics): fix test

- schematics/ng-add/setup-project/register-locale.ts
- schematics/utils/build-component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update the @angular/cdk APIs

- tslint.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: add linebreak-style rule

- components/core/util/text-measure.ts
- components/typography/demo/module
- components/typography/demo/suffix.md
- components/typography/demo/suffix.ts
- components/typography/doc/index.en-US.md
- components/typography/doc/index.zh-CN.md
- components/typography/nz-typography.component.html
- components/typography/nz-typography.component.ts
- components/typography/nz-typography.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4620
```
[ ] Yes
[x] No
```
> feat(module:typography): support `nzSuffix` property

- components/cascader/cascader.component.ts
- components/cascader/demo/basic.ts
- components/cascader/demo/change-on-function.ts
- components/cascader/demo/change-on-select.ts
- components/cascader/demo/custom-field-names.ts
- components/cascader/demo/custom-render.ts
- components/cascader/demo/custom-template.ts
- components/cascader/demo/default-value-and-asyn-options.ts
- components/cascader/demo/default-value-and-lazyload.ts
- components/cascader/demo/default-value.ts
- components/cascader/demo/disabled.ts
- components/cascader/demo/hover.ts
- components/cascader/demo/lazy.ts
- components/cascader/demo/modal.ts
- components/cascader/demo/reactive-form.ts
- components/cascader/demo/search.ts
- components/cascader/demo/trigger-action.ts
- components/cascader/demo/trigger.ts
Patch #4841
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix dark mode cascader

- components/date-picker/abstract-picker.component.html
- components/date-picker/abstract-picker.component.ts
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/lib/abstract-table.ts
- components/date-picker/lib/year-table.component.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/year-picker.component.spec.ts
Close #2020
Close #1614 
Close #4148
- 新增 [nzDefaultPickerValue]
- 新增 [nzSeparator]
- overlay 修改调用方式，减少一层DOM结构
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:date-picker): add some inputs

- angular.json
- ngsw-config.json
- scripts/gulp/tasks/site.ts
- scripts/site/_site/doc/app/app.module.ts
- scripts/site/_site/doc/app/app.service.ts
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.html
- scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
- scripts/site/_site/doc/app/share/nz-highlight/nz-highlight.component.ts
- scripts/site/_site/doc/environments/environment.pre-prod.ts
- scripts/site/_site/doc/environments/environment.ts
- scripts/site/generate-site.js
- scripts/site/template/code-box.template.html
- scripts/site/template/demo-component.template.ts
- scripts/site/utils/generate-demo-code-files.js
- scripts/site/utils/generate-demo.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: use lazyload to loading demo code

- components/affix/affix.component.ts
- components/affix/affix.module.ts
- components/affix/affix.spec.ts
- components/affix/demo/basic.ts
- components/affix/nz-affix.component.html
- components/affix/respond-events.ts
- components/affix/utils.ts
- components/cascader/cascader.component.ts
- components/pagination/pagination.component.ts
- components/popconfirm/popconfirm.ts
- components/tooltip/base.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:affix): refactor

- components/back-top/back-top.component.ts
- components/back-top/back-top.module.ts
- components/back-top/back-top.spec.ts
- components/back-top/nz-back-top.component.html
- components/back-top/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:back-top): refactor

- components/breadcrumb/style/patch.less
close #4855
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:breadcrumb): fix breadcrumb link style

- components/grid/demo/gutter.ts
- components/grid/demo/module
- components/grid/demo/playground.ts
- components/grid/row.directive.ts
- components/typography/text-copy.component.ts
- components/typography/text-edit.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:grid): fix grid responsive bug

- components/empty/demo/config.ts
- components/select/option-container.component.ts
- components/select/select.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select empty status

- components/form/demo/validate-reactive.md
- components/form/form-control.component.ts
- components/form/form-control.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4525 
```
[ ] Yes
[x] No
```
> feat(module:form): reactive form support warning status

- components/date-picker/demo/disabled-date.ts
- components/date-picker/demo/format.ts
```
[ ] Bugfix
[ ] Feature
[*] Refactoring (no functional changes, no api changes)
```
Displays 'Select date' text on nz-month-picker and nz-year-picker components.
Displays the correct text on nz-month-picker and nz-year-picker components.
```
[ ] Yes
[*] No
```
> docs(module:date-picker): 2 missing placeholders in democode

- components/table/src/table-data.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix nzTotal in frontend pagination false

- components/pagination/doc/index.en-US.md
- components/pagination/doc/index.zh-CN.md
- components/pagination/pagination.component.ts
- components/pagination/pagination.spec.ts
Upstream https://github.com/ant-design/ant-design/pull/21959
Pending #4856 
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:pagination): add auto resize

- components/time-picker/time-picker-panel.component.ts
- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
- package.json
Fixes #4943
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:time-picker): ngModelChange not work

- .gitignore
- azure-pipelines.yml
- build-config.js
- components/table/src/table-data.service.ts
- components/table/src/table/table.component.ts
- integration/angular-cli/package.json
- integration/angular-cli/src/app/app.module.ts
- integration/rollup/src/app/app.module.ts
- integration/webpack/src/app/app.module.ts
- package.json
- scripts/build-config.ts
- scripts/gulp/tasks/library.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table no data

- components/list/list-item-meta-cell.ts
close #4912
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4912
```
[ ] Yes
[x] No
```
> fix(module:list): fix the avatar part old API

- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1996 #4765 
1. Will search in a case insensitive manner
2. Will highlight in a case insensitive manner
```
[ ] Yes
[X] No
```
> fix(module:tree): fix search case sensitivity

- components/auto-complete/autocomplete-trigger.directive.ts
- components/drawer/drawer.component.ts
- components/dropdown/context-menu.service.ts
- components/ng-zorro-antd.module.ts
- components/pagination/pagination-default.component.ts
- components/pagination/pagination-simple.component.ts
- components/pagination/pagination.component.ts
- components/pagination/pagination.spec.ts
- components/pagination/style/entry.less
- components/pagination/style/patch.less
- components/table/src/addon/filter.component.ts
- components/table/src/cell/td-addon.component.ts
- components/table/src/cell/th-addon.component.ts
- components/table/src/table.module.ts
- components/table/src/table/table.component.ts
- components/table/src/testing/table.spec.ts
- docs/contributing.en-US.md
- docs/contributing.zh-CN.md
- docs/faq.en-US.md
- docs/faq.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- scripts/site/_site/doc/polyfills.ts
- scripts/site/_site/doc/theme.less
- scripts/site/_site/doc/zone-flags.ts
- scripts/site/template/example-split.template.html
- scripts/site/utils/marked.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix 4.1.0 style error

- components/modal/demo/service.md
- components/modal/demo/service.ts
- components/modal/modal-types.ts
close #3111
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #3111
```
[ ] Yes
[x] No
```
> docs(module:modal): add template context usage

- components/modal/modal-footer.directive.spec.ts
- components/modal/modal.component.ts
close #4948
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4948
```
[ ] Yes
[x] No
```
> fix(module:modal): `nzModalFooter` not work when the modal open on init

- components/core/animation/collapse.ts
- components/package.json
- components/tree/nz-tree-indent.component.ts
- components/tree/nz-tree-node.component.ts
- components/tree/nz-tree.component.ts
- components/tree/nz-tree.spec.ts
- components/tree/style/patch.less
- docs/introduce.zh-CN.md
- scripts/site/_site/doc/index.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tree): fix tree animation

- components/time-picker/time-picker-panel.component.spec.ts
- components/time-picker/time-picker-panel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:time-picker): scroll to wrong position in datepicker

- components/code-editor/typings.ts
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:code-editor): upgrade monaco to 0.20.0 and update interfaces

- components/core/config/config.service.ts
- components/core/time/candy-date.ts
- components/form/demo/layout.ts
- components/slider/handle.component.ts
- components/time-picker/time-picker-panel.component.ts
- components/tree/demo/dynamic.ts
- components/typography/text-edit.component.ts
- schematics/ng-add/setup-project/register-locale.ts
- schematics/ng-add/setup-project/theming.ts
- schematics/utils/build-component.ts
- schematics/utils/ng-update/elements.ts
- schematics/utils/package-config.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: add optional chaining and nullish coalescing

- components/components.less
- components/core/config/config.ts
- components/space/demo/basic.md
- components/space/demo/basic.ts
- components/space/demo/customize.md
- components/space/demo/customize.ts
- components/space/demo/module
- components/space/demo/size.md
- components/space/demo/size.ts
- components/space/demo/vertical.md
- components/space/demo/vertical.ts
- components/space/doc/index.en-US.md
- components/space/doc/index.zh-CN.md
- components/space/index.ts
- components/space/package.json
- components/space/public-api.ts
- components/space/space-item.component.ts
- components/space/space.component.spec.ts
- components/space/space.component.ts
- components/space/space.module.ts
- components/space/style/entry.less
- components/space/style/index.less
- components/space/style/patch.less
- components/space/types.ts
close #4913
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4913
```
[ ] Yes
[x] No
```
> feat(module:space): add new component

- components/page-header/doc/index.en-US.md
- components/page-header/doc/index.zh-CN.md
- components/page-header/page-header.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #4945
```
[ ] Yes
[x] No
```
> fix(module:page-header): location inject error

- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:modal): fix close button style

- components/ng-zorro-antd.compact.less
- components/ng-zorro-antd.dark.less
- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
- scripts/build/compile-styles.ts
close #5007
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5007
```
[ ] Yes
[x] No
```
> fix: add theme bundle files

- package.json
- schematics/ng-update/data/input-names.ts
- schematics/ng-update/data/output-names.ts
- schematics/ng-update/test-cases/v9/deprecated-class-dropdown.spec.ts
- schematics/ng-update/test-cases/v9/deprecated-component-dropdown.spec.ts
- schematics/ng-update/test-cases/v9/deprecated-component-tooltip-like.spec.ts
- schematics/ng-update/test-cases/v9/input-names-calendar.spec.ts
- schematics/ng-update/test-cases/v9/input-names-icon.spec.ts
- schematics/ng-update/test-cases/v9/input-names-tree-like.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add v9 migration rules for tree

- components/slider/handle.component.ts
```
[x] Bugfix, a style bug fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: fix handle transform in vertical mode

- components/date-picker/date-picker.component.html
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/inner-popup.component.ts
- components/time-picker/time-picker-panel.component.spec.ts
- components/time-picker/time-picker-panel.component.ts
- components/time-picker/time-picker.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:date-picker): improve interaction again

- components/button/button.component.ts
- components/button/button.spec.ts
close #4955
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:button): fix icon only style

- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v9/deprecated-component-form.spec.ts
- schematics/ng-update/test-cases/v9/deprecated-injection-tokens.spec.ts
- schematics/ng-update/upgrade-rules/checks/calendar-input-rule.ts
- schematics/ng-update/upgrade-rules/checks/form-template-rule.ts
- schematics/ng-update/upgrade-rules/checks/injection-token-rule.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(schematics): add v9 migration rules for form

- components/core/index.ts
- components/core/package.json
- components/core/public-api.ts
- components/tree-select/demo/async.ts
- components/tree/demo/basic-controlled.ts
- components/tree/demo/basic.ts
- components/tree/demo/directory.ts
- components/tree/demo/draggable-confirm.ts
- components/tree/demo/draggable.ts
- components/tree/demo/dynamic.ts
- components/tree/demo/line.ts
- components/tree/demo/search.ts
- components/tree/public-api.ts
- docs/animations.en-US.md
- docs/animations.zh-CN.md
- docs/global-config.en-US.md
- docs/global-config.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
breaking on v10
```
[ ] Yes
[x] No
```
> chore: add the core entry port compatibility

- components/core/config/config.ts
- components/form/demo/auto-tips.md
- components/form/demo/auto-tips.ts
- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/form-control.component.ts
- components/form/form-control.spec.ts
- components/form/form.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:form): modify nzTipOptions to nzAutoTips

- components/select/select.component.ts
- components/select/select.spec.ts
Fixes #5011
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): wrong sort in group option

- components/select/option-container.component.ts
- components/select/style/patch.less
close #5047
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5047
```
[ ] Yes
[x] No
```
> fix(module:select): options overflow content cannot be hidden

- components/core/transition-patch/transition-patch.directive.ts
- components/select/option-container.component.ts
- components/select/select.component.ts
- components/select/select.spec.ts
- components/select/style/patch.less
- components/spin/spin.component.ts
- docs/faq.zh-CN.md
close #5058
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix nzDropdownMatchSelectWidth not work

- components/tooltip/base.ts
- components/tooltip/tooltip.spec.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/NG-ZORRO/ng-zorro-antd/issues/5043
Issue Number: 5043
It can be programmatically open and close multiple times
```
[ ] Yes
[x] No
```
> fix(module:popover): change visible correctly

- components/button/button.component.ts
close #5026
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:button): fix button type definition

- components/core/config/config.ts
- components/date-picker/date-picker.component.html
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.module.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/picker.component.ts
- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
- components/time-picker/time-picker.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module: date-picker, time-picker): support custom suffix icon

- components/date-picker/date-range-popup.component.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/picker.component.ts
- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal.module.ts
- components/select/select.component.ts
- components/skeleton/skeleton-element.component.ts
- components/skeleton/skeleton.spec.ts
close #5088
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: backward-compatible with the previous rendering engine

- components/menu/menu-item.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:menu): fix menu matchRouter not work

- components/core/config/config.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select-arrow.component.ts
- components/select/select.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:select): support global config nzSuffixIcon

- components/tooltip/base.ts
close #5087
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tooltip): fix title not updated to component

- components/time-picker/time-picker.component.ts
Fixes #5100
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:time-picker): allow undefined or null input

- components/modal/modal-config.ts
- components/modal/modal-container.ts
- components/modal/modal.service.ts
close #5093
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5093
```
[ ] Yes
[x] No
```
> fix(module:modal): `NoopAnimations` do not work with modal mask

- components/page-header/page-header.component.ts
- components/page-header/style/index.less
ref #5018
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(module:page-header): sync ant-design v4.1.4

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
Fixes #5118
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): set formControl disabled not work

- README-zh_CN.md
- README.md
- components/core/transition-patch/transition-patch.directive.ts
- components/select/option-container.component.ts
- components/select/select-search.component.ts
- components/select/select.module.ts
close #5110
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix ie11 select search input

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/option-container.component.ts
- components/select/select.component.ts
close #5112
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:select): support option height and opiton overflow size

- components/table/src/table-data.service.ts
close #5113
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): remove table nzQueryParams debounceTime

- components/space/space.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:space): fix config name

- components/notification/demo/placement.ts
- components/notification/notification-container.component.ts
- components/notification/typings.ts
close #5135
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:notification): fix global config nzPlacement not working

- components/form/demo/auto-tips.ts
- components/form/form-control.component.ts
- components/form/form-control.spec.ts
close #5129
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:form): the setStatus needs to call again on tips changes

- README-zh_CN.md
- README.md
- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add fossa scan result

- components/progress/progress.component.ts
close #5130
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:progress): fix nzFormat not shown status is exception

- components/descriptions/descriptions-item.component.ts
- components/descriptions/descriptions.component.ts
close #5127
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:description): fix description not accept TemplateRef

- components/select/demo/big-data.ts
- components/select/demo/options.md
- components/select/demo/options.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
- components/select/select.spec.ts
- components/select/select.types.ts
close #5106
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:select): support input nzOptions in select

- components/menu/submenu.component.ts
close #4837
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:menu): fix submenu scrollable

- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:tree): add tips for the order of property settings

- components/auto-complete/autocomplete-trigger.directive.ts
- components/auto-complete/autocomplete.module.ts
- components/auto-complete/autocomplete.spec.ts
- components/input/input-group.component.ts
- components/input/input.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): dropdown position error with group-input

- package.json
- scripts/gulp/util/task-helpers.ts
close #4709
close #5150
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix test:watch on Windows

- components/modal/modal-confirm-container.component.ts
- components/modal/modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5172
```
[ ] Yes
[x] No
```
> fix(module:modal): rollback to component types can be the content of confirm-mode

- package.json
- schematics/ng-update/index.ts
- schematics/ng-update/upgrade-data.ts
- schematics/ng-update/upgrade-rules/checks/calendar-input-rule.ts
- schematics/ng-update/upgrade-rules/checks/carousel-like-template-rule.ts
- schematics/ng-update/upgrade-rules/checks/dropdown-class-rule.ts
- schematics/ng-update/upgrade-rules/checks/dropdown-template-rule.ts
- schematics/ng-update/upgrade-rules/checks/form-template-rule.ts
- schematics/ng-update/upgrade-rules/checks/icon-template-rule.ts
- schematics/ng-update/upgrade-rules/checks/injection-token-rule.ts
- schematics/ng-update/upgrade-rules/checks/secondary-entry-points-rule.ts
- schematics/ng-update/upgrade-rules/checks/tooltip-like-template-rule.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: bump @angular/cdk from 9.0.0 to 9.2.2

- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:select): add `nzBorderless`

- components/anchor/style/entry.less
- components/auto-complete/style/entry.less
- components/calendar/style/entry.less
- components/card/style/entry.less
- components/cascader/style/entry.less
- components/code-editor/style/entry.less
- components/date-picker/style/entry.less
- components/dropdown/style/entry.less
- components/form/style/entry.less
- components/list/style/entry.less
- components/menu/style/entry.less
- components/modal/style/entry.less
- components/page-header/style/entry.less
- components/pagination/style/entry.less
- components/popconfirm/style/entry.less
- components/rate/style/entry.less
- components/select/style/entry.less
- components/slider/style/entry.less
- components/table/style/entry.less
- components/transfer/style/entry.less
- components/tree-select/style/entry.less
- components/upload/style/entry.less
close #5185
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:*): fix dependeny components' file import

- build-config.js
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5209
```
[ ] Yes
[x] No
```
> fix(module:schematics): invalid version will be added when the package already exists

- components/core/util/text-measure.ts
- components/typography/typography.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:typography): ellipsis line measurement error

- components/upload/upload-list.component.ts
- close #5201
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:upload): fix invalid preview image in picture card

- components/alert/alert.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:alert): `nzNoAnimation` not work with the alert component

- scripts/gulp/tasks/site.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #5189
```
[ ] Yes
[x] No
```
> build: fix `watch:site` task cannot work on Windows

- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix customize-theme typo

- components/timeline/timeline-item.component.ts
- components/timeline/timeline.component.ts
- components/timeline/timeline.service.ts
close #5230
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:timeline): fix timeline check error

- scripts/site/_site/doc/app/online-ide/online-ide.service.ts
close #5229
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix stackblitz error with @angular/cdk

- components/dropdown/dropdown.directive.ts
- components/dropdown/dropdown.module.ts
close #5186
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:dropdown): fix dropdown break SSR

- components/table/src/table-style.service.ts
close #5207
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table expand in multiple thead tr

- components/auto-complete/autocomplete-trigger.directive.ts
- components/core/config/config.ts
- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer-options.ts
- components/drawer/drawer.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5142
```
[ ] Yes
[x] No
```
> fix(module:auto-complete,drawer): cannot reopen when reuse route snapshots

- components/badge/badge.component.ts
- components/modal/modal-config.ts
- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-container.ts
- components/modal/modal-ref.ts
- components/modal/modal-types.ts
- components/modal/modal.component.ts
- components/modal/modal.service.ts
- components/modal/modal.spec.ts
- components/modal/utils.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5223
```
[ ] Yes
[x] No
```
> fix(module:modal): global config cannot work with service mode

- components/list/list.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5260
```
[ ] Yes
[x] No
```
> fix(module:list): empty content is always rendered

- components/slider/demo/reverse.md
- components/slider/demo/reverse.ts
- components/slider/doc/index.en-US.md
- components/slider/doc/index.zh-CN.md
- components/slider/handle.component.ts
- components/slider/slider.component.ts
- components/slider/slider.spec.ts
- components/slider/track.component.ts
close #4937
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:slider): add nzReverse property

- scripts/release/release-site.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: clean the site files

- docs/schematics.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix typo

- components/affix/affix.component.ts
- components/affix/affix.spec.ts
- components/anchor/anchor.component.ts
- components/core/util/convert.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(affix,anchor): wrong value is set when the initial value is non-number

- scripts/site/_site/doc/app/online-ide/online-ide.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix codesandbox tempalte

- components/modal/modal-confirm-container.component.ts
- components/modal/modal-footer.component.ts
- components/modal/modal.component.ts
- components/modal/utils.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5319
```
[ ] Yes
[x] No
```
> fix(module:modal): `nzAutofocus` doesn't work correctly
