NG-ZORRO/ng-zorro-antd

- components/upload/demo/avatar.ts
- components/upload/demo/basic.ts
- components/upload/demo/default-file-list.ts
- components/upload/demo/drag.ts
- components/upload/demo/file-list.ts
- components/upload/demo/picture-card.ts
- components/upload/demo/picture-style.ts
- components/upload/demo/preview-file.ts
- components/upload/demo/transform-file.ts
- components/upload/demo/upload-manually.ts
- components/upload/demo/upload-with-aliyun-oss.ts
- components/upload/doc/index.en-US.md
- components/upload/doc/index.zh-CN.md
- components/upload/interface.ts
- components/upload/upload-btn.component.ts
- components/upload/upload-list.component.ts
- components/upload/upload.component.ts
- components/upload/upload.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(module:upload):  rename public interfaces

- scripts/build/compile-styles.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: optimize less compilation performance

- components/badge/badge.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:badge): fix parent component use onpush nzCount not show

- components/message/message-container.component.ts
close #5301
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
This seems to be a bug of Angular. Investigating...
> fix(module:message): fix style not changed when property changes

- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
Fixes #5320
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): get input width before panel open

- scripts/site/_site/doc/app/share/contributors-list/contributors-list.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix Github API handling errors

- components/list/demo/grid.md
- components/list/demo/grid.ts
- components/list/demo/resposive.md
- components/list/demo/resposive.ts
- components/list/list.component.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update docs and fix demo

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: fix theme generate error

- components/page-header/page-header.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:page-header): add compact style

- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
…me: nzSelectedIndex => index
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:tags): fix nz-tabset nzSelectChange event object field name

- components/table/src/cell/cell-fixed.directive.ts
close #5238
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix ExpressionChangedAfterError of nzRight and nzLeft

- components/select/select.spec.ts
- components/table/src/table/thead.component.ts
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: 
```
Add a missing nz-select unit test for previous pull request #5264 ;
Remove duplicate words from deprecated message of `thead.component.ts`.
```
[ ] Yes
[x] No
```
> test(module:select): add test for selected class

- components/typography/demo/ellipsis.ts
- components/typography/demo/interactive.md
- components/typography/demo/suffix.ts
- components/typography/doc/index.en-US.md
- components/typography/doc/index.zh-CN.md
- components/typography/typography.component.ts
- components/typography/typography.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:typography): support `nzOnEllipsis` output

- components/notification/notification-container.component.ts
- components/notification/notification.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: 4787
```
[ ] Yes
[x] No
```
> fix(module:notification): fix issue 4787

- components/input/input.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:input): fix input missing attr disabled

- components/button/button.component.ts
- components/button/button.spec.ts
- package.json
close #5392
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:button): fix button init loading status

- components/select/demo/optgroup.ts
- components/select/select.component.ts
close #5276
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix group label search

- components/menu/menu-group.component.ts
close #5363
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:menu): fix menu group ng-template error

- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/cell/th-measure.directive.ts
close #5410
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table colspan & empty data style

- components/table/src/cell/th-selection.component.ts
close #5388
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix th nzChecked supersedes nzShowCheckbox

- components/select/select.component.ts
close #5381
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select autofocus behavior

- components/input-number/doc/index.en-US.md
- components/input-number/doc/index.zh-CN.md
- components/input-number/input-number.component.ts
close #5341
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:input-number): support inputmode

- components/radio/demo/radiogroup-more.ts
- components/radio/radio.component.ts
close #5285
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:radio): fix radio focus

- components/select/option-container.component.ts
- components/select/option-item.component.ts
close #5178
ref https://github.com/angular/components/issues/15838
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select nzCustomContent render

- components/input/input.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:input): support reactive form disabled

- components/form/demo/register.ts
- components/input/input.directive.ts
close #5137
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:input): fix reactive form disabled input-group style

- components/core/testing/componet-bed.ts
close #5426
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #5426
```
[ ] Yes
[x] No
```
> test: update the `createComponentBed` options type

- components/table/demo/expand-children.ts
close #5033
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:table): change table demo key

- components/dropdown/dropdown.directive.ts
close #5258
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:dropdown): fix dropdown disabled button

- components/select/select.component.ts
close #5220
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix tag mode wrong value with keydown

- components/table/src/table-data.service.ts
close #5262
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table sort default value change

- components/core/config/config.ts
- components/select/doc/index.en-US.md
- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/table/table.component.ts
close #5224
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:select): support nzBorderless in global config

- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-container.ts
- components/modal/modal.spec.ts
close #5376
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5376
```
[ ] Yes
[x] No
```
> fix(module:modal): modal will close when clicking the scrollbar

- components/table/demo/basic.ts
- components/table/demo/virtual.ts
- components/table/src/table/table.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
**Example**
```ts
interface Person {
key: string;
name: string;
age: number;
address: string;
}
@Component({
template: `
<nz-table #table [nzData]="listOfData">
<thead>
<tr>
<th>Name</th>
<th>Age</th>
<th>Address</th>
</tr>
</thead>
<tbody>
<tr *ngFor="let data of table.data">
<td>{{ data.name }}</td>
<td>{{ data.agr }}</td>
<td>{{ …
```
> feat(module:table): support the generic type of data

- components/modal/demo/service.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-container.ts
- components/modal/modal-ref.ts
- components/modal/modal.component.ts
- components/modal/modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:modal): some cases there is no changes detected

- components/grid/col.directive.ts
- components/grid/row.directive.ts
close #5435
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:grid): fix gutter zero

- azure-pipelines.yml
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- scripts/gulp/tasks/site.ts
参考：https://indepth.dev/how-to-automate-npm-package-publishing-with-azure-devops-2/
- 提交 release pr
- CI 成功后前往 azure pipe，点击下方进入 release
- Deploy：push 新分支到官网 repo（手动触发）
- Publish：发布到 npm（手动触发，需要 approve）
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: deploy and publish in azure

- components/core/tree/nz-tree-base.service.ts
- components/tree-select/tree-select.component.ts
- components/tree/tree.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5385 #5195 #5068 5068
```
[ ] Yes
[x] No
```
> fix(module: tree): fix nzCheckStrictly and selected keys bug

- components/table/src/table-style.service.ts
- components/table/src/table/table.component.ts
close #5370 close #5324 close #5318 close #5309 close #5167 close #5160
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table nzWidth not work with scroll

- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
close #5350
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5350
```
[ ] Yes
[x] No
```
> fix(module:drawer): don't prevent events when nzMask is false

- components/date-picker/date-picker.component.ts
- components/i18n/nz-i18n.interface.ts
- components/i18n/nz-i18n.service.spec.ts
Fixes #5444
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:i18n): some locales compile error

- components/date-picker/picker.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5284 
```
[ ] Yes
[x] No
```
> fix(module:datepicker): not open panel when input change

- components/modal/modal-container.ts
- components/modal/modal.service.ts
- components/modal/modal.spec.ts
close #5454
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5454
```
[ ] Yes
[x] No
```
> fix(module:modal): throw an error when autofocus on the confirm-mode

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.spec.ts
- components/popconfirm/popconfirm.ts
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/popover/popover.spec.ts
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5365
```
[ ] Yes
[x] No
```
> fix(module:tooltip): replace public api with more specific ones

- components/upload/upload.component.html
- close #5472
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:upload): fix  'uploadError' of undefined

- components/timeline/demo/position.md
- components/timeline/demo/position.ts
- components/timeline/doc/index.en-US.md
- components/timeline/doc/index.zh-CN.md
- components/timeline/public-api.ts
- components/timeline/timeline-item.component.ts
- components/timeline/timeline.component.ts
- components/timeline/timeline.spec.ts
- components/timeline/typings.ts
close #5470
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:timeline): support custom position

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.ts
- components/popover/demo/control.md
- components/popover/demo/control.ts
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5449
```
[ ] Yes
[x] No
```
> feat(module:tooltip): add more specific api (#5449)

- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/cell/cell-fixed.directive.ts
- components/table/src/cell/th-measure.directive.ts
- components/table/src/table-style.service.ts
- components/table/src/table/thead.component.ts
- components/table/src/table/tr.directive.ts
close #5509
close #5481 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table no data colSpan

- components/select/option-container.component.ts
close #5456
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix select scroll render buffer

- components/date-picker/inner-popup.component.ts
Fixes #5528
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): nzDateRender render incorrectly

- components/core/config/config.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:core): fix empty check

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer-ref.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.service.ts
- components/drawer/drawer.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5489
```
[ ] Yes
[x] No
```
> feat(module:drawer): support get component instance for content

- components/popconfirm/popconfirm.ts
- components/popover/popover.ts
- components/tooltip/tooltip.ts
close #1825
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip,*): enable cdk push

- components/modal/demo/service.md
- components/modal/demo/service.ts
- components/modal/modal-footer.component.ts
close #5506
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module: modal): support params and modelRef when footer is template

- .prettierrc
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> style: update .prettierrc

- components/drawer/demo/from-drawer.ts
- components/drawer/demo/service.ts
- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer-options.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
close #4618
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4618 
```
[ ] Yes
[x] No
```
> feat(module:drawer): add `nzFooter` property

- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/tab-add-button.component.ts
- components/tabs/tab-nav-bar.component.ts
- components/tabs/tab-nav-item.directive.ts
- components/tabs/tab-nav-operation.component.ts
- components/tabs/tab.component.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:tabs): add test cases

- components/breadcrumb/breadcrumb.component.ts
close #5613
close #5615
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:breadcrumb): fix auto-generated with lazy modules

- components/code-editor/code-editor.service.ts
- components/code-editor/typings.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:code-editor): init event never emit when using static loading

- components/tabs/style/patch.less
- components/tabs/tab-nav-operation.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tabs): fix dropdown style

- components/upload/doc/index.en-US.md
change type issue muse be use => must use
-  [X] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
-  [X] Tests for the changes have been added (for bug fixes / features)
-  [X] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Typo issue fixes on upload component documentation
```
[ ] Yes
[x] No …
```
> docs: type issue on upload component doc

- docs/customize-theme.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #5714 
```
[ ] Yes
[x] No
```
> docs: add missing code

- .github/workflows/sync-styles.yml
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
master[push] 时自动触发，也可以手动触发和指定版本。
> chore: add action to sync Ant Design styles

- components/tabs/style/patch.less
- components/tabs/tabset.component.ts
close #5696
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tabs): fix clickable area of tab-link

- scripts/site/_site/doc/app/components-overview/components-overview.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add autofocus for overview page search-input

- components/mention/mention.component.ts
- components/mention/nz-mention.spec.ts
close #5722
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5722
```
[ ] Yes
[x] No
```
> fix(module:mention): not emit `(nzOnSearchChange)` when value is empty

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/testing/util.ts
- components/date-picker/year-picker.component.spec.ts
Fixes #5562
```
[x] Bugfix
[ ] Feature
```
Issue Number:
```
[ ] Yes
[x] No
```
> fix(module:date-picker): open the panel wrongly in IE11

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/picker.component.ts
- components/date-picker/week-picker.component.spec.ts
- components/i18n/date-helper.service.spec.ts
Fixes #5327 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): modify date-fns week-year format

- components/select/doc/index.zh-CN.md
- components/select/select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5709 
```
[ ] Yes
[x] No
```
> fix(module:select): cursor abnormal in nz-select with nzDisabled

- components/button/button.spec.ts
- components/tabs/style/patch.less
close #5549, close #5543
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5543
```
[ ] Yes
[x] No
```
> fix(module:tabs): tab-link cannot be disabled

- components/tree-select/tree-select.component.ts
- components/tree-select/tree-select.spec.ts
close #5664
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5664
```
[ ] Yes
[x] No
```
> fix(module:tree-select): not clear search value when dropdown close

- components/tree-select/demo/virtual-scroll.md
- components/tree-select/demo/virtual-scroll.ts
- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/tree-select.component.ts
- components/tree/doc/index.en-US.md
- components/tree/doc/index.zh-CN.md
close #5589
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5589
```
[ ] Yes
[x] No
```
> feat(module:tree-select): support virtual scroll

- components/typography/demo/basic.ts
- components/typography/demo/text.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:typography): support keyboard and link types

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:drawer): support `[nzCloseIcon]`

- components/space/demo/align.md
- components/space/demo/align.ts
- components/space/doc/index.en-US.md
- components/space/doc/index.zh-CN.md
- components/space/public-api.ts
- components/space/space.component.spec.ts
- components/space/space.component.ts
- components/space/types.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:space): support `nzAlign`

- components/core/element-patch/element-patch.directive.ts
- components/core/element-patch/element-patch.spec.ts
close #5566
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:core): enhance nzElementRef

- components/tree-select/tree-select.component.ts
- components/tree-select/tree-select.spec.ts
close #5603
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5603
```
[ ] Yes
[x] No
```
> fix(module:tree-select): should be not clearable when disabled or unselected

- components/notification/notification-container.component.ts
- components/notification/typings.ts
- schematics/ng-update/data/class-names.ts
- schematics/ng-update/data/property-names.ts
- schematics/ng-update/test-cases/v10/notification-deprecated.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:notification): remove deprecated APIs for v10

- components/core/transition-patch/transition-patch.directive.ts
- components/divider/doc/index.en-US.md
- components/divider/doc/index.zh-CN.md
- components/input/demo/borderless.md
- components/input/demo/borderless.ts
- components/input/doc/index.en-US.md
- components/input/doc/index.zh-CN.md
- components/input/input.directive.ts
- package.json
- scripts/site/_site/doc/app/header/header.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:input): support borderless

- components/select/select.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): fix click arrow open

- components/date-picker/demo/presetted-ranges.ts
```
[ ] Bugfix
[ ] Feature
```
It's a bit confusing that there are 2 range variables but only one is being used.
Remove the unneeded range variable
```
[ ] Yes
[x] No
```
> docs(module:date-picker): remove unneeded variable

- components/core/tree/nz-tree-base-node.ts
- schematics/ng-update/data/property-names.ts
- schematics/ng-update/test-cases/v10/tree-deprecated.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:tree): remove deprecated APIs for v10

- components/form/form-item.component.ts
- components/grid/row.directive.ts
- schematics/ng-update/data/property-names.ts
- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v10/grid-deprecated.spec.ts
- schematics/ng-update/upgrade-rules/checks/grid-template-rule.ts
- schematics/utils/ng-update/elements.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:form,grid): remove deprecated APIs for v10 

- components/table/src/table/table-inner-scroll.component.ts
close #5405
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:table): fix scroll bar displays always even unnecessary

- components/table/demo/bordered.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/table/table.component.ts
- components/table/style/patch.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:table): support nzOuterBordered

- components/table/src/cell/th-addon.component.ts
- components/table/src/cell/th-selection.component.ts
- components/table/src/table/thead.component.ts
- components/table/src/testing/th.spec.ts
- components/table/src/testing/thead.spec.ts
- schematics/ng-update/data/class-names.ts
- schematics/ng-update/data/input-names.ts
- schematics/ng-update/data/output-names.ts
- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v10/table-deprecated.spec.ts
- schematics/ng-update/upgrade-rules/checks/grid-template-rule.ts
- schematics/ng-update/upgrade-rules/checks/table-template-rule.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:table): remove deprecated APIs for v10

- components/card/card.component.ts
- components/card/doc/index.en-US.md
- components/card/doc/index.zh-CN.md
- components/core/config/config.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:card): support nzBorderless

- components/divider/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
Fixed the typo in the docs
```
[ ] Yes
[x] No
```
> docs(module:divider): fix typo

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/demo/start-end.md
- components/date-picker/demo/start-end.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/picker.component.ts
Closes #3352
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:date-picker): add open() and close()

- components/message/typings.ts
- components/modal/demo/service.ts
- components/modal/doc/index.zh-CN.md
- components/modal/modal-container.ts
- components/modal/modal-footer.component.ts
- components/modal/modal-ref.ts
- components/modal/modal-types.ts
- components/modal/modal.component.ts
- components/modal/utils.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:modal): change deprecated APIs for v10

- components/badge/badge-sup.component.ts
- components/badge/badge.component.ts
- components/badge/badge.module.ts
- components/badge/badge.spec.ts
- components/badge/demo/change.ts
- components/badge/demo/colorful.ts
- components/badge/demo/module
- components/badge/demo/no-wrapper.md
- components/badge/demo/no-wrapper.ts
- components/badge/demo/ribbon.md
- components/badge/demo/ribbon.ts
- components/badge/doc/index.en-US.md
- components/badge/doc/index.zh-CN.md
- components/badge/ribbon.component.ts
- components/badge/style/entry.less
- components/badge/style/patch.less
- components/core/util/check.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:badge): add standalone mode

- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/demo/time.ts
- components/date-picker/range-picker.component.spec.ts
Fixes #5782
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): nzCalendarChange not work when clicking ok

- components/progress/progress.component.ts
- components/progress/progress.spec.ts
close #5585
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:progress): fix value not updated when is steps

- components/carousel/carousel.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:carousel): rename syncStrategy method and make-public

- components/popconfirm/doc/index.zh-CN.md
- components/tooltip/base.ts
- schematics/ng-update/data/input-names.ts
- schematics/ng-update/data/output-names.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:tooltip, popover, popconfirm): change deprecated APIs for v10

- README-zh_CN.md
- README.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- scripts/site/utils/marked.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add component library users

- azure-pipelines.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: fix build pipeline

- components/pipes/doc/index.en-US.md
- components/pipes/doc/index.zh-CN.md
- schematics/migration.json
- scripts/site/_site/doc/app/header/header.component.ts
- scripts/site/_site/doc/app/header/navigation.component.ts
- scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
- scripts/site/_site/doc/app/online-ide/online-ide.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update version and pipes

- CHANGELOG.md
- components/package.json
- schematics/ng-update/data/input-names.ts
- schematics/ng-update/test-cases/v9/secondary-entry-points.spec.ts
- schematics/ng-update/upgrade-rules/checks/secondary-entry-points-rule.ts
- schematics/ng-update/upgrade-rules/checks/table-template-rule.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(schematics): fix table rules

- components/date-picker/calendar-footer.component.ts
- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): today showing incorrectly

- angular.json
- package.json
- scripts/gulp/tasks/site.ts
- scripts/gulp/tasks/universal.ts
- scripts/prerender/sitemap.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: fix site build

- CHANGELOG.md
Fixes typo in Changelog.
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe: Fixes typo in Changelog.
```
```
[ ] Yes
[ ] No
```
> docs(changelog): Fixes missing closing backtick

- docs/migration-v10.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: correct Angular version

- components/upload/demo/picture-card.ts
- components/upload/upload-list.component.html
- close #5850
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:upload): fix upload list style of picture card type

- components/package.json
- docs/migration-v10.en-US.md
- docs/migration-v10.zh-CN.md
- package.json
- schematics/ng-update/data/input-names.ts
- schematics/ng-update/data/output-names.ts
- schematics/ng-update/data/property-names.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: bump @angular/cdk to 10.2.4

- components/breadcrumb/breadcrumb.component.ts
close #4751
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:breadcrumb): fix breadcrumbs not returned

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/year-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
Fixes #5562
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:date-picker,time-picker): open the panel wrongly in IE11

- docs/customize-theme.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
I have tried to use the same method to create themes but it lacked the last step to add the styles to the body. This should help new people to use this method.
> docs: show how to append theme style 

- ngsw-config.json
- package.json
- scripts/gulp/tasks/universal.ts
- scripts/prerender/ngsw-config.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: update ngsw-config.json

- components/table/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:table): improves documentation

- components/modal/modal-ref.ts
- components/modal/modal.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5321
After processing the component state, continue to throw an exception upward
```
[ ] Yes
[x] No
```
When Promise throws an exception, do you need to stop closing the modal? but will introduce a breaking change.
> fix(module:modal): modal's nzOnOk/nzOnCancel swallow Promise Rejection

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/inner-popup.component.ts
- components/date-picker/lib/month-table.component.ts
- components/date-picker/lib/year-table.component.ts
- components/date-picker/month-picker.component.spec.ts
Fixes #5633
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): years contain disabled date cannot select

- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- docs/schematics.en-US.md
- docs/schematics.zh-CN.md
- scripts/site/_site/doc/app/app.component.ts
- scripts/site/_site/doc/app/app.module.ts
- scripts/site/_site/doc/app/app.routing.module.ts
- scripts/site/_site/doc/app/header/github-button.component.ts
- scripts/site/_site/doc/app/header/header.component.ts
- scripts/site/_site/doc/app/header/navigation.component.ts
- scripts/site/_site/doc/app/share/codebox/codebox.component.html
- scripts/site/_site/doc/app/share/share.module.ts
- scripts/site/template/title.template.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: optimization site

- components/pagination/pagination-options.component.ts
- close #5668
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:pagination): fix shoule be only allowed number

- components/slider/slider.component.ts
- components/slider/slider.spec.ts
close #5699
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:slider): fix slider precision when step is decimal

- components/popconfirm/popconfirm.ts
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/demo/basic.ts
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
close #5713
```
[x] Bugfix
[ ] Feature
```
现在的行为跟 React 版本一致
```
[x] Yes
[ ] No
```
> fix(module:tooltip): fix mouse leave overlay not obey delaying

- README-zh_CN.md
- README.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
- docs/getting-started.en-US.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- docs/recommendation.en-US.md
- docs/recommendation.zh-CN.md
- scripts/prerender/ngsw-config.ts
- scripts/prerender/route-paths.txt
- scripts/site/_site/doc/app/footer/footer.component.ts
- scripts/site/_site/doc/app/share/contributors-list/contributors-list.component.ts
- scripts/site/_site/doc/style/highlight.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add pipes in prerender routers

- docs/introduce.zh-CN.md
- scripts/site/_site/doc/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: better LCP with prerender

- components/tooltip/base.ts
- components/tooltip/demo/basic.ts
！！！这一条 merge 的时候不要进入 changelog！！！
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip): fix tooltip trigger delay not get

- components/date-picker/date-picker.component.ts
- components/i18n/languages/ar_EG.ts
- components/i18n/languages/by_BY.ts
- components/i18n/languages/ca_ES.ts
- components/i18n/languages/cs_CZ.ts
- components/i18n/languages/de_DE.ts
- components/i18n/languages/default.ts
- components/i18n/languages/en_US.ts
- components/i18n/languages/fa_IR.ts
- components/i18n/languages/fi_FI.ts
- components/i18n/languages/fr_FR.ts
- components/i18n/languages/ga_IE.ts
- components/i18n/languages/gl_ES.ts
- components/i18n/languages/it_IT.ts
- components/i18n/languages/ja_JP.ts
- components/i18n/languages/kmr_IQ.ts
- components/i18n/languages/lt_LT.ts
- components/i18n/languages/nb_NO.ts
- components/i18n/languages/pl_PL.ts
- components/i18n/languages/pt_BR.ts
- components/i18n/languages/ru_RU.ts
- components/i18n/languages/th_TH.ts
- components/i18n/languages/tr_TR.ts
- components/i18n/languages/uk_UA.ts
- components/i18n/languages/zh_CN.ts
- components/i18n/languages/zh_HK.ts
- components/i18n/nz-i18n.interface.ts
- components/i18n/nz-i18n.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:core): sync i18n files

- README-zh_CN.md
- README.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update readme

- components/tabs/style/patch.less
close #5857
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tabs): link is not active on the whole tab

- components/select/select-search.component.ts
- components/select/select-top-control.component.ts
close #5645
close #4296
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): input search not work in IE11

- components/dropdown/demo/basic.ts
- components/menu/doc/index.en-US.md
- components/menu/doc/index.zh-CN.md
- components/menu/menu-item.directive.ts
- components/menu/menu.spec.ts
close #5881
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:menu): add danger style

- components/avatar/avatar.component.ts
- components/avatar/avatar.spec.ts
- components/avatar/demo/dynamic.ts
- components/avatar/demo/module
- components/avatar/doc/index.en-US.md
- components/avatar/doc/index.zh-CN.md
- components/core/config/config.ts
close #5883
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5883
```
[ ] Yes
[x] No
```
> feat(module:avatar): support for set gap

- components/typography/demo/ellipsis.ts
- components/typography/demo/text.ts
- components/typography/demo/title.ts
- components/typography/doc/index.en-US.md
- components/typography/doc/index.zh-CN.md
- components/typography/typography.component.ts
- components/typography/typography.spec.ts
close #5906
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5906
```
[ ] Yes
[x] No
```
> feat(module:typography): support success type

- components/cascader/cascader-li.component.ts
- components/cascader/cascader.component.ts
- components/cascader/cascader.spec.ts
- components/cascader/demo/basic.ts
- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
close #5885
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:cascader): support suffix icon & expand icon

- components/anchor/anchor.component.ts
- components/anchor/anchor.spec.ts
- components/back-top/back-top.component.ts
- components/back-top/doc/index.en-US.md
- components/back-top/doc/index.zh-CN.md
- components/core/services/scroll.spec.ts
- components/core/services/scroll.ts
- close #5887
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:back-top): add `nzDuration` property

- components/descriptions/demo/custom-size.ts
- components/descriptions/demo/module
- components/descriptions/descriptions.component.ts
- components/descriptions/doc/index.en-US.md
- components/descriptions/doc/index.zh-CN.md
fix(module:descriptions): fix header DOM structure
close #5855
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:descriptions): add extra property

- components/avatar/avatar-group.component.ts
- components/avatar/avatar.module.ts
- components/avatar/avatar.spec.ts
- components/avatar/demo/group.md
- components/avatar/demo/group.ts
- components/avatar/demo/module
- components/avatar/doc/index.en-US.md
- components/avatar/doc/index.zh-CN.md
close #5882
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5882
```
[ ] Yes
[x] No
```
> feat(module:avatar): add avatar group component

- components/core/config/config.ts
- components/typography/demo/interactive.ts
- components/typography/doc/index.en-US.md
- components/typography/doc/index.zh-CN.md
- components/typography/text-copy.component.ts
- components/typography/text-edit.component.ts
- components/typography/typography.component.ts
- components/typography/typography.module.ts
- components/typography/typography.spec.ts
close #5888
```
[ ] Bugfix
[x] Feature
```
Issue Number: #5888
```
[ ] Yes
[x] No
```
> feat(module:typography): support custom icons and tooltips

- components/core/color/color.ts
- components/core/color/index.ts
- components/core/color/package.json
- components/core/color/public-api.ts
- components/tag/tag.component.ts
- components/tooltip/base.ts
- components/tooltip/demo/color.md
- components/tooltip/demo/color.ts
- components/tooltip/demo/module
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
close #5884 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:tooltip): add nzTooltipColor

- components/form/form-control.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:form): explain status style not work with sync antd 4.7.2

- components/form/demo/auto-tips.md
- components/form/demo/auto-tips.ts
- components/form/form-control.component.ts
- components/form/form-control.spec.ts
close #5917
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:form): support a fallback locale for validation tips

- components/icon/doc/index.zh-CN.md
11
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:icon): fix API docs

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/demo/bordered.md
- components/date-picker/demo/bordered.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/inner-popup.component.ts
- components/date-picker/lib/abstract-table.ts
- components/date-picker/picker.component.ts
close #5680
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:date-picker): add `nzBorderless`

- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
`[nzOutBordered]`
`[nzOuterBordered]`
```
[ ] Yes
[x] No
```
>  fix(module:table): fix typo nzOuterBordered

- components/select/option-item.component.ts
- components/select/select-top-control.component.ts
close #5281
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:select): title not display

- components/list/demo/infinite-load.ts
- components/list/demo/module
close #4118
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #4118
```
[ ] Yes
[x] No
```
> docs(module:list): update the infinite load demo

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.ts
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/demo/placement.ts
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/tooltip/tooltip.ts
close #5733
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:tooltip): enable custom placements

- components/breadcrumb/style/patch.less
```
[x] Bugfix
[ ] Feature
```
close #5942 
```
[ ] Yes
[x] No
```
> fix(module:breadcrumb): patch last-child's style indule a is included

- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
close #5396
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5396
```
[ ] Yes
[x] No
```
> fix(module:tabs): `nzTabBarGutter` is not work in vertical position

- components/tabs/tab-nav-bar.component.ts
close #6009, close #4802, close #3999
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6009,  #4802,  #3999
```
[ ] Yes
[x] No
```
> fix(module:tabs): ink-bar does not render correctly in some cases

- components/typography/demo/ellipsis.ts
- components/typography/typography.component.ts
close #6057
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6057
```
[ ] Yes
[x] No
```
> fix(module:typography): ellipsis does not work with copy action

- components/tree-select/tree-select.component.ts
- components/tree-select/tree-select.spec.ts
close #6063
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tree-select): selector cannot focus

- CONTRIBUTING.md
- README-zh_CN.md
- README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update readme & discord

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
```
[ ] Bugfix
[x] Feature
```
close #5999 
```
[ ] Yes
[x] No
```
> feat(module:drawer): support nzVisible two-way binding

- components/core/config/config.ts
- components/pagination/doc/index.en-US.md
- components/pagination/doc/index.zh-CN.md
- components/pagination/pagination.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: resolve #6042 
```
[ ] Yes
[x] No
```
> feat(module:pagination): support Global Config

- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
close #6072 
```
[ ] Yes
[x] No
```
> docs(module:time-picker): update nzAddOn property

- components/graph/graph-node.directive.ts
- components/graph/graph-svg-container.component.ts
- components/graph/graph.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module: graph): remove detach to make sure contentChild can be rendered

- components/descriptions/descriptions.component.ts
close #6109 
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> fix(module:descriptions): fix DOM structure

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.service.ts
close #6070
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): clear wrong date input after closing panel

- components/steps/step.component.ts
- components/steps/steps.spec.ts
```
[ ] Bugfix
[x] Feature
```
close #5579 
```
[ ] Yes
[x] No
```
> feat(module:steps): step supports enable and disable

- components/upload/upload-list.component.html
- close #6095
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:upload): fix prevent trigger submit when click list button

- components/tag/demo/control.ts
```
[ ] Bugfix
[ ] Feature
```
close #6117 
```
[ ] Yes
[x] No
```
> docs(module:tag): replace nzAfterClose with nzOnClose

- components/core/time/candy-date.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module:date-picker): fix test in month comparison

- components/tree/tree-indent.component.ts
- components/tree/tree-node.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tree): fix indent line styles

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/demo/bordered.md
- components/date-picker/demo/date-render.md
- components/date-picker/demo/disabled-date.md
- components/date-picker/demo/disabled.md
- components/date-picker/demo/format.md
- components/date-picker/demo/module
- components/date-picker/demo/presetted-ranges.md
- components/date-picker/demo/size.md
- components/date-picker/demo/start-end.md
- components/date-picker/demo/switch.md
- components/date-picker/demo/switch.ts
- components/date-picker/demo/time.md
- components/date-picker/picker.component.ts
close #6052
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): display error in dynamic switching nzMode

- components/date-picker/lib/abstract-table.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): panel not update when changing to week

- components/button/demo/basic.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:button): Add missing description for text button

- scripts/gulp/util/task-helpers.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: fix type error

- components/mention/mention.component.ts
close NG-ZORRO#5995
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5995 
Mention suggestions will scroll automatically to keep focused item in the overlay view.
```
[ ] Yes
[x] No
```
> fix(module:mention): scroll to focus when arrow up or down

- components/descriptions/descriptions.component.ts
close #6151
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6151 
[nzColon]="false" is now working.
```
[ ] Yes
[x] No
```
> fix(module:description): fix label colon not working

- components/auto-complete/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
The desc in chinese make me confused, i can't find the slightly different in input element...
I find out the function until i read the source code..
Maybe it's my problem, or not..
```
[ ] Yes
[x] No
```
> docs(module:auto-complete): add details for docs desc

- components/upload/demo/picture-card.ts
- components/upload/style/index.less
- components/upload/upload-list.component.html
- components/upload/upload-list.component.ts
- components/upload/upload.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: sync upload component styles

- components/alert/alert.component.ts
- components/alert/style/index.less
- components/alert/style/rtl.less
- scripts/site/_site/doc/theme.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: sync ant design style

- components/tabs/tab-nav-bar.component.ts
- components/tabs/tabset.component.spec.ts
close #6139
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6139
```
[ ] Yes
[x] No
```
> fix(module:tabs): keyboard events in extra areas trigger navigation

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix changelog

- components/date-picker/calendar-footer.component.ts
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/range-picker.component.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/6146
```
[ ] Yes
[x] No
```
> feat(module:date-picker): add `nzShowNow`

- components/tree/tree-drop-indicator.component.ts
- components/tree/tree-node-title.component.ts
- components/tree/tree-node.component.ts
- components/tree/tree.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tree): fix tree styles

- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/picker.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:date-picker): active bar not work

- components/button/button.component.ts
fixes #6191, fixes #6187
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:button): only warn about deprecated value when used (#6193)

- components/dropdown/style/index.less
- components/image/style/index.less
- components/menu/submenu-title.component.ts
- components/modal/style/modal.less
- components/style/mixins/modal-mask.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: fix ant-design v4.9.3 styles

- components/modal/modal-container.ts
- components/modal/modal-legacy-api.ts
- components/modal/modal-ref.ts
- components/modal/modal-types.ts
- components/modal/modal.component.ts
- components/modal/modal.spec.ts
- components/modal/utils.ts
- schematics/migration.json
- schematics/ng-update/data/property-names.ts
- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v11/modal-deprecated.spec.ts
- schematics/ng-update/upgrade-rules/checks/modal-template-rule.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:modal): remove deprecated APIs for v11

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/standard-types.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:date-picker): remove deprecated APIs for v11

- components/modal/demo/confirm.ts
- components/modal/demo/service.ts
- components/modal/modal-confirm-container.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:button): fix nzOkDanger confirm btn and demo

- schematics/migration.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: append issue url to v11 migration

- components/package.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:icon): upgrade dependency version

- components/select/select-search.component.ts
close #6209
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6209 
```
[ ] Yes
[x] No
```
> fix(module:select): fix XSS vulnerabilities

- components/core/config/config.ts
- components/image/doc/index.en-US.md
- components/image/doc/index.zh-CN.md
- components/image/image-preview-options.ts
- components/image/image.directive.ts
- components/image/image.service.ts
- scripts/site/_site/doc/app/header/header.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:image): support rtl direction and fix props

- components/list/list.component.ts
- close #6229
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:list): fix template rendering order

- components/graph/demo/customized.ts
- components/graph/doc/index.en-US.md
- components/graph/doc/index.zh-CN.md
- components/graph/graph-edge.component.ts
- components/graph/graph-minimap.component.ts
- components/graph/graph-node.component.ts
- components/graph/graph.component.ts
- components/graph/interface.ts
- components/graph/package.json
- components/graph/style/index.less
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(module: graph): support graph component under experimental

- components/i18n/languages/uk_UA.ts
```
[x] Bugfix
[ ] Feature
```
Fixed compilation errors when using uk_UA locale.
```
[ ] Yes
[x] No
```
> fix(module:i18n): fix Ukrainian i18n file

- angular.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: remove unused dep

- components/cascader/doc/index.zh-CN.md
- components/graph/doc/index.en-US.md
- components/image/doc/index.en-US.md
- components/image/doc/index.zh-CN.md
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/progress/doc/index.zh-CN.md
- components/table/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix typo & missing part

- .github/CODEOWNERS
```
[ ] Bugfix
[ ] Feature
```
add image component code owner
```
[ ] Yes
[x] No
```
> chore: add image component code owner

- scripts/site/_site/doc/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix doc ssr

- CHANGELOG.md
- angular.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
- package.json
- scripts/gulp/tasks/universal.ts
- scripts/prerender/route-paths.txt
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update changelog and prerender router

- components/page-header/doc/index.en-US.md
- components/page-header/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number:  #6252
```
[ ] Yes
[x] No
```
> docs: fix PageHeader component document table format

- components/image/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:images): fix table of NzImageService

- components/form/demo/validate-reactive.md
- components/form/demo/validate-template.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #6265
```
[ ] Yes
[x] No
```
> docs(module:form): fix template-syntax outer link

- components/image/image.module.ts
```
[x] Bugfix
[ ] Feature
```
close #6271 
```
[ ] Yes
[x] No
```
> fix(module:image): add missing imported modules

- components/tabs/style/patch.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tabs): fix clickable area of the anchor element

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:modal): fix uncorrect 'NzModalService' markdown style

- components/collapse/collapse-panel.component.ts
- components/collapse/collapse.module.ts
- components/style/patch.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:collapse): animation cannot be disabled

- components/page-header/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #6276
```
[ ] Yes
[x] No
```
> docs(module:page-header): remove remove extra parentheses

- .github/CODEOWNERS
- .github/nz-boot.yml
- scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add new modules in DEMO module

- components/image/image-preview.component.ts
- components/image/image.spec.ts
- components/image/public-api.ts
- components/image/utils.ts
```
[x] Bugfix
[ ] Feature
```
image will fit content when drag released
```
[ ] Yes
[x] No
```
> fix(module:image): image fit content when drag released

- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/addon/filter-trigger.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:table): add nzHasBackdrop on nz-filter-trigger

- components/image/doc/index.en-US.md
- components/image/doc/index.zh-CN.md
> docs(module:image): add NzImageModule import guide

- components/modal/modal-container.ts
- components/modal/modal.spec.ts
close #6288
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:modal): mask is not set with the `nzZindex` property

- components/carousel/style/patch.less
```
[x] Bugfix
[ ] Feature
```
close #6268 
```
[ ] Yes
[x] No
```
> fix(module:carousel): remove unused patch style

- components/tabs/tab-link.directive.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tabs): index only changed by router event when nzLinkRouter

- components/transfer/demo/table-transfer.ts
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
Issue Number: #6130
display the checkbox
```
[ ] Yes
[X] No
```
> docs: fix demo table don't display the checkbox

- components/table/src/table/table.component.ts
- components/table/src/testing/table.spec.ts
close #6272
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): data is not updated when pagination exists

- components/carousel/carousel.component.ts
- components/carousel/carousel.spec.ts
close #6301
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:carousel): throw error when changing rtl

- components/icon/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: export `NZ_ICONS_USED_BY_ZORRO`

- components/image/image.module.ts
```
[x] Bugfix
[ ] Feature
```
close #6299 
```
[ ] Yes
[x] No
```
> fix(module:image): add missing entry components

- components/anchor/anchor.spec.ts
- components/input/input-group.component.ts
- components/table/src/table/tr.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:*): replace deprecated APIs without side effects

- components/table/src/table/tr.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table):  memory leak

- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: refine docs of customize and switch themes

- components/carousel/carousel.component.ts
- components/carousel/strategies/base-strategy.ts
- components/carousel/strategies/transform-strategy.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:carousel): fix carousel under rtl

- components/core/time/candy-date.ts
close #6310
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): remove wrong warning message

- components/core/config/config.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:core): fix nzBordered typo (#6331)

- components/core/time/candy-date.spec.ts
- components/core/time/candy-date.ts
- components/date-picker/calendar-footer.component.ts
- components/date-picker/date-picker.service.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/lib/date-table.component.ts
- components/date-picker/lib/decade-table.component.ts
- components/date-picker/lib/month-table.component.ts
- components/date-picker/lib/year-table.component.ts
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/time-picker/time-picker-panel.component.ts
fix(module:date-picker,timepicker): trackBy function
close #6308
close #6142
close #5992
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): start and end month displays unreasonable

- components/modal/demo/position.md
- components/modal/demo/position.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-types.ts
- components/modal/modal.component.ts
- components/modal/modal.spec.ts
- components/modal/utils.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6327 
```
[ ] Yes
[x] No
```
> feat(module:modal): add nzCentered for modal

- components/upload/doc/index.en-US.md
- components/upload/doc/index.zh-CN.md
- components/upload/interface.ts
- components/upload/upload-list.component.html
- components/upload/upload-list.component.ts
- components/upload/upload.component.ts
- close #6279
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:upload): support `NzUploadFile` parameter of `nzIconRender`

- components/date-picker/date-picker.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/picker.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6242 
Possible to add id attribute to the input of an nz-date-picker component.
```
[ ] Yes
[x] No
```
> feat(module:date-picker): support nzId (#6242)

- components/table/demo/dynamic-settings.ts
- components/table/demo/row-selection-and-operation.ts
- components/table/demo/row-selection-custom.ts
- components/table/src/table-data.service.ts
- components/table/src/table-style.service.ts
- components/table/src/table/table.component.ts
- components/table/src/table/tbody.component.ts
```
[ ] Bugfix
[x] Feature
```
Support ReadonlyArray in nzData
```
[x] Yes
[ ] No
```
Some type should rewrite to ReadonlyArray
> feat(module:table): add support for ReadonlyArray

- components/table/src/table/table-content.component.ts
- components/table/src/table/table-inner-default.component.ts
- components/table/src/table/table-inner-scroll.component.ts
- components/table/src/table/tr-measure.component.ts
- components/typography/text-edit.component.ts
- components/typography/typography.component.ts
- components/typography/typography.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:typography): edit area cannot get the content

- components/table/src/table/table-inner-scroll.component.ts
- package.json
- scripts/site/_site/doc/app/app.module.ts
- scripts/site/_site/doc/app/share/share.module.ts
close #6135 close #6254
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix table nzBordered

- components/tree-view/doc/index.en-US.md
- components/tree-view/doc/index.zh-CN.md
- components/tree-view/tree-virtual-scroll-view.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tree-view): correct API typo

- components/modal/modal-footer.directive.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module:modal): fix typo in modal-footer-directive.spec.ts

- components/i18n/languages/es_ES.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> fix(module:18n): adding new translations es_ES

- components/core/config/config.ts
- components/time-picker/doc/index.en-US.md
- components/time-picker/doc/index.zh-CN.md
- components/time-picker/time-picker-panel.component.ts
- components/time-picker/time-picker.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: [#6388](https://github.com/NG-ZORRO/ng-zorro-antd/issues/6388)
```
[ ] Yes
[x] No
```
> feat(module:time-picker): support updating OK and Now button text

- components/table/src/addon/filter.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: resolve #6384
```
[ ] Yes
[x] No
```
> fix(module:table): fix table filter (#6384)

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:docs): fix dependabot alert

- components/i18n/languages/de_DE.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:18n): adding new translations de_DE

- components/transfer/transfer.component.ts
- close #6425
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(module:transfer): change private to publish of `lists` variable

- components/graph/doc/index.en-US.md
- components/graph/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
NzGraphEdge api table cannot be displayed normally, see https://ng.ant.design/experimental/graph/zh#nzgraphedge
Fix markdown table format
```
[ ] Yes
[x] No
```
> docs(module:graph): fix markdown table format

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/demo/inline.md
- components/date-picker/demo/inline.ts
- components/date-picker/demo/module
- components/date-picker/picker.component.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/style/entry.less
- components/date-picker/style/patch.less
- close #6435
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:date-picker): add `nzInline` property

- docs/join.en-US.md
- docs/join.zh-CN.md
- scripts/site/_site/doc/app/header/header.component.ts
- scripts/site/_site/doc/app/header/header.module.ts
- scripts/site/_site/doc/app/header/join-tip.components.ts
- scripts/site/_site/doc/app/side/side.component.ts
- scripts/site/template/router.template.ts
- scripts/site/utils/generate-routes.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add join page

- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:date-picker): add `nzInline` document

- components/modal/modal-footer.component.ts
```
[x] Bugfix
[ ] Feature
```
close #6467 
```
[ ] Yes
[x] No
```
> fix(module:modal): fix incorrect assignment of 'nzFooter'

- components/pagination/pagination-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: pagination): fix syntax error in NzPaginationItemComponent

- components/tooltip/base.ts
- components/tooltip/tooltip.spec.ts
```
[x] Bugfix
[ ] Feature
```
close #6483
close #6402
```
[ ] Yes
[x] No
```
> fix(module:tooltip): keep tooltip visibility when trigger is null

- components/rate/rate.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:rate): fix invalid type of `nzCount` in `strictTemplates`

- components/space/demo/align.ts
- components/space/demo/basic.ts
- components/space/demo/customize.ts
- components/space/demo/module
- components/space/demo/size.ts
- components/space/demo/split.md
- components/space/demo/split.ts
- components/space/demo/vertical.ts
- components/space/doc/index.en-US.md
- components/space/doc/index.zh-CN.md
- components/space/space-item.component.ts
- components/space/space-item.directive.ts
- components/space/space.component.spec.ts
- components/space/space.component.ts
- components/space/space.module.ts
- components/space/types.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:space): add `nzSplit` support

- components/table/demo/virtual.ts
- components/table/style/patch.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: #5555
```
[ ] Yes
[x] No
```
> fix(module:table): virtual scroll bordered style

- components/radio/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: Fix broken table in radio component's docs

- components/descriptions/descriptions.component.ts
```
[x] Bugfix
[ ] Feature
```
close #6512 
```
[ ] Yes
[x] No
```
> fix(module:descriptions): fix dom structure under vertical layout

- components/space/public-api.ts
```
[x] Bugfix
[ ] Feature
```
close #6520 
```
[ ] Yes
[x] No
```
> fix(module:space): add missing exports

- components/core/time/candy-date.ts
- components/date-picker/demo/basic.ts
- components/date-picker/demo/disabled-date.ts
- components/date-picker/demo/inline.ts
- components/date-picker/demo/presetted-ranges.ts
- components/date-picker/demo/range-picker.ts
- components/i18n/date-helper.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker,core,i18n): import date-fns by esm

- components/descriptions/demo/vertical.md
- components/descriptions/demo/vertical.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:descriptions): sync 'vertical' document

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/image/doc/index.en-US.md
- components/image/doc/index.zh-CN.md
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
close #6451
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: improve the description of the `nzCloseOnNavigation` API

- components/tooltip/base.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6469
```
[ ] Yes
[x] No
```
> fix(module:tooltip): detect trigger change

- components/mention/config.ts
- components/mention/mention-trigger.ts
- components/mention/mention.component.ts
fix #6175
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:mention): preserve white spaces when insert suggestions

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-title.directive.spec.ts
- components/modal/modal-title.directive.ts
- components/modal/modal.component.ts
- components/modal/modal.module.ts
- components/modal/public-api.ts
close #4343, close #6337
```
[ ] Bugfix
[x] Feature
```
Issue Number: #4343 #6337
```
[ ] Yes
[x] No
```
> feat(module:modal): add nzModalTitle directive (#6337)

- CHANGELOG.md
- components/package.json
- components/version/version.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: release 11.3.0

- components/table/src/table-data.service.ts
close #5457
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: table): fix sort and filter when nzFrontPagination is false

- components/space/space.component.ts
closes #6549 
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6549 
```
[ ] Yes
[x] No
```
> fix(module:space): fix deprecated warning for nz-space-item (#6549)

- components/tabs/demo/slide.ts
- components/tabs/tab-nav-bar.component.ts
fix #6579
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6579
```
[ ] Yes
[ ] No
```
> fix(module:tabs): not scrolling to the selected tab after init

- components/drawer/drawer.component.ts
- components/drawer/drawer.spec.ts
fix #6381, close #6534
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6381
```
[ ] Yes
[x] No
```
> fix(module:drawer): content is attached before the drawer is opened

- components/tree-select/tree-select.component.ts
```
[x] Bugfix
```
this fix the following issue https://github.com/ngx-formly/ngx-formly/issues/2781, in case of the tree-select component is destroyed before the `ngOnInit` call
```
[ ] Yes
[x] No
```
> fix(module:tree-select): rely on destroy$ to clear subscriptions

- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: fix changelog typo

- components/i18n/languages/ka_GE.ts
<h2>PR Checklist</h2>
<p>Please check if your PR fulfills the following requirements:</p>
<ul class="contains-task-list">
<li class="task-list-item" draggable="false">
<span class="handle">
<svg class="drag-handle" `aria-hidden="true"` width="16" height="16">
<path d="M10 13a1 1 0 100-2 1 1 0 000 2zm-4 0a1 1 0 100-2 1 1 0 000 2zm1-5a1 1 0 11-2 0 1 1 0 012 0zm3 1a1 1 0 100-2 1 1 0 000 2zm1-5a1 1 0 11-2 0 1 1 0 012 0zM6 5a1 1 0 100-2 1 1 0 000 2z"></path>
</svg>
</span>
<span class="handle">
<svg class="drag-handle" aria-hidden="true" width="16" height="16">
<path d="M10 13a1 1 0 100-2 1 1 0 000 2zm-4 0a1 1 0 100-2 1 1 0 000 2zm1-5a1 1 0 11-2 0 1 1 0 012 0zm3 1a1 1 0 100-2 1 1 0 000 2zm1-5a1 1 0 11-2 0 1 1 0 012 0zM6 5a1 1 0 100-2 1 1 0 000 2z"></path>
</svg>
</span><input type="checkbox" …
> fix(module:i18n): added property missing in ka_GE

- components/table/demo/edit-row.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: table): change to nzPopconfirmTitle

- components/graph/core/minimap.ts
- components/image/image.directive.ts
- components/upload/upload-list.component.ts
- components/upload/upload.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6559 
```
[ ] Yes
[x] No
```
> fix: create image using document method to avoid ReferenceError in SSR

- components/message/doc/index.en-US.md
- components/message/doc/index.zh-CN.md
- components/notification/doc/index.en-US.md
- components/notification/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
close #6617 
```
[ ] Yes
[x] No
```
> docs(module:message,notification): add a link to `global-config`

- components/core/time/candy-date.spec.ts
- components/core/time/candy-date.ts
fix https://github.com/NG-ZORRO/ng-zorro-antd/issues/6322#issuecomment-798868317
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:date-picker): not switch month panel when range is same month

- docs/changelog.zh-CN.md
chore: fix changelog typo
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(changelog): fix typo

- components/image/image-config.ts
- components/image/image.spec.ts
- components/modal/modal-config.ts
- components/modal/modal.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: update animation classname

- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
close #6587
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add FAQ of date picker format

- components/slider/slider.component.ts
- components/slider/slider.spec.ts
```
[x] Bugfix
[ ] Feature
```
close #6586 
```
[ ] Yes
[x] No
```
> fix(module:slider): fix range slider not working for arrow keys

- docs/changelog.zh-CN.md
- docs/universal.en-US.md
- docs/universal.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(universal): fix typo

- components/graph/data-source/graph-data-source.ts
- components/graph/graph-edge.component.ts
- components/graph/graph.component.ts
- components/graph/interface.ts
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:graph): fix edge default style and wrong toggling group nodes

- components/graph/doc/index.en-US.md
- components/graph/doc/index.zh-CN.md
- components/graph/graph-edge.component.ts
- components/graph/graph.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:graph): fix wrong default edge style

- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
Old theme.less is deleted by #6603
close #6638
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update customize theme

- components/checkbox/checkbox-group.component.ts
- components/checkbox/checkbox.component.ts
- components/input-number/input-number.component.ts
- components/input/input-group.component.ts
- components/radio/radio.component.ts
- components/select/select.component.ts
- components/switch/switch.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: close #6555 
```
[ ] Yes
[n] No
```
> fix: focus monitor cleanup

- components/modal/modal-ref.ts
- components/modal/modal.component.ts
- components/modal/modal.spec.ts
close #6647
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6647,  #6320
```
[ ] Yes
[x] No
```
> fix(module:modal): `nzVisible` not updated when implicitly closed

- components/icon/doc/index.en-US.md
- components/icon/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:icon): fix iconfont docs

- components/i18n/languages/ar_EG.ts
```
[ ] Bugfix
[ ] Feature
```
More accurate translation for Arabic words
```
[ ] Yes
[x] No
```
> fix(module:*): arabic translations 'copied' & 'expand'

- components/cascader/demo/modal.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:cascader): use `nzModalContent` instead

- components/slider/slider.component.ts
- components/slider/slider.spec.ts
```
[x] Bugfix
[ ] Feature
```
close #6635 
```
[ ] Yes
[x] No
```
> fix(module:slider): processing value zero correctly

- components/core/resize-observers/package.json
- components/date-picker/package.json
- components/icon/package.json
- components/ng-package.json
deprecate whitelistedNonPeerDependencies in favor of allowedNonPeerDependencies
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: deprecate `whitelistedNonPeerDependencies`

- components/auto-complete/autocomplete-trigger.directive.ts
- components/auto-complete/autocomplete.component.ts
- components/auto-complete/autocomplete.spec.ts
close #6286
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6286
```
[ ] Yes
[x] No
```
> fix(module:autocomplete): no reset status when no matching inputs

- components/tree-view/demo/editable.ts
- components/tree-view/indent.ts
fix #6714
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6714
```
[ ] Yes
[x] No
```
> fix(module:tree-view): node indent line without mark change check

- components/core/color/color.ts
- components/tag/tag.component.ts
fix #6732
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6732
```
[ ] Yes
[x] No
```
> fix(module:tag): missing styles on view engine

- components/select/doc/index.en-US.md
> docs: Typo

- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #4732
```
[ ] Yes
[x] No
```
> docs(module:cascader): make filter make more sense

- angular.json
- schematics/collection.json
- schematics/migration.json
- schematics/ng-update/index.ts
- scripts/gulp/tasks/library.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: update config files

- components/graph/graph.component.ts
- components/table/demo/reset-filter.ts
- components/table/demo/sort-filter.ts
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/src/cell/th-addon.component.ts
- components/table/src/table-data.service.ts
- components/table/src/table.types.ts
- components/table/src/table/table-inner-scroll.component.ts
- components/table/src/table/table-virtual-scroll.directive.ts
- components/table/src/table/table.component.ts
- components/table/src/table/thead.component.ts
- components/table/src/testing/table.spec.ts
- components/table/src/testing/th.spec.ts
- components/transfer/demo/table-transfer.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:table): fix `TrackByFunction` type infer

- .husky/pre-commit
- components/grid/grid.spec.ts
- components/icon/page/index.ts
- components/tsconfig.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: add tsc type check for pre-commit

- components/button/button.component.ts
- components/button/button.spec.ts
- schematics/utils/ng-update/elements.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:button): remove deprecated APIs for v12

- components/tabs/tabset.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:tabs): remove deprecated APIs test cases

- components/dropdown/dropdown.directive.spec.ts
- components/dropdown/dropdown.directive.ts
- components/table/src/addon/filter-trigger.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:dropdown, table): deprecate `nzHasBackdrop` input

- components/pagination/pagination-item.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: pagination): pagination in form will trigger submit

- components/time-picker/time-picker.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:time-picker): remove duplicated import identifiers

- components/core/config/config.ts
- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.module.ts
- components/popconfirm/popconfirm.spec.ts
- components/popconfirm/popconfirm.ts
- components/tooltip/base.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6249 
```
[ ] Yes
[x] No
```
> feat(module:popconfirm): support nzAutoFocus

- components/core/config/config.ts
- components/core/services/image-preload.ts
- components/experimental-image/demo/auto-srcset.md
- components/experimental-image/demo/auto-srcset.ts
- components/experimental-image/demo/module
- components/experimental-image/demo/preloading.md
- components/experimental-image/demo/preloading.ts
- components/experimental-image/demo/src-loader.md
- components/experimental-image/demo/src-loader.ts
- components/experimental-image/doc/index.en-US.md
- components/experimental-image/doc/index.zh-CN.md
- components/experimental/image/image-loader.ts
- components/experimental/image/image.component.ts
- components/experimental/image/image.module.ts
- components/experimental/image/image.spec.ts
- components/experimental/image/index.ts
- components/experimental/image/package.json
- components/experimental/image/public-api.ts
- components/experimental/image/typings.ts
- components/experimental/image/utils.ts
- components/image/image-preview-options.ts
- components/image/image-preview.component.ts
- components/image/image.directive.ts
- scripts/prerender/route-paths.txt
- scripts/site/generate-site.js
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6514  
add new experimental component `nz-image-view`
```
[ ] Yes
[x] No
```
> feat(module:experimental-image): add experimental image component

- components/tree/tree-node.component.ts
```
[x] Bugfix
[ ] Feature
```
close #6730 
close #6526 
close #5807 
```
[ ] Yes
[x] No
```
> fix(module:tree): stop drop event change url in firefox

- components/menu/demo/inline-collapsed.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:menu): correct the `Layout` demo link

- .husky/pre-commit
- components/carousel/carousel.component.ts
- components/carousel/carousel.spec.ts
- components/carousel/demo/autoplay.ts
- components/carousel/demo/basic.ts
- components/carousel/demo/custom.md
- components/carousel/demo/custom.ts
- components/carousel/demo/fade.ts
- components/carousel/demo/position.ts
- components/carousel/public-api.ts
- components/carousel/strategies/experimental/flip-strategy.ts
- components/carousel/strategies/experimental/transform-no-loop-strategy.ts
- components/carousel/strategies/opacity-strategy.ts
- components/carousel/strategies/transform-strategy.ts
- package.json
close #6749
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:carousel): add demo to use custom transition strategy

- components/typography/style/index.less
- components/typography/typography.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:typography): single line ellipsis style

- components/style/core/base.less
- components/style/core/global.less
- components/style/mixins/modal-mask.less
- components/style/themes/dark.less
- components/style/themes/default.less
- components/table/src/addon/filter-trigger.component.ts
- components/table/src/addon/filter.component.ts
- components/table/src/addon/sorters.component.ts
- components/table/style/bordered.less
- components/table/style/index.less
- components/table/style/patch.less
- components/table/style/size.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:table): sync filter style

- components/rate/demo/customize.md
- components/rate/demo/customize.ts
- components/rate/rate-item.component.ts
- components/rate/rate.component.ts
- components/rate/rate.spec.ts
```
[ ] Bugfix
[x] Feature
```
https://ant.design/components/rate-cn/#components-rate-demo-character-function
```
[ ] Yes
[x] No
```
> feat(module:rate): support customize character

- components/select/select-top-control.component.ts
```
[x] Bugfix
[ ] Feature
```
close #6774 
```
[ ] Yes
[x] No
```
> fix(module:select): focus input when selector is clicked

- components/timeline/demo/label.md
- components/timeline/demo/label.ts
- components/timeline/demo/module
- components/timeline/doc/index.en-US.md
- components/timeline/doc/index.zh-CN.md
- components/timeline/timeline-item.component.ts
- components/timeline/timeline.component.ts
- components/timeline/timeline.spec.ts
close #6682
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(timeline): support `nzLabel`

- components/package.json
- docs/introduce.zh-CN.md
- docs/join.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update introduce

- .gitignore
- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v12/space-deprecated.spec.ts
- schematics/ng-update/upgrade-rules/checks/space-template-rule.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: add space component migration scripts

- components/cdk/resize-observer/package.json
- components/cdk/resize-observer/public-api.ts
- components/cdk/resize-observer/resize-observer.service.ts
- components/ng-package.json
- components/package.json
- scripts/site/_site/doc/app/app.module.ts
- scripts/site/_site/doc/app/header/join-tip.components.ts
close #6696
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: remove the default resize observer polyfill

- components/code-editor/code-editor.service.ts
```
[x] Bugfix
```
I've noticed the `NzCodeEditorService` cannot be GC'd since it subscribes `configUpdated$` which is a subject and keeps subscribers in its `observers` property until it's teardowned. This creates a memory leak for server-side rendered applications since the `NzCodeEditorService` is created and destroyed there per each HTTP request.
The `NzCodeEditorService` is GC'd successfully.
```
[ ] Yes
[x] No
```
> fix(module:code-editor): resolve memory leak

- components/code-editor/code-editor.component.ts
```
[x] Bugfix
```
Monaco's models are stored independently from the editor instance (inside the `ModelService`). So they also have to be disposed separately.
The event listener is disposed when the component is destroyed.
```
[x] No
```
> fix(module:code-editor): dispose the event listener when the component is destroyed

- components/timeline/doc/index.en-US.md
- components/timeline/doc/index.zh-CN.md
docs(timeline): fix typo
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
>  docs(module:timeline): fix typo

- package.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix immer dependency security issue

- components/auto-complete/autocomplete.component.ts
```
[x] Bugfix
```
Currently, the `NzAutocompleteComponent` is not GC'd successfully since its subscriptions keep referencing subscribers, subscribers reference `next` callback and all `next` callbacks capture `this`, preventing the `NzAutocompleteComponent` from being GC'd.
This can be observed on the below image. The `__ngContext__` is an `lView`, it's an array. `__ngContext__[2]` is `LViewFlags`, which is a bit mask for the current view state. `256` is `LViewFlags.Destroyed = 0b000100000000`.
By running `(temp1.__ngContext__[2] & 256) === 256` we can see that the component is in destroyed state, but it's still not garbage collected:
The `NzAutocompleteComponent` is GC'd successfully.
```
[x] No
```
> fix(module:autocomplete): resolve memory leak

- components/button/button.component.ts
- components/button/button.spec.ts
```
[x] Bugfix
```
The button component is probably one of the most used components. Currently, button components trigger change detections on each click event, tho they shouldn't. The click handler only checks if the event target is an anchor and then calls native DOM API, which doesn't require Angular to run `tick()`.
Button components do not trigger change detection anymore.
```
[x] No
```
> fix(module:button): do not trigger change detections on click events

- components/core/overlay/overlay-position.ts
- components/pipes/nz-bytes.pipe.ts
- components/tooltip/base.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: limit object propertyies of mapped types

- scripts/site/_site/doc/app/header/header.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix the site dir toggle button

- components/table/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x] No
```
> fix(module:table): add measurement for nzWidth

- components/pagination/pagination-default.component.ts
- components/pagination/pagination.spec.ts
when the 4th page is selected.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: pagination): the prevFiveItem should not be displayed

- components/graph/core/minimap.ts
- components/graph/graph-minimap.component.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:graph): resolve minimap memory leaks

- components/select/doc/index.zh-CN.md
> docs(module:select):   typo error

- components/upload/upload-btn.component.ts
- components/upload/upload.spec.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:upload): do not trigger change detection for `nz-upload-btn`

- components/resizable/resizable.directive.ts
- components/resizable/resizable.spec.ts
- components/resizable/resize-handle.component.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:resizable): reduce change detection cycles

- components/select/select-top-control.component.ts
- components/select/select.spec.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:select): reduce change detections for `nz-select-top-control`

- components/graph/graph-node.component.ts
- components/graph/graph.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:graph): reduce change detections on click events

- components/core/overlay/nz-connected-overlay.ts
- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.ts
- components/popover/demo/arrow-point-at-center.ts
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/demo/arrow-point-at-center.md
- components/tooltip/demo/arrow-point-at-center.ts
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/tooltip/tooltip.spec.ts
- components/tooltip/tooltip.ts
close #2858
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:tooltip, etc): add arrow point at center

- components/radio/radio.component.ts
- components/radio/radio.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:radio): reduce change detection cycles

- components/tooltip/demo/template.md
- components/tooltip/demo/template.ts
- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/tooltip/tooltip.ts
close #6607
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:tooltip): support tooltip template context

- components/tree-view/node.ts
- components/tree-view/tree-virtual-scroll-view.ts
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> fix(module:tree-view): not updates when datasource data changes #7040

- components/core/services/scroll.spec.ts
- components/core/services/scroll.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:core): do not run change detection when scrolling

- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-container.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:modal): do not run change detection when focusing element

- components/core/config/config.ts
- components/dropdown/dropdown.directive.ts
- components/table/src/addon/filter-trigger.component.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #6951
```
[ ] Yes
[x] No
```
> feat(module:core,dropdown,table): add config for backdrop

- components/tree-view/tree-virtual-scroll-view.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tree-view): incorrect type of `trackBy`

- .github/workflows/sync-styles.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: bump antd-styles-sync-action to v1.1.4

- .github/workflows/sync-styles.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: update sync-styles action

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): resolve memory leaks

- components/cascader/cascader.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:cascader): do not run change detections on non-handled `keydown` events

- components/time-picker/time-picker-panel.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:time-picker): do not run change detection when scrolling

- components/icon/icon.directive.ts
- components/menu/submenu.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:icon): do not run change detection when changing icon

- components/table/src/addon/filter-trigger.component.ts
- components/table/src/testing/th.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:table): do not run change detections on click events for the `nz-filter-trigger`

- components/switch/switch.component.ts
- components/switch/switch.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:switch): reduce change detection cycles

- components/dropdown/dropdown.directive.ts
- components/modal/utils.ts
- components/table/src/addon/filter-trigger.component.ts
- schematics/migration.json
- schematics/ng-update/data/input-names.ts
- schematics/ng-update/index.ts
- schematics/ng-update/test-cases/v13/backdrop-deprecated.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
- `[nzHasBackdrop]` has been removed, please use `[nzBackdrop]` instead.
> refactor(module:dropdown, table): remove deprecated APIs for V13

- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-container.directive.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:modal): do not run change detection on mouse events

- components/core/services/breakpoint.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:core): remove `resize` listener when the app is destroyed

- components/auto-complete/autocomplete-trigger.directive.ts
```
[x] Bugfix
[ ] Feature
```
Fix memory leak.
```
[ ] Yes
[x] No
```
> fix(module:auto-complete): memory leak

- components/icon/demo/module
- components/icon/page/en-US.txt
- components/icon/page/index.ts
- components/icon/page/zh-CN.txt
close #5170
Same as [1], on the icon page, support to quickly find the icons
that users may find through upload or paste icon.
[1] https://ant.design/components/icon-cn
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x]  No
```
> docs(module:icon): support upload image to search icon (#5170)

- components/transfer/transfer-list.component.ts
- components/transfer/transfer.spec.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:transfer): do not trigger change detection when the checkbox is clicked

- components/statistic/countdown.component.ts
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```
> fix(module:statistic): re-enter the Angular zone when the `nzCountdownFinish` emits

- components/cdk/overflow/overflow-container.component.ts
> fix(module:cdk): resolve leak

- components/steps/step.component.ts
- components/steps/steps.component.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:steps): do not run change detection if there are no `nzIndexChange` listeners

- components/back-top/back-top.component.ts
- components/back-top/back-top.spec.ts
- close #7199
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:back-top): fix more reliable scrolling listener

- package.json
- scripts/site/utils/generate-docs.js
- scripts/site/utils/get-meta.js
- scripts/site/utils/parse-demo-md.js
- scripts/site/utils/parse-doc-md.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: bump marked from 2.0.0 to 4.0.10

- docs/recommendation.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add ng-ant-admin website URL (#7213)

- components/i18n/languages/fa_IR.ts
```
[ ] Bugfix
[ ] Feature
```
Adding missing translations from the en_US file to the fa_IR file.
```
[ ] Yes
[x] No
```
> fix(module:i18n): update fa-IR.ts translations

- components/date-picker/style/patch.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): fix `z-index` to `auto` in inline mode

- package.json
close #7177 
Reference to [Angular version guide](https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: add node v16 as part of engines field in package.json

- components/i18n/languages/kk_KZ.ts
- components/i18n/public-api.ts
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
No kk_KZ i18n
Add kk_KZ i18n
```
[ ] Yes
[x] No
```
> feat(module:i18n): add kk_KZ to i18n

- components/image/image-preview.component.ts
> perf(module:image): do not run change detection if there are no `containerClick` listeners

- components/mention/mention.component.ts
> perf(module:mention): do not run change detection when the dropdown cannot be closed

- components/tabs/tabset.component.ts
> perf(module:tabs): do not run change detection when the promise resolves

- components/time-picker/time-picker-panel.component.ts
> perf(module:time-picker): do not run change detection when the timer fires

- docs/recommendation.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add ng-ant-admin website URL in EN(#7213)(#7230)

- components/auto-complete/autocomplete-trigger.directive.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:auto-complete): do not run change detection when the promise resolves

- components/radio/radio.component.ts
- components/radio/radio.spec.ts
```
[x] Bugfix
```
Issue Number: #7254 
```
[ ] Yes
[x] No
```
> fix(module:radio): emit `false` to the `ngModel` whenever the radio button is deselected

- components/resizable/demo/drawer.ts
- components/resizable/demo/table.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:resizable): fix demos of resizable

- components/mention/mention-trigger.ts
```
```
```
[ ] Yes
[x] No
```
> perf(module:mention): do not trigger change detections if there are no event listeners

- components/collapse/collapse-panel.component.ts
```
[x] Bugfix
[ ] Feature
```
When collapse title is clicked, it is not collapsed 
```
[ ] Yes
[x] No
```
> fix(module:collapse): markForCheck after collapse title clicked

- components/grid/demo/gutter.ts
- components/space/demo/align.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: remove warnings caused by wrong spelling while building lib

- components/select/select.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #6812
```
[ ] Yes
[x] No
```
> fix(module:select): exact match while searching should be active

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:modal): fix typo

- components/skeleton/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:skeleton): fix typo

- components/i18n/languages/fr_BE.ts
- components/i18n/languages/fr_CA.ts
- components/i18n/languages/fr_FR.ts
```
[ ] Bugfix
[ ] Feature
```
global.placeholder translation is missing, causing a warning in the cascader component.
```
[ ] Yes
[x] No
```
Add global.placeholder translation for fr-XX.ts
Fixing warning in cascader when call to getLocalData('global')
> fix(module:i18n): update fr translations

- scripts/schematics/demo2schematics.ts
- scripts/schematics/template/schema.json.template
- close #7280
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(schematics): change `id` to `$id` in demo `schema.json` file

- scripts/site/_site/doc/app/online-ide/online-ide.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix codesandbox

- components/code-editor/code-editor.service.ts
- components/core/config/config.ts
- add global configuration `codeEditor.extraConfig` to support monaco require config
```
[ ] Bugfix
[x] Feature
```
monaco required configuration, for example
```typescript
const ngZorroConfig: NzConfig = {
codeEditor: {
assetsRoot: `https://cdn.jsdelivr.net/npm/monaco-editor@latest/min`,
extraConfig: {
'vs/nls': { availableLanguages: { '*': 'zh-cn' } }
}
}
};
```
```
[ ] Yes
[x] No
```
> feat(module:code-editor): add global configuration to support monaco require config

- components/layout/doc/index.en-US.md
- components/layout/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:layout): fix typo

- components/cascader/cascader.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cascader): fix the problem of disappearing drop-down menu

- components/tree-view/tree-virtual-scroll-view.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tree-view): trigger markforcheck after nodes changed

- components/mention/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module: mention): fix API docs button to bottom

- components/mention/mention.component.ts
- components/mention/mention.module.ts
- components/mention/nz-mention.spec.ts
- components/mention/style/patch.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:mention): change dom to fit antd

- components/tabs/doc/index.zh-CN.md
- components/tabs/style/patch.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tabs): fix inconsistent animation behavior with previous

- components/i18n/languages/es_ES.ts
Add and update translations for es_ES
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
>  fix(module:18n): updating es_ES translations

- components/transfer/demo/module
- components/transfer/demo/status.md
- components/transfer/demo/status.ts
- components/transfer/doc/index.en-US.md
- components/transfer/doc/index.zh-CN.md
- components/transfer/transfer.component.ts
- components/transfer/transfer.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:transfer): support setting status

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/demo/status.md
- components/date-picker/demo/status.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/range-picker.component.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:date-picker): support setting status

- components/input/demo/module
- components/input/demo/status.md
- components/input/demo/status.ts
- components/input/doc/index.en-US.md
- components/input/doc/index.zh-CN.md
- components/input/input-group.component.ts
- components/input/input-group.spec.ts
- components/input/input.directive.ts
- components/input/input.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:input): support setting status

- components/input-number/demo/addon.md
- components/input-number/demo/addon.ts
- components/input-number/demo/group.md
- components/input-number/demo/group.ts
- components/input-number/demo/module
- components/input-number/demo/prefix.md
- components/input-number/demo/prefix.ts
- components/input-number/demo/status.ts
- components/input-number/doc/index.en-US.md
- components/input-number/doc/index.zh-CN.md
- components/input-number/input-number-group-slot.component.ts
- components/input-number/input-number-group.component.ts
- components/input-number/input-number-group.spec.ts
- components/input-number/input-number.component.ts
- components/input-number/input-number.module.ts
- components/input-number/public-api.ts
- components/input-number/style/entry.less
- components/input-number/style/patch.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:input-number): support input number group

- components/layout/doc/index.en-US.md
fix typo in the documentation from "stlye" to "style"
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module : layout) : fix typo "stlye" to "style"

- scripts/site/_site/doc/app/online-ide/online-ide.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore(module:*): fix stackblitz type

- components/tooltip/base.ts
In some cases, the rendering takes into account the height at which the `arrow` is in wrong place, so `cdk` sets the container position incorrectly.
To avoid this, after placing the `arrow` in the correct position, we should `re-calculate` the position of the `overlay`.
Fixes #7453.
```
[x] Bugfix
[ ] Feature
```
Issue Number: #7453
```
[ ] Yes
[x] No
```
> fix(module:tooltip): is not aligned on first display

- components/collapse/demo/extra.ts
- components/collapse/demo/module
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:collapse): add `nzExpandIconPosition` example to extra demo

- components/badge/badge-sup.component.ts
- components/badge/badge.component.ts
- components/badge/badge.spec.ts
- components/badge/demo/module
- components/badge/demo/no-wrapper.ts
- components/badge/demo/offset.md
- components/badge/demo/offset.ts
- components/badge/demo/ribbon.ts
- components/badge/demo/size.md
- components/badge/demo/size.ts
- components/badge/doc/index.en-US.md
- components/badge/doc/index.zh-CN.md
- components/badge/ribbon.component.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:badge): support size

- components/date-picker/demo/placement.md
- components/date-picker/demo/status.md
- components/time-picker/demo/bordered.md
- components/time-picker/demo/status.md
- components/time-picker/demo/use12-hours.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 7389
```
[ ] Yes
[x] No
```
> docs: update date-picker and time-picker demo order

- components/menu/doc/index.en-US.md
- components/menu/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:menu): fix typo

- components/cascader/doc/index.en-US.md
- components/cascader/doc/index.zh-CN.md
close #5098
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:cascader): add an FAQ section

- components/cascader/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cascader): fix wrong format of docs

- components/i18n/languages/it_IT.ts
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Italian translations update
```
```
[ ] Yes
[X] No
```
> fix(module:i18n): update it_IT.ts

- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
close #6756 
```
[ ] Yes
[x] No
```
> docs(module:dropdown): additional notes on `nzMode` of `nz-menu`

- components/code-editor/typings.ts
close #7663
```
[x] Bugfix
[ ] Feature
```
Issue Number: #7663 
```
[ ] Yes
[ ] No
```
> fix(module:code-editor): fix declaration of Window as monaco-editor

- components/descriptions/descriptions.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:descriptions): nzStringTemplateOutlet title style error

- components/cron-expression/cron-expression.component.ts
- components/cron-expression/cron-expression.module.ts
- components/cron-expression/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cron-expression): clear ul & li default style

- components/i18n/languages/hu_HU.ts
```
[x] Bugfix
[ ] Feature
```
The date-picker fails in the Hungarian language because of the missing texts.
```
[ ] Yes
[ ] No
```
> fix(module:i18n): add missing hu texts

- azure-pipelines.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: set version of node instead of using latest

- components/form/demo/validate-reactive.ts
- components/input/style/patch.less
fix #7574
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:input): textarea-count combined with nzHasFeedback location

- components/date-picker/date-picker.component.ts
```
[ ] Bugfix
[ ] Feature
```
None.
```
[ ] Yes
[x] No
```
> perf(module:date-picker): remove unused variable

- docs/introduce.zh-CN.md
fix #7771 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: replace the QR code of the DingTalk group

- components/time-picker/time-picker-panel.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> test(module:date-picker): fix typo

- components/popconfirm/doc/index.zh-CN.md
nzOkType remove Danger
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(popconfirm): remove nzOkType danger

- components/form/form-control.component.ts
```
[ ] Bugfix
[ ] Feature
```
None.
```
[ ] Yes
[ ] No
```
> perf(module:form): remove a unused variable

- components/package.json
This PR change the angular icons version to have full compatibility with angular v15 on npm install
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Avoir warning on installation NgZorro v15.0.0.beta-0
```
Warning on angular icon version on installation NgZorro v15.0.0.beta-0
No warning on installation
```
[ ] Yes
[x] No
```
> chore(module:components): update angular icons version for v15

- components/drawer/drawer.component.ts
- close #7620
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:drawer): fix `nzContentParams` definition error

- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
rename SageUrl to SafeUrl
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:code-editor): fix typo

- components/qr-code/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:qrcode): update index.en-US.md

- docs/migration-v15.en-US.md
Update migration-v15.en-US.md from 13.x -> 14.x to 14.x -> 15.x
- [* ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ *] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ *] Documentation content changes
```
Incorrect migration description
Updated correct migration description
```
[ ] Yes
[ *] No
```
> docs: migration description

- components/tooltip/tooltip.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tooltip): fix tooltip.spec.ts

- components/anchor/anchor-link.component.ts
- components/breadcrumb/breadcrumb.component.ts
- components/carousel/carousel-content.directive.ts
- components/carousel/carousel.component.ts
- components/cascader/cascader-li.component.ts
- components/checkbox/checkbox-wrapper.component.ts
- components/form/form-control.component.ts
- components/form/form-item.component.ts
- components/form/form-label.component.ts
- components/form/form-split.component.ts
- components/form/form-text.component.ts
- components/form/form.directive.ts
- components/input/input.directive.ts
- components/list/list-item-meta.component.ts
- components/list/list-item.component.ts
- components/menu/menu-divider.directive.ts
- components/skeleton/skeleton.component.ts
```
[ ] Bugfix
[ ] Feature
```
Use renderer to dynamically add class names to host element.
Use decorators to statically add class names to host element.
```
[ ] Yes
[x] No
```
> refactor(module:*): simplify addition of class name for host element

- components/qr-code/demo/error-level.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:qrcode): update demo.md

- package.json
- scripts/prerender/route-paths.txt
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: make ssr work

- components/time-picker/time-picker.component.spec.ts
- components/time-picker/time-picker.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number:  close #7899 
close time panel, the input won't foucus
```
[ ] Yes
[X] No
```
> fix(module:time-picker): modelChange trigger twice

- components/i18n/languages/zh_TW.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update zh_TW downloadFile translation
```
```
[ ] Yes
[x] No
```
> fix(module:i18n): update zh_TW.ts

- components/table/doc/index.zh-CN.md
- components/timeline/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:*): fix typo

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module:modal): add [nzModalContent] directive

- components/cron-expression/cron-expression-input.component.ts
- components/cron-expression/cron-expression.component.ts
- components/cron-expression/demo/basic.ts
- components/cron-expression/demo/borderless.md
- components/cron-expression/demo/borderless.ts
- components/cron-expression/demo/collapse.md
- components/cron-expression/demo/semantic.md
- components/cron-expression/demo/shortcuts.md
- components/cron-expression/demo/type.md
- components/cron-expression/demo/use.md
- components/cron-expression/doc/index.en-US.md
- components/cron-expression/doc/index.zh-CN.md
- components/cron-expression/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:cron-expression): support nzDisabled && nzBorderless

- components/cron-expression/cron-expression.component.ts
- components/cron-expression/cron-expression.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:cron-expression): add Unit Testing

- components/date-picker/date-picker.component.ts
- [☑︎] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
fix code comment in date picker component
```
[ ] Bugfix
[ ] Feature
[☑︎] Other... Please describe:
```
```
[ ] Yes
[☑︎] No
```
> fix(module:date-picker): fix code comment

- components/table/demo/custom-column.md
- components/table/demo/custom-column.ts
- components/table/demo/module
- components/table/doc/index.en-US.md
- components/table/doc/index.zh-CN.md
- components/table/public-api.ts
- components/table/src/cell/custom-column.directive.ts
- components/table/src/table-data.service.ts
- components/table/src/table.module.ts
- components/table/src/table.types.ts
- components/table/src/table/table.component.ts
- components/table/src/testing/custom-column.spec.ts
- components/table/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:table): support display and sorting of custom table columns

- components/tree/tree-node.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: tree): fix nz-tree-node keep dragging class with nzBeforeDrop

- components/qr-code/demo/background.md
- components/qr-code/demo/background.ts
- components/qr-code/demo/color.md
- components/qr-code/demo/color.ts
- components/qr-code/demo/padding.ts
- components/qr-code/doc/index.en-US.md
- components/qr-code/doc/index.zh-CN.md
- components/qr-code/qrcode.component.ts
- components/qr-code/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:qrcode): optimize demo display and nzPadding value

- components/tree/tree-node.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tree): remove console.log

- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix fix latest angular version supported

- components/form/demo/label-wrap.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
https://4x.ant.design/components/form-cn/#components-form-demo-layout-can-wrap
> docs(module:form): improve demo of label-wrap

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix wrong Chinese characters

- components/core/config/config.service.ts
- components/core/config/css-variables.ts
- components/core/util/dynamic-css.ts
- components/core/wave/nz-wave-renderer.ts
- components/core/wave/nz-wave.directive.ts
The `ConfigService` needs to insert a `style` tag when registering theme. These changes use the new `CSP_NONCE` token to avoid CSP issues.
Closes #7644
> fix(module:core): resolve CSP errors

- components/graph/graph-zoom.directive.ts
```
[ ] Bugfix
[ ] Feature
```
No longer use `Selection.bind()`
```
[ ] Yes
[x] No
```
> refactor(module:graph): replace selection with transition

- components/cron-expression/demo/semantic.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cron-expression): clear console warnings

- components/drawer/drawer.service.ts
- components/message/message.module.ts
- components/message/message.service.module.ts
- components/message/message.service.ts
- components/message/public-api.ts
- components/notification/notification.service.ts
providedIn ngModule 用法已被弃用：https://angular.cn/api/core/Injectable#providedin
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:*): make service provided in root

- components/icon/page/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:icon): component factory is no longer needed

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: update ng-antd-color-picker version

- components/color-picker/doc/index.en-US.md
- components/color-picker/doc/index.zh-CN.md
- components/qr-code/doc/index.en-US.md
- components/qr-code/doc/index.zh-CN.md
- components/water-mark/doc/index.en-US.md
- components/water-mark/doc/index.zh-CN.md
- scripts/site/_site/doc/app/side/side.component.ts
- scripts/site/_site/doc/styles.less
- scripts/site/template/router.template.ts
- scripts/site/utils/generate-routes.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: component Map supports tag identification

- components/cascader/cascader.service.ts
```
[x] Bugfix
[ ] Feature
```
Since angular/core is still compatible with rxjs v6, we need to be compatible with it too.
https://github.com/angular/angular/blob/16.2.x/packages/core/package.json#L19
```
[ ] Yes
[x] No
```
> fix(module:cascader): compatible with rxjs v6

- components/i18n/languages/fa_IR.ts
```
[ ] Bugfix
[ ] Feature
[✔] Code style update (formatting, local variables)
```
Missing some translation keys
Updated internationalization for persian language.
```
[ ] Yes
[✔] No
```
> fix(module:i18n): update fa_IR translations

- components/pipes/demo/safe-null.md
- components/pipes/nz-safe-null.pipe.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:pipe): deprecated nz-safe-null pipe

- components/auto-complete/autocomplete.spec.ts
- components/cascader/cascader.spec.ts
- components/checkbox/checkbox.spec.ts
- components/cron-expression/cron-expression.component.ts
- components/cron-expression/cron-expression.spec.ts
- components/cron-expression/typings.ts
- components/date-picker/date-picker.component.spec.ts
- components/form/form-control.spec.ts
- components/input-number/input-number.spec.ts
- components/input/input.spec.ts
- components/radio/radio.spec.ts
- components/rate/rate.spec.ts
- components/slider/slider.spec.ts
- components/switch/switch.spec.ts
- components/tree-select/tree-select.spec.ts
PR 将分为两部分：
1. 重构源代码/测试代码中的 UntypedForm 用法（此 PR）
2. 重构 Demo 中的 UntypedForm 用法（[后续 PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8025)）
**关于部分测试代码中的 FormGroup 被重构为 FormControl：**
在此之前，部分测试代码中使用 FormGroup 似乎只是为了组合使用 `[formGroup]` 与 `[formControlName]` 指令，并没有真正用到 FormGroup 和 `[formGroup]` 指令的功能。
对于这种情况，我们可以使用 `[formControl]` 指令来完成表单绑定，这使得代码更简单，更容易完成类型推断。
为了便于 review，此 PR 将包含多个 commits。
*在这项工作完成后，我们应该尽可能的避免合并包含 UntypedForm 的代码。*
```
[ ] Bugfix
[ ] Feature
[ ] Application (the showcase website) / …
```
> refactor(*): migrate to typed form

- components/i18n/date-config.ts
- components/i18n/date-helper.service.ts
- components/menu/menu-group.component.ts
- components/menu/menu.directive.ts
- components/tree-select/tree-select.component.ts
- components/tree/tree.component.ts
- docs/global-config.en-US.md
- docs/global-config.zh-CN.md
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
此提交主要调整了 FactoryProvider，逐步减少对参数装饰器的使用
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:*): use inject function to simplify code

- components/slider/step.component.ts
fix: #7817
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:slider): step can not click the problem

- .github/CODEOWNERS
- components/components.less
- components/hash-code/demo/basic.md
- components/hash-code/demo/basic.ts
- components/hash-code/demo/copy.md
- components/hash-code/demo/copy.ts
- components/hash-code/demo/logo.md
- components/hash-code/demo/logo.ts
- components/hash-code/demo/module
- components/hash-code/demo/primary.md
- components/hash-code/demo/primary.ts
- components/hash-code/demo/rect.md
- components/hash-code/demo/rect.ts
- components/hash-code/demo/single.md
- components/hash-code/demo/single.ts
- components/hash-code/demo/strip.md
- components/hash-code/demo/strip.ts
- components/hash-code/doc/index.en-US.md
- components/hash-code/doc/index.zh-CN.md
- components/hash-code/hash-code.component.spec.ts
- components/hash-code/hash-code.component.ts
- components/hash-code/hash-code.module.ts
- components/hash-code/index.ts
- components/hash-code/ng-package.json
- components/hash-code/public-api.ts
- components/hash-code/style/entry.less
- components/hash-code/style/index.less
- components/hash-code/typings.ts
- scripts/prerender/route-paths.txt
- scripts/site/template/ng-zorro-antd.module.template.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:hash-code): add HashCode component

- components/tree-select/tree-select.component.ts
> fix(module:tree-select): 修复nz-tree-select组件tag回显与提交顺序不一致问题

- components/i18n/languages/pl_PL.ts
Added translations related with date picker and calendar for week and range placeholders
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> fix(module:i18n): added missing translations to pl_PL

- components/resizable/resize-handle.component.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/NG-ZORRO/ng-zorro-antd/pull/8042#discussion_r1379680545
```
[ ] Yes
[x] No
```
> fix(module:resizable): fix pointer capture bug

- components/i18n/languages/fr_BE.ts
- components/i18n/languages/fr_CA.ts
- components/i18n/languages/fr_FR.ts
- [x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[x ] Code style update (formatting, local variables)
```
```
[ ] Yes
[x ] No
```
> fix(module:i18n): update fr/be/ca translations

- .gitignore
```
[ ] Bugfix
[ ] Feature
[✔] Other... Please describe: changed made in .gitignore file
```
The folder .nx is not included in the .gitignore file, so it can be committed and pushed to the repository.
Added the .nx and .nx-cache folders to the .gitignore file.
```
[ ] Yes
[✔] No
```
> chore: added nx cache to gitignore

- components/image/image-preview.component.ts
- components/image/image.directive.ts
- components/image/image.service.ts
```
[ ] Bugfix
[ ] Feature
[✔] Code style update (formatting, local variables)
```
I have opened a new PR to address the unresolved comments from the previous PR. Here is the link to the new PR: <a href="https://github.com/NG-ZORRO/ng-zorro-antd/pull/8163">[PR #8163]</a>.
Followed NG-ZORRO's naming convention
```
[ ] Yes
[✔] No
```
> refactor(module:image): follow nz-zorro conventions

- scripts/site/utils/marked.js
```
[x] Bugfix
[ ] Feature
```
在支持 `:standalone` 后缀 后，指令的 `]` 字符不一定会是 heading text 的最后一位，例如：
```
[nz-flex]:standalone
```
```
[ ] Yes
[x] No
```
> fix: fix logic for generating directive tags

- components/radio/doc/index.en-US.md
- components/radio/doc/index.zh-CN.md
- components/radio/radio-button.directive.ts
- components/radio/radio-group.component.ts
- components/radio/radio.component.ts
- components/radio/radio.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Radio component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:radio): support standalone component

- components/qr-code/doc/index.en-US.md
- components/qr-code/doc/index.zh-CN.md
- components/qr-code/qrcode.component.ts
- components/qr-code/qrcode.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated QR code component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:qr-code): support standalone component

- components/slider/doc/index.en-US.md
- components/slider/doc/index.zh-CN.md
- components/slider/handle.component.ts
- components/slider/marks.component.ts
- components/slider/slider.component.ts
- components/slider/slider.module.ts
- components/slider/slider.spec.ts
- components/slider/step.component.ts
- components/slider/track.component.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Slider component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:slider): support standalone component

- components/switch/doc/index.en-US.md
- components/switch/doc/index.zh-CN.md
- components/switch/switch.component.ts
- components/switch/switch.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Switch component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:switch): support standalone component

- components/spin/doc/index.en-US.md
- components/spin/doc/index.zh-CN.md
- components/spin/spin.component.ts
- components/spin/spin.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Spin component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:spin): support standalone component

- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
- components/steps/step.component.ts
- components/steps/steps.component.ts
- components/steps/steps.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Steps component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:steps): support standalone component

- components/typography/doc/index.en-US.md
- components/typography/doc/index.zh-CN.md
- components/typography/text-copy.component.ts
- components/typography/text-edit.component.ts
- components/typography/typography.component.ts
- components/typography/typography.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Typography component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:typography): support standalone component

- components/rate/doc/index.en-US.md
- components/rate/doc/index.zh-CN.md
- components/rate/rate-item.component.ts
- components/rate/rate.component.ts
- components/rate/rate.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Rate component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:rate): support standalone component

- components/tooltip/doc/index.en-US.md
- components/tooltip/doc/index.zh-CN.md
- components/tooltip/tooltip.module.ts
- components/tooltip/tooltip.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Tooltip component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:tooltip): support standalone component

- components/page-header/doc/index.en-US.md
- components/page-header/doc/index.zh-CN.md
- components/page-header/page-header-cells.ts
- components/page-header/page-header.component.ts
- components/page-header/page-header.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Page header component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:page-header): support standalone component

- components/pipes/doc/index.en-US.md
- components/pipes/doc/index.zh-CN.md
- components/pipes/nz-aggregate.pipe.ts
- components/pipes/nz-bytes.pipe.ts
- components/pipes/nz-css-unit.pipe.ts
- components/pipes/nz-ellipsis.pipe.ts
- components/pipes/nz-pipes.module.ts
- components/pipes/nz-safe-null.pipe.ts
- components/pipes/nz-sanitizer.pipe.ts
- components/pipes/nz-trim.pipe.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Pipes to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:pipes): support standalone component

- components/timeline/doc/index.en-US.md
- components/timeline/doc/index.zh-CN.md
- components/timeline/timeline-item.component.ts
- components/timeline/timeline.component.ts
- components/timeline/timeline.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Timeline component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:timeline): support standalone component

- components/space/doc/index.en-US.md
- components/space/doc/index.zh-CN.md
- components/space/space-item.directive.ts
- components/space/space.component.ts
- components/space/space.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Space component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:space): support standalone component

- components/statistic/countdown.component.ts
- components/statistic/doc/index.en-US.md
- components/statistic/doc/index.zh-CN.md
- components/statistic/statistic-number.component.ts
- components/statistic/statistic.component.ts
- components/statistic/statistic.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Statistics component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:statistics): support standalone component

- components/segmented/doc/index.en-US.md
- components/segmented/doc/index.zh-CN.md
- components/segmented/segmented.component.ts
- components/segmented/segmented.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Segmented component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:segmented): support standalone component

- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/popover/popover.module.ts
- components/popover/popover.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Popover component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:popover): support standalone component

- components/popconfirm/doc/index.en-US.md
- components/popconfirm/doc/index.zh-CN.md
- components/popconfirm/popconfirm.module.ts
- components/popconfirm/popconfirm.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Pop confirm component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:pop-confirm): support standalone component

- components/tree-view/checkbox.ts
- components/tree-view/doc/index.en-US.md
- components/tree-view/doc/index.zh-CN.md
- components/tree-view/indent.ts
- components/tree-view/node.ts
- components/tree-view/option.ts
- components/tree-view/outlet.ts
- components/tree-view/padding.ts
- components/tree-view/toggle.ts
- components/tree-view/tree-view.module.ts
- components/tree-view/tree-view.ts
- components/tree-view/tree-virtual-scroll-view.ts
- components/tree-view/tree.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Tree view component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:tree-view): support standalone component

- components/skeleton/doc/index.en-US.md
- components/skeleton/doc/index.zh-CN.md
- components/skeleton/skeleton-element.component.ts
- components/skeleton/skeleton.component.ts
- components/skeleton/skeleton.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Skeleton component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:skeleton): support standalone component

- components/tabs/doc/index.en-US.md
- components/tabs/doc/index.zh-CN.md
- components/tabs/tab-add-button.component.ts
- components/tabs/tab-body.component.ts
- components/tabs/tab-close-button.component.ts
- components/tabs/tab-link.directive.ts
- components/tabs/tab-nav-bar.component.ts
- components/tabs/tab-nav-item.directive.ts
- components/tabs/tab-nav-operation.component.ts
- components/tabs/tab-scroll-list.directive.ts
- components/tabs/tab.component.ts
- components/tabs/tab.directive.ts
- components/tabs/tabs-ink-bar.directive.ts
- components/tabs/tabs.module.ts
- components/tabs/tabset.component.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Tab component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:tab): support standalone component

- components/breadcrumb/breadcrumb-item.component.ts
- components/breadcrumb/breadcrumb-separator.component.ts
- components/breadcrumb/breadcrumb.component.ts
- components/breadcrumb/breadcrumb.module.ts
- components/breadcrumb/doc/index.en-US.md
- components/breadcrumb/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Didn't find any usage of `OverlayModule`. Removed it.
I also kept `BidiModule` export in the module. I'm pretty sure that it's not the responsibillity of this module to reexport `BidiModule`, but it will be a breaking change if I remove it.
Imported standalone directives from `@angular/common` instead of `CommonModule.`
> feat(module:breadcrumb): support standalone component

- components/popconfirm/popconfirm.ts
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/tooltip.ts
```
[ ] Bugfix
[ ] Feature
[] Other... Please describe:
```
ComponentFactoryRsolver is depreacted but still use in BaseTooltip
ComponentFactoryResolver is removed
```
[ ] Yes
[X] No
```
> refactor(module:core): remove componentFactorResolver

- angular.json
```
[ ] Bugfix
[ ] Feature
[X] Build related changes
```
Whe we build the application there is a warning on cron parser dependencies
Fix the warning
```
[ ] Yes
[X] No
```
> fix(build): warning cron parser common js dependencies

- components/form/doc/index.en-US.md
- components/form/doc/index.zh-CN.md
- components/form/form-control.component.ts
- components/form/form-item.component.ts
- components/form/form-label.component.ts
- components/form/form-label.spec.ts
- components/form/form-split.component.ts
- components/form/form-split.spec.ts
- components/form/form-text.component.ts
- components/form/form-text.spec.ts
- components/form/form.directive.ts
- components/form/form.module.ts
- components/form/form.spec.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Form component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:form): support standalone component

- components/input/autosize.directive.ts
- components/input/doc/index.en-US.md
- components/input/doc/index.zh-CN.md
- components/input/input-group-slot.component.ts
- components/input/input-group.component.ts
- components/input/input.directive.ts
- components/input/input.module.ts
- components/input/textarea-count.component.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Input component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:input): support standalone component

- components/descriptions/descriptions-item.component.ts
- components/descriptions/descriptions.component.ts
- components/descriptions/descriptions.module.ts
- components/descriptions/doc/index.en-US.md
- components/descriptions/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Descriptions component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:description): support standalone component

- components/resizable/doc/index.en-US.md
- components/resizable/doc/index.zh-CN.md
- components/resizable/resizable.directive.ts
- components/resizable/resizable.module.ts
- components/resizable/resize-handle.component.ts
- components/resizable/resize-handles.component.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Resizable component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:resizable): support standalone component

- components/grid/col.directive.ts
- components/grid/doc/index.en-US.md
- components/grid/doc/index.zh-CN.md
- components/grid/grid.module.ts
- components/grid/row.directive.ts
- [c] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[✔] Feature
```
Updated Grid component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:grid): support standalone component

- components/graph/doc/index.en-US.md
- components/graph/doc/index.zh-CN.md
- components/graph/graph-defs.component.ts
- components/graph/graph-edge.component.ts
- components/graph/graph-edge.directive.ts
- components/graph/graph-group-node.directive.ts
- components/graph/graph-minimap.component.ts
- components/graph/graph-node.component.ts
- components/graph/graph-node.directive.ts
- components/graph/graph-zoom.directive.ts
- components/graph/graph.component.ts
- components/graph/graph.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Graph component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:graph): support standalone component

- components/button/button-group.component.ts
- components/button/button-group.spec.ts
- components/button/button.component.ts
- components/button/button.module.ts
- components/button/button.spec.ts
- components/button/doc/index.en-US.md
- components/button/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Button component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:button): support standalone component

- components/core/element-patch/element-patch.directive.ts
- components/core/element-patch/element-patch.module.ts
- components/core/highlight/highlight.module.ts
- components/core/highlight/highlight.pipe.ts
- components/core/no-animation/nz-no-animation.directive.ts
- components/core/no-animation/nz-no-animation.module.ts
- components/core/outlet/outlet.module.ts
- components/core/outlet/string_template_outlet.directive.ts
- components/core/pipe/nz-pipe.module.ts
- components/core/pipe/time-range.pipe.ts
- components/core/trans-button/nz-trans-button.directive.ts
- components/core/trans-button/nz-trans-button.module.ts
- components/core/transition-patch/transition-patch.directive.ts
- components/core/transition-patch/transition-patch.module.ts
- components/core/wave/nz-wave.directive.ts
- components/core/wave/nz-wave.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Core components to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:core): support standalone component

- components/cdk/overflow/overflow-container.component.ts
- components/cdk/overflow/overflow-item.directive.ts
- components/cdk/overflow/overflow-rest.directive.ts
- components/cdk/overflow/overflow-suffix.directive.ts
- components/cdk/overflow/overflow.module.ts
- components/cdk/resize-observer/resize-observer.directive.ts
- components/cdk/resize-observer/resize-observer.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Cdk component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:cdk): support standalone component

- components/dropdown/doc/index.en-US.md
- components/dropdown/doc/index.zh-CN.md
- components/dropdown/dropdown-a.directive.ts
- components/dropdown/dropdown-button.directive.ts
- components/dropdown/dropdown-menu.component.ts
- components/dropdown/dropdown.directive.ts
- components/dropdown/dropdown.module.ts
- components/tabs/tab-nav-operation.component.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Dropdown component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:dropdown): support standalone component #8254

- components/card/card-grid.directive.ts
- components/card/card-loading.component.ts
- components/card/card-meta.component.ts
- components/card/card-tab.component.ts
- components/card/card.component.ts
- components/card/card.module.ts
- components/card/doc/index.en-US.md
- components/card/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Card component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:card): component support standalone

- components/collapse/collapse-panel.component.ts
- components/collapse/collapse.component.ts
- components/collapse/collapse.module.ts
- components/collapse/doc/index.en-US.md
- components/collapse/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Collapse component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:collapse): support standalone component

- components/comment/comment-cells.ts
- components/comment/comment.component.ts
- components/comment/comment.module.ts
- components/comment/doc/index.en-US.md
- components/comment/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Comment component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:comment): support standalone component

- components/calendar/calendar-cells.ts
- components/calendar/calendar-header.component.ts
- components/calendar/calendar-header.spec.ts
- components/calendar/calendar.component.ts
- components/calendar/calendar.module.ts
- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Calendar component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:calendar): support standalone component

- components/cron-expression/cron-expression-input.component.ts
- components/cron-expression/cron-expression-label.component.ts
- components/cron-expression/cron-expression-preview.component.ts
- components/cron-expression/cron-expression.component.ts
- components/cron-expression/cron-expression.module.ts
- components/cron-expression/doc/index.en-US.md
- components/cron-expression/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Cron expression component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:cron-expression): support standalone component

- components/code-editor/code-editor.component.ts
- components/code-editor/code-editor.module.ts
- components/code-editor/doc/index.en-US.md
- components/code-editor/doc/index.zh-CN.md
```
[ ] Bugfix
[✔] Feature
```
Updated Code editor component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:code-editor): support standalone component

- components/drawer/doc/index.en-US.md
- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer-content.directive.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Drawer component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:drawer): support standalone component

- components/cron-expression/cron-expression.component.ts
fix: #8188
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:cron-expression): output type error

- components/menu/doc/index.en-US.md
- components/menu/doc/index.zh-CN.md
- components/menu/menu-divider.directive.ts
- components/menu/menu-group.component.ts
- components/menu/menu-item.component.ts
- components/menu/menu.directive.ts
- components/menu/menu.module.ts
- components/menu/submenu-inline-child.component.ts
- components/menu/submenu-non-inline-child.component.ts
- components/menu/submenu-title.component.ts
- components/menu/submenu.component.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Menu component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:menu): support standalone component

- components/list/doc/index.en-US.md
- components/list/doc/index.zh-CN.md
- components/list/list-cell.ts
- components/list/list-item-cell.ts
- components/list/list-item-meta-cell.ts
- components/list/list-item-meta.component.ts
- components/list/list-item.component.ts
- components/list/list.component.ts
- components/list/list.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated List component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:list): support standalone component

- components/tree-select/doc/index.en-US.md
- components/tree-select/doc/index.zh-CN.md
- components/tree-select/tree-select.component.ts
- components/tree-select/tree-select.module.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Tree select component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:tree-select): support standalone component

- components/date-picker/calendar-footer.component.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.module.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/inner-popup.component.ts
- components/date-picker/lib/abstract-panel-header.ts
- components/date-picker/lib/abstract-table.html
- components/date-picker/lib/abstract-table.ts
- components/date-picker/lib/date-header.component.ts
- components/date-picker/lib/date-table.component.ts
- components/date-picker/lib/decade-header.component.ts
- components/date-picker/lib/decade-table.component.ts
- components/date-picker/lib/lib-packer.module.ts
- components/date-picker/lib/lib-packer.spec.ts
- components/date-picker/lib/month-header.component.ts
- components/date-picker/lib/month-table.component.ts
- components/date-picker/lib/year-header.component.ts
- components/date-picker/lib/year-table.component.ts
- components/date-picker/month-picker.component.ts
- components/date-picker/range-picker.component.ts
- components/date-picker/week-picker.component.ts
- components/date-picker/year-picker.component.ts
```
[ ] Bugfix
[✔] Feature
```
Updated Date picker component to work as a standalone component.
```
[ ] Yes
[✔] No
```
> feat(module:date-picker): support standalone component

- components/alert/alert.component.ts
```
[ ] Bugfix
[ ] Feature
```
Alert component still use ngIf directive
Alert component now use the new code flow
```
[ ] Yes
[X] No
```
> refactor(module:alert): implement new control flow

- components/avatar/avatar.component.ts
```
[ ] Bugfix
[ ] Feature
```
Avatar component still use ngIf structural directive
Avatar component use the new code flow syntax
```
[ ] Yes
[X] No
```
> refactor(module:avatar): implement new control flow

- components/anchor/anchor-link.component.ts
- components/anchor/anchor.component.ts
```
[ ] Bugfix
[ ] Feature
```
Anchor component sill use ngIf for managing control flow
Anchor component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:anchor): implement new control flow

- components/back-top/back-top.component.ts
```
[ ] Bugfix
[ ] Feature
```
BackTop component still use ngIf directive to manage control flow
BackTop Component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:back-top): implement new control flow

- components/badge/badge-sup.component.ts
- components/badge/badge.component.ts
- components/badge/badge.spec.ts
- components/badge/demo/colorful.ts
```
[ ] Bugfix
[ ] Feature
```
Badge component still use structural directive for control flow
Badge component use now the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:badge): implement new control flow

- components/breadcrumb/breadcrumb-item.component.ts
- components/breadcrumb/breadcrumb.component.ts
```
[ ] Bugfix
[ ] Feature
```
Breadcrumb component still use structural directive to manage the control flow
Breadcumb component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:breadcrumb): implement new control flow

- components/button/button.component.ts
```
[ ] Bugfix
[ ] Feature
```
Button component still use structural directive to manage the control flow
Button component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:button): implement new control flow

- components/calendar/calendar-header.component.ts
- components/calendar/calendar.component.ts
- components/calendar/demo/notice-calendar.ts
```
[ ] Bugfix
[ ] Feature
```
Calendar component use strucural directive to manage the control flow
Calendar component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:calendar): implement new control flow

- components/card/card-loading.component.ts
- components/card/card-meta.component.ts
- components/card/card.component.ts
```
[ ] Bugfix
[ ] Feature
```
Card component still use structural directive to manage the control flow
Card component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:card): implement new control flow

- components/carousel/carousel.component.ts
- components/carousel/carousel.spec.ts
- components/carousel/demo/autoplay.ts
- components/carousel/demo/basic.ts
- components/carousel/demo/custom.ts
- components/carousel/demo/fade.ts
- components/carousel/demo/loop.ts
- components/carousel/demo/position.ts
```
[ ] Bugfix
[ ] Feature
```
Carousel still use structural directive to manage the control flow
Carousel now used the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:carousel): implement new control flow

- components/cascader/cascader-li.component.ts
- components/cascader/cascader.component.ts
- components/cascader/cascader.spec.ts
- components/cascader/demo/custom-render.ts
```
[ ] Bugfix
[ ] Feature
```
Cascader component still use structural directive to manage the control flow
Cascader component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:cascader): implement new control flow

- components/checkbox/checkbox-group.component.ts
```
[ ] Bugfix
[ ] Feature
```
Checkbox component still use structural directive to manage the control flow
Checkbox component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:checkbox): implement new control flow

- components/code-editor/code-editor.component.ts
```
[ ] Bugfix
[ ] Feature
```
Code Editor component still use the older control flow
Code Editor component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:code-editor): implement new control flow

- components/collapse/collapse-panel.component.ts
- components/collapse/demo/accordion.ts
- components/collapse/demo/basic.ts
- components/collapse/demo/borderless.ts
- components/collapse/demo/custom.ts
- components/collapse/demo/extra.ts
- components/collapse/demo/ghost.ts
- components/collapse/demo/mix.ts
- components/collapse/demo/noarrow.ts
```
[ ] Bugfix
[ ] Feature
```
Collapse still use the older control flow
Collapse component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:collapse): implement new control flow

- components/color-picker/color-format.component.ts
- components/color-picker/color-picker.component.ts
```
[ ] Bugfix
[ ] Feature
```
Color Picker still use the older control flow
Color picker use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:color-picker): refactor control flow

- components/comment/comment-cells.ts
- components/comment/comment.component.ts
- components/comment/demo/editor.ts
- components/comment/demo/nested.ts
```
[ ] Bugfix
[ ] Feature
```
Comment component still use the older control flow
Comment component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:comment): refactor control flow

- components/cron-expression/cron-expression-preview.component.ts
- components/cron-expression/cron-expression.component.ts
- components/cron-expression/demo/shortcuts.ts
```
[ ] Bugfix
[ ] Feature
```
Cron Expression component still use the older control flow
Cron expression component now use the noew control flow
```
[ ] Yes
[X] No
```
> refactor(module:cron-expression): refactor control flow

- components/date-picker/calendar-footer.component.ts
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-range-popup.component.ts
- components/date-picker/inner-popup.component.ts
- components/date-picker/lib/abstract-panel-header.html
- components/date-picker/lib/abstract-table.html
- components/date-picker/lib/abstract-table.ts
- components/date-picker/lib/date-table.component.ts
- components/date-picker/lib/interface.ts
- components/date-picker/month-picker.component.spec.ts
- components/date-picker/range-picker.component.spec.ts
- components/date-picker/week-picker.component.spec.ts
- components/date-picker/year-picker.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
DatePicker still use the older control flow
DatePicker use now the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:date-picker): refactor control flow

- components/descriptions/descriptions.component.ts
- components/descriptions/descriptions.spec.ts
- components/descriptions/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
```
Descriptions component still use the older control flow
Descripitions component use the new control flow
```
[ ] Yes
[ ] No
```
> refactor(module:description): refactor control flow

- components/dropdown/demo/placement.ts
```
[ ] Bugfix
[ ] Feature
```
Drowpdown component still use the older controlflow 
Dropdown component use now the new control flow
```
[] Yes
[X] No
```
> refactor(module:dropdown): refactor control flow

- components/flex/demo/gap.ts
- components/flex/demo/wrap.ts
```
[ ] Bugfix
[ ] Feature
```
Flex component still use the older control flow
Flex component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:flex): refactor control flow

- components/empty/config.ts
- components/empty/embed-empty.component.ts
- components/empty/empty.component.ts
```
[ ] Bugfix
[ ] Feature
```
Empty component still use the older control flow
Empty component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:empty): refactor control flow component

- components/drawer/drawer.component.ts
```
[ ] Bugfix
[ ] Feature
```
Drawer component still use the older control flow
Drawer component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:drawer): refactor control flow component

- components/divider/divider.component.ts
```
[ ] Bugfix
[ ] Feature
```
Divider component still use the older control flow
Divider component use now the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:divider): refactor control flow component

- components/grid/demo/playground.ts
```
[ ] Bugfix
[ ] Feature
```
Grid component still use the older control flow
Grid component now use the new control flow
```
[] Yes
[X] No
```
> refactor(module:grid): refactor control flow component

- components/graph/graph-edge.component.ts
- components/graph/graph-node.component.ts
- components/graph/graph.component.ts
```
[ ] Bugfix
[ ] Feature
```
Graph component still use the older control flow
Graph Component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:graph): refactor control flow component

- components/form/demo/advanced-search.ts
- components/form/demo/auto-tips.ts
- components/form/demo/dynamic-form-item.ts
- components/form/demo/register.ts
- components/form/demo/validate-reactive.ts
- components/form/demo/validate-template.ts
- components/form/form-control.component.ts
- components/form/form-control.spec.ts
- components/form/form-label.component.ts
- components/form/form.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Form component still use the older control flow
Form component use the new control flow
```
[] Yes
[X] No
```
> refactor(module:form): refactor control flow component

- components/grid/demo/playground.ts
```
[ ] Bugfix
[ ] Feature
```
Doc grid playground have mistake by using ngFor and @for on the same item
Remove the *ngFor directive use
```
[ ] Yes
[X] No
```
> docs(module:grid): fix doc demo grid

- components/icon/page/index.ts
```
[ ] Bugfix
[ ] Feature
```
Icon component still use the older control flow
Icon Component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:icon): refactor control flow component

- components/hash-code/hash-code.component.ts
```
[ ] Bugfix
[ ] Feature
```
Hashcode component still use the older control flow
HashCode component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:hashcode): refactor control flow component

- components/icon/doc/index.en-US.md
```
[ ] Bugfix
[ ] Feature
[✔] Documentation content changes
```
typo fixed
```
[ ] Yes
[✔] No
```
> docs(module:icon): typo in icon document

- components/input/demo/allow-clear.ts
- components/input/input-group-slot.component.ts
- components/input/input-group.component.ts
- components/input/input-group.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Input component still use the older control flow
Input component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:input): refactor control flow component

- components/image/image-preview.component.ts
```
[ ] Bugfix
[ ] Feature
```
Image component still use the older control flow
Image component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:image): refactor control flow component

- components/color-picker/color-block.component.ts
- components/color-picker/color-format.component.ts
- components/color-picker/color-picker.component.ts
- components/color-picker/color-picker.module.ts
- components/color-picker/doc/index.en-US.md
- components/color-picker/doc/index.zh-CN.md
```
[ ] Bugfix
[X] Feature
```
Color Picker component is not standalone
Color picker component is standalone
```
[ ] Yes
[X] No
```
> feat(module:color-picker): make color picker standalone

- components/tree-select/tree-select.component.ts
- components/tree-select/tree-select.spec.ts
> fix(module:tree-select): fix search box exception when Chinese search

- components/mention/mention.component.ts
- components/mention/nz-mention.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Mention component still use the older control flow
Mention component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:mention): refactor control flow component

- components/layout/sider-trigger.component.ts
- components/layout/sider.component.ts
```
[ ] Bugfix
[ ] Feature
```
Layout component still use the older control flow
Layout component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:layout): refactor control flow component

- components/input-number/input-number-group-slot.component.ts
- components/input-number/input-number-group.component.ts
- components/input-number/input-number-group.spec.ts
- components/input-number/input-number.component.ts
```
[ ] Bugfix
[ ] Feature
```
Input number component still use the older control flow
Input number component use now the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:input-number): refactor control flow component

- components/flex/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
flex docs add Chinese translation
```
[ ] Yes
[x] No
```
> feat(module: flex docs): add Chinese translation

- components/layout/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
This PR fixes a minor typo in the word "collapse".
> fixed typo

- components/menu/demo/recursive.ts
- components/menu/menu-group.component.ts
- components/menu/menu.spec.ts
- components/menu/submenu-title.component.ts
- components/menu/submenu.component.ts
```
[ ] Bugfix
[ ] Feature
```
Menu component still use the older control flow
Menu component now use the new comtrol flow
```
[ ] Yes
[X] No
```
> refactor(module:menu): refactor control flow component

- components/modal/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
#8389
--
```
[ ] Yes
[x] No
```
> docs(module:modal doc): add Chinese api translation

- components/notification/notification-container.component.ts
- components/notification/notification.component.ts
```
[ ] Bugfix
[ ] Feature
```
Notification component still use the older control flow
Notification component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:notification): refactor control flow component

- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.component.ts
- components/modal/modal-footer.component.ts
```
[ ] Bugfix
[ ] Feature
```
Modal Component still use the older control flow
Modal component now use the new control flow
```
[ ] Yes
[ ] No
```
> refactor(module:modal): refactor control flow component

- components/page-header/page-header.component.ts
```
[ ] Bugfix
[ ] Feature
```
Page Header component still use the older control flow
Page Header component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:page-header): refactor control flow component

- components/pagination/demo/item-render.ts
- components/pagination/pagination-default.component.ts
- components/pagination/pagination-item.component.ts
- components/pagination/pagination-options.component.ts
- components/pagination/pagination.component.ts
- components/pagination/pagination.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Pagination component still use the older control flow
Pagination component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:pagination): refactor control flow component

- components/i18n/languages/ja_JP.ts
Added translations related with date picker and calendar for week and range placeholders
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:i18n): added missing translations to ja_JP

- components/i18n/languages/pt_PT.ts
```
[x] Bugfix
[ ] Feature
```
The date-picker fails in the Portuguese language because of the missing texts.
```
[ ] Yes
[x] No
```
> fix(module:i18n): add missing pt texts

- components/i18n/languages/vi_VN.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:i18n): added missing translations to vi_VN

- components/avatar/avatar.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:avatar): fix prerender

- components/icon/icons.ts
https://github.com/ng-alain/delon/actions/runs/8244404359/job/22546576735?pr=1778
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:image): missing swip icon

- components/progress/progress.component.ts
```
[ ] Bugfix
[ ] Feature
```
Progress component still use the older control flow
Progress component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:progress): refactor control flow progress

- components/popover/popover.ts
```
[ ] Bugfix
[ ] Feature
```
Popover component still use the old control flow
Popover component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:popover): refactor control flow popover

- scripts/site/_site/doc/app/header/header.less
- scripts/site/_site/doc/app/header/logo.component.ts
```
[ ] Bugfix
[ ] Feature
```
According to the original plan, we restored the ZORRO Logo style.
```
[ ] Yes
[x] No
```
> docs: restore style of logo

- components/list/list-item-cell.ts
This commit removes the `NgZone` dependency from the list item cell. With zone.js becoming optional, `onStable` won't emit any value when `provideZonelessChangeDetection` is used in the application config. Instead, it now listens to a subject emission when the content projection has been initialized.
> fix(module:list): remove NgZone dependency

- components/flex/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module:flex): subtitle copywriting revision

- components/notification/notification-container.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:notification): nzMaxStack initial value error

- components/qr-code/qrcode.component.ts
```
[ ] Bugfix
[ ] Feature
```
Qrcode component still use the older control flow
Qrcode component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:qrcode): use the new control flow

- components/radio/demo/radiogroup-more.ts
- components/radio/demo/radiogroup-options.ts
- components/radio/radio.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Radio component and documentation use the older control flow
Radio component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:radio): use the new control flow

- components/result/result.component.ts
```
[ ] Bugfix
[ ] Feature
```
Result component still use the older control flow
Result component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:result): use the new control flow

- components/rate/demo/customize.ts
- components/rate/demo/text.ts
- components/rate/rate.component.ts
```
[ ] Bugfix
[ ] Feature
```
Rate component still use the older control flow
Rate component use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:rate): use the new control flow

- components/resizable/demo/drawer.ts
- components/resizable/demo/table.ts
- components/resizable/resize-handles.component.ts
```
[ ] Bugfix
[ ] Feature
```
Resizable component still use the older control flow
Resizable component now use the new control flow
```
[ ] Yes
[X] No
```
> refactor(module:resizable): use the new control flow

- components/tag/style/patch.less
fix:#8492
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:tag): borderless style is invalid in default state

- components/core/no-animation/nz-no-animation.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: simplify no-animation directive

- components/modal/modal-ref.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:modal): supports masked layer response for each click

- components/slider/marks.component.ts
- components/slider/slider.component.ts
- components/slider/slider.spec.ts
- components/slider/step.component.ts
- components/slider/style/entry.less
- components/slider/style/patch.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:slider): fix the style of step-dots in vertical mode

- components/button/button.component.ts
- components/button/button.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:button): add ant-btn-default class

- components/skeleton/demo/element.ts
- components/skeleton/doc/index.en-US.md
- components/skeleton/doc/index.zh-CN.md
- components/skeleton/skeleton-element.component.ts
- components/skeleton/skeleton.type.ts
```
[ ] Bugfix
[x] Feature
```
Waiting for #8479.
```
[ ] Yes
[x] No
```
> feat(module:skeleton): support for square shape of skeleton button

- components/notification/notification-container.component.ts
- [  ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:notification): popup order adjustment

- components/segmented/demo/custom.ts
- components/segmented/segmented.component.ts
```
[ ] Bugfix
[ ] Feature
```
Segmented component still use the older control flow
Segmented compnent nous ise the now control flow
```
[ ] Yes
[X] No
```
> refactor(module:segmented): refactor segmented control flow

- components/popconfirm/popconfirm.ts
```
[x] Bugfix
[ ] Feature
```
This is an error due to synchronization of the new Ant-Design styles.
```
[ ] Yes
[x] No
```
> fix(module:popconfirm): fix message icon style

- components/popconfirm/popconfirm.ts
- components/popover/popover.ts
- components/tooltip/base.ts
- components/tooltip/tooltip.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8510, #8181, #8406
https://angular.dev/errors/NG0500
```
[ ] Yes
[x] No
```
> fix(module:tooltip,popover,popconfirm): fix hydration error

- scripts/site/_site/doc/app/share/codebox/codebox.component.html
- scripts/site/_site/doc/app/share/codebox/codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8510
```
[ ] Yes
[x] No
```
> docs: make nz-code-box to skip hydration

- tea.yaml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: init tea project

- components/list/list-item-cell.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8517
Since the ng-template within an action component is static, we can turn on the static option to get to them faster.
```
[ ] Yes
[x] No
```
> fix(module:list): static query list-item-action template

- components/qr-code/qrcode.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(module:qr-code): improved background drawing efficiency

- components/i18n/languages/lv_LV.ts
- [ +] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ +] Tests for the changes have been added (for bug fixes / features)
- [+ ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[+ ] Other... Please describe: lv_LV locale fixes (fixed spelling, added missing translations, etc.)
```
```
[ ] Yes
[+ ] No
```
> feat(i18n): update lv_LV lang

- components/tooltip/tooltip.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:tooltip): fix arrow color when custom color

- components/statistic/demo/basic.ts
- components/statistic/demo/module
- components/statistic/doc/index.en-US.md
- components/statistic/doc/index.zh-CN.md
- components/statistic/statistic.component.ts
- components/statistic/statistic.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:statistic): support for loading state

- components/upload/upload.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:upload): prevent drop event for firefox only

- components/table/src/addon/filter.component.ts
- components/table/src/addon/selection.component.ts
- components/table/src/addon/sorters.component.ts
- components/table/src/cell/td-addon.component.ts
- components/table/src/cell/th-addon.component.ts
- components/table/src/table/table-content.component.ts
- components/table/src/table/table-fixed-row.component.ts
- components/table/src/table/table-inner-scroll.component.ts
- components/table/src/table/table.component.ts
- components/table/src/table/tbody.component.ts
- components/table/src/table/thead.component.ts
- components/table/src/table/tr-measure.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:table): use the new control flow

- package-lock.json
- package.json
- scripts/gulp/util/task-helpers.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #7982
Resolve local 'npm run start' Out of Memory issue
The 'npm run start' command now uses more memory to prevent out of memory errors.
```
[ ] Yes
[x] No
```
> chore: support for running npm scripts in windows

- .lintstagedrc
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix lint-staged

- components/pagination/pagination-default.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:pagination): page item 'track' mistake

- components/table/src/table/table-content.component.ts
- components/table/src/table/tr-measure.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:table): fix @for track function

- components/graph/graph.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:graph): fix @for track function

- components/icon/page/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:icon): fix @for track function

- components/i18n/languages/fa_IR.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #8596
fix type fa_IR like en_US add scanned field to QRCode
```
[ ] Yes
[X] No
```
> fix(module:i18n): add scanned field to QRCode fa_IR

- components/table/src/table/table-fixed-row.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:table): missing no-result in fixed header table

- package-lock.json
```
[ ] Bugfix
[ ] Feature
```
DevDependency `tree-dump` has no license file, and had already add license file in v1.0.2 https://github.com/streamich/tree-dump/issues/4
```
[ ] Yes
[x] No
```
> chore: bump dev deps tree-dump 1.0.1 t0 1.0.2

- components/tsconfig.lib.json
```
[X] Bugfix
[ ] Feature
```
Types defintion of secondary entry package of the library are not found by the ide
Ide found the type defintion of all the secondary entry package of ng-zorro library
```
[ ] Yes
[X] No
```
> fix: typescript type config definition

- components/i18n/languages/fr_BE.ts
- components/i18n/languages/fr_CA.ts
- components/i18n/languages/fr_FR.ts
- components/i18n/languages/lv_LV.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #8613 
No type error is thrown while compiling.
```
[ ] Yes
[x] No
```
> fix(module:i18n): add scanned field to QRCode for fr_BE, fr_CA, fr_FR and lv_LV

- components/transfer/doc/index.en-US.md
- components/transfer/doc/index.zh-CN.md
> docs(module:transfer): supplementary API

- components/i18n/languages/pt_BR.ts
```
[ ] Bugfix
[ ] Feature
[X ] Other... Please describe: Translate pt_BR Cron Component
```
```
[ ] Yes
[X ] No
```
> fix(module:i18n): add missing translations to `pt_BR`

- scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
`nzGap` not resolved due to NzFlexModule is missing
> docs(module:flex): add missing flex module

- components/date-picker/lib/abstract-panel-header.html
- components/date-picker/lib/abstract-panel-header.ts
- components/date-picker/lib/abstract-table.html
Due to the refactor of the control flow of this component, an issue was raised. NG0956, this issue is a warning raised when a collection of a loop is re create each time on render. This is due to a wrong track parameters
Issue Number: #8653
NG0956 is fixed
> fix(module:datepicker): ng0956 recreation entire collection

- components/switch/switch.component.ts
> refactor(module:switch): migrate to new control flow

- components/statistic/statistic-number.component.ts
> refactor(module:statistic): migrate to new control flow

- components/pipes/demo/safe-null.ts
> refactor(module:pipes): migrate to new control flow

- components/color-picker/src/ng-antd-color-picker.component.ts
> refactor(module:color-picker): migrate to new control flow

- components/slider/marks.component.ts
- components/slider/slider.component.ts
- components/slider/step.component.ts
> refactor(module:slider): migrate to new control flow

- components/core/form/nz-form-item-feedback-icon.component.ts
- components/core/form/nz-form-patch.module.ts
- components/core/wave/nz-wave.spec.ts
> refactor(module:core): migrate to new control flow

- components/message/message-container.component.ts
- components/message/message.component.ts
> refactor(module:message): migrate to new control flow

- components/spin/spin.component.ts
> refactor(module:spin): migrate to new control flow

- components/steps/demo/progress.ts
- components/steps/demo/step-next.ts
- components/steps/step.component.ts
- components/steps/steps.spec.ts
> refactor(module:steps): migrate to new control flow

- components/auto-complete/autocomplete.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:auto-complete): migrate to new control flow

- components/skeleton/skeleton.component.ts
- components/skeleton/skeleton.spec.ts
> refactor(module:skeleton): migrate to new control flow

- components/space/space.component.spec.ts
- components/space/space.component.ts
> refactor(module:space): migrate to new control flow

- components/tag/demo/borderless.ts
- components/tag/demo/control.ts
- components/tag/demo/hot-tags.ts
- components/tag/tag.component.ts
Tag component still use the older control flow
Tag component used now the new control flow
> refactor(module:tag): migrate tag component to new control flow

- components/select/demo/automatic-tokenization.ts
- components/select/demo/coordinate.ts
- components/select/demo/custom-dropdown-menu.ts
- components/select/demo/default-value.ts
- components/select/demo/hide-selected.ts
- components/select/demo/label-in-value.ts
- components/select/demo/max-count.ts
- components/select/demo/multiple.ts
- components/select/demo/scroll-load.ts
- components/select/demo/search-box.ts
- components/select/demo/select-users.ts
- components/select/demo/size.ts
- components/select/demo/tags.ts
- components/select/option-container.component.ts
- components/select/option-item.component.ts
- components/select/select-arrow.component.ts
- components/select/select-clear.component.ts
- components/select/select-item.component.ts
- components/select/select-search.component.ts
- components/select/select-top-control.component.ts
- components/select/select.component.ts
- components/select/select.spec.ts
> refactor(module:select): migrate to new control flow

- components/tabs/demo/card-top.ts
- components/tabs/demo/card.ts
- components/tabs/demo/custom-add-trigger.ts
- components/tabs/demo/disabled.ts
- components/tabs/demo/editable-card.ts
- components/tabs/demo/extra.ts
- components/tabs/demo/guard.ts
- components/tabs/demo/icon.ts
- components/tabs/demo/position.ts
- components/tabs/demo/size.ts
- components/tabs/demo/slide.ts
- components/tabs/tab-body.component.ts
- components/tabs/tab-nav-bar.component.ts
- components/tabs/tab-nav-operation.component.ts
- components/tabs/tabset.component.spec.ts
- components/tabs/tabset.component.ts
> refactor(module:tabs): migrate to new control flow

- components/tooltip/demo/color.ts
> refactor(module:tooltip): migrate to new control flow

- components/time-picker/time-picker-panel.component.ts
- components/time-picker/time-picker.component.ts
> refactor(module:time-picker): migrate to new control flow

- components/transfer/demo/table-transfer.ts
- components/transfer/transfer-list.component.ts
- components/transfer/transfer-search.component.ts
- components/transfer/transfer.component.ts
> refactor(module:transfer): migrate to new control flow

- components/timeline/timeline-item.component.ts
- components/timeline/timeline.component.ts
- components/timeline/timeline.spec.ts
> refactor(module:timeline): migrate to new control flow

- components/grid/demo/playground.ts
> fix(module:grid): fix the NG0955 warning

- components/upload/demo/avatar.ts
- components/upload/upload-list.component.html
- components/upload/upload-list.component.ts
- components/upload/upload.component.html
- components/upload/upload.component.ts
- components/upload/upload.spec.ts
> refactor(module:upload): migrate to new control flow

- components/experimental-image/demo/preloading.md
> docs(module:experimental-image): migrate to new control flow

- components/typography/text-edit.component.ts
- components/typography/typography.component.ts
> refactor(module:typography): migrate to new control flow

- components/tree-select/demo/placement.ts
- components/tree-select/tree-select.component.ts
- components/tree-view/demo/dynamic.ts
- components/tree-view/demo/line.ts
- components/tree-view/indent.ts
- components/tree-view/node.ts
- components/tree/demo/customized-icon.ts
- components/tree/demo/directory.ts
- components/tree/tree-indent.component.ts
- components/tree/tree-node-switcher.component.ts
- components/tree/tree-node-title.component.ts
- components/tree/tree-node.component.ts
- components/tree/tree.component.ts
> refactor(module:tree,tree-select,tree-view): migrate to new control flow

- components/table/demo/ajax.ts
- components/table/demo/basic.ts
- components/table/demo/bordered.ts
- components/table/demo/break-word.ts
- components/table/demo/colspan-rowspan.ts
- components/table/demo/custom-column.ts
- components/table/demo/custom-filter-panel.ts
- components/table/demo/drag-sorting.ts
- components/table/demo/dynamic-settings.ts
- components/table/demo/edit-cell.ts
- components/table/demo/edit-row.ts
- components/table/demo/ellipsis.ts
- components/table/demo/expand-children.ts
- components/table/demo/expand-icon.ts
- components/table/demo/expand.ts
- components/table/demo/fixed-columns-header.ts
- components/table/demo/fixed-columns.ts
- components/table/demo/fixed-header.ts
- components/table/demo/grouping-columns.ts
- components/table/demo/multiple-sorter.ts
- components/table/demo/nested-table.ts
- components/table/demo/reset-filter.ts
- components/table/demo/row-selection-and-operation.ts
- components/table/demo/row-selection-custom.ts
- components/table/demo/size.ts
- components/table/demo/sort-filter.ts
- components/table/src/testing/custom-column.spec.ts
- components/table/src/testing/table.spec.ts
- components/table/src/testing/th.spec.ts
- components/table/src/testing/thead.spec.ts
> refactor(module:table): migrate to new control flow

- scripts/site/_site/doc/app/app.component.html
- scripts/site/_site/doc/app/header/header.component.html
> docs: migrate to new control flow

- components/i18n/languages/nb_NO.ts
Add missing Norwegian translations
> fix(module:i18n): add missing translations to `nb_NO`

- components/tree-select/tree-select.component.ts
> refactor(module:tree-select): simpilfy code

- components/image/image.spec.ts
> test(module:image): fix test

- components/drawer/drawer.component.ts
> fix(module:drawer): emit nzVisibleChange when close on navigation

- components/badge/badge-sup.component.ts
NG0095 warning
NG0095 warning disappears
> fix(module:badge): NG0955 warning in nz-badge-sup component

- components/transfer/demo/one-way.ts
- components/transfer/transfer.spec.ts
> docs(module:transfer): fix demo error

- .lintstagedrc
> ci: fix lint-staged

- components/qr-code/demo/background.md
- components/qr-code/demo/color.md
- components/qr-code/demo/custom-status.md
- components/qr-code/demo/custom-status.ts
- components/qr-code/demo/download.md
- components/qr-code/demo/error-level.md
- components/qr-code/demo/padding.md
- components/qr-code/doc/index.en-US.md
- components/qr-code/doc/index.zh-CN.md
- components/qr-code/qrcode.component.spec.ts
- components/qr-code/qrcode.component.ts
- [✅] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✅] Feature
> feat(module:qrcode): support custom state rendering

- components/table/demo/multiple-sorter.md
> docs: fix translation mistake of table documentation

- components/space/space-compact.component.ts
> fix(module:space): fix bug of space-compact

- components/image/image-config.ts
> chore: remove `FADE_CLASS_NAME_MAP` and `IMAGE_PREVIEW_MASK_CLASS_NAME`

- components/input-number/input-number.component.ts
Let me try the linkedSignal :)
> refactor(module:input-number): use linkedSignal to simplify code

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
> chore(changelog): correct deprecations

- components/auto-complete/demo/status.ts
- components/cascader/demo/size.ts
- components/cascader/demo/status.ts
- components/select/demo/status.ts
> docs: update demo

- components/date-picker/date-picker.component.ts
- components/input-number-legacy/input-number-group.component.ts
- components/input-number-legacy/input-number.component.ts
- components/input/input-group.component.ts
- components/mention/mention.component.ts
- components/select/select.component.ts
- components/time-picker/time-picker.component.ts
- components/tree-select/tree-select.component.ts
> refactor: remove usages of NzFormPatchModule

- tsconfig.json
https://angular.dev/reference/configs/angular-compiler-options#strictstandalone
> build: enable strictStandalone flag

- components/input-number/input-number.component.ts
> fix(module:input-number): fix nzDisabled bug when use with ngModel

- components/input-number/input-number.component.spec.ts
- components/input-number/input-number.component.ts
> fix(module:input-number): fix value out of range when hold shift key

- components/cascader/cascader.component.ts
> fix(module:cascader): abnormal width of search results

- components/input-number/doc/index.en-US.md
> docs(module:input-number): fix demo impot module error

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
> chore(changelog): update changelog for v19.0.0-beta.1

- components/input/doc/index.en-US.md
- components/input/doc/index.zh-CN.md
- components/space/doc/index.en-US.md
- components/space/doc/index.zh-CN.md
> docs: remove standalone suffixes

- components/i18n/languages/zh_TW.ts
- Add DatePicker.rangeQuarterPlaceholder
- Add DatePicker.timePickerLocale.rangePlaceholder
- Add TimePicker.rangePlaceholder
- Add Calendar.timePickerLocale.rangePlaceholder
- Add Table.filterCheckall
- Add Table.filterSearchPlaceholder
- Add CronExpression
- Add QRCode
- Remove Calendar.rangeQuarterPlaceholder
> fix(module:i18n): add missing translations to zh_TW

- components/menu/doc/index.en-US.md
- components/menu/doc/index.zh-CN.md
change EventEmitter\<NzMenuItemDirective\> to EventEmitter\<NzMenuItemComponent\>
> docs(module:menu): event name correction

- components/transfer/demo/tree-transfer.ts
> fix(module:transfer): fixed tree transfer demo

- components/upload/upload-btn.component.ts
remove the deprecated way to catch error with Rxjs
use catchError instead subscribe(() => {}, ()=> {})
> refactor(module:upload): replace deprecated code

- components/tabs/demo/draggable.md
- components/tabs/demo/draggable.ts
- components/tabs/tabset.component.ts
基于 cdk 实现标签可拖拽
cdk example: https://material.angular.io/cdk/drag-drop/examples#cdk-drag-drop-tabs
antd example: https://ant.design/components/tabs-cn#tabs-demo-custom-tab-bar-node
> docs(module:tabs): add draggable tabs example

- components/tabs/demo/draggable.ts
> docs(module:tabs): fix style pollution

- components/checkbox/doc/index.en-US.md
- components/checkbox/doc/index.zh-CN.md
> docs(module:checkbox): model type correction

- .stylelintrc.json
- package-lock.json
- package.json
- scripts/site/_site/doc/style/markdown.less
> docs: fix height of image

- components/checkbox/checkbox-group.component.ts
> fix(module:checkbox): fix NG0600 error

- components/input-number/input-number.component.ts
> fix(module:input-number): fix NG0600 error

- components/transfer/transfer-list.component.ts
> perf(module:transfer): use item.key as tracking for the list render

- components/segmented/segmented-item.component.ts
- components/segmented/segmented.component.ts
- components/segmented/segmented.service.ts
- components/segmented/segmented.spec.ts
> fix(module:segmented): fix emitting unnecessary value changed events

- components/avatar/avatar.component.ts
- components/avatar/demo/group.ts
> feat(module:avatar): support custom icon

- components/flex/flex.spec.ts
- components/flex/typings.ts
> fix(module:flex): fix NzAlign type

- components/auto-complete/autocomplete-trigger.directive.ts
- scripts/site/_site/doc/app/header/searchbar.component.ts
- tsconfig.json
> chore: enable typeCheckHostBindings flag

- components/alert/alert.component.ts
- components/alert/alert.spec.ts
> refactor(module:alert): use inject instead constructor

- components/button/button.component.ts
> refactor(module:button): use inject for injection

- components/badge/badge.component.ts
> refactor(module:badge): migrate to inject pattern

- components/auto-complete/autocomplete-option.component.ts
- components/auto-complete/autocomplete-trigger.directive.ts
- components/auto-complete/autocomplete.component.ts
- components/auto-complete/autocomplete.spec.ts
> refactor(module:autocomplete): use inject instead constructor

- components/back-top/back-top.component.ts
> refactor(module:backtop): use inject instead constructor

- components/card/card-tab.component.ts
- components/card/card.component.ts
> refactor(module:card): use inject instead constructor

- components/cascader/cascader-option.component.ts
- components/cascader/cascader.component.ts
- components/cascader/cascader.service.ts
> refactor(module:cascader): migrate to inject pattern

- components/space/space-compact-item.directive.ts
> fix(module:space): border radius compact mode one item

- components/checkbox/checkbox.component.ts
> refactor(module:checkbox): migrate to inject pattern

- components/code-editor/code-editor.component.ts
> refactor(module:code-editor): migrate to inject pattern

- components/anchor/anchor-link.component.ts
- components/anchor/anchor.component.ts
- components/anchor/anchor.spec.ts
> refactor(module:anchor): use inject instead constructor

- components/cron-expression/cron-expression-preview.component.ts
- components/cron-expression/cron-expression.component.ts
> refactor(module:cronexpression):  use inject pattern

- components/collapse/collapse-panel.component.ts
- components/collapse/collapse.component.ts
> refactor(module:collapse): use inject pattern

- components/descriptions/descriptions.component.ts
- [ X Refactoring (no functional changes, no api changes)
> refactor(module:descriptions): use inject pattern

- components/float-button/float-button-group.component.ts
- components/float-button/float-button-top.component.ts
- components/float-button/float-button.component.ts
> refactor(module:floatbutton): use inject pattern

- components/drawer/drawer-content.directive.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.service.ts
> refactor(module:drawer): use inject pattern

- components/dropdown/context-menu.service.ts
- components/dropdown/dropdown-menu.component.ts
- components/dropdown/dropdown.directive.ts
> refactor(module:dropdown): use inject pattern

- components/form/form-control.component.ts
- components/form/form-item.component.ts
- components/form/form-label.component.ts
- components/form/form.directive.ts
> refactor(module:form): use inject pattern

- components/experimental/image/image.component.ts
> refactor(module:experimental-image): use inject pattern

- docs/recommendation.en-US.md
- docs/recommendation.zh-CN.md
> docs: update resource recommendation list

- components/graph/graph-edge.component.ts
- components/graph/graph-minimap.component.ts
- components/graph/graph-zoom.directive.ts
- components/graph/graph.component.ts
> refactor(module:graph): use inject pattern

- components/modal/modal-close.component.ts
- components/modal/modal-confirm-container.component.ts
- components/modal/modal-container.directive.ts
- components/modal/modal-content.directive.ts
- components/modal/modal-footer.component.ts
- components/modal/modal-footer.directive.ts
- components/modal/modal-title.component.ts
- components/modal/modal-title.directive.ts
- components/modal/modal.component.ts
- components/modal/modal.service.ts
> refactor(module:modal): use inject pattern

- components/icon/icon.directive.ts
- components/icon/icon.service.ts
> refactor(module:icon): use inject pattern

- components/mention/mention.component.ts
- components/mention/mention.service.ts
> refactor(module:mention): use inject pattern

- components/list/list-item-cell.ts
- components/list/list-item-meta.component.ts
- components/list/list-item.component.ts
- components/list/list.component.ts
> refactor(module:list): use inject pattern

- components/qr-code/qrcodegen.ts
> chore(module:qrcode): update the qrcodgen file

- components/layout/content.component.ts
- components/layout/footer.component.ts
- components/layout/header.component.ts
- components/layout/layout.component.ts
- components/layout/sider.component.ts
> refactor(module:layout): use inject pattern

- components/tabs/tab-nav-bar.component.ts
> fix(module:tabs): fix typo in tabnav

- docs/changelog.en-US.md
> docs: fix typo in changelog

- components/tabs/demo/draggable.ts
Issue Number: close #9255
Add a `CD` invocation, and it works well now.
> docs(module:tabs): draggable showcase: hide content after switching tabs

- components/modal/modal-ref.ts
> refactor(module:modal): replace string with enum value

- components/float-button/demo/group-menu.ts
- components/float-button/demo/group-placement.md
- components/float-button/demo/group-placement.ts
- components/float-button/demo/group.ts
- components/float-button/demo/top.md
- components/float-button/doc/index.en-US.md
- components/float-button/doc/index.zh-CN.md
- components/float-button/float-button-group.component.spec.ts
- components/float-button/float-button-group.component.ts
- components/float-button/style/index.less
you can set `nzPlacement` for `nz-float-button-group` to customize the pop placement of its menu buttons
> feat(module:float-button): support nzPlacement

- components/input-number/input-number.component.spec.ts
- components/input-number/input-number.component.ts
input-number should accept numbers with commas, consistent with antd's behavior.
> feat(module:input-number): accepted numbers with commas

- components/layout/demo/basic.md
- components/layout/demo/basic.ts
- components/layout/demo/custom-trigger.ts
- components/layout/demo/fixed-sider.ts
- components/layout/demo/fixed.ts
- components/layout/demo/responsive.ts
- components/layout/demo/side.ts
- components/layout/demo/top-side-2.md
- components/layout/demo/top-side.md
- components/layout/demo/top-side.ts
- components/layout/demo/top.ts
- scripts/site/_site/doc/app/codebox/codebox.component.html
> fix(module:layout): fix showcases

- components/i18n/languages/cs_CZ.ts
> fix(module:i18n): add missing translations to `cs_CZ`

- components/i18n/languages/sk_SK.ts
> fix(module:i18n): add missing translations to `sk_SK`

- components/tag/tag.component.ts
- components/tag/typings.ts
> feat(module:tag): export `NzTagColor` type

- components/segmented/segmented-item.component.ts
- components/segmented/segmented.component.ts
- components/segmented/segmented.spec.ts
> fix(module:segmented): should render single element in item if icon-only

- components/float-button/demo/group-menu.md
- components/float-button/demo/group-placement.md
- components/float-button/demo/group.md
- components/float-button/demo/open.md
- components/float-button/demo/tooltip.md
- components/float-button/demo/tooltip.ts
- components/float-button/demo/top.md
Issue Number: [9263](https://github.com/NG-ZORRO/ng-zorro-antd/issues/9263)
float-button - tooltip
add demo for tooltip in float-button module
> docs(module:float-button): add tooltip demo for float-button

- components/segmented/segmented.component.ts
> fix(module:segmented): fix NG0950 error

- components/auto-complete/autocomplete-trigger.directive.ts
- components/drawer/drawer.component.ts
- components/drawer/drawer.service.ts
- components/dropdown/context-menu.service.ts
- components/dropdown/dropdown.directive.ts
- components/image/image.service.ts
- components/mention/mention.component.ts
- components/message/base.ts
- components/modal/modal.service.ts
Switch to tree-shakeable overlay APIs. After this, we should avoid injecting Overlay services
Ref: https://github.com/angular/components/pull/30929
> refactor(module:*): replace overlay service with standalone functions

- components/core/config/config.service.ts
- components/core/config/config.spec.ts
> refactor(module:core): add default value arg to `withConfig` function

- scripts/site/_site/doc/app/header/header.component.html
> docs: fixed version select width

- .claude/.mcp.json
- .cursor/mcp.json
- .gemini/settings.json
- .gitignore
- .junie/mcp.json
- .vscode/mcp.json
This PR is just adding usefull MCP for cursor editor
> chore: add mcp configuration

- components/auto-complete/demo/variant.md
- components/auto-complete/demo/variant.ts
Add a Demo to show how to support nzVariant with autoComplete
- [] Yes
> docs(module:auto-complete): add demo for nzVariant

- components/auto-complete/autocomplete.spec.ts
For the auto complete some test are failing, cause the mock for the Directinality Service was not correct
Auto Complete componente test are failing
Test for the Auto Complete component passed
> test(module:auto-complete): introduce valueSignal to MockDirectionality
